### DISCUSSION TITLE
Require response timeouts configuration via helm values

### DISCUSSION THREAD

**Discussion by Nbarola** [linkerd/linkerd2#10055] [General] [answered]
Hi All, I wanted to check if global timeout can be set for the linkerd proxies via helm values.
Able to configure timeouts timeouts for each [route](https://linkerd.io/2.12/tasks/configuring-timeouts/#:~:text=Each%20route%20may%20define%20a,default%20timeout%20is%2010%20seconds)
`It mentions If unspecified, the default timeout is 10 seconds` , So is there any global value that can be set to increase this default timeout for all routes/proxies.
I found values in helm to update timeout during establishing connection, please let me know if there is something for `response timeout `as well
```
proxy:
  # -- Maximum time allowed for the proxy to establish an outbound TCP
  # connection
  outboundConnectTimeout: 1000ms
  # -- Maximum time allowed for the proxy to establish an inbound TCP
  # connection
  inboundConnectTimeout: 100ms
  ```
  
  I see proxy containers having these values under args
  ```
- name: LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE
      value: 10000ms
- name: LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE
      value: 10000ms
  ```
  
Are these corresponding to response timeout?
if yes, what are the equivalent values in helm values.yaml?
