### DISCUSSION TITLE
ServiceProfile matching via ExternalName

### DISCUSSION THREAD

**Discussion by iamnoah** [linkerd/linkerd2#10089] [Q&A]
Our teams use a namespace per service pattern. e.g., svc-foo lives in namespace svc-foo. When a service needs to connect to another service, we target it by adding an ExternalName service. e.g.,

```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-foo
  namespace: svc-bar
spec:
  type: ExternalName
  externalName: svc-foo.svc-foo.svc.cluster.local
```

Then svc-foo has its profile:

```yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
    creationTimestamp: null
    name: svc-foo.svc-foo.svc.cluster.local
    namespace: svc-foo
...
```

My hope is that requests in namespace `svc-bar` to `svc-foo` will match the profile in `svc-foo` but the docs say "That value is mapped to the fully qualified DNS name" which would end up being svc-foo.svc-**bar**.svc.cluster.local, and I don't see any route matches in the viz dashboard. Does that mean I need a duplicate ServiceProfile for each namespace that targets my service?
