### DISCUSSION TITLE
Doesn't work with gvisor

### DISCUSSION THREAD

**Discussion by Pithikos** [linkerd/linkerd2#10371] [Help]
I'm relatively new to Kubernetes and need to add SSL between pods. I thought of using linkerd since it seems the most minimal solution out there.

However it seems I can't get it working under gvisor.

```
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   vel=info msg="iptables-save v1.8.8 (legacy): Cannot initialize: Permission denied (you must be root)\n\n"
time="2023-02-22T08:48:46Z" level=error msg="aborting firewall configuration"
```

My test deployment looks like below
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        linkerd.io/inject: enabled
    spec:
      runtimeClassName: gvisor  # This brings havoc
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80
```

How do I resolve this?
