### DISCUSSION TITLE
How to embed linkerd grafna dashbord

### DISCUSSION THREAD

**Discussion by limboys** [linkerd/linkerd2#10622] [Help]
I want to embed linkerd grafana dashbord like the following
```
<!DOCTYPE html>
<html>
<head>
  <title>嵌入网页示例</title>
</head>
<body>
  <h1>嵌入网页示例</h1>
  <p>以下是一个嵌入的网页：</p>
  <iframe src="http://linkerd-web.xxxxx.com/grafana/d-solo/linkerd-namespace/linkerd-namespace?var-namespace=autors&orgId=1&refresh=1m&from=1679729719400&to=1679730019400&panelId=29" width="450" height="200" frameborder="0"></iframe>
</body>
</html>
```
But the page returns a rejected request as shown in the figure：
![image](https://user-images.githubusercontent.com/36941711/227704142-6e49c909-aa47-4450-a26b-5b42002f6439.png)

The linkerd version runs Linkerd 2.12.3 (stable).
I tried turning grafna's anonymous access on and off and embedding,but it didn't work
```
[analytics]
check_for_updates = false
[auth]
disable_login_form = true
[auth.anonymous]
org_name = Main Org.
enabled = true
org_role = Admin
[security]
allow_embedding = true
x_content_type_options = false
content_security_policy = false
x_xss_protection = 0
cookie_samesite = none
csrf_trusted_origins = .*
[auth.basic]
enabled = false
[grafana_net]
url = https://grafana.net
[log]
mode = console
[log.console]
format = text
level = info
[panels]
disable_sanitize_html = true
[paths]
data = /var/lib/grafana/
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
[server]
domain = '.*'
root_url = %(protocol)s://%(domain)s:/grafana/
```
When I change `root_url = %(protocol)s://%(domain)s:/grafana/ `to` root_url = %(protocol)s://%(domain)s:%(http_port)s/ `I can use nodeport to access and the dashboard can be embedded, but this loses The linkerd web page jump access, when I don't modify it, I use nodeport access then it fails as follows
![image](https://user-images.githubusercontent.com/36941711/227703572-a73b95e5-33c2-4b30-8d2c-5259d635c5ef.png)
Using the link `http://10.82.49.144:30443/grafna` remains the same
So I think rejection is what linkerd web is responding to

I also tried this link https://linkerd.io/2.12/tasks/exposing-dashboard/ for settings ingress and web，and it also does not work embedding is still rejected
![image](https://user-images.githubusercontent.com/36941711/227703813-50c681b2-899a-4dd9-b325-75e3c605f6b2.png)
```
    - name: web
      image: 'cr.l5d.io/linkerd/web:stable-2.12.3'
      args:
        - >-
          -linkerd-metrics-api-addr=metrics-api.linkerd-viz.svc.cluster.local:8085
        - '-cluster-domain=cluster.local'
        - '-grafana-addr=grafana.grafana:3000'
        - '-controller-namespace=linkerd'
        - '-log-level=info'
        - '-log-format=plain'
        - '-enforced-host=.*'
        - '-enable-pprof=false'
```
Oh yeah when I embed the main linkerd web page it does the same thing, so I'm more thinking that it's rejected by linkerd web, or linkerd proxy?
So what I want to ask is whether linkerd web can set X-Frame-Options to allow embedding, or whether there is another way to handle it
