### DISCUSSION TITLE
Dynamic Routing of gRPC using Linkerd

### DISCUSSION THREAD

**Discussion by hiteshwani29** [linkerd/linkerd2#10907] [Q&A] [answered]
We have a requirement to configure dynamic routing for grpc using linked. But I could not find any reference in the documentation to implement this using Linkerd.
 
We want to achieve this in a similar way as linked supports the HTTP dynamic routing based on the headers using HttpRoute(https://linkerd.io/2.13/tasks/configuring-dynamic-request-routing/)

_I tried to achieve dynamic routing using Gateway and Route as well but currently, it seems that Linked doesn't support these CRDs_

<table>
<tr>
<th>Route</th>
<th>Gateway</th>
</tr>
<tr>
<td>

```
apiVersion: linkerd.io/v1alpha2
kind: Route
metadata:
  name: grpc-route
spec:
  protocol: grpc
  routes:
    - name: backend-a
      condition:
        pathRegex: "/backend.BackendService/MethodFromBackend"
        headers:
          x-header-key: backend-a
      client:
        name: backend-a
        kind: service
    - name: backend-b
      condition:
        pathRegex: "/backend.BackendService/MethodFromBackend"
        headers:
          x-header-key: backend-b
      client:
        name: backend-b
        kind: service
```
</td>
<td>

```
apiVersion: gateway.linkerd.io/v1alpha2
kind: Gateway
metadata:
  name: grpc-gateway
spec:
  http:
    routes:
      - name: backend-a
        condition:
          pathRegex: "/backend.BackendService/MethodFromBackend"
          headers:
            x-header-key: backend-a
        servers:
          - name: backend-a
            port: 50051
      - name: backend-b
        condition:
          pathRegex: "/backend.BackendService/MethodFromBackend"
          headers:
            x-header-key: backend-b
        servers:
          - name: backend-b
            port: 50051
    servers:
      - name: backend-a
        port:
          name: grpc
          number: 50051
      - name: backend-b
        port:
          name: grpc
          number: 50051
```
</td>
</tr>
</table>

**Would someone from the community be able to help me to achieve this?**
