### DISCUSSION TITLE
Automatic Retires to HTTP/HTTPS ExternalName Service

### DISCUSSION THREAD

**Discussion by naing2victor** [linkerd/linkerd2#10980] [Help]
Hello,
I'm running linkerd stable-2.13.3 and want automatic retries to `ExternalName` HTTP/HTTPS endpoints. Following code block is the sample code that I used to test. Afterall I don't get the per-route metrics and when I tap the live traffic, they don't produce `rt_route` metrics. Am I missing something here? If I can get different example which retries automatically to external http endpoints, that also helps me.
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: dummy.test.svc.cluster.local
  namespace: test
spec:
  routes:
  - name: GET /all
    condition:
      method: GET
      pathRegex: '/.*'
    isRetryable: true
    responseClasses:
    - condition:
        status:
          min: 500
          max: 599
      isFailure: true
---
apiVersion: v1
kind: Service
metadata:
  name: dummy
  namespace: test
spec:
  type: ExternalName
  externalName: httpstat.us
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummy
  name: dummy
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/enable-external-profiles: "true"
      labels:
        app: dummy
    spec:
      containers:
      - image: nginx
        name: nginx
        command: ["/bin/bash", "-c"]
        args:
          - |
            while true; do
              curl dummy.test.svc.cluster.local/Random/200,500
              sleep 1
            done
```
Here I have 1 pod to generate traffic with curl and yet the logs of the pods seems resolve the `ExternalName` service and returns the logs as below.
```
curl -v dummy.test.svc.cluster.local/Random/200,500
*   Trying 20.40.202.3:80...
* Connected to dummy.test.svc.cluster.local (20.40.202.3) port 80 (#0)
> GET /Random/200,500 HTTP/1.1
> Host: dummy.test.svc.cluster.local
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< content-length: 2667
< content-type: text/html
< date: Fri, 02 Jun 2023 11:23:36 GMT
<
```
Per-route metrics
```
linkerd viz routes --namespace test svc/dummy
ROUTE       SERVICE   SUCCESS   RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
GET /all      dummy         -     -             -             -             -
[DEFAULT]     dummy         -     -             -             -             -
```
Live Tapping logs
```
linkerd viz tap -n test deploy/dummy -o wide | grep req
req id=0:0 proxy=out src=10.192.17.242:46760 dst=20.40.202.3:80 tls=not_provided_by_service_discovery :method=GET :authority=dummy.test.svc.cluster.local :path=/Random/200,500 src_control_plane_ns=linkerd src_deployment=dummy src_namespace=test src_pod=dummy-74c47f6ff6-ff8h6 src_pod_template_hash=74c47f6ff6 src_serviceaccount=default src_tls=loopback dst_tls=not_provided_by_service_discovery
req id=0:1 proxy=out src=10.192.17.242:46786 dst=20.40.202.3:80 tls=not_provided_by_service_discovery :method=GET :authority=dummy.test.svc.cluster.local :path=/Random/200,500 src_control_plane_ns=linkerd src_deployment=dummy src_namespace=test src_pod=dummy-74c47f6ff6-ff8h6 src_pod_template_hash=74c47f6ff6 src_serviceaccount=default src_tls=loopback dst_tls=not_provided_by_service_discovery
req id=0:2 proxy=out src=10.192.17.242:46806 dst=20.40.202.3:80 tls=not_provided_by_service_discovery :method=GET :authority=dummy.test.svc.cluster.local :path=/Random/200,500 src_control_plane_ns=linkerd src_deployment=dummy src_namespace=test src_pod=dummy-74c47f6ff6-ff8h6 src_pod_template_hash=74c47f6ff6 src_serviceaccount=default src_tls=loopback dst_tls=not_provided_by_service_discovery
req id=0:3 proxy=out src=10.192.17.242:46824 dst=20.40.202.3:80 tls=not_provided_by_service_discovery :method=GET :authority=dummy.test.svc.cluster.local :path=/Random/200,500 src_control_plane_ns=linkerd src_deployment=dummy src_namespace=test src_pod=dummy-74c47f6ff6-ff8h6 src_pod_template_hash=74c47f6ff6 src_serviceaccount=default src_tls=loopback dst_tls=not_provided_by_service_discovery
```
