### DISCUSSION TITLE
Setting linkerd-jaeger as grafana data source

### DISCUSSION THREAD

**Discussion by Jorrit05** [linkerd/linkerd2#11174] [Help]
Hi, I have a custom grafana running in my cluster, and would like to set my linkerd-jaeger extensions as a data source for Grafana. 

However, the Linkerd policy interferes:
`[  6426.350555s]  INFO ThreadId(01) inbound:server{port=16686}: linkerd_app_inbound::policy::http: Request denied server.group=policy.linkerd.io server.kind=server server.name=jaeger-ui route.group= route.kind=default route.name=default client.tls=Some(Established { client_id: Some(ClientId(Name("default.core.serviceaccount.identity.linkerd.cluster.local"))), negotiated_protocol: None }) client.ip=10.1.10.175

[  6426.350721s]  INFO ThreadId(01) inbound:server{port=16686}:rescue{client.addr=10.1.10.175:35218}: linkerd_app_core::errors::respond: HTTP/2.0 request failed error=client 10.1.10.175:35218: server: 10.1.10.99:16686: unauthorized request on route error.sources=[unauthorized request on route]`

And I can't really find in the documentation to allow my services to add allowances tor these policies.

Any help would be much appreciated, thanks!

**Comment by lucaskatayama** [comment]
> Hi, I have a custom grafana running in my cluster, and would like to set my linkerd-jaeger extensions as a data source for Grafana.
> 
> However, the Linkerd policy interferes: `[ 6426.350555s] INFO ThreadId(01) inbound:server{port=16686}: linkerd_app_inbound::policy::http: Request denied server.group=policy.linkerd.io server.kind=server server.name=jaeger-ui route.group= route.kind=default route.name=default client.tls=Some(Established { client_id: Some(ClientId(Name("default.core.serviceaccount.identity.linkerd.cluster.local"))), negotiated_protocol: None }) client.ip=10.1.10.175
> 
> [ 6426.350721s] INFO ThreadId(01) inbound:server{port=16686}:rescue{client.addr=10.1.10.175:35218}: linkerd_app_core::errors::respond: HTTP/2.0 request failed error=client 10.1.10.175:35218: server: 10.1.10.99:16686: unauthorized request on route error.sources=[unauthorized request on route]`
> 
> And I can't really find in the documentation to allow my services to add allowances tor these policies.
> 
> Any help would be much appreciated, thanks!

I figured out how to at least access data from grafana

1. Configure datasource (https://grafana.com/docs/grafana/latest/datasources/jaeger/#provisioning-example)
```yaml
....
     - name: Jaeger
        type: jaeger
        uid: EbPG8fYoz
        url: http://jaeger.linkerd-jaeger.svc.cluster.local:16686/jaeger <<<<<< the context path is important
        access: proxy
```

2. Create `AuthorizationPolicy` for grafana
```yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  namespace: linkerd-jaeger
  name: grafana
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: jaeger-ui
  requiredAuthenticationRefs:
    - kind: ServiceAccount
      name: grafana
      namespace: grafana
```
Apply it
```
$ kubectl apply -f config.yaml
```
