### DISCUSSION TITLE
Linkerd TrafficSplit with Contour HTTPProxy

### DISCUSSION THREAD

**Discussion by zyzlik** [linkerd/linkerd2#11448] [Help]
Hello!

I have a question regarding TrafficSplit and HTTPProxy working together.
I have two services `canary-atomation-stable` and `canary-automation-canary`, and `TrafficSplit` object that routes traffic between them:
```
apiVersion: v1
items:
- apiVersion: split.smi-spec.io/v1alpha2
  kind: TrafficSplit
  metadata:
    name: canary-automation-trafficsplit
    namespace: canary-automation
  spec:
    backends:
    - service: canary-automation-stable
      weight: 50
    - service: canary-automation-canary
      weight: 50
    service: canary-automation-stable
```

Locally, when I query `curl http://canary-automation-stable.canary-automation.svc.cluster.local:5000`, it works as expected.
However, when I add the `HTTPProxy` object and curl `xxx.us-east-2.elb.amazonaws.com`,  it routes the traffic only to the `stable` service:
```
apiVersion: v1
items:
- apiVersion: projectcontour.io/v1
  kind: HTTPProxy
  metadata:
    name: canary-automation
    namespace: canary-automation
  spec:
    routes:
    - requestHeadersPolicy:
        set:
        - name: l5d-dst-override
          value: canary-automation-stable.canary-automation.svc.cluster.local:5000
      services:
      - name: canary-automation-stable
        port: 5000
    virtualhost:
      fqdn: xxx.us-east-2.elb.amazonaws.com
 ```
Is there anything I'm missing?
