### DISCUSSION TITLE
Does linkerd control plane require hard-coded resource names?

### DISCUSSION THREAD

**Discussion by javsalgar** [linkerd/linkerd2#11610] [General]
Checking the linkerd helm chart and code, I saw that the healthcheck.go package has the following section:

```
	linkerdCNIDisabledSkipReason = "skipping check because CNI is not enabled"
	linkerdCNIResourceName       = "linkerd-cni"
	linkerdCNIConfigMapName      = "linkerd-cni-config"

	podCIDRUnavailableSkipReason    = "skipping check because the nodes aren't exposing podCIDR"
	configMapDoesNotExistSkipReason = "skipping check because ConigMap does not exist"

	proxyInjectorOldTLSSecretName = "linkerd-proxy-injector-tls"
	proxyInjectorTLSSecretName    = "linkerd-proxy-injector-k8s-tls"

	spValidatorOldTLSSecretName = "linkerd-sp-validator-tls"
	spValidatorTLSSecretName    = "linkerd-sp-validator-k8s-tls"

	policyValidatorTLSSecretName = "linkerd-policy-validator-k8s-tls"
	certOldKeyName               = "crt.pem"
	certKeyName                  = "tls.crt"
	keyOldKeyName                = "key.pem"
	keyKeyName                   = "tls.key"
)
```

I also see that the helm chart resource names, most of them, are fixed and not dependant on the release name:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    {{ include "partials.annotations.created-by" . }}
  labels:
    app.kubernetes.io/name: proxy-injector
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: {{.Values.linkerdVersion}}
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  name: linkerd-proxy-injector
  namespace: {{ .Release.Namespace }}

```

Does that mean that the linkerd deployment MUST have the resource names specified in the chart?
