### DISCUSSION TITLE
config.linkerd.io/default-inbound-policy setting in annotations not working

### DISCUSSION THREAD

**Discussion by wuzhuoquan** [linkerd/linkerd2#11648] [General] [answered]
According to the document ```https://linkerd.io/2.14/features/server-policy/```, ```config.linkerd.io/default-inbound-policy``` default is ```all-unauthenticated```
Then I want to test my workload to set it to deny, but after that, i still can request my workload api every where
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    config.linkerd.io/default-inbound-policy: "deny"
  name: app-1-v1
  namespace: five-test-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
        version: v1
      annotations:
        config.linkerd.io/default-inbound-policy: "deny"
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: VERSION
          value: v1
        image: registry.yingmi-inc.com/app/test:python-demo-20231116
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
          name: app
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /hostname
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 3
          periodSeconds: 5
          successThreshold: 2
      enableServiceLinks: false
      imagePullSecrets:
      - name: ym-docker-registry-secrets
      restartPolicy: Always
```

curl from other pod
```
root@jump-5d4d555c44-8vkcz:/# curl http://app-1.five-test-2:8080/hostname
app-1-v1-6c7b7b6f77-t8cpqroot@jump-5d4d555c44-8vkcz:/#
```

And no mather I  set this annotation in namespace or deployment or  pod, it just can't work
the iptables rule 
```
# Generated by iptables-save v1.4.21 on Fri Nov 24 16:03:44 2023
*raw
:PREROUTING ACCEPT [8291:668243]
:OUTPUT ACCEPT [8257:1525862]
COMMIT
# Completed on Fri Nov 24 16:03:44 2023
# Generated by iptables-save v1.4.21 on Fri Nov 24 16:03:44 2023
*nat
:PREROUTING ACCEPT [337:20220]
:INPUT ACCEPT [676:40560]
:OUTPUT ACCEPT [488:33450]
:POSTROUTING ACCEPT [488:33450]
:PROXY_INIT_OUTPUT - [0:0]
:PROXY_INIT_REDIRECT - [0:0]
-A PREROUTING -m comment --comment "proxy-init/install-proxy-init-prerouting/1700811354" -j PROXY_INIT_REDIRECT
-A OUTPUT -m comment --comment "proxy-init/install-proxy-init-output/1700811354" -j PROXY_INIT_OUTPUT
-A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -m comment --comment "proxy-init/ignore-proxy-user-id/1700811354" -j RETURN
-A PROXY_INIT_OUTPUT -o lo -m comment --comment "proxy-init/ignore-loopback/1700811354" -j RETURN
-A PROXY_INIT_OUTPUT -p tcp -m multiport --dports 4567,4568 -m comment --comment "proxy-init/ignore-port-4567,4568/1700811354" -j RETURN
-A PROXY_INIT_OUTPUT -p tcp -m comment --comment "proxy-init/redirect-all-outgoing-to-proxy-port/1700811354" -j REDIRECT --to-ports 4140
-A PROXY_INIT_REDIRECT -p tcp -m multiport --dports 4190,4191,4567,4568 -m comment --comment "proxy-init/ignore-port-4190,4191,4567,4568/1700811354" -j RETURN
-A PROXY_INIT_REDIRECT -p tcp -m comment --comment "proxy-init/redirect-all-incoming-to-proxy-port/1700811354" -j REDIRECT --to-ports 4143
COMMIT
# Completed on Fri Nov 24 16:03:44 2023
# Generated by iptables-save v1.4.21 on Fri Nov 24 16:03:44 2023
*filter
:INPUT ACCEPT [8291:668243]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [8257:1525862]
COMMIT
# Completed on Fri Nov 24 16:03:44 2023
# Generated by iptables-save v1.4.21 on Fri Nov 24 16:03:44 2023
*mangle
:PREROUTING ACCEPT [8291:668243]
:INPUT ACCEPT [8291:668243]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [8257:1525862]
:POSTROUTING ACCEPT [8257:1525862]
COMMIT
# Completed on Fri Nov 24 16:03:44 2023
```
