### DISCUSSION TITLE
Issue with AWS multi-cluster setup

### DISCUSSION THREAD

**Discussion by fbozic** [linkerd/linkerd2#11761] [Help]
Hi folks,
We have a peculiar issue with multi-cluster setup. We have 2 clusters, 1 in GCP and 1 in AWS. TL;DR communication from GCP to AWS doesn't work for some services.
Setup:
- 2 clusters
  - 1 in GCP
  - 1 in AWS.
- 2 namespaces in each cluster
  - l5d-server
    - nginx deployment and service - injected proxy to pod and exported service
    - [http-echo](https://github.com/mendhak/docker-http-https-echo) deployment and service - injected proxy to pod and exported service
  - l5d-client
    - curl deployment - injected proxy to pod

Results:
- From curl deployment in AWS cluster we can communicate with all 4 services (2 x nginx, 2 x httepcho) :white_check_mark:
- From curl deployment in GCP cluster we can communicate with only 3 services. It doesn't work for a nginx in AWS cluster. :x:
Error:
```
< HTTP/1.1 504 Gateway Timeout
< l5d-proxy-error: client 10.0.4.23:54439: server: 10.193.120.101:4143: logical service nginx.l5d-server.svc.cluster.local:80: service in fail-fast
< date: Mon, 11 Dec 2023 13:04:44 GMT
< content-length: 0
```

I've checked that services are replicated and I've checked endpoints (with linkerd diagnostics endpoints). Everything looks okay to me.
I've checked this document: https://linkerd.buoyant.io/t/what-are-failfast-errors-in-linkerd-and-how-do-you-debug-them/85 but it didn't help.

I've attached nginx and http-echo manifests and screenshots of curl requests.
If trace proxy logs are needed let me know.

<img width="514" alt="l5d-aws-2-gcp" src="https://github.com/linkerd/linkerd2/assets/70634661/14914f89-d6c7-4a45-a5b4-e55ef3f92f18">
<img width="1162" alt="l5d-gcp-2-aws" src="https://github.com/linkerd/linkerd2/assets/70634661/f42b53e4-0112-49b1-880a-f152080195ff">

Curl manifests
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  namespace: l5d-client
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
        # config.linkerd.io/proxy-log-level: trace
      labels:
        app: curl
    spec:
      containers:
        - name: curl
          image: curlimages/curl
          command: [/bin/sleep, 3650d]
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
```

Nginx manifests
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: l5d-server
  labels:
    mirror.linkerd.io/exported: "true"
spec:
  selector:
    app: nginx
  type: ClusterIP
  ports:
    - name: app
      port: 80
      protocol: TCP
      targetPort: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: l5d-server
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:stable-alpine3.17
          ports:
            - name: app
              containerPort: 80
```

Http echo manifests
```
apiVersion: v1
kind: Service
metadata:
  name: httpecho
  namespace: l5d-server
  labels:
    mirror.linkerd.io/exported: "true"
spec:
  selector:
    app: httpecho
  type: ClusterIP
  ports:
    - name: app
      port: 80
      protocol: TCP
      targetPort: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpecho
  namespace: l5d-server
  labels:
    app: httpecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpecho
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: httpecho
    spec:
      containers:
        - name: httpecho
          image: mendhak/http-https-echo:31
          ports:
            - name: app
              containerPort: 8080
```
