### DISCUSSION TITLE
when create a Server resource for some pods,the probe check failed

### DISCUSSION THREAD

**Discussion by wuzhuoquan** [linkerd/linkerd2#11986] [Q&A]
1. Create the deployment by applying the yaml with readinessProbe
```
readinessProbe:
    failureThreshold: 1
    httpGet:
      path: /check
      port: 8080
      scheme: HTTP
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 5
```
2. Create a Server for the deployment pods
```
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: linkerd-test
  name: test-app-1-v1-8080
spec:
  podSelector:
    matchLabels: 
      app: test-app-1
      version: v1
  port: 8080 
  proxyProtocol: HTTP/1
```
3. After I do that，the readinesProbe check failed and return 403，because onece the user set a Server for some pod's port, the port is mTLS-ed
4. Create a HTTPRoute and set the parentRef to the Server.If I don't set any rules match the probe check path, kubelet request to the probe path returned 404
5. Then I add a rule to match the probe path, this time kubelet get 403 again 😂
6. If I don't use the Server for the HTTPRoute parentRef, I can't use the  mTLS and Authorization
7. If I use the Server for the HTTPRoute parentRef, the probe check failed, and event can't use the route feature to route to diffrent version of my app.

So, how can i slove the probe?
[裂开][裂开][裂开][裂开][裂开][裂开][裂开][裂开]

**Comment by alpeb** [comment]
Note that, unlike regular traffic, probe requests are not mTLS'd (because the kubelet cannot be injected by linkerd). It seems however that you're doing the right thing. If you declare an HTTPRoute for your service, you're right you require to also declare an entry with the probe's path. 
One great way to diagnose whether these rules are getting applied is using the command `linkerd diagnostics policy -n linkerd-test po/<pod-name> 8080`.

**Reply by wuzhuoquan** [reply]
Thanks for your answer. You mean, after I create a Server instance for the pods, and declare an HTTPRoute with setting the  Server as the parentRef, and also I need to declare an entry with the probe's path?

**Reply by wuzhuoquan** [reply]
I declare  the ```HTTPRoute``` like below, but still return 403 to kubelet
```
apiVersion: policy.linkerd.io/v1beta3
kind: HTTPRoute
metadata:
  name: test-app-1
  namespace: linkerd-test
spec:
  parentRefs:
  - group: policy.linkerd.io
    kind: Server
    name: test-app-1-v1-8080
  rules:
  - matches:
    - path:
        type: Exact
        value: /check
```

403 return:
```
  Warning  Unhealthy  2m16s (x15 over 3m8s)  kubelet            Readiness probe failed: HTTP probe failed with statuscode: 403
```

**Reply by alpeb** [reply]
That seems right to me... Can you provide the output of the `linkerd diagnostics` command I mentioned above? Also, it'd be very helpfull  if you could provide a self-contained minimal repro for this issue.

**Reply by wuzhuoquan** [reply]
diagnostics info：
```
labels:
  group: policy.linkerd.io
  kind: server
  name: test-app-1-v1-8080
protocol:
  Kind:
    Http1:
      routes:
      - authorizations:
        - authentication:
            Permit:
              MeshTLS:
                Clients:
                  Identities:
                    identities:
                    - name: default.linkerd-test.serviceaccount.identity.linkerd.cluster.local
                    suffixes:
                    - {}
          labels:
            group: policy.linkerd.io
            kind: authorizationpolicy
            name: test-app-1
          metadata:
            Kind:
              Resource:
                group: policy.linkerd.io
                kind: authorizationpolicy
                name: test-app-1
          networks:
          - net:
              ip:
                Ip:
                  Ipv4: 0
          - net:
              ip:
                Ip:
                  Ipv6: {}
        metadata:
          Kind:
            Resource:
              group: policy.linkerd.io
              kind: HTTPRoute
              name: test-app-1
        rules:
        - matches:
          - path:
              Kind:
                Prefix: /
        - matches:
          - path:
              Kind:
                Exact: /check
```
