### DISCUSSION TITLE
Traffic splitting feature with Ingress

### DISCUSSION THREAD

**Discussion by tanzeemzillu** [linkerd/linkerd2#11992] [Help]
Hello all,
I am working on traffic splitting. Whereas it is working fine in general, it is not working when I am sending request via ingress.
In my use case, I have two service called service-ui and service-ui-bg and I want to split the traffic between these two. I defined a HTTPRoute policy which looks like the below
```
apiVersion: policy.linkerd.io/v1beta3
kind: HTTPRoute
metadata:
  name: service-ui-route
  namespace: cognigy-ai
spec:
  parentRefs:
    - group: core
      kind: Service
      name: service-ui
      port: 8000
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: service-ui
          port: 8000
          weight: 50
        - group: ''
          kind: Service
          name: service-ui-bg
          port: 8000
          weight: 50
      matches:
        - path:
            type: PathPrefix
            value: /
```
If I generate some load from another pod which is also meshed by running the command curl -I http://service-ui:8000/ then I see this is working fine
```
NAME            MESHED   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
service-ui         1/1   100.00%   0.1rps           0ms           0ms           0ms          1
service-ui-bg      1/1   100.00%   0.1rps           2ms           2ms           2ms          1
```
But when I am sending http request via ingress by running `curl -I https://tanzeem-test-az.cognigy.ai/ ` then I see splitting is not working. My ingress definition looks like below
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-ui
  namespace: cognigy-ai
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: cognigy-ai
    meta.helm.sh/release-namespace: cognigy-ai
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: cognigy-ai-ipwhitelistserviceui@kubernetescrd
status:
  loadBalancer: {}
spec:
  ingressClassName: traefik
  tls:
    - secretName: cognigy-traefik
  rules:
    - host: tanzeem-test-az.cognigy.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-ui
                port:
                  number: 8000
```
Just so you know, I am using Traefik as ingress controller and Traefik is meshed. What am I missing here? I would greatly appreciate any help.
