### DISCUSSION TITLE
Route based metrics from accessing ExternalName for external DNS entry

### DISCUSSION THREAD

**Discussion by alekhrycaiko** [linkerd/linkerd2#12772] [Help] [answered]
Hi there,

I've been trying to see whether it's possible to get route based metrics for Pod traffic requesting a `type: ExternalName` service. The externalName being requested is a DNS entry outside my cluster.

I've been able to make requests successfully through the external name service. But I haven't had any luck getting route based data concerning the external name service. I'm interested in knowing about errors and latency for requests to this particular DNS entry.

I see here in[ the docs](https://linkerd.io/2.15/tasks/setting-up-service-profiles/) that external name services are supported. But does that include support for DNS entries that are off cluster?

I have tried using the Linkerd CLI to debug this process. I've currently gotten no errors about the setup I've used locally, but no data points either.

My rough setup has included
- An external name service object and a service profile
- An application Pod and it's own Service object + service profile.
- An endpoint with logic that calls the external name service object.

In the above setup, I've been able to get route based data for the application itself (e.g. calling `/test`). But when doing a linkerd viz cli call such as `linkerd viz routes deploy/test --to svc/external-test -o wide` I get no data back about requests sent to the service.

**Comment by alekhrycaiko** [comment]
Following up with an example config in case that's helpful.

When executing a `GET` from an application to `test.default.svc.cluster.local`, should I expect Linkerd to instrument route based metrics for these requests? `redacted.com` in my case is an external DNS address unavailable on my system.

```
kind: Service
apiVersion: v1
metadata:
  name: test
spec:
  type: ExternalName
  externalName: redacted.com # External DNS not for an application on my cluster.
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
```

```
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: test.default.svc.cluster.local
spec:
  routes:
  - condition:
      method: GET
      pathRegex: '.*'
    name: External Name GET
    responseClasses:
    - condition:
        status:
          min: 500
          max: 599
      isFailure: true
```
