### DISCUSSION TITLE
Linkerd dashboards on grafana.com are deprecated

### DISCUSSION THREAD

**Discussion by janlonsetteig** [linkerd/linkerd2#12805] [General]
All our current Linkerd Grafana dashboards use the deprecated Angular plugin. Are there updated dashboards available? If not, will there be before Grafana 12 when angular support is permanently removed?

We import the dashboards from grafana.com
```yaml
    linkerd:
      # all these charts are hosted at https://grafana.com/grafana/dashboards/{id}
      top-line:
        gnetId: 15474
        revision: 4
        datasource: Prometheus
      kubernetes:
        gnetId: 15479
        revision: 2
        datasource: Prometheus
      namespace:
        gnetId: 15478
        revision: 3
        datasource: Prometheus
      deployment:
        gnetId: 15475
        revision: 7
        datasource: Prometheus
      pod:
        gnetId: 15477
        revision: 3
        datasource: Prometheus
      service:
        gnetId: 15480
        revision: 3
        datasource: Prometheus
      route:
        gnetId: 15481
        revision: 3
        datasource: Prometheus
      authority:
        gnetId: 15482
        revision: 3
        datasource: Prometheus
      cronjob:
        gnetId: 15483
        revision: 3
        datasource: Prometheus
      job:
        gnetId: 15487
        revision: 3
        datasource: Prometheus
      daemonset:
        gnetId: 15484
        revision: 3
        datasource: Prometheus
      replicaset:
        gnetId: 15491
        revision: 3
        datasource: Prometheus
      statefulset:
        gnetId: 15493
        revision: 3
        datasource: Prometheus
      replicationcontroller:
        gnetId: 15492
        revision: 4
        datasource: Prometheus
      multicluster:
        gnetId: 15488
        revision: 3
        datasource: Prometheus

```
