### DISCUSSION TITLE
The configuration for proxy-injection and the linkerd-config configmap

### DISCUSSION THREAD

**Discussion by krishgu** [linkerd/linkerd2#12997] [Q&A] [answered]
Team,

- when linkerd injects the proxy into a pod, where does it get the proxy's configuration from? for example
  -  cpu/memory resource requests/limits
  - environment variables such as `LINKERD2_PROXY_LOG`
  - imageregistry?

- I always thought that this was from the configmap `linkerd-config`, if that's not the case - is the configmap only used for addons? what is the minimal configmap to make a working version of linkerd? 
  - does the configmap need to be `kustomized` for each environment?

- Looked at [discussion 4966](https://github.com/linkerd/linkerd2/discussions/4966) and the [PR 4915](https://github.com/linkerd/linkerd2/pull/4915) https://github.com/linkerd/linkerd2/pull/4915 - but it is not clear where these configs are passed as command-line arguments in the proxy-injector. 

Thanks!

**Comment by krishgu** [comment, marked as answer]
Using stable-2.14.10, I tested this by modifying `linkerd-config` configmap, and restarting the `proxy-injector` deployment. The sections here from the `proxy` section seem to take effect.  

We can now use kustomize to patch the configmap, to kustomize registries/resources for each cluster. (replacing the full `values`)

```yaml
    proxy:
     ...
      enableExternalProfiles: false
      image:
        name: myregistry.etc/linkerd/proxy
        pullPolicy: ""
        version: ""
     ...
      opaquePorts: 25,587,3306,4444,5432,6379,9300,11211
    ...
      resources:
        cpu:
          limit: ""
          request: 27m
        memory:
          limit: 199Mi
          request: 23Mi
```
