### DISCUSSION TITLE
How to configure linkerd with CloudNativePG?

### DISCUSSION THREAD

**Discussion by 99hops** [linkerd/linkerd2#13105] [Q&A] [answered]
Friends, I am trying to configure the CloudNativePG operator to work with linkerd without luck so far.
Looks like I am missing some config that is unknown to me as there are no error I can debug from and saw things like `config.linkerd.io/opaque-ports` that may be relavant.

At this point I can confirm adding this will make cnpg work properly (especially the init cluster import part)
```
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dev
spec:
  inheritedMetadata:
    annotations:
      linkerd.io/inject: disabled <--------- HERE
```

Please advice

**Comment by 99hops** [comment]
Hmm I now think the issue here is `linkerd-proxy` container not terminating during pg import Job even with `config.alpha.linkerd.io/proxy-enable-native-sidecar: enabled` it's starying active while the other 3 containers are terminated.
![image](https://github.com/user-attachments/assets/1c1e00af-6fb5-4cce-bca6-135e63b9e04e)
![image](https://github.com/user-attachments/assets/2907606d-36ce-4dc5-bf27-3027f0163695)

**Comment by 99hops** [comment]
I believe I found the root cause, CloudNativePG have implemeted `http://localhost:4191/shutdown` hook to kill the proxy which is now disabled by default

```
curl -X POST http://localhost:4191/shutdown
shutdown endpoint is not enabled
```

Is there a way to enable it for the given use case and not globally?
Here is a snipped if config I can inject into the cnpg pods


```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dev
spec:
  inheritedMetadata:
    annotations:
      config.linkerd.io/proxy-await: enabled
      config.linkerd.io/response-timeout: "10s"
      config.linkerd.io/proxy-enable-shutdown: enabled    <----- LIKE SO?
```

I confirm I have no issues when enabled globally but this doesn't look optimal?
Here is helm snippet from ArgoCD
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: 'https://helm.linkerd.io/edge'
    targetRevision: 2024.8.2
    chart: linkerd-control-plane
    helm:
      values: |
         proxy:
           enableShutdownEndpoint: true  # Enable the proxy shutdown endpoint globally
```

**Reply by olix0r** [reply]
That sounds correct to me. It seems most desirable to configure the annotation-based solution so that only these workloads have this feature re-enabled.

**Reply by 99hops** [reply]
> That sounds correct to me. It seems most desirable to configure the annotation-based solution so that only these workloads have this feature re-enabled.

Right @olix0r but this looks not possible at the moment looking at https://linkerd.io/2.16/reference/proxy-configuration/ there is no such annotation?

**Reply by olix0r** [reply, marked as answer]
Actually, there is, but the docs haven't been updated yet ;) (sorry, it's a known gap and we'll fix it.) The annotation is `config.linkerd.io/proxy-admin-shutdown: enabled`.

**Reply by 99hops** [reply]
This is the working solution with annotation, enabling globally is also an option.

```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dev
spec:
  inheritedMetadata:
    annotations:
      config.linkerd.io/proxy-admin-shutdown: enabled
```

https://github.com/cloudnative-pg/cloudnative-pg/pull/5643/commits/f73cc8b950e25c28972a20ad1425543a2da47af4

**Comment by 99hops** [comment]
@olix0r maybe it's now the time to ask about `config.alpha.linkerd.io/proxy-enable-native-sidecar: enabled`
Reading the docs [here](https://linkerd.io/2.16/tasks/graceful-shutdown/#native-sidecar) I got the impression that this flag is enough by itself to not allow linkerd-proxy to be the only container left running but it seems this is not the case? (tested on 1.29.4 and 1.30.4) :smile_cat: 

Here is sample config
```
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  namespace: dev
spec:
  inheritedMetadata:
    annotations:
      config.alpha.linkerd.io/proxy-enable-native-sidecar: enabled
```
