### DISCUSSION TITLE
Add missing helm snipped to locked issue

### DISCUSSION THREAD

**Discussion by 99hops** [linkerd/linkerd2#13173] [Help]
Please add this in the end of [this issue](https://github.com/linkerd/linkerd2/issues/12382#issuecomment-2139505294) @adleong as the issue is locked and I belive it's a super important for other to use this solution (just verified) with helm (argo) but the thread is locked :pray: :smile_cat: 

```
-- heml value
networkPolicy:
   extraIngress:
      - ports:
         - protocol: TCP
           port: 4143 # Linkerd KEEP!
```
