### DISCUSSION TITLE
Gateway HttpRoute

### DISCUSSION THREAD

**Discussion by idc77** [linkerd/linkerd2#13637] [Q&A]
So I've migrated or rather I guess am migrating from nginx-gateway-fabric to linkerd.
I have this HttpRoute.yaml
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: nginx
  listeners:
    - name: blogs-http
      hostname: "blogs.bicki.de"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: blogs-https
      hostname: "blogs.bicki.de"
      port: 443
      protocol: HTTPS
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: blogs-bicki-de-tls
            kind: Secret
```
nginx had a gatewayclass named nginx
This here also uses cert-manager with an ACME ClusterIssuer

How do I do it with linkerd?
