### DISCUSSION TITLE
linkerd-proxy not able to access non-meshed services/ports

### DISCUSSION THREAD

**Discussion by eBeyond** [linkerd/linkerd2#14100] [Help]
Hi,

I'm trying to access an non-meshed alloy on port 4317 using linkerd-jaeger. I've also an (meshed) traefik which reports his metrics to this port already. The traefik-connection works as expected but not the configured linkerd-jaeger.

I've configured linkerd-jaeger like this:
```
collector:
  enabled: false # We don't need the collector, we can just ship it directly to Tempo
jaeger:
  enabled: false # We don't need the Jaeger UI, we'll just use Grafana
webhook:
  collectorSvcAddr: alloy-collector.alloy-system:4317
  collectorSvcAccount: alloy-collector
  collectorTraceProtocol: opentelemetry
```
But when the linkerd-proxy is running I get these messages:
`<service> linkerd-proxy [    84.470829s]  WARN ThreadId(01) tracing:controller{addr=alloy-collector.alloy-system:4317}:endpoint{addr=10.21.57.77:4317}: linkerd_reconnect: Failed to connect error=endpoint 10.21.57.77:4317: received corrupt message of type InvalidContentType error.sources=[received corrupt message of type InvalidContentType]`
It seems that the proxy isn't able to connect to the service. But it's already there and it's working.
Is there any blocker, which stops linkerd-proxy from accessing non-meshed services?

Ah, by the way: I've annotated the pod with:
`    config.linkerd.io/skip-outbound-ports: "12345,4317,4318"`
But this doesn't seem to affect linkerd-proxy. Is there some setting to let linkerd-proxy access this service?

Thanks
