### DISCUSSION TITLE
Removal of linkerd.io/helm-release-version annotation

### DISCUSSION THREAD

**Discussion by naseemkullah** [linkerd/linkerd2#4640] [General] [answered]
Hello,

I am looking for any objections to the following before opening a PR.

I'd like to propose removing of what I suspect to be clutter, unless a reason for having this annotation can be provided. The annotation in question is `linkerd.io/helm-release-version` whose value is the helm revision (run `helm ls` to compare).

The reason I would like to remove it is that it pollutes helm diff outputs as follows in the various places where it exists.

```diff
      matchLabels:
        linkerd.io/control-plane-component: proxy-injector
    template:
      metadata:
        annotations:
-         linkerd.io/helm-release-version: "29"
+         linkerd.io/helm-release-version: "1"
          linkerd.io/created-by: linkerd/helm stable-2.7.1
          linkerd.io/identity-mode: default
          linkerd.io/proxy-version: stable-2.7.1
        labels:
          linkerd.io/control-plane-component: proxy-injector
          linkerd.io/control-plane-n
```

Thanks! ✌️

**Comment by grampelberg** [comment, marked as answer]
Sounds reasonable to me.

**Comment by naseemkullah** [comment]
Thanks for confirming @grampelberg!

**Comment by alpeb** [comment]
Those annotations were introduced in #3673 to effectively have those templates always change upon each `helm update` operation, and force those services to be restarted. We need them to restart so that they pick their associated certificates that get generated anew upon each redeployment.

**Reply by muffl0n** [reply]
This is unnecessary when using cert-manager, right? Is there a way to disable it? Gives us a "release has changed" warning on every diff run we make. Effectively "breaking" our CI.

**Comment by naseemkullah** [comment]
ah thanks @alpeb, they do serve a purpose then and we cannot simply remove them

**Comment by rootik** [comment]
In a CI/CD for k8s components deployment scenario with helmfile it leads to unwanted behavior when linkerd pods got restarted on each pipeline run even nothing in the state has changed. What workaround would you propose?

**Reply by Fantaztig** [reply]
I suggest to run a helm diff check before running an upgrade.
We are using this for our CI/CD pipelines and it works as expected, I cannot really follow @naseemkullah original issue here as the annotation does not cause helm diff to recognize a diff in our case.

For reference, we are using this helm diff plugin: https://github.com/databus23/helm-diff

**Reply by rootik** [reply]
Thanks for your response but it doesn't work for us.
We just don't have a local linkerd chart to diff with.

It's all orchestrated by helmfile like this
```
---
repositories:
- name: grafana
  url: "https://grafana.github.io/helm-charts"
- name: linkerd
  url: "https://helm.linkerd.io/stable"
- name: vm
  url: "https://victoriametrics.github.io/helm-charts/"

helmDefaults:
  wait: true
  timeout: 1200

releases:
- name: linkerd-ca
  namespace: linkerd
  chart: .
  values:
    - ../bootstrap.values.yaml

- name: linkerd-crds
  namespace: linkerd
  createNamespace: false
  chart: linkerd/linkerd-crds
  needs:
  - linkerd/linkerd-ca

- name: linkerd-cni
  namespace: linkerd-cni
  createNamespace: false
  chart: linkerd/linkerd2-cni
  needs:
  - linkerd/linkerd-crds
  values:
  - values/values-cni.yaml

- name: linkerd
  namespace: linkerd
  createNamespace: false
  chart: linkerd/linkerd-control-plane
  needs:
  - linkerd/linkerd-ca
  - linkerd/linkerd-crds
  - linkerd-cni/linkerd-cni
  values:
  - values/values.yaml.gotmpl

- name: vm
  namespace: linkerd-viz
  createNamespace: false
  chart: vm/victoria-metrics-single
  needs:
  - linkerd/linkerd
  values:
  - values/values-vm.yaml

- name: grafana
  version: 6.30.3 # https://github.com/grafana/grafana/issues/54974
  namespace: linkerd-viz
  createNamespace: false
  chart: grafana/grafana
  needs:
  - linkerd/linkerd
  values:
  - values/values-grafana.yaml

- name: linkerd-viz
  namespace: linkerd-viz
  createNamespace: false
  chart: linkerd/linkerd-viz
  needs:
  - linkerd/linkerd-ca
  - linkerd/linkerd
  - linkerd-viz/vm
  values:
  - values/values-viz.yaml.gotmpl
```

I've just tried helmfile diff and to be honest have no clue how it exactly different from helmfile apply.
It just shows the same change:
![image](https://user-images.githubusercontent.com/13675167/199861898-654bb7cc-d8bf-4c3f-b486-7c879cce2176.png)
