### DISCUSSION TITLE
Service Profile not monitoring?

### DISCUSSION THREAD

**Discussion by oceaneLonneux** [linkerd/linkerd2#4776] [General]
Hello, I have a couple of questions regarding service profile :) 
    1. We tried using the command ‘linkerd routes svc/name-api-svc -t 20s -n=namespace’ but the time is never respected. The command returns the route almost right away. Is that on purpose…? I saw time in the Linkerd route —help, so confused as to why it reacts like that
    2. I have been following Linkerd guide for SP (and Digital Ocean https://www.digitalocean.com/community/tutorials/how-to-install-and-use-linkerd-with-kubernetes#step-2-—-installing-linkerd), however we aren’t really getting anywhere. 
Here is our yaml, which we applied. The pods are meshed. We use EKS. version 1.15. I checked the service name and it is the correct one.
```
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: name-api-svc.namespace.svc.cluster.local
  namespace: namespace
spec:
  routes:
  - name: ‘/name’
    isRetryable: true # Define it's safe to retry this route
    timeout: 100ms # Define a timeout for this route
    condition:
      method: GET
      pathRegex: /name
```
Is there something we are missing?

Thanks
