### DISCUSSION TITLE
Prefixing Prometheus metrics

### DISCUSSION THREAD

**Discussion by adinhodovic** [linkerd/linkerd2#4887] [General] [answered]
### What is the issue?

How do I prefix Linkerd Prometheus metrics, I've found documentation for [linkerd](https://github.com/linkerd/linkerd/blob/0edec7399396cfb3f453854bcc027e6fa8cd7dfe/linkerd/docs/telemetry.md#prometheus) but cannot find any documentation for linkerd2.

**Comment by ihcsim** [comment, marked as answer]
@adinhodovic For a static prefix, you can update the Prometheus `scrape_configs` with something like:

```yaml
metric_relabel_configs:
  - source_labels: [__name__]
    target_label: __name__
    replacement: "prefix_${1}"
```

For dynamic prefixes, it's better to use labels.
