### DISCUSSION TITLE
How to expose dashboard with GCE ingress on GKE

### DISCUSSION THREAD

**Discussion by WLun001** [linkerd/linkerd2#5116] [General] [answered]
The `ingress.yaml` is configure as below
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: linkerd-web-ingress
  namespace: linkerd
  annotations:
  # with or without this custom-request-headers also not working
    ingress.kubernetes.io/custom-request-headers: "l5d-dst-override: linkerd-web.linkerd.svc.cluster.local:8084"
    kubernetes.io/ingress.global-static-ip-name: linkerd-ip
    networking.gke.io/managed-certificates: linkerd-certificate
spec:
  backend:
    serviceName: linkerd-web
    servicePort: 8084
  rules:
    - host: linkerd.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: linkerd-web
              servicePort: 8084
```
Error
```javascript
jsonPayload: {
statusDetails: "failed_to_pick_backend"
@type: "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry"
}
```

Edited
`linkerd-web` is changed to `NodePort` instead of `ClusterIP`

**Comment by grampelberg** [comment]
It looks right to me... there might be a mismatch with the TTL? I'd verify that the `linkerd-web` pods are all healthy and reachable. You definitely don't need the header as the GCE ingress isn't injected with the proxy.

**Reply by WLun001** [reply]
Hi @grampelberg , i run `linkerd dashboard` locally, it works fine. 
I also change `linkerd-web`  to `NodePort` instead of `ClusterIP`, as GCE needs NodePort to work, but it still doesn't work

i tried port forward locally, it works too
```shell
kubectl port-forward service/linkerd-web 8084:8084 -n linkerd
```

**Reply by WLun001** [reply]
I guess something to do with readinessProbe? I checked the `yaml` of linkerd-web, it doesn't have readinessProbe
https://github.com/kubernetes/kubernetes/issues/20555

But I have other deployment without `readinessProbe`, it still works fine with GCE ingress though.

**Reply by WLun001** [reply]
After investigate further, the error is `INVALID_BACKEND`, which is caused by failed health check

https://cloud.google.com/load-balancing/docs/https/https-logging-monitoring#filtering_dimensions_for_metrics
![image](https://user-images.githubusercontent.com/23547929/96823020-03e8c580-145e-11eb-8278-43487763c6ad.png)

Not sure how to fix this

**Reply by grampelberg** [reply]
I'm not sure I have any great suggestions for you, make sure there are endpoints available in k8s. If there are, then there is an issue with the connection between the GCE load balancer and your k8s cluster.

**Reply by WLun001** [reply]
hmmmm. i have other GCE ingresses running on the same cluster, on `default` namespace, no issue.

**Comment by samstride** [comment]
@WLun001 , I am in the same situation. Looks like the GKE ingress requires an `HTTP 200` returned at `/`.

Not sure how to solve that one.

**Reply by WLun001** [reply]
@samstride I am going to change to Traefik

**Reply by samstride** [reply]
@WLun001 , let us know how it goes.

I am interested in these:

- Auto cert generation
- Ingress in 1 namespace able to across services in other namespaces
- Ease of setup/installation

**Reply by WLun001** [reply]
@samstride i wrote a [blog post](https://blog.yongweilun.me/traefik-in-actions-the-cloud-native-edge-router) about this. You may interested to check this out.

**Reply by samstride** [reply]
@WLun001 , I had a look at your post and also the repo. I have a few question around the [example-treafik.yaml](https://github.com/WLun001/cncf-demo/blob/main/kubernetes/example-treafik.yaml)

```yml
- --certificatesResolvers.myresolver.acme.dnsChallenge.provider=gcloud
- --certificatesresolvers.myresolver.acme.email=youremail@email.com
# Please note that this is the staging Let's Encrypt server.
#  Once you get things working, you should remove that whole line altogether.
- --certificatesresolvers.myresolver.acme.storage=/data/acme.json
```

We have our domain on Google domains and I was checking what value to use instead of `myresolver`  above?

Also, for the `google-dns-sa`, what permissions needed to be provided for the service account?

I also have a global IPaddress already generated. How do I pass that in?

**Reply by WLun001** [reply]
@samstride 
1. `myresolver` can be any name, as long as it is the same when reference to [IngressRoute](https://github.com/WLun001/cncf-demo/blob/main/kubernetes/ingress-route.yaml#L63)
2. `google`dns-sa` needs `DNS Administrator` permission, it stated on the [blog](https://blog.yongweilun.me/traefik-in-actions-the-cloud-native-edge-router#automatic-https)
3. For reserved IP you need to configure at Traefik service, more info can be found at [GKE docs](https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip#step_2a_using_a_service)

I updated [example-traefik.yaml](https://github.com/WLun001/cncf-demo/blob/main/kubernetes/example-treafik.yaml#L48), missing one line of code

**Reply by samstride** [reply]
@WLun001 , thanks I used your blog as a guide and I managed to setup traefik on GKE.

I have configured the sub domains I want on both google domains and in my route definition yaml. I'm running into the following 2 issues:

1. Auto cert generation is not working for me. I am running into this error:

```sh
error presenting token: googlecloud: no matching domain found for domain redacted.io.\n" providerName=myresolver
```

2. Having issues accessing linkerd dashboard

I setup a middleware for linkerd as follows:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: l5d-header-middleware
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: linkerd-web.linkerd.svc.cluster.local:8084
```

Then I added it to the ingress route

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: secure-ingress
  namespace: linkerd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`linkerd.example.io`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: linkerd-web
          port: 8084
      middlewares:
        - name: l5d-header-middleware
        - name: basic-auth
  tls:
    certResolver: myresolver
    domains:
      - main: "linkerd.example.io"
```

And I run into the host header issue. Any idea what I missed?

**Reply by WLun001** [reply]
@samstride 
1. Either generate service account for wrong project, or wrong permission

2. Generated from [traefik migration tools](https://github.com/traefik/traefik-migration-tool) based on [linkerd traefik example](https://linkerd.io/2/tasks/exposing-dashboard/#traefik), not tested but should work. I guess what you missing might be namespace
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: web-ingress
  namespace: linkerd
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: Host(`dashboard.example.com`)
    middlewares:
    - name: auth-18442390236333847385
      namespace: linkerd
    - name: headers-1412415333471367400
      namespace: linkerd
    priority: 0
    services:
    - kind: Service
      name: linkerd-web
      namespace: linkerd   # missed out namespace
      port: 8084
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-18442390236333847385
  namespace: linkerd
spec:
  basicAuth:
    secret: web-ingress-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers-1412415333471367400
  namespace: linkerd
spec:
  headers:
    customRequestHeaders:
      L5d-Dst-Override: linkerd-web.linkerd.svc.cluster.local:8084
```

**Reply by samstride** [reply]
@WLun001 , thanks.

1. Hmmm, I only have 1 GCP project and 1 GKE cluster in that project. The service account has only 1 permission - `DNS Administrator` as mentioned in your blog.

2. I tried your config (with appropriate changes):

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: web-ingress
  namespace: linkerd
spec:
  entryPoints: []
  routes:
    - kind: Rule
      match: Host(`linkerd.redacted.io`)
      middlewares:
        - name: headers-1412415333471367400
          namespace: linkerd
      priority: 0
      services:
        - kind: Service
          name: linkerd-web
          namespace: linkerd
          port: 8084
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers-1412415333471367400
  namespace: linkerd
spec:
  headers:
    customRequestHeaders:
      L5d-Dst-Override: linkerd-web.linkerd.svc.cluster.local:8084
```

and I get the same error:

```sh
It appears that you are trying to reach this service with a host of 'linkerd.redacted.io'.
This does not match /^(localhost|127\.0\.0\.1|linkerd-web\.linkerd\.svc\.cluster\.local|linkerd-web\.linkerd\.svc|\[::1\])(:\d+)?$/ and has been denied for security reasons.
Please see https://linkerd.io/dns-rebinding for an explanation of what is happening and how to fix it.
```

**Reply by WLun001** [reply]
@samstride 
1. Did you create secret based on the service account? Make sure it is map accordingly, [env](https://github.com/WLun001/cncf-demo/blob/main/kubernetes/example-treafik.yaml#L50-L55), [volume](https://github.com/WLun001/cncf-demo/blob/main/kubernetes/example-treafik.yaml#L135-L138)
2. refer to https://linkerd.io/dns-rebinding, `-enforced-host` need to set to empty string

**Reply by samstride** [reply]
@WLun001 , thanks:

1. Yup, I tried this as per your blog:

- create service account with `DNS Administrator` permission
- download JSON key
```sh
kubectl create secret generic dns-redacted \
  --from-file=key.json=dns-redacted.json -n traefik

### Double check secret exists

kubectl get secret -n traefik
```

- Yaml file has these values

```yaml
volumeMounts:
          - name: data
            mountPath: /data
          - name: tmp
            mountPath: /tmp
          - name: dns-redacted
            mountPath: /var/secret/google
            readOnly: true
.
.
.
- "--certificatesresolvers.myresolver.acme.email=valid@email.com"
- "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
- "--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
- "--certificatesResolvers.myresolver.acme.dnschallenge.provider=gcloud"
.
.
.
env:
          - name: GCE_PROJECT
            value: MY_PROJECT_ID
          - name: GCE_SERVICE_ACCOUNT_FILE
            value: /var/secret/google/key.json
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secret/google/key.json
.
.
.
volumes:
        - name: data
          persistentVolumeClaim:
            claimName: traefik
        - name: tmp
          emptyDir: {}
        - name: dns-redacted
          secret:
            secretName: dns-redacted
```

The error is:

```sh
error presenting token: googlecloud: no matching domain found for domain redacted.io.\n" providerName=myresolver.acme
```

I have a subdomain setup for `linkerd` in google domains. Is there any specific setting I need to get right in google domains?

2. Ok, so since header rewrite wasn't working (any ideas why?), I set enforced-host to empty string, removed the middleware and it's working now. Yaay.

Just need to sort out the certs...

**Reply by WLun001** [reply]
@samstride 
1. Do not have any specific setting for sub domain, if you exec to the traefik pod, can you find the service account file?
```bash
kubectl exec -it  deployment/traefik -n traefik -- sh
```

I noticed one typo on the args, should be `dnsChallenge`, not sure if that's relevant. 
```diff
+++ --certificatesResolvers.myresolver.acme.dnsChallenge.provider=gcloud
--- --certificatesResolvers.myresolver.acme.dnschallenge.provider=gcloud
```

2. Not sure though, I just get the idea from the error message you provided

**Reply by samstride** [reply]
@WLun001 

Yup, `key.json` for service account is present at `/var/secret/google` and it is the correct one.

I corrected typo and have applied the changes.

Same error...

**Reply by WLun001** [reply]
@samstride 
Is your DNS server hosted on Google Cloud DNS? This only applicable for Google Cloud DNS, not Google Domains

**Reply by samstride** [reply]
@WLun001 , right.

Step 4 from this [article](https://cloud.google.com/dns/docs/tutorials/create-domain-tutorial) a good one to follow?

**Reply by WLun001** [reply]
@samstride yes, good to go

**Reply by samstride** [reply]
@WLun001 , thanks.

I have set up Cloud DNS and have changed name servers in Google domains.

I now get this error:

```sh
time limit exceeded: last error: NS ns-cloud-c3.googledomains.com. returned NXDOMAIN for _acme-challenge.traefik.redacted.io.\n" providerName=myresolver.acme
```

The new nameservers are `ns-cloud-d{*}.googledomains.com` but the error message shows that the old nameservers are being used which are `ns-cloud-c{*}.googledomains.com`

Is it just a waiting game now ( I have waited 20 mins so far) ?

**Reply by WLun001** [reply]
@samstride it should be up in few minutes
I think you need to remove the existing `acme.json`, and let it generate again
exec to the pod and remove it, should works

Remember to remove the line below when it works, to avoid hitting [rate limit](https://letsencrypt.org/docs/rate-limits/)
```bash
--certificatesresolvers.myresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
```

**Reply by samstride** [reply]
@WLun001 , since I am using helm, I uninstalled the chart and re-installed it again so that way `acme.json` is generated again.

I also added this line:

```sh
- --certificatesresolvers.myresolver.acme.dnsChallenge.resolvers=8.8.8.8
```

The errors are gone now. However, I cannot access linkerd.redacted.io and it's just blank. Hmmmm....

**Reply by WLun001** [reply]
@samstride have to set `dnsChallenge.provider` to `gcloud` if you were using Google Cloud DNS

**Reply by samstride** [reply]
@WLun001 , thanks. I finally managed to get it to work.

I am having a strange issue when installing the chart

- an external ip is automatically generated (as expected)
- it is automatically used in the `traefik` service (as expected)
- after about 30 seconds, the IP address is released

I have to manually apply it again to the `traefik` service and everything works.

Anyways, need to investigate more why I experience this.

**Reply by WLun001** [reply]
@samstride nice. Not sure what is the issue with the reserved IP address, let me know if you found the cause.

**Comment by tgadam** [comment, marked as answer]
After many machinations I was able to get this working using GCE. This requires multiple patches to the linkerd configuration. The issue is that GCE Ingress uses a default health check route which doesn't work with linkerd-web. The linkerd-web health check is at port `9994`, path `/ping`. 

GCE allows you to create a custom health check config. Now reading the GCE docs you may get confused like me and think you needed to add this BackendConfig to the Ingress yaml. (I'm using IAP for authentication to the ingress and that's how you configured it). However that's incorrect. You need to add the custom BackendConfig for the health check to the **Service**.

Once I figured that out I was able to get the linkerd-web service to return healthy! However that wasn't enough despite having:
`ingress.kubernetes.io/custom-request-headers: "l5d-dst-override: linkerd-web.linkerd.svc.cluster.local:8084`
in the ingress config, the header was not getting rewritten. So I ended patching the linkerd-web deployment to not do host checking (not the most secure but I'll try and patch it to the correct hostname eventually). After doing that it **_finally worked!_**

_Please note there appears to some issues sometimes syncing changes depending on the order in which you apply changes (or it's possible I just wasn't patient enough for the changes to be scheduled and applied). I had to force update resources a couple of times before I finally got things working. Make sure and look at your events to ensure the changes actually got applied. Because I did so many iterations of this I'm unsure of the exact order to apply these. My guess based on GCP docs is that you should apply BackendConfigs first, then patches, and finally the ingress._

Below are my patch files and configs. I've omitted the certificate setup and IAP setup since those are well documented in the GCP docs:

##### Custom Health Check Config linkerd-web-service-bec.yaml
```
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: linkerd-web-healthcheck-config
  namespace: linkerd
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 10
    unhealthyThreshold: 5
    healthyThreshold: 1
    port: 9994
    type: HTTP
    requestPath: /ping
```

##### Here is the patch file for the linkerd-web Service linkerd-web-service-patch.yaml
```
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "linkerd-web-healthcheck-config"}'
spec:
  type: NodePort
```

##### Patch Command (notice merge)
```
kubectl patch svc linkerd-web --type='merge' -p "$(cat linkerd-web-service-patch.yaml)" -n linkerd
```

##### Patch file for linkerd-web Deployment linkerd-web-deployment-patch.json
```
[
    {
        "op" : "replace",
        "path": "/spec/template/spec/containers/0/args/5",
        "value": "-enforced-host="
    }
]
```

##### Patch Command (notice json)
```
kubectl patch deployment linkerd-web --type='json' -p "$(cat linkerd-web-deployment-patch.json)" -n linkerd
```

##### Ingress Config (the backend config here is for IAP)
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: linkerd-dashboard
  namespace: linkerd
  annotations:
    # If the class annotation is not specified it defaults to "gce".
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: linkerd-static-ip
    networking.gke.io/managed-certificates: linkerd-dashboard-cert
    ingress.kubernetes.io/custom-request-headers: "l5d-dst-override: linkerd-web.linkerd.svc.cluster.local:8084" # doesn't seeem to work
    beta.cloud.google.com/backend-config: '{"default": "linkerd-dashboard-ingress-config"}'
spec:
  rules:
  - host: linkerd.teselagen.net
    http:
      paths:
      - backend:
          serviceName: linkerd-web
          servicePort: 8084
```
