### DISCUSSION TITLE
Retry Budget - Can you please explain?

### DISCUSSION THREAD

**Discussion by kitkars** [linkerd/linkerd2#5378] [Q&A] [answered]
I have a simple app which is designed to return 500 error to test linkerd retry. This is a **_GET_** request. not POST
If I access the app with below retry budget - It retires 10 times. Why? (from where it is coming?)
I thought Retry ratio - for every 10 calls - should be 1 retry? (what does it even mean? for every 10 failures will we retry 1?)
```
spec:
  retryBudget:
    retryRatio: 0.1
    minRetriesPerSecond: 1
    ttl: 10s
  routes:
  - condition:
      method: GET
      pathRegex: /app
    name: GET /app
    isRetryable: true
```
