### DISCUSSION TITLE
Linkerd distributed tracing with OpenCensus

### DISCUSSION THREAD

**Discussion by jjangga0214** [linkerd/linkerd2#5419] [Q&A] [answered]
## Context

I am trying to use OpenCensus and Linkerd.
Though Linkerd has an option to automatically provision OpenCensus and jaeger in its namespace, I don't want to use them. Instead, I deployed them independently by myself under the namespace named 'ops'.

## Questions

1. Whether OpenCensus collector should be injected by Linkerd.

At the end (exactly 4th line from the last) of the the official [docs](https://linkerd.io/2/tasks/distributed-tracing/), it says,
> Ensure the OpenCensus collector is injected with the Linkerd proxy.  

What does this mean?  
Should I inject linkerd sidecar into OpenCensus collector pod?  
If so, why?

2. Should I suffix serviceaccount name by namespace?

For example, let's say I've configured the default namespace like this.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: default
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/trace-collector: my-opencensus-collector.ops:12345
    config.alpha.linkerd.io/trace-collector-service-account: my-opencensus-collector-service-account
```

`my-opencensus-collector` is in `ops` namespace, so I put `.ops` at the end of its service name, resulting `my-opencensus-collector.ops:12345`.
And the dedicated service account for the OpenCensus collector exists in `ops` namespace, too. In this case, should I put the namespace name at the end of service account name as well?

Which one would be right?
```yaml
config.alpha.linkerd.io/trace-collector-service-account: my-opencensus-collector-service-account
``` 
or 
```yaml
config.alpha.linkerd.io/trace-collector-service-account: my-opencensus-collector-service-account.ops
```

Thanks!
