### DISCUSSION TITLE
linkerd-proxy traces not showing up

### DISCUSSION THREAD

**Discussion by MrRexZ** [linkerd/linkerd2#5472] [Q&A]
Hi everyone,

My linkerd server & client version is `stable-2.9.1`.
I'm trying to get linkerd proxy spans to show up in Jaeger by going through my custom opencensus collector deployment, but wasn't able to for unknown reason.
The following is the opencensus deployment manifest:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-agent-conf
  labels:
    app: opencensus
    component: oc-agent-conf
data:
  oc-agent-config: |
    receivers:
      opencensus: {}
    exporters:
      opencensus:
        endpoint: "oc-collector.default:55678" # TODO: Update me
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oc-agent
  labels:
    app: opencensus
    component: oc-agent
spec:
  selector:
    matchLabels:
      app: opencensus
      component: oc-agent
  template:
    metadata:
      labels:
        app: opencensus
        component: oc-agent
    spec:
      containers:
        - command:
            - "/ocagent_linux"
            - "--config=/conf/oc-agent-config.yaml"
          image: omnition/opencensus-agent:0.1.6
          name: oc-agent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 55678
            - containerPort: 55679
          #        - containerPort: 14267
          #        - containerPort: 14268
          #        - containerPort: 9411
          volumeMounts:
            - name: oc-agent-config-vol
              mountPath: /conf
      volumes:
        - configMap:
            name: oc-agent-conf
            items:
              - key: oc-agent-config
                path: oc-agent-config.yaml
          name: oc-agent-config-vol
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-collector-conf
  labels:
    app: opencensus
    component: oc-collector-conf
data:
  oc-collector-config: |
    receivers:
      opencensus:
        keepalive:
          server-parameters:
            max-connection-age: 120s
            max-connection-age-grace: 30s
      jaeger: {}
      zipkin: {}
    exporters:
      jaeger:
        collector_endpoint: "http://jaeger-prod-collector.kube-system:14268/api/traces"
    queued-exporters:
      my-org-jaeger:
        num-workers: 2
        queue-size: 100
        retry-on-failure: true
        backoff-delay: 3s
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: "http://jaeger-prod-collector.kube-system:14268/api/traces"
          timeout: 5s
---
apiVersion: v1
kind: Service
metadata:
  name: oc-collector
  labels:
    app: opencesus
    component: oc-collector
spec:
  ports:
    - name: opencensus
      port: 55678
      protocol: TCP
      targetPort: 55678
  #  - name: jaeger-tchannel
  #    port: 14267
  #  - name: jaeger-thrift-http
  #    port: 14268
  #  - name: zipkin
  #    port: 9411
  selector:
    component: oc-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oc-collector
  labels:
    app: opencensus
    component: oc-collector
spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  selector:
    matchLabels:
      app: opencensus
      component: oc-collector
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        app: opencensus
        component: oc-collector
    spec:
      containers:
        - command:
            - "/occollector_linux"
            - "--config=/conf/oc-collector-config.yaml"
          env:
            - name: GOGC
              value: "80"
          image: omnition/opencensus-collector:0.1.6
          name: oc-collector
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 55678
          #        - containerPort: 14267
          #        - containerPort: 14268
          #        - containerPort: 9411
          volumeMounts:
            - name: oc-collector-config-vol
              mountPath: /conf
          #        - name: oc-collector-secrets
          #          mountPath: /secrets
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
      volumes:
        - configMap:
            name: oc-collector-conf
            items:
              - key: oc-collector-config
                path: oc-collector-config.yaml
          name: oc-collector-config-vol
#        - secret:
#            name: oc-collector-secrets
#            items:
#              - key: cert.pem
#                path: cert.pem
#              - key: key.pem
#                path: key.pem

```

I've added the following annotations to the service I want the proxy span to show up:
```
      linkerd.io/inject: enabled
      config.linkerd.io/trace-collector: oc-collector.default:55678
```
But still, none of the proxy spans showed up in my Jaeger UI. (I was able to see system-level traces (trace from jaeger itself), not from `linkerd-proxy` )

What I've done:
- Ensure both the custom opencensus collector and the service also already contains the proxy sidecar container
- Ensure  there isn't any tracing component added in the application code, so there shouldn't be any problem about propagation format that may cause this issue.
- The open census collector is already using default service account.
- I've also looked at other threads with a similar issue : https://stackoverflow.com/questions/65377607/linkerd-distributed-tracing-with-opencensus , but was unable to find any answer/hint to this problem.
- I ran `linkerd check` command and everything is ok.
- Ensure that my jaeger is correctly set up (I was able to see my manually injected span, but not `linkerd-proxy`'s spans)
- I checked `linkerd-proxy` in for one of my microservice instance, and no errors:
```
│ linkerd-proxy time="2021-01-04T19:46:05Z" level=info msg="running version stable-2.9.1"                                                                                        │
│ linkerd-proxy [     0.002410s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime                                                                      │
│ linkerd-proxy [     0.003574s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191                                                                              │
│ linkerd-proxy [     0.003647s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143                                                                            │
│ linkerd-proxy [     0.003670s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140                                                                         │
│ linkerd-proxy [     0.003689s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190                                                                                │
│ linkerd-proxy [     0.003729s]  INFO ThreadId(01) linkerd2_proxy: Local identity is default.default.serviceaccount.identity.linkerd.cluster.local                              │
│ linkerd-proxy [     0.003770s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.ser │
│ linkerd-proxy [     0.003792s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.s │
│ linkerd-proxy [     0.003811s]  INFO ThreadId(01) linkerd2_proxy: OpenCensus tracing collector at oc-collector.default:55678 (default.default.serviceaccount.identity.linkerd. │
│ linkerd-proxy [     0.020259s]  INFO ThreadId(01) outbound: linkerd2_app: listen.addr=127.0.0.1:4140 ingress_mode=false                                                        │
│ linkerd-proxy [     0.020643s]  INFO ThreadId(01) inbound: linkerd2_app: listen.addr=0.0.0.0:4143                                                                              │
│ linkerd-proxy [     0.399641s]  INFO ThreadId(02) daemon:identity: linkerd2_app: Certified identity: default.default.serviceaccount.identity.linkerd.cluster.local
```

Is it because I need to use the custom `linkerd-collector` provided by linkerd instead of using my own custom one?
Any help would be appreciated, thanks a lot! :)
