### DISCUSSION TITLE
Expose service using gateway (2.10.0)

### DISCUSSION THREAD

**Discussion by shahriak** [linkerd/linkerd2#5987] [Q&A]
Hello,

we are planning to upgrade to version 2.10.0. We are currently on version 2.8.1 and using Nginx-ingress (https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/) as the gateway and we included it as a subchart dependency. I have been following the documentation and trying to install linkerd 2.10.0 and it seems like linkerd-multicluster includes nginx ingress gateway as an extension. I am trying to now move away from the dependency chart to this extension, however, upon testing, some things are not working as expected, for example, exposing a service using the Gateway resource.

Here's the steps I am following:

1) Install linkerd 2.10.0
2) Install linkerd-multicluster - A loadbalancer is installed and has an external IP
3) Install emojvoto app
4) Inject emojivoto app with linkerd proxy
5) Create an Nginx-ingress gateway resource to expose service using an external IP:

```
kubectl apply -f - <<EOF
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
  - host: emojivoto
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80
EOF
```
6) kubectl get svc -n linkerd-multicluster (copy the external ip)
7) Curl the app:  curl -H "Host: emojivoto" https://20.69.135.223/api -k (external ip copied from step 6)
error message:
curl: (28) Failed to connect to 20.69.135.223 port 443: Connection timed out

I was previously able to get a successful response when I used the nginx-ingress chart directly as a dependency instead of the built-in gateway provided by linkerd-multicluster. Is there anything I am missing here?
