### DISCUSSION TITLE
Traefik loses Client IP when injecting Linkerd

### DISCUSSION THREAD

**Discussion by BenB196** [linkerd/linkerd2#5990] [Q&A]
Hi All,

I am trying to use linkerd with traefik and am running into a issue, where is I inject traefik with ```ingress```, it causes all IPs in traefik logs to show up as 127.0.0.1. If I un-inject linkerd from traefik I see the client IPs in the traefik logs again.

I've also tried injecting linkerd via ```enabled``` as well and got the same issue.

I believe this is either an issue with how linkerd/traefik interacts, because if I replace traefik with nginx, everything works fine.

Any help on this would be greatly appreciated as I've been stuck on this issue for a while now.

See below for deployment specific stuff.

Linkerd - 2.10.0
Traefik - 2.4.8

Traefik deployed via Helm: 

```
additionalArguments: []
additionalVolumeMounts: []
affinity: {}
autoscaling:
  enabled: false
deployment:
  additionalContainers: []
  additionalVolumes: []
  annotations: {}
  enabled: true
  imagePullSecrets: []
  initContainers: []
  kind: Deployment
  labels: {}
  podAnnotations:
    config.linkerd.io/proxy-cpu-limit: 300m
    config.linkerd.io/proxy-cpu-request: 100m
    config.linkerd.io/skip-inbound-ports: '80,443'
    linkerd.io/inject: ingress
  podLabels: {}
  replicas: 1
env: []
envFrom: []
experimental:
  kubernetesGateway:
    appLabelSelector: traefik
    certificates: []
    enabled: false
  plugins:
    enabled: false
globalArguments:
  - '--global.checknewversion'
  - '--global.sendanonymoususage'
hostNetwork: false
image:
  name: traefik
  pullPolicy: IfNotPresent
  tag: ''
ingressClass:
  enabled: false
  isDefaultClass: false
ingressRoute:
  dashboard:
    annotations: {}
    enabled: true
    labels: {}
logs:
  access:
    enabled: true
    fields:
      general:
        defaultmode: keep
        names: {}
      headers:
        defaultmode: drop
        names: {}
    filters: {}
  general:
    level: ERROR
nodeSelector: {}
persistence:
  accessMode: ReadWriteOnce
  annotations: {}
  enabled: false
  name: data
  path: /data
  size: 128Mi
pilot:
  enabled: false
  token: ''
podDisruptionBudget:
  enabled: false
podSecurityContext:
  fsGroup: 65532
podSecurityPolicy:
  enabled: false
ports:
  traefik:
    expose: true
    exposedPort: 9000
    port: 9000
    protocol: TCP
  web:
    expose: true
    exposedPort: 80
    port: 8000
    protocol: TCP
  websecure:
    expose: true
    exposedPort: 443
    port: 8443
    protocol: TCP
    tls:
      certResolver: ''
      domains: []
      enabled: false
      options: ''
priorityClassName: ''
providers:
  kubernetesCRD:
    enabled: true
    namespaces: []
  kubernetesIngress:
    enabled: true
    namespaces: []
    publishedService:
      enabled: false
rbac:
  enabled: true
  namespaced: false
resources: {}
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsGroup: 65532
  runAsNonRoot: true
  runAsUser: 65532
service:
  annotations: {}
  enabled: true
  externalIPs: []
  labels: {}
  loadBalancerSourceRanges: []
  spec:
    externalTrafficPolicy: Local
  type: LoadBalancer
serviceAccount:
  name: ''
serviceAccountAnnotations: {}
tlsOptions: {}
tolerations: []
volumes: []
global:
  systemDefaultRegistry: ''

```

Linkerd deployed via cli:
```
linkerd install -L linkerd --ha
```

Using Metallb to provide the LoadBalancer IP

Testing using the linkerd-viz web.

```
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: web-ingress-auth
  namespace: linkerd-viz
data:
  auth: LINKERD_DASHBOARD_BASIC_AUTH
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: web-l5d-header-middleware
  namespace: linkerd-viz
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "web.linkerd-viz.svc.cluster.local:8084"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: web-basic-auth
  namespace: linkerd-viz
spec:
  basicAuth:
    secret: web-ingress-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web-ingress
  namespace: linkerd-viz
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: "Host(`LINKERD_DASHBOARD_URL`)"
      middlewares:
        - name: web-l5d-header-middleware
        - name: web-basic-auth
      services:
        - kind: Service
          name: web
          port: 8084
```
