### DISCUSSION TITLE
ArgoCD Rollouts with Linkerd & Ingress controller (nginx)

### DISCUSSION THREAD

**Discussion by haim-ari** [linkerd/linkerd2#6094] [Q&A] [answered]
Hello,
I’m trying to configure `Argo Rollouts` with `Linkerd`.
The issue i’m having is that, while I do see the Traffic-Split (`TS`) created and progressing with weights over time, when I test the `Ingress` (`nginx`) address, I always see the same version of the app. 

Only when the `canary rollout` is completed I get the new app version response. 
Also, in the `Linkerd` UI, I don’t see any `SR` at all.

## Issue
While the TS progressing 90-10… until 100 no requests are served by the canary service when I try the ingress endpoint.
![image](https://user-images.githubusercontent.com/4179195/116978031-d6fa5280-accb-11eb-90e3-baa6a025294a.png)

Here are some `yaml` from the `Helm chart` & UI screenshots

<img width="2557" alt="Screen Shot 2021-05-04 at 11 30 37" src="https://user-images.githubusercontent.com/4179195/116978376-4cfeb980-accc-11eb-8605-1a61278f85b4.png">

## rollout.yaml

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "infoevent.fullname" . }}
  labels:
    app: {{ .Release.Name }}
    version: {{ .Chart.AppVersion }}
spec:
  strategy:
    canary:
      # Reference to a Service which the controller will update to point to the canary ReplicaSet
      canaryService: "rollout-{{ .Release.Name }}-canary"
      # Reference to a Service which the controller will update to point to the stable ReplicaSet
      stableService: "rollout-{{ .Release.Name }}-stable"
      trafficRouting:
        smi: {}
      steps:
      - setWeight: 10
      - pause: {duration: 2m}
      - setWeight: 25
      - pause: {duration: 2m}
      - setWeight: 50
      - pause: {duration: 2m}
      - setWeight: 75
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "infoevent.selectorLabels" . | nindent 6 }}
      app: {{ .Release.Name }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "infoevent.selectorLabels" . | nindent 8 }}
        app: {{ .Release.Name }}
        version: {{ .Chart.AppVersion }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "infoevent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if eq .Values.dc "amazon_va" }}
      nodeSelector:
        instance: "{{ .Values.nodeSelector.instance }}"
      tolerations:
      - key: "{{ .Values.tolerations.key }}"
        operator: "{{ .Values.tolerations.operator }}"
        effect: "{{ .Values.tolerations.effect }}"
      {{ end }}  
      containers:
      - env:
        - name: DC_NAME
          value: "{{ .Values.dc }}"
        - name: DC
          value: "{{ .Values.dc }}"
        - name: APPD_TIER
          value: "{{ .Values.appd_tier }}"
        - name: APPD_OPTS
          value: "{{ .Values.java_options }}"
        - name: APPD_APP_NAME
          value: "{{ .Values.appd_app_name }}"
        - name: JMX_REMOTE_PORT
          value: "{{ .Values.jmx_remote_port }}"
        - name: IMAGE_TAG
          value: "{{ .Values.image.tag }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: "/{{ .Release.Name }}/checkinit/final"
            port: 8402
            scheme: HTTP
          initialDelaySeconds: 150
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        name: infoevent
        ports:
        - containerPort: 8402
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: "/{{ .Release.Name }}/checkinit/final"
            port: 8402
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "{{ .Values.resources.limits.cpu }}"
            memory: "{{ .Values.resources.limits.memory }}"
          requests:
            cpu: "{{ .Values.resources.requests.cpu }}"
            memory: "{{ .Values.resources.requests.memory }}"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /AppAgent.4.3.0.2
          name: shared-data
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - my-domain.com
      initContainers:
      - args:
        - cp -r /AppAgent.4.3.0.2/* /appd/
        command:
        - /bin/sh
        - -c
        image: registry.my-registry/adplatform/appdynamics/rtb:4.3.0.2-v0.2.3
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: appdagent
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /appd
          name: shared-data
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: rtbmicroservice-infoevent
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: shared-data
```

## Ingress.yaml

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "rollouts-{{ .Release.Name }}-stable"
  namespace: production
  labels:
    app: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      # proxy_hide_header l5d-remote-ip;
      # proxy_hide_header l5d-server-id;
spec:
  rules:
    - host: {{ .Release.Name }}.my-domain.com
      http:
        paths:
        # - path: "/infoevent"
          - backend:
              serviceName: "rollout-{{ .Release.Name }}-stable"
              servicePort: 8402
```
## services.yaml

```yaml
apiVersion: v1
kind: Service
metadata:
  name: rollout-{{ .Release.Name }}-canary
spec:
  ports:
  - port: 8402
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
    # This selector will be updated with the pod-template-hash of the canary ReplicaSet. e.g.:
    # rollouts-pod-template-hash: 7bf84f9696
---
apiVersion: v1
kind: Service
metadata:
  name: rollout-{{ .Release.Name }}-stable
spec:
  ports:
  - port: 8402
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
    # This selector will be updated with the pod-template-hash of the stable ReplicaSet. e.g.:
    # rollouts-pod-template-hash: 789746c88d
```
## values.yaml

```yaml
# Default values for prd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# replicaCount: 2
image:
  repository: "registry.my-domain
<img width="2557" alt="Screen Shot 2021-05-04 at 11 30 37" src="https://user-images.githubusercontent.com/4179195/116978304-33f60880-accc-11eb-943b-4416e31246ed.png">
.com/adplatform/infoevent"
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: v0.1.53
  version: ""
imagePullSecrets: [
  name: regcred
]
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
podAnnotations:
  linkerd.io/inject: enabled 
  config.linkerd.io/proxy-cpu-limit: "1"
  config.linkerd.io/proxy-cpu-request: "0.2"
  config.linkerd.io/proxy-memory-limit: 2Gi
  config.linkerd.io/proxy-memory-request: 128Mi
podSecurityContext: {}
  # fsGroup: 2000
securityContext: 
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
service:
  type: ClusterIP
  port: None
  targetPort: None 
ingress:
  enabled: true

resources:
  limits:
    cpu: "4000m"
    memory: "8192Mi"
  requests:
    cpu: "2000m"
    memory: "4096Mi"
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65
  # targetMemoryUtilizationPercentage: 90
tolerations: []
affinity: {}
port: "8402"
public: "true"
dc: ""
```

**Comment by haim-ari** [comment]
## Update

I noticed there is something wrong with `Ingress-nginx-admission-patch`

```bash
kubectl get pods -n ingress-nginx
NAME                                  READY   STATUS     RESTARTS   AGE
flagger-674b58f457-94vj4              1/1     Running    0          6d19h
flagger-prometheus-596d6965cb-xpf2f   1/1     Running    0          6d19h
ingress-nginx-admission-patch-knwsb   1/2     NotReady   1          2m36s
ingress-nginx-controller-5j2mt        1/1     Running    0          4m19s
ingress-nginx-controller-gcx6j        1/1     Running    0          3m56s
ingress-nginx-controller-wgccs        1/1     Running    0          3m22s
```

I tried to remove the ingress `annotation` for Linkerd, but that didn't help as well

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
  annotations:
    fluxcd.io/ignore: "false"
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '3.12.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  values:
    controller:
      metrics:
        enabled: "true"
      podAnnotations:
       #  linkerd.io/inject: ingress 
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
      hostNetwork: "true"
      kind: DaemonSet
      service:
        type: NodePort
```

```
[~] kubectl logs -f ingress-nginx-admission-patch-knwsb -n ingress-nginx -c linkerd-proxy
```

```
time="2021-05-04T09:22:54Z" level=info msg="running version stable-2.10.1"
[     0.005507s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.006760s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.006789s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.006795s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.006800s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.006806s]  INFO ThreadId(01) linkerd2_proxy: Local identity is ingress-nginx-admission.ingress-nginx.serviceaccount.identity.linkerd.cluster.local
[     0.006811s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.006817s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.006822s]  INFO ThreadId(01) linkerd2_proxy: OpenCensus tracing collector at collector.linkerd-jaeger:55678 (collector.linkerd-jaeger.serviceaccount.identity.linkerd.cluster.local)
[     0.019296s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity: ingress-nginx-admission.ingress-nginx.serviceaccount.identity.linkerd.cluster.local
```

```
[~] kubectl logs -f ingress-nginx-admission-patch-knwsb -n ingress-nginx -c linkerd-init
```

```
2021/05/04 09:22:52 Tracing this script execution as [1620120172]
2021/05/04 09:22:52 current state
------------------------------------------------------------
2021/05/04 09:22:52 :; iptables-save
2021/05/04 09:22:52

2021/05/04 09:22:52 configuration
------------------------------------------------------------
2021/05/04 09:22:52 Will ignore port [4190 4191] on chain PROXY_INIT_REDIRECT
2021/05/04 09:22:52 Will redirect all INPUT ports to proxy
2021/05/04 09:22:52 Ignoring uid 2102
2021/05/04 09:22:52 Redirecting all OUTPUT to 4140
2021/05/04 09:22:52

2021/05/04 09:22:52 adding rules
------------------------------------------------------------
2021/05/04 09:22:52 :; iptables -t nat -N PROXY_INIT_REDIRECT -m comment --comment proxy-init/redirect-common-chain/1620120172
2021/05/04 09:22:52 :; iptables -t nat -A PROXY_INIT_REDIRECT -p tcp --match multiport --dports 4190,4191 -j RETURN -m comment --comment proxy-init/ignore-port-4190,4191/1620120172
2021/05/04 09:22:52 :; iptables -t nat -A PROXY_INIT_REDIRECT -p tcp -j REDIRECT --to-port 4143 -m comment --comment proxy-init/redirect-all-incoming-to-proxy-port/1620120172
2021/05/04 09:22:52 :; iptables -t nat -A PREROUTING -j PROXY_INIT_REDIRECT -m comment --comment proxy-init/install-proxy-init-prerouting/1620120172
2021/05/04 09:22:53 :; iptables -t nat -N PROXY_INIT_OUTPUT -m comment --comment proxy-init/redirect-common-chain/1620120172
2021/05/04 09:22:53 :; iptables -t nat -A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -o lo ! -d 127.0.0.1/32 -j PROXY_INIT_REDIRECT -m comment --comment proxy-init/redirect-non-loopback-local-traffic/1620120172
2021/05/04 09:22:53 :; iptables -t nat -A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -j RETURN -m comment --comment proxy-init/ignore-proxy-user-id/1620120172
2021/05/04 09:22:53 :; iptables -t nat -A PROXY_INIT_OUTPUT -o lo -j RETURN -m comment --comment proxy-init/ignore-loopback/1620120172
2021/05/04 09:22:53 :; iptables -t nat -A PROXY_INIT_OUTPUT -p tcp -j REDIRECT --to-port 4140 -m comment --comment proxy-init/redirect-all-outgoing-to-proxy-port/1620120172
2021/05/04 09:22:53 :; iptables -t nat -A OUTPUT -j PROXY_INIT_OUTPUT -m comment --comment proxy-init/install-proxy-init-output/1620120172
2021/05/04 09:22:53

2021/05/04 09:22:53 end state
------------------------------------------------------------
2021/05/04 09:22:53 :; iptables-save
2021/05/04 09:22:53 # Generated by iptables-save v1.8.2 on Tue May  4 09:22:53 2021
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:PROXY_INIT_OUTPUT - [0:0]
:PROXY_INIT_REDIRECT - [0:0]
-A PREROUTING -m comment --comment "proxy-init/install-proxy-init-prerouting/1620120172" -j PROXY_INIT_REDIRECT
-A OUTPUT -m comment --comment "proxy-init/install-proxy-init-output/1620120172" -j PROXY_INIT_OUTPUT
-A PROXY_INIT_OUTPUT ! -d 127.0.0.1/32 -o lo -m owner --uid-owner 2102 -m comment --comment "proxy-init/redirect-non-loopback-local-traffic/1620120172" -j PROXY_INIT_REDIRECT
-A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -m comment --comment "proxy-init/ignore-proxy-user-id/1620120172" -j RETURN
-A PROXY_INIT_OUTPUT -o lo -m comment --comment "proxy-init/ignore-loopback/1620120172" -j RETURN
-A PROXY_INIT_OUTPUT -p tcp -m comment --comment "proxy-init/redirect-all-outgoing-to-proxy-port/1620120172" -j REDIRECT --to-ports 4140
-A PROXY_INIT_REDIRECT -p tcp -m multiport --dports 4190,4191 -m comment --comment "proxy-init/ignore-port-4190,4191/1620120172" -j RETURN
-A PROXY_INIT_REDIRECT -p tcp -m comment --comment "proxy-init/redirect-all-incoming-to-proxy-port/1620120172" -j REDIRECT --to-ports 4143
COMMIT
# Completed on Tue May  4 09:22:53 2021

2021/05/04 09:22:53
```

## When adding the PodAnnotation for the ingress, This is how it looks:

```
kubectl describe pod/ingress-nginx-controller-m5wkn -n ingress-nginx
Name:         ingress-nginx-controller-m5wkn
Namespace:    ingress-nginx
Priority:     0
Node:         sin-prd-k8s-worker2.my-domain.com/10.199.199.76
Start Time:   Tue, 04 May 2021 12:33:10 +0300
Labels:       app.kubernetes.io/component=controller
              app.kubernetes.io/instance=ingress-nginx
              app.kubernetes.io/name=ingress-nginx
              controller-revision-hash=67467bbccd
              pod-template-generation=10
Annotations:  cattle.io/timestamp: 2021-05-04T09:20:54Z
              linkerd.io/inject: ingress
              prometheus.io/port: 10254
              prometheus.io/scrape: true
Status:       Running
IP:           10.199.199.76
IPs:
  IP:           10.199.199.76
Controlled By:  DaemonSet/ingress-nginx-controller
Containers:
  controller:
    Container ID:  docker://029a627b1ee01ea9cdf8811d186781b14b1e094c4a04c8e8583d45ac3fc0b70d
    Image:         k8s.gcr.io/ingress-nginx/controller:v0.41.2@sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de
    Image ID:      docker-pullable://k8s.gcr.io/ingress-nginx/controller@sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de
    Ports:         80/TCP, 443/TCP, 10254/TCP, 8443/TCP
    Host Ports:    80/TCP, 443/TCP, 10254/TCP, 8443/TCP
    Args:
      /nginx-ingress-controller
      --publish-service=$(POD_NAMESPACE)/ingress-nginx-controller
      --election-id=ingress-controller-leader
      --ingress-class=nginx
      --configmap=ingress-nginx/ingress-nginx-controller
      --validating-webhook=:8443
      --validating-webhook-certificate=/usr/local/certificates/cert
      --validating-webhook-key=/usr/local/certificates/key
    State:          Running
      Started:      Tue, 04 May 2021 12:33:11 +0300
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      100m
      memory:   90Mi
    Liveness:   http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=5
    Readiness:  http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:       ingress-nginx-controller-m5wkn (v1:metadata.name)
      POD_NAMESPACE:  ingress-nginx (v1:metadata.namespace)
      LD_PRELOAD:     /usr/local/lib/libmimalloc.so
    Mounts:
      /usr/local/certificates/ from webhook-cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from ingress-nginx-token-447bb (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  webhook-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-nginx-admission
    Optional:    false
  ingress-nginx-token-447bb:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-nginx-token-447bb
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                 node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists
                 node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                 node.kubernetes.io/unreachable:NoExecute op=Exists
                 node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason            Age                From                      Message
  ----     ------            ----               ----                      -------
  Normal   Scheduled         54s                default-scheduler         Successfully assigned ingress-nginx/ingress-nginx-controller-m5wkn to sin-prd-k8s-worker2.my-domain.com
  Normal   Pulled            55s                kubelet                   Container image "k8s.gcr.io/ingress-nginx/controller:v0.41.2@sha256:1f4f402b9c14f3ae92b11ada1dfe9893a88f0faeb0b2f4b903e2c67a0c3bf0de" already present on machine
  Normal   Created           55s                kubelet                   Created container controller
  Normal   Started           54s                kubelet                   Started container controller
  Warning  DNSConfigForming  53s (x4 over 55s)  kubelet                   Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 8.8.8.8 8.8.4.4 192.168.8.88
  Normal   RELOAD            53s                nginx-ingress-controller  NGINX reload triggered due to a change in configuration
```

When I re-added the annotation it seems to be set on the ingress pods, but still traffic is not shifting correctly

```
kubectl -n ingress-nginx describe pod/ingress-nginx-controller-gsv8r| grep "linkerd.io/inject: ingress"
```

```
linkerd.io/inject: ingress
```

![image](https://user-images.githubusercontent.com/4179195/116986803-eaf78180-acd6-11eb-93d9-a5035e78bda0.png)
