### DISCUSSION TITLE
Linkerd webhook namespaceSelector, values for AKS?

### DISCUSSION THREAD

**Discussion by johnmckenna** [linkerd/linkerd2#6193] [Q&A]
As mentioned in issue #3305 the namespaceSelector doesn't exclude the control plane in AKS.

I'm installing components  in AKS and was wanting to make sure if the configuration at the end of this question is correct for the helm charts for linkerd2-cni, linkerd2, linkerd-viz and linkerd-jaeger?

Microsoft suggest the following:

https://docs.microsoft.com/en-us/azure/aks/faq

Can I use admission controller webhooks on AKS?

Yes, you may use admission controller webhooks on AKS. It's recommended you exclude internal AKS namespaces, which are marked with the control-plane label. For example, by adding the below to the webhook configuration:
```
namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
```
linkerd2:
```
proxyInjector:
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
    - key: control-plane
      operator: DoesNotExist

profileValidator:
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
    - key: control-plane
      operator: DoesNotExist
```
linkerd-viz:
```
tapInjector:
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
```
linkerd-jaeger:
```
webhook:
  namespaceSelector:
    matchExpressions:
    - key: control-plane
      operator: DoesNotExist
```
Looks like this error still occurs with ```linkerd check``` even though I've applied the above configuration:
```
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/2.10/checks/#l5d-injection-disabled for hints
```
Thank you!
