### DISCUSSION TITLE
How to correctly do Automatic Proxy Injection?

### DISCUSSION THREAD

**Discussion by hongbo-miao** [linkerd/linkerd2#6349] [Q&A] [answered]
Hi everyone! I am reading [Automatic Proxy Injection](https://linkerd.io/2.10/features/proxy-injection/#) section, I thought if I add

```yml
      annotations:
        linkerd.io/inject: enabled
```

like

```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go-deployment
  namespace: hm
spec:
  ...
  template:
    metadata:
      labels:
        component: api-go
      annotations:
        linkerd.io/inject: enabled
```

After deploying by, for example, Helm by `helm install mychart mychart`, it will be auto injected instead of manually running

```sh
kubectl get deployments --namespace=hm --output=yaml | linkerd inject - | kubectl apply -f -
```

But turns out I am wrong.

I am wondering what is the right way for Automatic Proxy Injection? Thanks!
