### DISCUSSION TITLE
Traefik `l5d-dst-override` header

### DISCUSSION THREAD

**Discussion by WLun001** [linkerd/linkerd2#6351] [Q&A]
Based on the [docs](https://linkerd.io/2.10/tasks/using-ingress/#traefik-2-x), means have to define `l5d-dst-override` request headers for all services that are proxy through Traefik?

Example config to illustrate what I trying to say

```yaml
# web-svc 1
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: l5d-1
  namespace: emojivoto
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "web-svc.emojivoto.svc.cluster.local:80"
---
# web-svc 2
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: l5d-2
  namespace: emojivoto
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "web2-svc.emojivoto.svc.cluster.local:80"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: emojivoto-web-ingress-route
  namespace: emojivoto
spec:
  entryPoints: []
  routes:
  - kind: Rule
    match: PathPrefix(`/web`)
    middlewares:
      - name: l5d-1
    services:
      - name: web-svc #web-svc 1
        port: 80
  - kind: Rule
    match: PathPrefix(`/web2`)
    middlewares:
      - name: l5d-2
    services:
      - name: web2-svc  #web-svc 2
      - port: 80
```
