### DISCUSSION TITLE
Role of the identityTrustAnchorsPEM Helm parameter when cert-manager CA injector is used

### DISCUSSION THREAD

**Discussion by sysarch-repo** [linkerd/linkerd2#6771] [Q&A] [answered]
I can use the CA-injector of the cert-manager to insert the CA bundle in the config of the validating/mutating webhook used by the linkerd SP validator and proxy injector. Example:

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    ...
  annotations:
    cert-manager.io/inject-ca-from-secret: nti-security/cert-manager-linkerd-ca
```

I assume, there is no other use for the identityTrustAnchorsPEM Helm parameter across linkerd, or is the parameter utilized in other operations than defining the CA bundle in the webhook configs? If not, I could remove the CA cert from the install process completely - less deployment artifacts.
