### DISCUSSION TITLE
Alternative to disabling webhooks inside the linkerd namespace

### DISCUSSION THREAD

**Discussion by sysarch-repo** [linkerd/linkerd2#6773] [Q&A] [answered]
In case linkerd must be installed in a customer pre-defined namespace that does not allow additional labels, can the disabling of the webhooks for the linkerd components be simply added as an expression in the webhook config?
Example:

```
    namespaceSelector:
      matchExpressions:
      - key: config.linkerd.io/admission-webhooks
        operator: NotIn
        values:
        - disabled
      - key: "name"
        operator: "NotIn"
        values:
        - <linkerd-namespace>
```
