### DISCUSSION TITLE
Problem accessing Linkerd dashboard due to dns rebinding errors with Traefik

### DISCUSSION THREAD

**Discussion by MatteoGioioso** [linkerd/linkerd2#6859] [General] [answered]
I am trying to access the linkerd dashboard, however I still have the following error:

```
It appears that you are trying to reach this service with a host of 'yourcompany.com'.
This does not match /^(localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|\[::1\])(:\d+)?$/ and has been denied for security reasons.
Please see https://linkerd.io/dns-rebinding for an explanation of what is happening and how to fix it.
```

I went to the link and try to fix it, by creating a middleware or simply add the annotation like suggested in the docs: https://linkerd.io/2.10/tasks/exposing-dashboard/#traefik

However both solutions are not working. 

This is my IngressRoute:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: linkerd-dashboard-ingress
  namespace: linkerd-viz
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:web.linkerd-viz.svc.cluster.local:8084
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`{{.Values.linkerd.host}}`)"
      kind: Rule
      services:
        - name: web
          kind: Service
          port: 8084
      priority: 1
      middlewares:
        - name: linkerd-viz-l5d-header-middleware
          namespace: linkerd-viz
  tls:
    domains:
      - main: {{.Values.linkerd.host}}
    secretName: linkerd-dashboard-ssl-cert
```

This is my middleware

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: linkerd-viz-l5d-header-middleware
  namespace: linkerd-viz
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "web.linkerd-viz.svc.cluster.local:8084"
```

Linkerd installation script:

```
linkerd check --pre && linkerd install | kubectl apply -f - && linkerd viz install | kubectl apply -f - && linkerd check
```

Linkerd version (CLI):

```
Client version: stable-2.10.2
Server version: stable-2.10.2
```

EKS version: 1.20

Any idea? Thanks
