### DISCUSSION TITLE
Service profiles and nginx ingress

### DISCUSSION THREAD

**Discussion by schwichti** [linkerd/linkerd2#6965] [Q&A]
Hi,

I am using Linkerd edge-21.9.3 in conjunction with nginx ingress controller. I want to configure service profiles for retries and timeouts. 
Sidecars are up and running.
As described at https://linkerd.io/2.10/tasks/using-ingress/#nginx, I have added the annotation to my Ingresses:
`nginx.ingress.kubernetes.io/service-upstream: true`.

The service profile looks like this (values are for debugging):
```yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: appshell.simphera.svc.cluster.local
  namespace: simphera
spec:
  routes:
  - name: 'GET /projects'
    condition:
      pathRegex: '/projects'
      method: GET
    isRetryable: true
    timeout: 60000ms
  retryBudget:
    retryRatio: 1.0
    minRetriesPerSecond: 10
    ttl: 10s
```

Retries does not seem to work and when I run `linkerd viz routes` this is what I see:
```
ROUTE            SERVICE   SUCCESS   RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99
GET /projects   appshell         -     -             -             -             -
[DEFAULT]       appshell         -     -             -             -             -
```

Any hint what is going wrong?
