### DISCUSSION TITLE
GKE - Ingress "Unmeshed"

### DISCUSSION THREAD

**Discussion by sonicSW** [linkerd/linkerd2#7764] [Q&A] [answered]
Dear community,

I am struggling to update the GKE ingress controller to include traffic from external IPs.
The full ingress route is Cloudflare-->GCP-LB-->GKE in my case and the result remains for external request:
Unmeshed
ip/130.211.3.76
ip/130.211.1.53
ip/130.211.3.62

I followed the guide https://linkerd.io/2.11/tasks/using-ingress/#gce. 
I removed the line for the cert-manager as I use a secret file, is this supported?
What I do not understand, is it "suggests" I would have a web-svc in namespace XYZ, but nothing is installed with linked or shall this be a service pointing to my deployments? In this case, what to do with multiple services I have mapped in the ingress controller.
Probably the answer is so obvious and I just lost the plot.

thank you already to the person for taking the time to read my QA post.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.project }}-ingress
  namespace: {{ .Values.global.nameSpace }}
  
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    kubernetes.io/ingress.allow-http: "false"

    # WebSockets Support
    cloud.google.com/backend-config: '{"ports": {"80":"{{ .Values.webSocket.instanceShort }}-backend"}}'
    cloud.google.com/neg: '{"ingress": true}'

    #Linkerd 2.11.1
    ingress.kubernetes.io/custom-request-headers: "l5d-dst-override: web-svc.{{ .Values.global.nameSpace }}.svc.cluster.local:80"
```
