### DISCUSSION TITLE
Unmeshed Ingress

### DISCUSSION THREAD

**Discussion by sonicSW** [linkerd/linkerd2#7920] [General]
Dear all,
I am struggling to implement ingress and to get it to work. 

In GKE I use the inkerd.io/inject: ingress annotation in my deployments which are facing incoming traffic, other internal services I left (for example redis with the annotation enabled <-- correct?)

The service pointing to the deployment, running as a simple hello world:

```
apiVersion: v1
kind: Service

metadata:
  name: hello-service
  namespace: test
  
spec:
  selector:
    app: hello-app
    
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80}
```

In googles ingress config I defined

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: test
  
  annotations:
    kubernetes.io/ingress.global-static-ip-name: hello-ip
    kubernetes.io/ingress.allow-http: "false"

    #LinkerD Ingess
    ingress.kubernetes.io/custom-request-headers: "l5d-dst-override: hello-service.test.svc.cluster.local:80"

spec:
  tls:
  - hosts:
    - SOME-URL.SOMETHING.COM
    secretName: tls-ssl
  rules:
  - host: SOME-URL.SOMETHING.COM
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: hello-service
            port:
              number: 80
```

What remains is still all requests are shown from external as unmeshed...
![image](https://user-images.githubusercontent.com/95349556/154669576-15b9356f-5c94-4d7b-84b0-75f912e6b606.png)

where do I go wrong?
