### DISCUSSION TITLE
"linkerd viz edges po -A" returns "No edges found."

### DISCUSSION THREAD

**Discussion by stevehuangc7s** [linkerd/linkerd2#8192] [Q&A] [answered]
I have installed the `linkerd` and `linkerd-viz` with helm charts in my EKS cluster at 1.18, where the helm repo is https://helm.linkerd.io/stable and chart version is `2.11.1` for both charts. Then I followed steps from https://linkerd.io/2.11/getting-started/#step-4-install-the-demo-app to install the demo app. When trying to see if the mTLS is properly enabled for the demo app, I got `No edges found.` in response to command `linkerd viz edges po -A`.

To investigate the issue, I have tried the `linkerd check`, `linkerd viz check` and `linkerd check --proxy`. All check returned one issue - `‼ prometheus is installed and configured correctly`. And `linkerd check --proxy` returned one more issue:
```console
‼ data plane proxy metrics are present in Prometheus
    Data plane metrics not found for emojivoto/vote-bot-64dd87cb87-qwl67, emojivoto/voting-f7f875999-hk69p, emojivoto/web-5798f7d79f-czq48, emojivoto/emoji-5f947b5dbd-m6shh.
```
I am not sure if it's relevant to the `linkerd viz edges` problems but I used an existing prometheus setup from within the EKS cluster in `monitoring` namespace for the `linkerd-viz` installation. Please see below the chart values for more information. Could you please suggest what I can do to fix the problem and to validate if mTLS is enabled?

Please see below my values for both charts:
```yaml
# values for linkerd
  valuesFrom:
    - kind: Secret
      name: linkerd-certs
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.crt
      targetPath: identity.issuer.tls.crtPEM
    - kind: Secret
      name: linkerd-certs
      valuesKey: issuer.key
      targetPath: identity.issuer.tls.keyPEM

  # Default values
  # https://artifacthub.io/packages/helm/linkerd2/linkerd2
  values:
    installNamespace: false
    enablePodAntiAffinity: true

    # proxy configuration
    proxy:
      resources:
        cpu:
          request: 100m
        memory:
          limit: 250Mi
          request: 20Mi

    # controller configuration
    controllerReplicas: 3
    controllerResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi
    destinationResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi

    # identity configuration
    identityResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 10Mi

    # heartbeat configuration
    heartbeatResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi

    # proxy injector configuration
    proxyInjectorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi

    webhookFailurePolicy: Fail

    # service profile validator configuration
    spValidatorResources:
      cpu:
        limit: ""
        request: 100m
      memory:
        limit: 250Mi
        request: 50Mi

# values for linkerd-viz
  values:
    linkerdNamespace: linkerd
    installNamespace: false
    namespace: linkerd-viz
    prometheusUrl: "http://prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
    grafanaUrl: "http://prometheus-stack-grafana.monitoring.svc.cluster.local:80"
    grafana:
      enabled: false
    prometheus:
      enabled: false
```
