### DISCUSSION TITLE
TrafficSplit + Ingress

### DISCUSSION THREAD

**Discussion by lucasgrvarela** [linkerd/linkerd2#8726] [Help] [answered]
How do I make the TrafficSplit/ServiceProfile work with ingress?

We have setup 3 services and created the TrafficSplit config, we tested it and worked well internally but not outside.
```
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: canary-split
  namespace: sre-sandbox
spec:
  service: nginx-prod
  backends:
  - service: nginx-prod
    weight: 50
  - service: nginx-baseline
    weight: 25
  - service: nginx-canary
    weight: 25
```

The ServiceProfile was created automatically by the TrafficSplit
```
$ k get sp -n sre-sandbox
NAME                                       AGE
nginx-prod.sre-sandbox.svc.cluster.local   45m
```

If I call my root service inside a pod in the cluster, it's working and we can see the traffic being splitted for the three services we configured. Example:
```
root@pod-test-canary:/# for i in {1..5}; do curl nginx-prod; done
nginx-prod
nginx-baseline
nginx-canary
nginx-baseline
nginx-baseline
...
```

ExternalService
```
$ k -n sre-sandbox get svc
NAME                      TYPE           CLUSTER-IP    EXTERNAL-IP                                PORT(S)   AGE
nginx-external-resolver   ExternalName   <none>        nginx-prod.sre-sandbox.svc.cluster.local   80/TCP    6m42s
```

Ingress manifest
```
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/service-upstream: "true"
    name: nginx-ingress
    namespace: sre-sandbox
  spec:
    rules:
    - host: canary.abc.com
      http:
        paths:
        - backend:
            service:
              name: nginx-external-resolver
              port:
                number: 80
          path: /
          pathType: ImplementationSpecific
```

My /etc/hosts
```
35.xxx.xxx.xxx canary.abc.com
```

Example calling from outside passing by Ingress.
```
$ for i in {1..100}; do curl canary.abc.com; done
nginx-prod
nginx-prod
nginx-prod
nginx-prod
nginx-prod
...
```

I have the impression the TrafficSplit is being ignored by Ingress for some reason. Any suggestion how to do that?
