### DISCUSSION TITLE
Helm resource requests and limits are declared differently than kubernetes

### DISCUSSION THREAD

**Discussion by mladedav** [linkerd/linkerd2#8991] [General] [answered]
Kubernetes usually follows
```
resources:
  requests:
    memory:
    cpu:
  limits:
    memory:
    cpu:
```
while linkerd helm chart follows
```
resources:
  cpu:
    limit:
    request:
  memory:
    limit:
    request:
```
Is there a reason for this? Wouldn't it be easier for users to keep the structure that is widely used, especially since it is so similar?
