### DISCUSSION TITLE
Linkerd 2.12.0 injects proxies into control plane pods

### DISCUSSION THREAD

**Discussion by ngc4579** [linkerd/linkerd2#9276] [Q&A] [answered]
We've just upgraded vom Linkerd 2.11.4 to 2.12.0 and notice Linkerd (now?) injects data plane proxies into the control plane. I actually can't quite remember if this was the case before the upgrade - the control plane has been installed into the exact same namespace set up as follows:

```
labels:
    config.linkerd.io/admission-webhooks: disabled
    field.cattle.io/projectId: p-fr8ck
    kubernetes.io/metadata.name: linkerd
    linkerd.io/control-plane-ns: linkerd
    linkerd.io/is-control-plane: "true"
  annotations:
    ...
    linkerd.io/inject: disabled
```

Is this somewhat intended behaviour? Especially as the namespace is annotated as `linkerd.io/inject: disabled` I'd rather assume the control plane pods don't get injected with data plane proxies.

As a side note...: I've only noticed the above because of a success rate below 100% for both `linkerd` and `linkerd-viz` namespaces - some yet unidentified component of our Rancher 2 environment keeps unsuccessfully requesting control plane pods.

```
[124341.307486s]   INFO ThreadId(01)  inbound:server{port=9996}:rescue{client.addr=10.10.0.114:37276}:  linkerd_app_core::errors::respond: Request failed error=connection  closed before message completed
[124341.307490s] WARN ThreadId(01) inbound:server{port=9996}:rescue{client.addr=10.10.0.114:37276}: linkerd_app_inbound::http::server: Unexpected error error=connection closed before message completed
```

The origin IP is one of some DaemonSet pods on the same node...

```
canal (rancher/mirrored-calico-node:v3.19.2)
cattle-node-agent (rancher/rancher-agent:2.6.3)
csi-cinder-nodeplugin (k8s.gcr.io/sig-storage/csi-node-driver-registrar:v1.3.0)
pushprox-kube-proxy-client (rancher/pushprox-client:v0.1.0-rancher2-client)
rancher-monitoring-prometheus-node-exporter (rancher/mirrored-prometheus-node-exporter:v1.2.2)
```

... But - as mentioned above - that was only the root cause that had me look into the control plane noticing it suddenly (?) has data plane proxies injected.
