### DISCUSSION TITLE
Setting limits on Prometheus Pod

### DISCUSSION THREAD

**Discussion by arunxls** [linkerd/linkerd2#9352] [General] [answered]
* might be a dup of https://github.com/linkerd/linkerd2/issues/4122

I'm looking for flags that we can set to limit prometheus memory usage. I looked at the values.yaml but couldn't find anything to specify this. Would love some pointers on how we can configure this at linkerd install.

Thanks!

**Comment by Sierra1011** [comment, marked as answer]
It is definitely possible. If you're using the Helm chart the relevant section of the values file is [right at the bottom](https://github.com/linkerd/linkerd2/blob/b3710e4c66c46e42d86f7bab90ed90722ae75c96/viz/charts/linkerd-viz/values.yaml#L478). 

In the [docs](https://github.com/linkerd/linkerd2/tree/main/viz/charts/linkerd-viz) for linkerd-viz, you can see these values that are configurable:


```
prometheus.resources.cpu.limit                 | string | nil 
prometheus.resources.cpu.request               | string | nil 
prometheus.resources.ephemeral-storage.limit   | string | "" 
prometheus.resources.ephemeral-storage.request | string | ""
prometheus.resources.memory.limit              | string | nil  
prometheus.resources.memory.request            | string | nil
```

In a values file that you're passing to the install, it would look like:
```
...

prometheus:
  resources:
    cpu:
      # -- Maximum amount of CPU units that the prometheus container can use
      limit:
      # -- Amount of CPU units that the prometheus container requests
      request:
    memory:
      # -- Maximum amount of memory that prometheus container can use
      limit:
      # -- Amount of memory that the prometheus container requests
      request:
```
