### DISCUSSION TITLE
ServiceProfile routes not picked up for Traefik-to-backend traffic

### DISCUSSION THREAD

**Discussion by zerok** [linkerd/linkerd2#9378] [Q&A] [answered]
Hi 🙂

I'm currently struggling to setup route-based metrics for a service that is behind a Traefik ingress. The setup consists of 3 elements:

1. Traefik 2 (with IngressRoutes) as ingress controller
2. "Frontend" inside the namespace "namespacename"
3. "Backend" inside the namespace "namespacename", which can receive requests from "Frontend" *and* Traefik

All 3 components are wired. The following checks are all green:

```
linkerd check --proxy --namespace namespacename
linkerd check --proxy --namespace traefik
```

I've set up the following service profile:

```yaml
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: backend.namespacename.svc.cluster.local
  namespace: namespacename
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /awesome
    name: awesome-endpoint
```

When a request now passes through the system via traefik -> frontend -> backend then I can see the `awesome-endpoint` route being listed with `linkerd viz top ns/namespacename --routes`.

The problem is now when I do a request *directly* to the backend via Traefik. Then the route isn't resolved and the routes look like this:

```
Source                    Destination              Route       Count    Best   Worst    Last  Success Rate
traefik-6bb7f86d57-n5js4  backend-6bc75f8d6-jdx8q  [DEFAULT]       2     9ms    61ms     9ms       100.00%
```

Frontend and Backend have l5d-dst-override headers set.

When I tap into the service with JSON output, I can also see that the `l5d-dst-override` header is part of the request but the `routeMeta` object is empty.

Any idea where my mistake could be? Thank! 🙂
