### DISCUSSION TITLE
Ingress from 1 cluster to invoke service in another cluster

### DISCUSSION THREAD

**Discussion by manju-rn** [linkerd/linkerd2#9476] [Q&A]
Can I directly call a service hosted in another cluster (say cluster master) from ingress in agent cluster, without having to define any native service in agent cluster? 

I have the following setup:
 - 2 K3S cluster setup in linkerd multicluster mode - v2.12.0.  
 - The Traefik (default from K3s) is the ingress controller in both clusters.
 - linkerd multicluster link `masterlink` is setup from say - master to agent cluster -i.e any service in master marked as mirror is available in agent cluster. 
 - The link works fine if the call from service A in agent cluster calls the service B in master via the link like `serviceb-masterlink` 
 - However, if I do not have any service in agent cluster, but use the ingress in agent cluster to call the `serviceb-masterlink`. It does not work it shows mTLS error.  I have tried marking the `serverauthorization` object as `unauthenticated: true` in both master and agent 
 ```
[   814.451457s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated error.sources=[direct connections must be mutually authenticated] client.addr=10.42.0.1:36334
```

The serverauthorization resource
```
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
[...]
  labels:
    app: linkerd-gateway
    linkerd.io/extension: multicluster
  [...]
  name: linkerd-gateway
  namespace: linkerd-multicluster
   [...]
spec:
  client:
    networks:
      - cidr: 0.0.0.0/0
      - cidr: '::/0'
    unauthenticated: true
  server:
    name: linkerd-gateway
```
