### ISSUE TITLE
"cluster networks contains all services" fails with services of type ClusterIP

### ISSUE THREAD

**Issue by MrCoffey** [linkerd/linkerd2#10045]
### What is the issue?

linkerd check fails on the "cluster networks contains all services" check even when the cluster only has services of type ClusterIP, my pod has two containers.

My service looks like this:

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod
  name: pod-auto-deploy
  namespace: pod
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: pod
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: pod-celery-exporter
    port: 9808
    protocol: TCP
    targetPort: 9808
  selector:
    app: pod
    tier: web
  type: ClusterIP

```

### How can it be reproduced?

I don't know how to reproduce this error since all our services use ClusterIP services; it only fails with the one in the description. 

### Logs, error output, etc

Running `linkerd check` fails.

### output of `linkerd check -o short`

```
× cluster networks contains all pods
    the Linkerd clusterNetworks ["10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16"] do not include pod pod/pod-5cb86477d6-xbslm (10.15.1.244)
    see https://linkerd.io/2/checks/#l5d-cluster-networks-pods for hints
```

### Environment

Kubernetes Version: 1.22
Cluster Environment: EKS
Host OS:  linux/amd64

I tried with them, both showed the same behavior.

Linkerd version: edge-22.12.1
and stable-2.12.3

### Possible solution

Use a different service mesh

### Additional context

Fresh deployments of `linkerd` fail due to the check falling and blocking the tool's usage. The documentation does not provide a clear recommendation to resolve this issue. 

Upgrading `clusterNetworks` with the IP range of the cluster or adding the IP shown on the error didn't help.

### Would you like to work on fixing this bug?

yes
