### ISSUE TITLE
Require global response timeouts configuration via helm values

### ISSUE THREAD

**Issue by Nbarola** [linkerd/linkerd2#10056]
### What problem are you trying to solve?

Rather than configuring timeouts for each [routes](https://linkerd.io/2.12/tasks/configuring-timeouts/#:~:text=Each%20route%20may%20define%20a,default%20timeout%20is%2010%20seconds), wanted a global configurable value to set global response timeouts for proxies.

### How should the problem be solved?

The document mentions that if unspecified, the default response timeout is 10 seconds, so we can have a global response timeout for all routes/proxies.

It would be great if we have something similar in helm values as we have for `outboundConnectTimeout` for establishing outbound connection

```
proxy:
  # -- Maximum time allowed for the proxy to establish an outbound TCP
  # connection
  outboundConnectTimeout: 1000ms
  # -- Maximum time allowed for the proxy to establish an inbound TCP
  # connection
  inboundConnectTimeout: 100ms
  ```
  It can be like
  ```
  proxy:
     responseTimeout: 10000ms
  ```
  
  

### Any alternatives you've considered?

Adding timeouts to all the routes, but we have to configure all the routes first in order to do that.

### How would users interact with this feature?

This value can be configured in helm custom values manifest file and can be used while installing/upgrading linked control plane via helm

### Would you like to work on this feature?

None
