### ISSUE TITLE
Cannot get metrics from helm install with own prometheus and PKI

### ISSUE THREAD

**Issue by fredczj** [linkerd/linkerd2#10086]
### What is the issue?

Having installed linkerd and linkerd-viz from Helm Charts with private cert-manager PKI and own instance prometheus/grafana.

Service Mesh is working fine. Prometheus scrape configuration sounds fine too (at least it is accepted by prometheus server), metrics sounds available when looking at `linkerd diagnostic`, but I cannot get them via viz dashboard.

I cannot query them neither on prometheus.

This issue comes after [this empty discussion](https://github.com/linkerd/linkerd2/discussions/10067)

### How can it be reproduced?

```
helm install linkerd-control-plane -n linkerd \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set identity.issuer.scheme=kubernetes.io/tls \
  --set prometheus.enabled=false \
  --set prometheusUrl=http://prometheus-server.monitoring \
  --set proxyInit.runAsRoot=true \
  --version 1.9.4 \
  linkerd/linkerd-control-plane
```

And linkerd-viz yaml: 

```
grafana:
  enabled: false
  externalUrl: "https://mygrafana.centiloc.com"

prometheus:
  enabled: false

prometheusUrl: "http://prometheus-server.monitoring"
```

### Logs, error output, etc

Actually, I have no errors logs. Nor I don't know where to look.

### output of `linkerd check -o short`

```text
Linkerd core checks
===================

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-02-03T19:56:52Z
    see https://linkerd.io/2.12/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.2 but the latest stable version is 2.12.3
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane and cli versions match
    control plane running stable-2.12.3 but cli running stable-2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies and cli versions match
    linkerd-destination-64975fbdb5-l4w4j running stable-2.12.3 but cli running stable-2.12.2
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-cli-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-86d75ffc69-gc7h9 (stable-2.12.2)
	* tap-8577b8b69-zpqfc (stable-2.12.2)
	* tap-injector-b7b9fc9f6-tdv5p (stable-2.12.2)
	* web-66b6b55fb7-qswl7 (stable-2.12.2)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √

```

### Environment

- linkerd 2.12.2
- kubernetes 1.25.4
- Hosted in OVH
- 

### Possible solution

I mostly miss checkpoints to understand why prometheus is not collecting the metrics which sounds available, or why `viz` cannot display them neither.

### Additional context

prometheus helm chart extra scrape configuration:

```yaml

# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config
extraScrapeConfigs: |
  - job_name: 'linkerd-controller'
    kubernetes_sd_configs:
    - role: pod
      namespaces:
        names:
        - linkerd
        - linkerd-viz
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_container_port_name
      action: keep
      regex: admin-http
    - source_labels: [__meta_kubernetes_pod_container_name]
      action: replace
      target_label: component

  - job_name: 'linkerd-service-mirror'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_label_linkerd_io_control_plane_component
      - __meta_kubernetes_pod_container_port_name
      action: keep
      regex: linkerd-service-mirror;admin-http$
    - source_labels: [__meta_kubernetes_pod_container_name]
      action: replace
      target_label: component

  - job_name: 'linkerd-proxy'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_pod_container_name
      - __meta_kubernetes_pod_container_port_name
      - __meta_kubernetes_pod_label_linkerd_io_control_plane_ns
      action: keep
      regex: ^{{default .Values.proxyContainerName "linkerd-proxy" .Values.proxyContainerName}};linkerd-admin;{{.Values.linkerdNamespace}}$
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: pod
    # special case k8s' "job" label, to not interfere with prometheus' "job"
    # label
    # __meta_kubernetes_pod_label_linkerd_io_proxy_job=foo =>
    # k8s_job=foo
    - source_labels: [__meta_kubernetes_pod_label_linkerd_io_proxy_job]
      action: replace
      target_label: k8s_job
    # drop __meta_kubernetes_pod_label_linkerd_io_proxy_job
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_linkerd_io_proxy_job
    # __meta_kubernetes_pod_label_linkerd_io_proxy_deployment=foo =>
    # deployment=foo
    - action: labelmap
      regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
    # drop all labels that we just made copies of in the previous labelmap
    - action: labeldrop
      regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
    # __meta_kubernetes_pod_label_linkerd_io_foo=bar =>
    # foo=bar
    - action: labelmap
      regex: __meta_kubernetes_pod_label_linkerd_io_(.+)
    # Copy all pod labels to tmp labels
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
      replacement: __tmp_pod_label_$1
    # Take `linkerd_io_` prefixed labels and copy them without the prefix
    - action: labelmap
      regex: __tmp_pod_label_linkerd_io_(.+)
      replacement:  __tmp_pod_label_$1
    # Drop the `linkerd_io_` originals
    - action: labeldrop
      regex: __tmp_pod_label_linkerd_io_(.+)
    # Copy tmp labels into real labels
    - action: labelmap
      regex: __tmp_pod_label_(.+)

  # - job_name: 'prometheus-blackbox-exporter'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #   static_configs:
  #     - targets:
  #       - https://example.com
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: prometheus-blackbox-exporter:9115
```

### Would you like to work on fixing this bug?

None
