### ISSUE TITLE
Data plane proxies do not survive l5d control plane outage

### ISSUE THREAD

**Issue by ls250412** [linkerd/linkerd2#10200]
### What is the issue?

When the l5d control plane deployments are unavailable, our k8s application immediately starts to fail. 

Investigation shows that the service discovery fails.

NOTE: As I have been unable to properly reproduce the issue in a cutdown example.  please request any additional info I can capture / tests to perform that can help progress. I can also be available to show the issue on the system in a shared session if that would be help.

### How can it be reproduced?

We run a complex application and I have not been able to replicate the underlying observed issues / logs in a cut down version. 

The following modification of the emojivoto example application shows an issue on my environment for same changes to the linkerd control plane - but present differently on deeper analysis of messages being requested etc.

In our application the 'center' service (represented by web in example) never calls down to the leaf services, but makes the following calls monitoring its interface:
- DNS request for the leaf service - gives the service IP as a response
- DNS request for the linkerd-dst-headless service - gives service IP
- attempts to access 8086 on the linkerd-destination pod ip (fails when down)
- No calls are made to the downstream pod - either via its retrieved service IP or a cached endpoint IP

In the emojivoto example I have, the emoji web service continues to intiiate requests to the leaf emoji and voting services (via their endpoint IP) so assuming the failure is then in these end services

The manifests used for the example emojivoto are as follows:
```
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: emoji-server
  namespace: emojivoto
spec:
  podSelector:
    matchLabels:
      app: emoji-svc
  port: 8080
  proxyProtocol: unknown
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: emoji-server-auth
  namespace: emojivoto
spec:
  client:
    meshTLS:
      serviceAccounts:
      - name: web
        namespace: emojivotoweb
  server:
    name: emoji-server
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: voting-server
  namespace: emojivoto
spec:
  podSelector:
    matchLabels:
      app: voting-svc
  port: 8080
  proxyProtocol: unknown
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: voting-server-auth
  namespace: emojivoto
spec:
  client:
    meshTLS:
      serviceAccounts:
      - name: web
        namespace: emojivotoweb
  server:
    name: voting-server
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: web-server
  namespace: emojivotoweb
spec:
  podSelector:
    matchLabels:
      app: web-svc
  port: 8080
  proxyProtocol: unknown
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: web-server-auth
  namespace: emojivotoweb
spec:
  client:
    meshTLS:
      serviceAccounts:
      - name: default
        namespace: emojivotobot
  server:
    name: web-server
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: emoji
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emoji
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: v11
  template:
    metadata:
      labels:
        app: emoji-svc
        version: v11
    spec:
      serviceAccountName: emoji
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-emoji-svc:v11
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: emojivoto
spec:
  selector:
    app: emoji-svc
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
---
apiVersion: v1
kind: Namespace
metadata:
  name: emojivoto
---
apiVersion: v1
kind: Namespace
metadata:
  name: emojivotoweb
---
apiVersion: v1
kind: Namespace
metadata:
  name: emojivotobot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  namespace: emojivotobot
  labels:
    app.kubernetes.io/name: ubuntu
    app.kubernetes.io/part-of: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - image: ubuntu
        name: ubuntu
        command:
          - "sleep"
          - "604800"
        resources:
          requests:
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-bot
  namespace: emojivotobot
  labels:
    app.kubernetes.io/name: vote-bot
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
      version: v11
  template:
    metadata:
      labels:
        app: vote-bot
        version: v11
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc.emojivotoweb:80
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: vote-bot
        resources:
          requests:
            cpu: 10m
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: voting
  namespace: emojivoto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      version: v11
  template:
    metadata:
      labels:
        app: voting-svc
        version: v11
    spec:
      serviceAccountName: voting
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: docker.l5d.io/buoyantio/emojivoto-voting-svc:v11
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: emojivoto
spec:
  selector:
    app: voting-svc
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: web
  namespace: emojivotoweb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: emojivotoweb
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v11
  template:
    metadata:
      labels:
        app: web-svc
        version: v11
    spec:
      serviceAccountName: web
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: docker.l5d.io/buoyantio/emojivoto-web:v11
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivotoweb
spec:
  type: ClusterIP
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 8080
```

Note: The emojivoto doctored app above may not need to be in different namespaces, I have created that as it best represents the case in our app that I have been able to pinpoint

UI service -> Back End proxy service -> calls multiple business services

It should also be noted, that I initially used the standard vote-bot in the top namespace but could not illicit the issue using curl, and moved to ubuntu for finer control and requests to the lower services (without the rest of the bot automation)

Test:
1. All namespaces above meshed
2. Exec into the Ubuntu container, and install curl
3. Run the commands against the emojivoto web service, for example
curl http://web-svc.emojivotoweb/api/vote?choice=":ok_woman:"
curl http://web-svc.emojivotoweb/api/leaderboard
All works fine
4. Take down the l5d control plane, then see errors
root@ubuntu-fddc4ccf6-4j9rl:/# curl http://web-svc.emojivotoweb/api/vote?choice=":ok_woman:"
curl: (56) Recv failure: Connection reset by peer

In my testing to pinpoint service discovery I am turning off more fine grain than whole l5d control plane.

I have scaled down to 0 the following linkerd deployments:
- linkerd-proxy-injector
- linkerd-identity
Firewalled off all access to the destination deployment pod except access to linkerd-proxy and destination in that pod

With the above setup (so only destination / service discovery operational of the l5d control plane - all works fine

If I bring down the i/f to the destination pod / block port 8086 to that pod the application no longer works (see the failures above)

### Logs, error output, etc

See above for the error message arising from the test on the OS side

As stated in the description, the behaviour is different in the example emojivoto pasted and what is actually being observed in pods in our application.

Further details on the 'real' application are below. Observed packets on the destination pod interface when the access to destination service endpoint blocked (port 8086). This is NOT from the emojivoto example, I am having trouble replicating the behaviour of the real application

```
11:36:58.538557 IP 192.168.137.12.44128 > 192.168.31.144.8090: Flags [S], seq 654396186, win 64860, options [mss 1410,sackOK,TS val 1391163763 ecr 0,nop,wscale 7], length 0
11:36:58.928226 IP 192.168.153.25.35282 > 192.168.137.12.3001: Flags [P.], seq 34836:37947, ack 9271, win 502, options [nop,nop,TS val 3964703910 ecr 1935767396], length 3111
11:36:58.928289 IP 192.168.137.12.3001 > 192.168.153.25.35282: Flags [.], ack 37947, win 489, options [nop,nop,TS val 1935769891 ecr 3964703910], length 0
11:36:58.955681 IP 192.168.137.12.52712 > 10.96.0.10.53: 52405+ A? leaf-pod.interim-namespace.client-namespace.svc.cluster.local. (91)
11:36:58.955892 IP 192.168.137.12.52712 > 10.96.0.10.53: 53293+ AAAA? leaf-pod.interim-namespace.client-namespace.svc.cluster.local. (91)
11:36:58.956759 IP 10.96.0.10.53 > 192.168.137.12.52712: 52405 NXDomain*- 0/1/0 (184)
11:36:58.956850 IP 10.96.0.10.53 > 192.168.137.12.52712: 53293 NXDomain*- 0/1/0 (184)
11:36:58.956954 IP 192.168.137.12.47267 > 10.96.0.10.53: 28373+ A? leaf-pod.interim-namespace.svc.cluster.local. (68)
11:36:58.957071 IP 192.168.137.12.47267 > 10.96.0.10.53: 29306+ AAAA? leaf-pod.interim-namespace.svc.cluster.local. (68)
11:36:58.957841 IP 10.96.0.10.53 > 192.168.137.12.47267: 28373*- 1/0/0 A 10.107.243.210 (134)
11:36:58.957911 IP 10.96.0.10.53 > 192.168.137.12.47267: 29306*- 0/1/0 (161)
11:36:58.958867 IP 192.168.137.12.42384 > 192.168.31.144.8086: Flags [P.], seq 4565:4750, ack 432272, win 4948, options [nop,nop,TS val 1391164183 ecr 2482573671], length 185
11:36:58.959060 IP 192.168.137.12.58326 > 10.96.0.10.53: 14479+ SRV? linkerd-dst-headless.linkerd.svc.cluster.local. (64)
11:36:58.959849 IP 10.96.0.10.53 > 192.168.137.12.58326: 14479*- 1/0/1 SRV 192-168-31-144.linkerd-dst-headless.linkerd.svc.cluster.local.:8086 0 100 (268)
11:36:59.163884 IP 192.168.137.12.42384 > 192.168.31.144.8086: Flags [P.], seq 4565:4750, ack 432272, win 4948, options [nop,nop,TS val 1391164388 ecr 2482573671], length 185
11:36:59.375761 IP 192.168.137.12.42384 > 192.168.31.144.8086: Flags [P.], seq 4565:4750, ack 432272, win 4948, options [nop,nop,TS val 1391164600 ecr 2482573671], length 185
```
The DNS returned above (10.107.243.210) is correct for the target leaf pod, but there are no subsequent packets directed at that service IP or the endpoint (single endpoint, unchanged through all tests - stable for days - IP 192.168.137.24)

Logs from the linkerd-proxy at debug on the interim-pod for an equivalent failure period is below:
```
{"timestamp":"[431951.206408s]","level":"DEBUG","fields":{"message":"Caching new client","use_absolute_form":false},"target":"linkerd_proxy_http::h1","spans":[{"client.addr":"192.168.153.38:43216","name":"accept"},{"port":3001,"name":"server"},{"v":"h2","name":"http"},{"name":"emerald-desktop-bff.retail-emerald-desktop.svc.cluster.local:3001","name":"http1"},{"name":"http1"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431951.206516s]","level":"DEBUG","fields":{"message":"Connecting","server.addr":"192.168.137.12:3001"},"target":"linkerd_proxy_transport::connect","spans":[{"client.addr":"192.168.153.38:43216","name":"accept"},{"port":3001,"name":"server"},{"v":"h2","name":"http"},{"name":"emerald-desktop-bff.retail-emerald-desktop.svc.cluster.local:3001","name":"http1"},{"name":"http1"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431951.206940s]","level":"DEBUG","fields":{"message":"Connected","local.addr":"192.168.137.12:60062","keepalive":"None"},"target":"linkerd_proxy_transport::connect","spans":[{"client.addr":"192.168.153.38:43216","name":"accept"},{"port":3001,"name":"server"},{"v":"h2","name":"http"},{"name":"emerald-desktop-bff.retail-emerald-desktop.svc.cluster.local:3001","name":"http1"},{"name":"http1"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431951.207072s]","level":"DEBUG","fields":{"message":"client connection open"},"target":"linkerd_transport_metrics::client","spans":[{"client.addr":"192.168.153.38:43216","name":"accept"},{"port":3001,"name":"server"},{"v":"h2","name":"http"},{"name":"emerald-desktop-bff.retail-emerald-desktop.svc.cluster.local:3001","name":"http1"},{"name":"http1"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431951.224600s]","level":"DEBUG","fields":{"message":"Caching new value","key":"Accept { orig_dst: OrigDstAddr(10.104.121.243:4444), protocol: () }"},"target":"linkerd_cache","spans":[{"client.addr":"192.168.137.12:52280","name":"accept"},{"addr":"10.104.121.243:4444","name":"proxy"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431951.224880s]","level":"DEBUG","fields":{"message":"Allowing profile lookup"},"target":"linkerd_app_outbound::discover","spans":[{"client.addr":"192.168.137.12:52280","name":"accept"},{"addr":"10.104.121.243:4444","name":"proxy"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431951.225039s]","level":"DEBUG","fields":{"message":"TCP Server service has become unavailable"},"target":"linkerd_stack::failfast","spans":[{"client.addr":"192.168.137.12:52280","name":"accept"},{"addr":"10.104.121.243:4444","name":"proxy"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431952.058753s]","level":"WARN","fields":{"message":"Failed to connect","error":"connect timed out after 1s"},"target":"linkerd_reconnect","spans":[{"addr":"linkerd-policy.linkerd.svc.cluster.local:8090","name":"controller"},{"addr":"192.168.31.144:8090","name":"endpoint"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431952.058788s]","level":"DEBUG","fields":{"message":"Recovering"},"target":"linkerd_reconnect","spans":[{"addr":"linkerd-policy.linkerd.svc.cluster.local:8090","name":"controller"},{"addr":"192.168.31.144:8090","name":"endpoint"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431952.058801s]","level":"DEBUG","fields":{"message":"Disconnected","backoff":"true"},"target":"linkerd_reconnect","spans":[{"addr":"linkerd-policy.linkerd.svc.cluster.local:8090","name":"controller"},{"addr":"192.168.31.144:8090","name":"endpoint"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431952.560948s]","level":"DEBUG","fields":{"message":"Disconnected","backoff":"true"},"target":"linkerd_reconnect","spans":[{"addr":"linkerd-policy.linkerd.svc.cluster.local:8090","name":"controller"},{"addr":"192.168.31.144:8090","name":"endpoint"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431952.561017s]","level":"DEBUG","fields":{"message":"Creating service","backoff":"true"},"target":"linkerd_reconnect","spans":[{"addr":"linkerd-policy.linkerd.svc.cluster.local:8090","name":"controller"},{"addr":"192.168.31.144:8090","name":"endpoint"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431952.561046s]","level":"DEBUG","fields":{"message":"Connecting","server.addr":"192.168.31.144:8090"},"target":"linkerd_proxy_transport::connect","spans":[{"addr":"linkerd-policy.linkerd.svc.cluster.local:8090","name":"controller"},{"addr":"192.168.31.144:8090","name":"endpoint"}],"threadId":"ThreadId(1)"}
{"timestamp":"[431953.562840s]","level":"WARN","fields":{"message":"Failed to connect","error":"connect timed out after 1s"},"target":"linkerd_reconnect","spans":[{"addr":"linkerd-policy.linkerd.svc.cluster.local:8090","name":"controller"},{"addr":"192.168.31.144:8090","name":"endpoint"}],"threadId":"ThreadId(1)"}
```

I can grab more logs / wider context as required

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-existence
-----------------
× control plane pods are ready
    No running pods for "linkerd-proxy-injector"
    see https://linkerd.io/2.12/checks/#l5d-api-control-ready for hints

Status check results are ×
```

As expected - I have the l5d control plane in a specific mode as explained above to investigate observed issues with l5d control plane unavailable

### Environment

- Kubernetes version: v1.24.4
- Cluster: Local provision (kubeadm)
- Host OS: Ubuntu 22.04.1 LTS
- Linkerd version: 2.12.2

### Would you like to work on fixing this bug?

None
