### ISSUE TITLE
QueryParamMatch type RegularExpression does not work

### ISSUE THREAD

**Issue by revero-doug** [linkerd/linkerd2#10255]
### What is the issue?

`HTTPRoute` `.spec.rules[].matches[].queryParams[].type` `RegularExpression` doesn't work as described in documentation. A quick search through source code suggests this may be the culprit: https://github.com/linkerd/linkerd2/blob/695f8439146388e8d5b3448b24716859270739bc/policy-controller/k8s/index/src/http_route.rs#L327

### How can it be reproduced?

1. add a `Server` with a sole `HTTPRoute` with a queryParam matcher (and only a queryParam matcher) using type `RegularExpression`
2. apply an `AuthorizationPolicy` targeting the `HTTPRoute` defined in step 1 with `requiredAuthenticationRefs: []`
3. set a `readinessProbe` with `periodSeconds: 10` that applies a query param matching the regex configured in step 1
4. tail the logs of the corresponding `linkerd-proxy` container and observe lines that look similar to log output in next section

### Logs, error output, etc

```
[    37.698906s]  INFO ThreadId(01) inbound:server{port=3000}:rescue{client.addr=172.17.0.1:45322}: linkerd_app_core::errors::respond: Request failed error=no route found for request
[    47.699311s]  INFO ThreadId(01) inbound:server{port=3000}:rescue{client.addr=172.17.0.1:45562}: linkerd_app_core::errors::respond: Request failed error=no route found for request
```

### output of `linkerd check -o short`

```bash
Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    Get "https://versioncheck.linkerd.io/version.json?version=stable-2.12.3&uuid=unknown&source=cli": read tcp 192.168.1.23:62965->172.67.150.14:443: read: connection reset by peer
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

```bash
$ linkerd version
Client version: stable-2.12.3
Server version: stable-2.12.3
```

### Possible solution

Fix this line that logically maps `RegularExpression` type to `Exact` type: https://github.com/linkerd/linkerd2/blob/695f8439146388e8d5b3448b24716859270739bc/policy-controller/k8s/index/src/http_route.rs#L327

### Additional context

this works:
```yaml
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: 10-foo-probe-route
  namespace: default
spec:
  parentRefs:
  - name: foo-server
    kind: Server
    group: policy.linkerd.io
  rules:
  - matches:
    - path:
        type: Exact
        value: "/graphql"
      method: GET
      queryParams:
      - type: Exact
        name: query
        value: "{healthz{livenessProbe}}"
    - path:
        type: Exact
        value: "/graphql"
      method: GET
      queryParams:
      - type: Exact
        name: query
        value: "{healthz{readinessProbe}}"
    - path:
        type: Exact
        value: "/graphql"
      method: GET
      queryParams:
      - type: Exact
        name: query
        value: "{healthz{startupProbe}}"
```

this fails:
```yaml
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: 10-foo-probe-route
  namespace: default
spec:
  parentRefs:
  - name: foo-server
    kind: Server
    group: policy.linkerd.io
  rules:
  - matches:
    - path:
        type: Exact
        value: "/graphql"
      method: GET
      queryParams:
      - type: RegularExpression
        name: query
        value: ".*healthz.*"
```

### Would you like to work on fixing this bug?

no
