### ISSUE TITLE
Local file dependency in helm chart 

### ISSUE THREAD

**Issue by presidenten** [linkerd/linkerd2#10252]
### What is the issue?

There is a link to a local dependency to `file://../partials` in all helm charts that does not get resolved by helm.

### How can it be reproduced?

```bash
❯ helm repo add linkerd https://helm.linkerd.io/stable
❯ helm fetch --untar linkerd/linkerd-control-plane
❯ cat linkerd-control-plane/Chart.yaml
apiVersion: v2
appVersion: stable-2.12.3
dependencies:
- name: partials
  repository: file://../partials
  version: 0.1.0
.
.
.
```

Its being used alot in the helm charts. So might be an idea to include it in the published charts maybe?

### Logs, error output, etc

Same if trying to install directly from repo
```yaml
❯ helm upgrade --install linkerd-crds linkerd/linkerd-crds -n linked --create-namespace --dry-run
...
# Source: linkerd-crds/templates/policy/server.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servers.policy.linkerd.io
  annotations:
    linkerd.io/created-by: linkerd/helm %!s(<nil>)
```

`%!s(<nil>)` at the end doesnt look good guys

### output of `linkerd check -o short`

-

### Environment

```
❯ helm version
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

### Possible solution

Make sure it is included in the repos before pushing to artifacthub

### Would you like to work on fixing this bug?

no
