### ISSUE TITLE
Support Dynamic request routing

### ISSUE THREAD

**Issue by carllhw** [linkerd/linkerd2#1028]
Would conduit support [Dynamic request routing](https://linkerd.io/features/routing/) like [Dtabs](https://linkerd.io/advanced/dtabs/) ?

**Comment by wmorgan** [comment]
Hi @carllhw! Request routing is on the roadmap, though many of the details are still under design. I would be a little surprised if Conduit used dtabs specifically, but it's possible.

You can help us by giving us a couple concrete use cases you would like to support with configurable routing policy. 😄

**Comment by carllhw** [comment]
To support canary deploy, I want to config request routing by user defined labels or percentage.

For example: 
- 80% to v1 instances, 20% to v2 instances. 
- request has v1 label to v1 instances, request has v2 label to v2 instances

**Comment by carllhw** [comment]
Would 0.5 or 0.6 support dynamic request routing ?

**Comment by wmorgan** [comment]
0.5 definitely not. 0.6 it's not 100%, but my guess would be no. We'd like to prioritize prod readiness first, then work on routing.

**Comment by Disturbing** [comment]
x-version = v1 goes to label v1,

**Comment by nickjackson** [comment]
Like mentioned above, I'd quite like the ability to canary new deployments by traffic shifting based on HTTP headers and traffic percentages. This would allow me to do something like the following...

1) Send only integration test traffic through to the new deployment
2) Gradually shift the production traffic from the previous deployment to the new one over a certain time frame

**Comment by wmorgan** [comment]
I think we should keep this open to track this, unless there's another, better issue (cc @grampelberg).

**Comment by grampelberg** [comment]
Interestingly enough, this is the only canary issue open right now. +1 to keeping it open!

**Comment by nickjackson** [comment]
I'd be interested to hear what the current thoughts are on how this might be implemented?

As far as I know, currently the only way to update a k8s deployment is with the rolling update strategy. There doesn't appear to be a way to do a blue/green or canary type thing on a deployment directly - so you'd have to have an `app-v1` and `app-v2` deployment and then switch the pod selectors on the k8s service accordingly.

And considering LD2 revolves around "deployments", I presume you'd have to do something similar as well.

How might this work with your shiny new service profiles?

**Comment by wmorgan** [comment]
Thanks Nick. We're still in brainstorming mode for this. Attaching it to service profiles feels like a natural starting point. From your perspective, how would you want to parameterize a canary or a blue-green deploy?

**Comment by Disturbing** [comment]
I would suggest following istio on this one /w their Destination Rules, but without having to make a full on separate file for it:

 - destination:
        host: reviews.prod.svc.cluster.local
        subset: v1
      weight: 75

**Comment by Disturbing** [comment]
Just going to take a quick stab at this since server profiles are quite different to other offerings out there.  So I'm trying to KISS, but the following can be written more clear by describing both routes versus just attaching something on top of the default.  Also - First time reading about service profiles so hopefully not botching this up ;)

```
### ServiceProfile for webapp.default  Example of blue-green ###
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: webapp.default.svc.cluster.local
  namespace: linkerd
spec:
  routes:
  - name: 'blue-deployment' # This is used as the value for the rt_route label
    condition:
       - headers:
            canary: 'blue'
    destination: # Destination cannot work with the required condition above, no condition = OK.
        labels:
            - app: 'v2'
        weight: 0
```

```
### ServiceProfile for webapp.default  Example of canary (95% default, 5% v2) ###
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: webapp.default.svc.cluster.local
  namespace: linkerd
spec:
  routes:
  - name: 'webapp-v2' # This is used as the value for the rt_route label, no condition = OK.
     destination: # Destination cannot work with the required condition above
        labels:
          - app: 'v2'
        weight: 5
```

This is the more "descriptive way" following istio and others which means, that if a route is in place, then default traffic has to be described otherwise gets a 503
        
```
### ServiceProfile for webapp.default  Example of canary (95% default, 5% v2) ###
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: webapp.default.svc.cluster.local
  namespace: linkerd
spec:
  routes:
  - name: 'webapp-v1' # This is used as the value for the rt_route label
     destination: # Destination cannot work with the required condition above, no condition = OK.
        labels:
          - app: 'v1'
        weight: 95
  - name: 'webapp-v2' # This is used as the value for the rt_route label
     destination: # Destination cannot work with the required condition above, no condition = OK.
        labels:
          - app: 'v2'
        weight: 5
```

**Comment by nickjackson** [comment]
@wmorgan Good question.

So I think blue/green is already possible by having `app-v1` and `app-v2` deployments and then just switching over the k8s service pod selector.

My use case is to be able to canary new deployments by sending a portion of traffic to it. This might be by some kind of weight/proportion or by HTTP header. In theory, it would be possible to do a blue/green deploy this way as well.

This is a bit rough, but something like this would work well for me.

```yaml
apiVersion: linkerd.io/v1alpha1
...
spec:
  ...
  traffic:
    shift:
      weights:
      - weight: 95
        labels:
          - app: v1
      - weight: 5
        labels:
          - app: v2
      headers:
      - field: X-CANARY
        value: foo
        labels:
          - app: v3
      - field: X-CANARY
        value: bar
        labels:
          - app: v4
```

In essence, normal traffic would be split 95% to `v1` and 5% to `v2`. But if one of those headers was present in a request, it would direct to `v3` or `v4`. Those labels could be deployment or pod labels (I'm not sure which, or if it even matters).

This would fit my usecase, but I'm not sure if this is flexible enough for others.
