### ISSUE TITLE
Not working with gVisor

### ISSUE THREAD

**Issue by Pithikos** [linkerd/linkerd2#10372]
### What is the issue?

I'm trying to get linkerd2 working so my pods running on gVisor pools on GKE can communicate over SSL. I've followed the installation instructions to the letter and scheduling seems to work fine but it seems the pod never initializes properly. Works fine removing the linkerd2 inject annotation.

### How can it be reproduced?

Trying to apply below manifest in a new GKE cluster with gvisor enabled

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        linkerd.io/inject: enabled
    spec:
      runtimeClassName: gvisor  # This brings havoc
      containers:
        - name: myapp
          image: nginx:latest
          ports:
            - containerPort: 80
```

### Logs, error output, etc

kubectl get all
```
pod/myapp-85588c88b-4gb2m                        0/2     Init:CrashLoopBackOff   6 (3m34s ago)   9m21s
```

kubectl describe
```
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   vel=info msg="iptables-save v1.8.8 (legacy): Cannot initialize: Permission denied (you must be root)\n\n"
time="2023-02-22T08:48:46Z" level=error msg="aborting firewall configuration"
```

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

GKE with gvisor

### Would you like to work on fixing this bug?

None
