### ISSUE TITLE
External Identitiy Issuer setup failing

### ISSUE THREAD

**Issue by dexma-dev** [linkerd/linkerd2#10391]
### What is the issue?

While setting up a external identitiy issuer i am getting errors upon install. I am therefore unable to setup linkerd with the external identity issuer. 

I have setup cert-manager with hashicorp vault as external pki and that is working. The certificate `linkerd-identity-issuer` is issued successfully. 

### How can it be reproduced?

I am following the offical guide for the tls rotation: https://linkerd.io/2.12/tasks/automatically-rotating-control-plane-tls-credentials/

I have created the corresponding certificate:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
  - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
```

### Logs, error output, etc

`linkerd install --identity-external-issuer | kubectl apply -f -`
`Error: failed to validate issuer credentials: issuer cert is not a CA`

### output of `linkerd check -o short`

linkerd is not installed. therefore the command fails

### Environment

- Kubernetes Version. 1.23.15
- Linkerd Version: 2.12

### Would you like to work on fixing this bug?

maybe
