### ISSUE TITLE
linkerd TrafficSplit doesn't work with Traefik IngressRoute

### ISSUE THREAD

**Issue by prajithp13** [linkerd/linkerd2#10553]
### What is the issue?

We have deployed all required deployments but Service failover or TrafficSplit is not working as expected. 

configs
```
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
    name: whoami
    namespace: tools
spec:
    service: whoami
    backends:
        - service: whoami
          weight: 50
        - service: whoami-test
          weight: 50
```
and we have an  ingressroute config with following rules.
```
spec:
  entryPoints:
  - http
  routes:
  - kind: Rule
    match: Host(`whoami-http.example.com`) && PathPrefix(`/`)
    middlewares:
    - name: whoami-l5d-header-middleware
    priority: 1000
    services:
    - name: whoami
      namespace: tools
      port: 80
```
and if call whoami-http.example.com the request is still going to whoami pod and it doesn't split the traffic. 

### How can it be reproduced?

Install linkerd, smi and traefik proxy and create a sample ingressrout and trafficsplit. 

### Logs, error output, etc

No logs

### output of `linkerd check -o short`

```
Linkerd extensions checks
=========================

linkerd-failover
----------------
‼ Linkerd extension command linkerd-failover exists
    exec: "linkerd-failover": executable file not found in $PATH
    see https://linkerd.io/2.12/checks/#extensions for hints

Status check results are √
```

### Environment

k8s: 1.23
Linkerd: 2.12
OS: Linux
EKS

### Would you like to work on fixing this bug?

None
