### ISSUE TITLE
External Outbound Requests Timing Out

### ISSUE THREAD

**Issue by michaelst** [linkerd/linkerd2#10602]
### What is the issue?

When making a request to a url external of the cluster we are seeing time outs if the response takes longer than 10s. For example we get errors like this `Net::ReadTimeout with #Socket:(closed)` or just `timeout`. I tested this with a external service (not in k8s) that sleeps for 12s before returning a response. A pod running with the proxy sidecar times out, a pod without the sidecar gets the response fine.

### How can it be reproduced?

Setup a webserver that sleeps for longer than the timeout and make a request from a pod with the proxy sidecar.

### Logs, error output, etc

Net::ReadTimeout with #Socket:(closed)

nothing is logged by the proxy

### output of `linkerd check -o short`

not able to use the linkerd tool with our cluster, it is installed through helm

### Environment

k8s version: 1.24.9-gke.3200
cr.l5d.io/linkerd/proxy:stable-2.12.3
linkerd-control-plane helm chart version: 1.9.5

### Would you like to work on fixing this bug?

maybe

**Comment by adleong** [comment]
This behavior is documented here: https://linkerd.io/2.12/features/protocol-detection/#configuring-protocol-detection

As per the flow-chart in the above, you'll want to use `skip-outbound-ports` to avoid this timeout.

**Comment by yc185050** [comment]
It is likely the [LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE](https://github.com/linkerd/linkerd2/blob/main/charts/partials/templates/_proxy.tpl#L79) which is something not customizable today.

**Comment by alpeb** [comment]
I wasn't able to reproduce this problem. Can you please provide a minimalistic repro we could use? Also it'd be useful to get some proxy logs (on debug level) along with metrics, that you can obtain via `linkerd diagnostics proxy-metrics` (note that you can install the linkerd CLI in your laptop regardless of how you deployed linkerd in the cluster). Also please use the latest stable release 2.12.4.

I tried reproducing the issue with the following setup:

- server running on my local machine:
```bash
#!/usr/bin/env sh

function handle_request {
    sleep 20
    echo -e "HTTP/1.1 200 OK\nContent-Type: text/plain\n\nHello, World!\n"
}

while true; do
    (echo -ne "HTTP/1.1 200 OK\r\nContent-Length: 56\r\nContent-Type: text/html\r\n\r\n"; handle_request) | nc -N 0.0.0.0 -l 8000 2>&1
done
```

- Injected deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  labels:
    app: curl
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: curl
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 10; done;" ]
```
Then I exec'd into the client side via `kubectl exec -ti curl-xxxxx-xxx -c curl sh` and triggered the request:
```bash
/ $ time curl -v 192.168.1.18:8000
*   Trying 192.168.1.18:8000...
* Connected to 192.168.1.18 (192.168.1.18) port 8000 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.18:8000
> User-Agent: curl/8.0.1-DEV
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 56
< Content-Type: text/html
<
HTTP/1.1 200 OK
Content-Type: text/plain

Hello, World!
* Connection #0 to host 192.168.1.18 left intact
real    0m 17.17s
user    0m 0.00s
sys     0m 0.00s
```
