### ISSUE TITLE
Allow a path in an HTTPRoute to be excluded

### ISSUE THREAD

**Issue by Tolsto** [linkerd/linkerd2#10611]
### What problem are you trying to solve?

It is currently not easily possible to exclude a certain path from an HTTPRoute matcher. For instance, if I want to match all paths except `/metrics`

### How should the problem be solved?

```
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: all-paths-except-metrics
spec:
  parentRefs:
    - name: my-server
      kind: Server
      group: policy.linkerd.io
  rules:
    - matches:
        - path:
            value: "/"
            except: 
               - "/metrics"
          method: GET
```

### Any alternatives you've considered?

Go doesn't support a regex with negative lookaheads. A workaround would be to use something like the following which matches everything except `metrics`.

`^([^m]|m(m|e(m|t(m|r(m|i(m|cm)))))*([^em]|e([^mt]|t([^mr]|r([^im]|i([^cm]|c[^ms]))))))*(m(m|e(m|t(m|r(m|i(m|cm)))))*(e(t?|tr(i?|ic)))?)?$`

For obvious reasons, that's not a very good solution.

### Would you like to work on this feature?

None
