### ISSUE TITLE
Getting "400 Bad Request" with Linkerd and external proxy

### ISSUE THREAD

**Issue by jensg-st** [linkerd/linkerd2#10642]
### What is the issue?

We are using linkerd in an environment where all external requests are going via a corporate proxy. The pods are configured with the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables and the namespace is configured with `linkerd.io/inject=enabled`. So far everything has worked perfectly fine (btw, thanks for that). We are experiencing now one edge case with Python's pip and I can not really figure out what is going wrong exactly. 

I can curl/wget to pypi.org but the request from pip is not leaving the linkerd proxy and it returns an error `CONNECT request not valid for HTTP/1.0: pypi.org:443`. 

The following is the output of `pip install datetime`:

```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request'))': /simple/datetime/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request'))': /simple/datetime/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 400 Bad Request'))': /simple/datetime/

```

### How can it be reproduced?

- Start Squid proxy 
```
docker run -d --name squid-container -e TZ=UTC -p 3128:3128 ubuntu/squid:5.2-22.04_beta
```
- Annotate namespace

```
kubectl annotate ns default config.linkerd.io/proxy-log-level=debug
kubectl annotate ns default linkerd.io/inject=enabled
```

- Deploy two pods

First vanilla pod

```
apiVersion: v1
kind: Pod
metadata:
  name: python
spec:
  containers:
  - name: python
    image: python:latest
    ports:
    - containerPort: 80
    imagePullPolicy: Always
    command: ["tail"]
    args: ["-f", "/dev/null"] 
```

Second pod uses the docker squid proxy

```
apiVersion: v1
kind: Pod
metadata:
  name: python-proxy
spec:
  containers:
  - name: python
    image: python:latest
    ports:
    - containerPort: 80
    imagePullPolicy: Always
    command: ["tail"]
    args: ["-f", "/dev/null"] 
    env:
    - name: HTTP_PROXY
      value: http://***YOU-HOST-IP-HERE***:3128
    - name: HTTPS_PROXY
      value: http://***YOU-HOST-IP-HERE***:3128
```

- Run command in pods

```
kubectl exec --container python --stdin --tty python- -- /bin/bash
pip install datetime
```

This one fails
```
kubectl exec --container python --stdin --tty python-proxy- -- /bin/bash
pip install datetime
```

### Logs, error output, etc

```
[   163.351444s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}: tower::buffer::worker: service.ready=true processing request
[   163.351527s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}: linkerd_detect: DetectResult protocol=Some(Http1) elapsed=31.669µs
[   163.351638s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}:http{v=1.x}: linkerd_proxy_http::server: Creating HTTP service version=Http1
[   163.351702s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}:http{v=1.x}: linkerd_proxy_http::server: Handling as HTTP version=Http1
[   163.351745s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}:http{v=1.x}: hyper::proto::h1::io: parsed 0 headers
[   163.351761s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}:http{v=1.x}: hyper::proto::h1::conn: incoming body is empty
[   163.351772s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}:http{v=1.x}: linkerd_proxy_http::h1: CONNECT request not valid for HTTP/1.0: pypi.org:443
[   163.351863s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}:http{v=1.x}: hyper::proto::h1::io: flushed 84 bytes
[   163.351928s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}:proxy{addr=192.168.0.123:3128}:http{v=1.x}: linkerd_proxy_http::server: The client is shutting down the connection res=Ok(())
[   163.351951s] DEBUG ThreadId(01) outbound:accept{client.addr=10.42.0.11:50536}: linkerd_app_core::serve: Connection closed
```

### output of `linkerd check -o short`

I don't have `linkerd` cli installed but install it with Helm charts:

```
NAME                 	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART                      	APP VERSION  
linkerd-control-plane	linkerd  	1       	2023-03-29 15:44:17.163683686 +0200 CEST	deployed	linkerd-control-plane-1.9.6	stable-2.12.4
linkerd-crds         	linkerd  	1       	2023-03-29 15:44:16.545860606 +0200 CEST	deployed	linkerd-crds-1.4.0         	             
```

### Environment

- Kubernetes: v1.25.7+k3s1
- OS: 5.19.0-35-generic 36~22.04.1-Ubuntu SMP
- Linkerd: stable-2.12.4

### Possible solution

The only solution at the moment is to skip the port 8080 (which is the proxy port). That works of course but a couple of internal services using 8080 as well and that defeats the purpose a little bit. 

### Would you like to work on fixing this bug?

None
