### ISSUE TITLE
Readiness/Liveness probes with HTTP/2

### ISSUE THREAD

**Issue by lbkolev** [linkerd/linkerd2#10775]
### What problem are you trying to solve?

Linkerd doesn't support readiness/liveness probes sent from kubelet whenever the `Server` CRD is configured with `proxyProtocol: "HTTP/2"`.

Example configuration:
```
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: svc-http
  labels:
    app: svc
  namespace: services
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: svc
  port: http
  proxyProtocol: "HTTP/2"
---
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: svc-route-probe
  namespace: services
spec:
  parentRefs:
    - name: svc-http
      kind: Server
      group: policy.linkerd.io
  rules:
    - matches:
      - path:
          value: "/readiness-check"
        method: GET
---
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: svc-authn-probe
  namespace: services
spec:
  networks:
    - cidr: 0.0.0.0/0
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: svc-policy-probe
  namespace: services
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: svc-route-probe
  requiredAuthenticationRefs:
    - name: svc-authn-probe
      kind: NetworkAuthentication
      group: policy.linkerd.io
```

Error: `Readiness probe failed Get "http://<ip>:<port>/readiness-check": net/http: HTTP/1.x transport connection broken: malformed HTTP response "\x00\x00\x12\x04\x00\x00\x00\x00 ││ \x00\x00\x04\x00\x00\xff\xff\x00\x05\x00\x00@\x00\x00\x06\x01\x00\x00\x00"`

### How should the problem be solved?

One solution would be to make `proxyProtocol` configurable through `HTTPRoute`, so that each `HTTPRoute` can have personalized `proxyProtocol`. This kind of circumvents the issue, but still.

### Any alternatives you've considered?

None

### Would you like to work on this feature?

None
