### ISSUE TITLE
Docs: Dynamic Request Routing support with Cilium Socket LB

### ISSUE THREAD

**Issue by log1cb0mb** [linkerd/linkerd2#10788]
### What problem are you trying to solve?

In environments running Cilium with kube-proxy free setup (` kube-proxy-replacement=strict`), in order for header based routing to work, following Cilium config is required:

> If Cilium is deployed with the kube-proxy replacement (this is not the case by default) you need to pass --config bpf-lb-sock-hostns-only=true to cilium CLI or socketLB.hostNamespaceOnly option with Helm. Without this option, when Cilium does service resolution via socket load balancing, Istio sidecar will be bypassed, resulting in loss of Istio features including encryption and telemetry.

Reference: https://docs.cilium.io/en/v1.13/network/istio/#setup-cilium
However the above applies to Linkerd as well. 

More details on verifiying this config:
https://linkerd.buoyant.io/t/linkerd-dynamic-request-routing-support-with-cilium-socket-lb/99

### How should the problem be solved?

Should this be documented under Linkerd install/setup guide as sort of hint?

### Any alternatives you've considered?

Similar documentation on Cilium side as well maybe? Integration with Linkerd2.

### Would you like to work on this feature?

None

**Comment by log1cb0mb** [comment]
@mateiidavid That is strange. I retried and now even with explicitly setting `socketLB.hostNamespaceOnly=false` and i am able to reproduce the issue. Basically either not passing that config or explicitly set `false`, header-based routing does not occur.

Here is my cilium config (with this I do not get header-based matched backend):

```
cilium install \
  --version $ciliumVersion \
  --helm-set debug.enabled=false \
  --helm-set ipam.mode=cluster-pool-v2beta \
  --helm-set ipam.operator.clusterPoolIPv4PodCIDRList\[0\]="10.51.0.0/17" \
  --helm-set tunnel=disabled \
  --helm-set ipv4NativeRoutingCIDR="10.51.0.0/17" \
  --helm-set bgpControlPlane.enabled=true \
  --helm-set gatewayAPI.enabled=true \
  --helm-set kubeProxyReplacement="strict" \
  --helm-set bpf.masquerade=true \
  --helm-set ipMasqAgent.enabled=true \
  --helm-set ipMasqAgent.config.nomasq-all-reserved-ranges=true \
  --helm-set k8sServiceHost=$clusterName-control-plane \
  --helm-set k8sServicePort="6443" \
  --helm-set securityContext.privileged=true \
  --helm-set socketLB.enabled=true \
  --helm-set socketLB.hostNamespaceOnly=false
```

<details>
<summary>Cilium CM:</summary>
<br>

```yml
agent-not-ready-taint-key: node.cilium.io/agent-not-ready
arping-refresh-period: 30s
auto-direct-node-routes: "false"
bpf-lb-external-clusterip: "false"
bpf-lb-map-max: "65536"
bpf-lb-sock: "true"
bpf-lb-sock-hostns-only: "false"
bpf-map-dynamic-size-ratio: "0.0025"
bpf-policy-map-max: "16384"
bpf-root: /sys/fs/bpf
cgroup-root: /run/cilium/cgroupv2
cilium-endpoint-gc-interval: 5m0s
cluster-id: "0"
cluster-name: kind-pck
cluster-pool-ipv4-cidr: 10.51.0.0/17
cluster-pool-ipv4-mask-size: "24"
cni-uninstall: "true"
custom-cni-conf: "false"
debug: "false"
debug-verbose: ""
disable-cnp-status-updates: "true"
disable-endpoint-crd: "false"
enable-auto-protect-node-port-range: "true"
enable-bgp-control-plane: "true"
enable-bpf-clock-probe: "true"
enable-bpf-masquerade: "true"
enable-endpoint-health-checking: "true"
enable-envoy-config: "true"
enable-gateway-api: "true"
enable-gateway-api-secrets-sync: "true"
enable-health-check-nodeport: "true"
enable-health-checking: "true"
enable-hubble: "true"
enable-ip-masq-agent: "true"
enable-ipv4: "true"
enable-ipv4-masquerade: "true"
enable-ipv6: "false"
enable-ipv6-big-tcp: "false"
enable-ipv6-masquerade: "true"
enable-k8s-terminating-endpoint: "true"
enable-l2-neigh-discovery: "true"
enable-l7-proxy: "true"
enable-local-redirect-policy: "false"
enable-policy: default
enable-remote-node-identity: "true"
enable-sctp: "false"
enable-svc-source-range-check: "true"
enable-vtep: "false"
enable-well-known-identities: "false"
enable-xt-socket-fallback: "true"
gateway-api-secrets-namespace: cilium-secrets
hubble-disable-tls: "false"
hubble-listen-address: :4244
hubble-socket-path: /var/run/cilium/hubble.sock
hubble-tls-cert-file: /var/lib/cilium/tls/hubble/server.crt
hubble-tls-client-ca-files: /var/lib/cilium/tls/hubble/client-ca.crt
hubble-tls-key-file: /var/lib/cilium/tls/hubble/server.key
identity-allocation-mode: crd
identity-gc-interval: 15m0s
identity-heartbeat-timeout: 30m0s
install-no-conntrack-iptables-rules: "false"
ipam: cluster-pool-v2beta
ipv4-native-routing-cidr: 10.51.0.0/17
kube-proxy-replacement: strict
kube-proxy-replacement-healthz-bind-address: ""
monitor-aggregation: medium
monitor-aggregation-flags: all
monitor-aggregation-interval: 5s
node-port-bind-protection: "true"
nodes-gc-interval: 5m0s
operator-api-serve-addr: 127.0.0.1:9234
preallocate-bpf-maps: "false"
remove-cilium-node-taints: "true"
set-cilium-is-up-condition: "true"
sidecar-istio-proxy-image: cilium/istio_proxy
skip-cnp-status-startup-clean: "false"
synchronize-k8s-nodes: "true"
tofqdns-dns-reject-response-code: refused
tofqdns-enable-dns-compression: "true"
tofqdns-endpoint-max-ip-per-hostname: "50"
tofqdns-idle-connection-grace-period: 0s
tofqdns-max-deferred-connection-deletes: "10000"
tofqdns-min-ttl: "3600"
tofqdns-proxy-response-max-delay: 100ms
tunnel: disabled
unmanaged-pod-watcher-interval: "15"
vtep-cidr: ""
vtep-endpoint: ""
vtep-mac: ""
vtep-mask: ""
```
</details>
