### ISSUE TITLE
Introducing a l5d-client-id-header

### ISSUE THREAD

**Issue by elruwen** [linkerd/linkerd2#10789]
### What problem are you trying to solve?

Hi!

I would like to use Linkerd in combination with Knative Serving. Knative allows scaling to 0. In a nutshell, Knative Serving works like this:

Service A -> Knative -> Service B

When Service A does a request, Knative holds the request, scales up Service B if necessary and then forwards the request.

I managed to setup mTLS. So now the connection between Service A and Knative and the connection between Knative and Service B is secured via mTLS.
But I would also like to use an Authorization Policy to make sure that only Service A can talk to Service B and not for example Service C. But since currently everything goes through Knative, that is at the moment not possible.

### How should the problem be solved?

Currently the linkerd-proxy sets the `l5d-client-id` header.

I would like to propose a second header called `l5d-client-id-history` (or a better name). Whenever the linkerd-proxy sees a request with that header, it also appends the value it is about to write into the `l5d-client-id` to that header.

So Service B would receive the following headers (in my example I use contour):
- `l5d-client-id: controller.knative-serving.serviceaccount.identity.linkerd.cluster.local`
- `l5d-client-id-history: service-a.my-namespace.serviceaccount.identity.linkerd.cluster.local,envoy.contour-internal.serviceaccount.identity.linkerd.cluster.local,controller.knative-serving.serviceaccount.identity.linkerd.cluster.local`

The AuthorizationPolicy for Service B would look like this:
- A HTTPRoute which makes sure that the header `l5d-client-id-history` matches the above example
- MeshTLSAuthentication which makes sure all requests are coming from `controller.knative-serving.serviceaccount.identity.linkerd.cluster.local`

This would allow me to control who talks to B with the following limitations:
- I need to trust the code running in the contour and knative. Those services could fake the headers. But those two components got already full access to my HTTP request. If they are compromised, I am lost anyways.
- Service A could fake the header. This can be prevented by setting `proxy.defaultInboundPolicy` to `all-authenticated` on the contour and the knative namespace. This way I always get
  linkerd to set its headers. If the application also sets the header, the resulting value will be `fake-value,service-a.my-namespace.serviceaccount.identity.linkerd.cluster.local,envoy.contour-internal.serviceaccount.identity.linkerd.cluster.local,controller.knative-serving.serviceaccount.identity.linkerd.cluster.local`
  which again would not match the authorization policy.

Such a solution could also benefit similar setups, just not knative.

### Any alternatives you've considered?

So far I had no other idea.

### How would users interact with this feature?

Some example yaml. The service go-client is allowed to talk to go-server.

```yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: go-web
  namespace: ruwen
spec:
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: MeshTLSAuthentication
      name: go-web
      namespace: ruwen
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: go-web
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: go-webhealth
  namespace: ruwen
spec:
  requiredAuthenticationRefs: []
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: go-webhealth
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: go-web
  namespace: ruwen
spec:
  identities:
    - controller.knative-serving.serviceaccount.identity.linkerd.cluster.local
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  labels:
    app: go-web
  name: go-web
  namespace: ruwen
spec:
  podSelector:
    matchLabels:
      app: go-web
  port: queue-port
  proxyProtocol: unknown
---
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: go-web
  namespace: ruwen
spec:
  parentRefs:
    - group: policy.linkerd.io
      kind: Server
      name: go-web
  rules:
    - matches:
        - headers:
            - name: Client-Id-History
              value: go-client.ruwen.serviceaccount.identity.linkerd.cluster.local,envoy.contour-internal.serviceaccount.identity.linkerd.cluster.local,controller.knative-serving.serviceaccount.identity.linkerd.cluster.local
---
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: go-webhealth
  namespace: ruwen
spec:
  parentRefs:
    - group: policy.linkerd.io
      kind: Server
      name: go-web
  rules:
    - matches:
        - headers:
            - name: K-Network-Probe
              value: queue
          path:
            type: Exact
            value: /
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-web
  namespace: ruwen
spec:
  template:
    metadata:
      labels:
        app: go-web
    spec:
      containers:
        - image: ...
          name: go-web
          ports:
            - containerPort: 8081
      serviceAccountName: go-web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: go-web
  namespace: ruwen

```

### Would you like to work on this feature?

yes
