### ISSUE TITLE
no TCP traffic in dashboard for php and rabbitmq services

### ISSUE THREAD

**Issue by Vodzo** [linkerd/linkerd2#10798]
### What is the issue?

I've been testing linkerd to see if it would work in my environment. My services are usually many nginx, php and rabbitmq services so I made a PoC to see how it would work but i dont see any TCP traffic between nginx->php->rabbitmq when checking through the dashboard. I tried playing with opaque ports but i'm not sure if that is the problem or something else.

### How can it be reproduced?

Attached is the manifest used for testing. You can reproduce by running `cat nginx.yaml | linkerd inject - | kubectl apply -f -` and open http://localhost:32222 in browser

nginx.yaml:
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tester
  namespace: linkerd-test
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: linkerd-test
spec:
  type: NodePort
  selector:
    app: nginx-svc
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 32222
---
apiVersion: v1
kind: Service
metadata:
  name: rmq-svc
  namespace: linkerd-test
spec:
  type: NodePort
  selector:
    app: rmq-svc
  ports:
  - name: http-admin
    port: 15672
    targetPort: 15672
    nodePort: 32224
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: linkerd-test
data:
  nginx.conf: |
    server {
      listen 80;
      listen [::]:80;
      access_log off;
      root /var/www/html;
      index index.php;
      server_name example.com;
      server_tokens off;
      location / {
        #proxy_pass http://nginxq-svc.linkerd-test:80;
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ /index.php?$args;
      }
      # pass the PHP scripts to FastCGI server listening on wordpress:9000
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
          
        # Change The Service Name
        fastcgi_pass php-svc.linkerd-test:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-content
  namespace: linkerd-test
data:
  index.php: |
    <?php
    ini_set('display_errors', 1);
    error_reporting(E_ALL);
    require('vendor/autoload.php');

    use PhpAmqpLib\Connection\AMQPStreamConnection;
    use PhpAmqpLib\Message\AMQPMessage;

    $connection = new AMQPStreamConnection('rmq-svc.linkerd-test', 5672, 'guest', 'guest');
    $channel = $connection->channel();

    $channel->queue_declare('hello', false, false, false, false);

    $msg = new AMQPMessage('Hello World!');
    $channel->basic_publish($msg, '', 'hello');

    echo "php exec done";
  composer.json: |
    {
      "require": {
          "php-amqplib/php-amqplib": "^3.5"
      }
    }

---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
  namespace: linkerd-test
spec:
  type: ClusterIP
  selector:
    app: php-svc
  ports:
  - name: php-port
    port: 9000
    protocol: TCP
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: linkerd-test
spec:
  selector:
    matchLabels:
      app: nginx-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-svc
    spec:
      containers:
      - name: nginx-svc
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-config
            subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: php
    app.kubernetes.io/part-of: linkerd-test
    app.kubernetes.io/version: v11
  name: php
  namespace: linkerd-test
spec:
  selector:
    matchLabels:
      app: php-svc
      version: v11
  replicas: 1
  template:
    metadata:
      labels:
        app: php-svc
        version: v11
    spec:
      serviceAccountName: tester
      containers:
      - name: php-svc
        image: php:8.1-fpm-alpine
        command: ["/bin/ash"]
        args: ["-c", "apk add composer && docker-php-ext-install sockets && docker-php-ext-enable sockets && composer install --ignore-platform-req=ext-sockets && docker-php-entrypoint php-fpm"]
        ports:
        - containerPort: 9000
          protocol: TCP
          name: php-fpm
        volumeMounts:
          - mountPath: /var/www/html/index.php
            name: php-content
            subPath: index.php
          - mountPath: /var/www/html/composer.json
            name: php-content
            subPath: composer.json
      volumes:
        - name: php-content
          configMap:
            name: php-content
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmq
  namespace: linkerd-test
spec:
  selector:
    matchLabels:
      app: rmq-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: rmq-svc
    spec:
      containers:
      - name: rmq-svc
        image: rabbitmq:3-management
        ports:
        - containerPort: 15672
          name: http-admin
        - containerPort: 5672
          name: rabbitmq
```

### Logs, error output, etc

-

### output of `linkerd check -o short`

```text
Status check results are √
```

### Environment

- Kubernetes version: 1.25.4
- Host OS: macOS
- Linkerd version: stable-2.13.1

### Would you like to work on fixing this bug?

None
