### ISSUE TITLE
WebSocket connection to 'ws://xxxx.xxxx.com/api/tap' failed

### ISSUE THREAD

**Issue by 5279314** [linkerd/linkerd2#10824]
### What is the issue?

i'm using traefik controllers.Linkerd dashboard and grafana dashboards are working finely.but in linkerd dashboard tops and taps are not showing up. when i inspect, it gives me this error message.
```
WebSocket connection to 'ws://viz.od.com/api/tap' failed: 
```

### How can it be reproduced?

Traefik configuration
```
cat k8s-yaml/viz-ing.yaml 
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: linkerd-dashboard
  namespace: linkerd-viz
  annotations:
    ingress.kubernetes.io/custom-request-headers: l5d-dst-override:web.linkerd-viz.svc.cluster.local:8084
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`viz.od.com`)  # 指定域名
    kind: Rule
    services:
    - name: web
      port: 8084
  - match: Host(`viz.od.com`) && Path(`/api/tap`)
    kind: Rule
    services:
    - name: tap
      port: 8088
```
Nginx proxy
```
upstream default_backend_traefik {
        server 10.1.1.120:30080 max_fails=3 fail_timeout=10s;
        server 10.1.1.100:30080 max_fails=3 fail_timeout=10s;
        server 10.1.1.130:30080 max_fails=3 fail_timeout=10s;
    }
server {
    server_name *.od.com;
  
    location / {
        proxy_pass http://default_backend_traefik;
        proxy_set_header Host       $http_host;
        proxy_set_header x-forwarded-for $proxy_add_x_forwarded_for;
    }
}
```

### Logs, error output, etc

WebSocket connection to 'ws://viz.od.com/api/tap' failed: 

### output of `linkerd check -o short`

```text
linkerd check -o short
linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.1 but the latest stable version is 2.13.2
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.1 but the latest stable version is 2.13.2
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-7fcf6649dd-qxtwv (stable-2.13.1)
        * linkerd-identity-68d57d5-s6kt5 (stable-2.13.1)
        * linkerd-proxy-injector-759c487549-sdw78 (stable-2.13.1)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-57d84584db-jbvp9 pod
    see https://linkerd.io/2.13/checks/#l5d-viz-pods-injection for hints
‼ viz extension pods are running
    container "linkerd-proxy" in pod "metrics-api-57d84584db-jbvp9" is not ready
    see https://linkerd.io/2.13/checks/#l5d-viz-pods-running for hints
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
        * tap-85c5cdb685-8bbx6 (stable-2.13.1)
        * tap-injector-f88789d8f-lr2k7 (stable-2.13.1)
        * web-75b4d744df-v5d7b (stable-2.13.1)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

Kubernetes Version:v1.23.6
Host OS:Centos
Linkerd version: stable-2.13.1

### Would you like to work on fixing this bug?

None
