### ISSUE TITLE
Mutating Webhook - Configurable with Helm Chart

### ISSUE THREAD

**Issue by rufreakde** [linkerd/linkerd2#10867]
### What problem are you trying to solve?

We are using a hyperscaler framework called Gardener which maintains cluster configurations hybernation reconcilation with updates etc.

Here we have the following error:
```bash
Your Action is required
This error is flagged as user error which indicates that no Gardener operator action is required. Please read the error message carefully and take action.
A misconfigured webhook prevents Gardener from performing operations. Please resolve this as this can lead to required actions not being performed which will eventually turn the cluster into an error state.
[Best practices](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings)

MutatingWebhookConfiguration "linkerd-proxy-injector-webhook-config" is problematic: webhook "linkerd-proxy-injector.linkerd.io" with failurePolicy "Fail" and 10s timeout might prevent worker nodes from properly joining the shoot cluster
```
[Best practices](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings)

I looked into the helm chart we use and cant see any way to configure the defaults.

### How should the problem be solved?

It seems that it is currently not possible to modify these values in the helm chart? Should be opened up?
```yaml
---
{{- end }}
{{- include "linkerd.webhook.validation" .Values.proxyInjector }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: linkerd-proxy-injector-webhook-config
  {{- if or (.Values.proxyInjector.injectCaFrom) (.Values.proxyInjector.injectCaFromSecret) }}
  annotations:
  {{- if .Values.proxyInjector.injectCaFrom }}
    cert-manager.io/inject-ca-from: {{ .Values.proxyInjector.injectCaFrom }}
  {{- end }}
  {{- if .Values.proxyInjector.injectCaFromSecret }}
    cert-manager.io/inject-ca-from-secret: {{ .Values.proxyInjector.injectCaFromSecret }}
  {{- end }}
  {{- end }}
  labels:
    linkerd.io/control-plane-component: proxy-injector
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
webhooks:
- name: linkerd-proxy-injector.linkerd.io
  namespaceSelector:
    {{- toYaml .Values.proxyInjector.namespaceSelector | trim | nindent 4 }}
  objectSelector:
    {{- toYaml .Values.proxyInjector.objectSelector | trim | nindent 4 }}
  clientConfig:
    service:
      name: linkerd-proxy-injector
      namespace: {{ .Release.Namespace }}
      path: "/"
    {{- if and (empty .Values.proxyInjector.injectCaFrom) (empty .Values.proxyInjector.injectCaFromSecret) }}
    caBundle: {{ ternary (b64enc (trim $ca.Cert)) (b64enc (trim .Values.proxyInjector.caBundle)) (empty .Values.proxyInjector.caBundle) }}
    {{- end }}
  failurePolicy: {{.Values.webhookFailurePolicy}}
  admissionReviewVersions: ["v1", "v1beta1"]
  rules:
  - operations: [ "CREATE" ]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods", "services"]
  sideEffects: None
```

### Any alternatives you've considered?

Configure the default values in a way so users do not need to take care of it (would be a preferred approach?
[Best practices](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings)

### How would users interact with this feature?

N/A

### Would you like to work on this feature?

no
