### ISSUE TITLE
Grafana dashboards old templating datasource

### ISSUE THREAD

**Issue by albundy83** [linkerd/linkerd2#10873]
### What is the issue?

Hello,
to not have the error `Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found` when manually importing Grafana dashboards, it will be nice to add the following part to `templating` section in Grafana dashboards:
From:
```yaml
....
"templating": {
    "list": [
      {
        "allValue": ".*",
        "current": {},
        "datasource": "${DS_PROMETHEUS}",
        "definition": "",
        "hide": 0,
        "includeAll": false,
        "label": "Namespace",
        "multi": false,
        "name": "namespace",
        "options": [],
        "query": "label_values(request_total, namespace)",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
...
```
To:
```yaml
....
"templating": {
    "list": [
      {
        "hide": 0,
        "label": "datasource",
        "name": "DS_PROMETHEUS",
        "options": [],
        "query": "prometheus",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      },
      {
        "allValue": ".*",
        "current": {},
        "datasource": "${DS_PROMETHEUS}",
        "definition": "",
        "hide": 0,
        "includeAll": false,
        "label": "Namespace",
        "multi": false,
        "name": "namespace",
        "options": [],
        "query": "label_values(request_total, namespace)",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
...
```

If you are agree, I can do a MR 👍 

### How can it be reproduced?

Manually import Grafana dashboards when you have your own Grafana deployment.

### Logs, error output, etc

The error message in Grafana: `Failed to upgrade legacy queries Datasource ${DS_PROMETHEUS} was not found`

### output of `linkerd check -o short`

```text
linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-05-11T14:56:57Z
    see https://linkerd.io/2.13/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
        * metrics-api-56f77c67cd-fd76g (stable-2.13.2)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints
‼ viz extension proxies and cli versions match
    metrics-api-56f77c67cd-fd76g running stable-2.13.2 but cli running stable-2.13.3
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cli-version for hints

Status check results are √
```

### Environment

- Kubernetes: v1.24.13
- Self made cluster with RKE
- Ubuntu 22.04
- Linkerd: 2.13.3

### Possible solution

Add this to templating in dashboards:
```yaml
      {
        "hide": 0,
        "label": "datasource",
        "name": "DS_PROMETHEUS",
        "options": [],
        "query": "prometheus",
        "refresh": 1,
        "regex": "",
        "type": "datasource"
      },
```

### Would you like to work on fixing this bug?

yes
