### ISSUE TITLE
Probes respond with 403 if using URL parameters

### ISSUE THREAD

**Issue by marianbendik** [linkerd/linkerd2#10877]
### What is the issue?

When URL parameters are part of the httpGet probe path, Linkerd's responds with HTTP 403. If no URL parameter is set as a part of the probe path, probes are successful.

### How can it be reproduced?

```
apiVersion: v1
kind: Namespace
metadata:
  name: test-nginx
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/default-inbound-policy: deny
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-nginx
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: nginx-service
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/app: nginx
  port: 80
  proxyProtocol: unknown
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          command: ["nginx", "-g", "daemon off;"]
          startupProbe:
            httpGet:
              path: /health?xx=yy
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 1
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
            items:
              - key: default.conf
                path: default.conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  namespace: test-nginx
data:
  default.conf: |
    server {
        listen 80;
        location /health {
            return 200;
      }
    }
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: application-workload-mesh-tls-authentication
  namespace: test-nginx
spec:
  identities:
  - '*.test-nginx.serviceaccount.identity.linkerd.cluster.local'
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  labels:
  name: application-workload-authorization-policy
  namespace: test-nginx
spec:
  requiredAuthenticationRefs:
  - group: policy.linkerd.io
    kind: MeshTLSAuthentication
    name: application-workload-mesh-tls-authentication
  targetRef:
    kind: Namespace
    name: test-nginx
```

### Logs, error output, etc

Deployment events:
```
Events:
  Type     Reason           Age                From               Message
  ----     ------           ----               ----               -------
  Warning  FailedMount      47s                kubelet            MountVolume.SetUp failed for volume "nginx-config" : configmap "nginx-configmap" not found
  Normal   Scheduled        47s                default-scheduler  Successfully assigned test-nginx/nginx-deployment-65c489b94b-7v8n7 to ip-10-63-205-124.ec2.internal
  Normal   Pulled           46s                kubelet            Container image "cr.l5d.io/linkerd/proxy-init:v2.2.1" already present on machine
  Normal   Created          46s                kubelet            Created container linkerd-init
  Normal   Started          44s                kubelet            Started container linkerd-init
  Normal   Pulled           43s                kubelet            Container image "cr.l5d.io/linkerd/proxy:stable-2.13.1" already present on machine
  Normal   Created          43s                kubelet            Created container linkerd-proxy
  Normal   Started          43s                kubelet            Started container linkerd-proxy
  Normal   Pulled           42s                kubelet            Successfully pulled image "nginx:latest" in 98.078719ms
  Warning  PolicyViolation  17s                kyverno-scan       policy require-requests-limits/validate-resources fail: validation error: CPU and memory resource requests and limits are required. rule validate-resources failed at path /sp
ec/containers/0/resources/limits/
  Warning  PolicyViolation  17s                kyverno-scan       policy disallow-latest-tag/validate-image-tag fail: validation error: Using a mutable image tag e.g. 'latest' is not allowed. rule validate-image-tag failed at path /spec/con
tainers/1/image/
  Normal   Pulling          16s (x2 over 42s)  kubelet            Pulling image "nginx:latest"
  Normal   Started          16s (x2 over 42s)  kubelet            Started container nginx
  Normal   Created          16s (x2 over 42s)  kubelet            Created container nginx
  Normal   Killing          16s                kubelet            Container nginx failed startup probe, will be restarted
  Normal   Pulled           16s                kubelet            Successfully pulled image "nginx:latest" in 107.116616ms
  Warning  Unhealthy        1s (x4 over 26s)   kubelet            Startup probe failed: HTTP probe failed with statuscode: 403
```

Pod logs:
```
linkerd-init time="2023-05-10T11:58:13Z" level=info msg="/sbin/iptables-save -t nat"
linkerd-init time="2023-05-10T11:58:13Z" level=info msg="# Generated by iptables-save v1.8.8 on Wed May 10 11:58:13 2023\n*nat\n:PREROUTING ACCEPT [0:0]\n:INPUT ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\nCOMMIT\n# Completed on Wed May 10 11:58:13 2023\n"
linkerd-init time="2023-05-10T11:58:13Z" level=info msg="/sbin/iptables -t nat -N PROXY_INIT_REDIRECT"
linkerd-init time="2023-05-10T11:58:13Z" level=info msg="/sbin/iptables -t nat -A PROXY_INIT_REDIRECT -p tcp --match multiport --dports 4190,4191,4567,4568 -j RETURN -m comment --comment proxy-init/ignore-port-4190,4191,4567,4568/1683719893"
linkerd-init time="2023-05-10T11:58:13Z" level=info msg="/sbin/iptables -t nat -A PROXY_INIT_REDIRECT -p tcp -j REDIRECT --to-port 4143 -m comment --comment proxy-init/redirect-all-incoming-to-proxy-port/1683719893"
linkerd-init time="2023-05-10T11:58:13Z" level=info msg="/sbin/iptables -t nat -A PREROUTING -j PROXY_INIT_REDIRECT -m comment --comment proxy-init/install-proxy-init-prerouting/1683719893"
linkerd-init time="2023-05-10T11:58:13Z" level=info msg="/sbin/iptables -t nat -N PROXY_INIT_OUTPUT"
linkerd-init time="2023-05-10T11:58:14Z" level=info msg="/sbin/iptables -t nat -A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -j RETURN -m comment --comment proxy-init/ignore-proxy-user-id/1683719893"
linkerd-init time="2023-05-10T11:58:14Z" level=info msg="/sbin/iptables -t nat -A PROXY_INIT_OUTPUT -o lo -j RETURN -m comment --comment proxy-init/ignore-loopback/1683719893"
linkerd-init time="2023-05-10T11:58:14Z" level=info msg="/sbin/iptables -t nat -A PROXY_INIT_OUTPUT -p tcp --match multiport --dports 4567,4568 -j RETURN -m comment --comment proxy-init/ignore-port-4567,4568/1683719893"
linkerd-init time="2023-05-10T11:58:14Z" level=info msg="/sbin/iptables -t nat -A PROXY_INIT_OUTPUT -p tcp -j REDIRECT --to-port 4140 -m comment --comment proxy-init/redirect-all-outgoing-to-proxy-port/1683719893"
linkerd-init time="2023-05-10T11:58:14Z" level=info msg="/sbin/iptables -t nat -A OUTPUT -j PROXY_INIT_OUTPUT -m comment --comment proxy-init/install-proxy-init-output/1683719893"
linkerd-init time="2023-05-10T11:58:14Z" level=info msg="/sbin/iptables-save -t nat"
linkerd-init time="2023-05-10T11:58:14Z" level=info msg="# Generated by iptables-save v1.8.8 on Wed May 10 11:58:14 2023\n*nat\n:PREROUTING ACCEPT [0:0]\n:INPUT ACCEPT [0:0]\n:OUTPUT ACCEPT [0:0]\n:POSTROUTING ACCEPT [0:0]\n:PROXY_INIT_OUTPUT - [0:0]\n:PROXY_INIT_REDIRECT - [0:0]\n-A PREROUTING -m comment --comment \"proxy-init/install-proxy-init-prerouting/1683719893\" -j PROXY_INIT_REDIRECT\n-A OUTPUT -m comment --comment \"proxy-init/install-proxy-init-output/1683719893\" -j PROXY_INIT_OUTPUT\n-A PROXY_INIT_OUTPUT -m owner --uid-owner 2102 -m comment --comment \"proxy-init/ignore-proxy-user-id/1683719893\" -j RETURN\n-A PROXY_INIT_OUTPUT -o lo -m comment --comment \"proxy-init/ignore-loopback/1683719893\" -j RETURN\n-A PROXY_INIT_OUTPUT -p tcp -m multiport --dports 4567,4568 -m comment --comment \"proxy-init/ignore-port-4567,4568/1683719893\" -j RETURN\n-A PROXY_INIT_OUTPUT -p tcp -m comment --comment \"proxy-init/redirect-all-outgoing-to-proxy-port/1683719893\" -j REDIRECT --to-ports 4140\n-A PROXY_INIT_REDIRECT -p tcp -m multiport --dports 4190,4191,4567,4568 -m comment --comment \"proxy-init/ignore-port-4190,4191,4567,4568/1683719893\" -j RETURN\n-A PROXY_INIT_REDIRECT -p tcp -m comment --comment \"proxy-init/redirect-all-incoming-to-proxy-port/1683719893\" -j REDIRECT --to-ports 4143\nCOMMIT\n# Completed on Wed May 10 11:58:14 2023\n"
linkerd-proxy [     0.002097s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
linkerd-proxy [     0.002503s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
linkerd-proxy [     0.002520s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
linkerd-proxy [     0.002523s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
linkerd-proxy [     0.002526s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
linkerd-proxy [     0.002529s]  INFO ThreadId(01) linkerd2_proxy: Local identity is default.test-nginx.serviceaccount.identity.linkerd.cluster.local
linkerd-proxy [     0.002532s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
linkerd-proxy [     0.002535s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
linkerd-proxy [     0.012936s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity id=default.test-nginx.serviceaccount.identity.linkerd.cluster.local
linkerd-proxy [    16.356987s]  INFO ThreadId(01) inbound:server{port=80}: linkerd_app_inbound::policy::http: Request denied server.group= server.kind=default server.name=deny route.group= route.kind=default route.name=default client.tls=None(NoClientHello) client.ip=10.63.205.124
linkerd-proxy [    16.357048s]  INFO ThreadId(01) inbound:server{port=80}:rescue{client.addr=10.63.205.124:34506}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=client 10.63.205.124:34506: server: 10.63.201.157:80: unauthorized request on route error.sources=[unauthorized request on route]
linkerd-proxy [    21.357272s]  INFO ThreadId(01) inbound:server{port=80}: linkerd_app_inbound::policy::http: Request denied server.group= server.kind=default server.name=deny route.group= route.kind=default route.name=default client.tls=None(NoClientHello) client.ip=10.63.205.124
linkerd-proxy [    21.357309s]  INFO ThreadId(01) inbound:server{port=80}:rescue{client.addr=10.63.205.124:34508}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=client 10.63.205.124:34508: server: 10.63.201.157:80: unauthorized request on route error.sources=[unauthorized request on route]
linkerd-proxy [    26.356402s]  INFO ThreadId(01) inbound:server{port=80}: linkerd_app_inbound::policy::http: Request denied server.group= server.kind=default server.name=deny route.group= route.kind=default route.name=default client.tls=None(NoClientHello) client.ip=10.63.205.124
linkerd-proxy [    26.356440s]  INFO ThreadId(01) inbound:server{port=80}:rescue{client.addr=10.63.205.124:57128}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=client 10.63.205.124:57128: server: 10.63.201.157:80: unauthorized request on route error.sources=[unauthorized request on route]
nginx 2023/05/10 11:58:41 [notice] 1#1: using the "epoll" event method
nginx 2023/05/10 11:58:41 [notice] 1#1: nginx/1.23.4
nginx 2023/05/10 11:58:41 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
nginx 2023/05/10 11:58:41 [notice] 1#1: OS: Linux 5.10.167-147.601.amzn2.x86_64
nginx 2023/05/10 11:58:41 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker processes
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 7
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 8
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 9
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 10
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 11
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 12
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 13
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 14
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 15
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 16
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 17
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 18
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 19
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 20
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 21
nginx 2023/05/10 11:58:41 [notice] 1#1: start worker process 22
Stream closed EOF for test-nginx/nginx-deployment-65c489b94b-7v8n7 (linkerd-init)

```

### output of `linkerd check -o short`

linkerd check -o short
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.3 but the latest stable version is 2.13.3
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.1 but the latest stable version is 2.13.3
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.13.1 but cli running stable-2.12.3
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-85975b4cfd-dx27k (stable-2.13.1)
	* linkerd-identity-5d66f99675-qr6dw (stable-2.13.1)
	* linkerd-proxy-injector-8674789f59-xjnvs (stable-2.13.1)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints
‼ control plane proxies and cli versions match
    linkerd-destination-85975b4cfd-dx27k running stable-2.13.1 but cli running stable-2.12.3
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-cli-version for hints

Status check results are √

### Environment

- Kubernetes version: v1.24.10-eks-48e63af
- Linkerd version: stable-2.13.1

### Additional context

Based on the [Default Authorization](https://linkerd.io/2.13/features/server-policy/#default-authorizations) documentation, the Kubelet probes do not need to be explicitly authorized, if no HTTPRoutes are configured for that Server - which is our case.

As part of the Linkerd implementation in our ecosystem, we are meshing Elasticsearch, that uses an httpProbe with path `/_cluster/health?wait_for_status=yellow&timeout=2s`. After deleting the URL param's, the probe was working as expected. 

### Would you like to work on fixing this bug?

None
