### ISSUE TITLE
Documentation needs update / tracing part

### ISSUE THREAD

**Issue by Jeansen** [linkerd/linkerd2#10887]
### What is the issue?

https://linkerd.io/2.13/tasks/distributed-tracing/

documents under "Bring your own jaeger" as part of the configruation:

```
exporters:
      jaeger:
        endpoint: my-jaeger-collector.my-jaeger-ns:14250
        insecure: true
``` 

This will fail. With reference to https://github.com/linkerd/linkerd2/blob/stable-2.13.3/jaeger/charts/linkerd-jaeger/values.yaml it should be:

```
exporters:
      jaeger:
        endpoint: my-jaeger-collector.my-jaeger-ns:14250
        tls:
          insecure: true
```

Also, at the end of section "Integration with Dashboard, there is this command:

```
linkerd viz install --set jaegerUrl=jaeger.linkerd-jaeger:16686
```

which should be

```
linkerd viz install --set jaegerUrl=jaeger.linkerd-jaeger:16686 | kubectl apply -f -
```

### How can it be reproduced?

n/a

### Logs, error output, etc

n/a

### output of `linkerd check -o short`

n/a

### Environment

n/a

### Possible solution

Maybe it is best to review the whole documentation? :-)

### Additional context

n/a

### Would you like to work on fixing this bug?

None
