### ISSUE TITLE
Viz dashboard integration with jaeger not working

### ISSUE THREAD

**Issue by Jeansen** [linkerd/linkerd2#10895]
### What is the issue?

Integration of Jaeger with the Dashboard does not work.

My Jaegert installation is reachable e.g. via `jaeger-query.default.svc.cluster.local:16686`. I confirmed this from a temporary pod. The service just provided is reachable.

If I ran `linkerd viz install --set jaegerUrl=jaeger-query.default.svc.cluster.local:16686`, but whenever I click an any service, I get a blank page. 

### How can it be reproduced?

1. Have a k8s cluster (mine runs 1.27).
2. Install Jaeger
3. Follow https://linkerd.io/2.13/tasks/distributed-tracing/#integration-with-the-dashboard, but deviate from it with the part, where you bring your own Jaeger.

### Logs, error output, etc

n/a

### output of `linkerd check -o short`

```
Status check results are √
```

### Environment

- Kubernetes: 1.27
- Linkerd: 2.13.3
- OS: Debian 11
- Cluster: Custom local installation, 3 master Nodes, 4 Workers.

### Possible solution

n/a

### Additional context

In the Dashboard, when I click on any pod, e.g. `http://localhost:50750/jaeger/search?service=linkerd-proxy&tags={%22linkerd.io%2Fproxy-deployment%22%3A%22emoji%22%2C%22linkerd.io/workload-ns%22%3A%22emojivoto%22}`, I get a white page.

That's also true for `http://localhost:50750/jaeger/`

In the developer tools I see that `http://localhost:50750/static/index-69a9fbe0.js` and `http://localhost:50750/static/index-3c2d679b.css` return a 404 page not found.

### Would you like to work on fixing this bug?

maybe

**Comment by alpeb** [comment]
Thanks for the detailed report :+1: 
Those URLs like `http://localhost:50750/static/index-69a9fbe0.js` are the smoking gun. Those resources should be retrieved from something like `http://localhost:50750/jaeger/static/index-69a9fbe0.js` instead. Can you look into your Jaeger config, maybe there's some setting related to the website's root directory? If that doesn't bring any clues, can you provide some deployment instructions I could follow to reproduce the issue?

**Comment by Jeansen** [comment]
@alpeb So, I did some more configuring in my cluster. Currently I utilize ExternalDNS with my local DNS. This works like a charm! I can now access the linkerd dashbarod via my Ingress in my local DNS, e.g. vis.k8s.lab. The same is true for jaeger, at jaeger.k8s.lab. 

So, I have these two dashboards available. Then, I ran `linkerd viz install --set jaegerUrl=jaeger.k8s.lab | kubectl apply -f -`. Now, I see the jaeger icon next to some pods. 

But when I click on them, I get something like this:
`http://viz.k8s.lab/jaeger/search?service=linkerd-proxy&tags={%22host.name%22%3A%22linkerd-destination-59ccc8cdb-k9vbk%22%2C%22linkerd.io/workload-ns%22%3A%22linkerd%22}`

This does not forward me to my jaeger UI. If I replace this with `http://jaeger.k8s.lab/search?service=linkerd-proxy&tags={%22host.name%22%3A%22linkerd-destination-59ccc8cdb-k9vbk%22%2C%22linkerd.io/workload-ns%22%3A%22linkerd%22}`, it get the right search request in the jaeger UI.

**Comment by Jeansen** [comment]
I now also played around with the emoji demo. When I click on one of the pods, e.g. the vote Pod and correct the URL, the following tags will be filled in: `host.name=emoji-65f997979d-rpbnw linkerd.io/workload-ns=emojivoto`

But when I check the spans, there is not `host.name`. What I find is `http.host`. And that works, with the service name, instead of the Pod name. ` host.name` is no Tag, but part of the Process. Also, in no span I find the tags `linkerd.io/workload-ns=emojivoto`.

**Comment by alpeb** [comment]
You can access jaeger with `jaeger.k8s.lab` via your ingress, but the linkerd-viz extension requires the internal fqdn for jaeger which is `<svc_name>.<svc_namespace>:16686` assuming the jaeger ui is listening on that port.

As for the tags, from my understanding one can filter with either "tags" or "process tags". Clicking on the jaeger icon for the vote-bot for example brings jaeger with the tags filter `host.name=vote-bot-5f7c89757-gxwg9 linkerd.io/workload-ns=emojivoto` and clicking on any trace on the right and then on the first span I see the process tags corresponding to the filter:
![image](https://github.com/linkerd/linkerd2/assets/554287/27b13c19-3c41-4122-91d4-78117260f857)

**Comment by Jeansen** [comment]
@alpeb Thank you for the details. where would I configure the jaeger enpoint for linkerd? I followed https://linkerd.io/2.13/tasks/distributed-tracing/#bring-your-own-jaeger and my setting for this looks like this:

```
kubectl apply --force -f - <<EOF
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-daemonset
  namespace: $ns
#  namespace: opentelemetry-operator-system
spec:
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - operator: Exists
      effect: NoSchedule
    - operator: Exists
      effect: NoExecute
  mode: daemonset
  config: |
    receivers:
      # Make sure to add the otlp receiver.
      # This will open up the receiver on port 4317
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318" 
      opencensus:
      zipkin:
      jaeger:
        protocols:
          grpc:
          thrift_http:
          thrift_compact:
          thrift_binary:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      batch:
    extensions:
      health_check:
    exporters:
      jaeger:
        endpoint: jaeger-collector.${ns}.svc.cluster.local:14250
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: "http://prometheus-grafana-kube-pr-prometheus.default.svc.cluster.local:9090/api/v1/write"
        external_labels:
          cluster: prod
      logging:
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp,opencensus,zipkin,jaeger]
          processors: [memory_limiter, batch]
          exporters: [jaeger]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [prometheusremotewrite, logging]
EOF
```
