### ISSUE TITLE
Multicluster - Support Headless Services that do not match STS serviceName

### ISSUE THREAD

**Issue by jalder** [linkerd/linkerd2#10916]
### What problem are you trying to solve?

I have a need to export headless services that do not match the statefulset's serviceName (pod's subdomain).  

In Kubernetes, the headless service's endpoints do not include a hostname field unless the pod subDomain (pulled from the statefulset's serviceName) matches that of the headless service name.

However, it is viable to create headless services that do not match the serviceName and the targets are still discovered by labels successfully.

The endpoints for a headless service without matching serviceName appear as such:
```
subsets:
- addresses:
  - ip: 10.42.0.70
    nodeName: k3d-cluster1-agent-1
    targetRef:
      kind: Pod
      name: linkerd-0-1
      namespace: mongodb
      uid: 57326f33-2938-4041-821c-f631f7ac58db
  - ip: 10.42.3.45
    nodeName: k3d-cluster1-agent-0
    targetRef:
      kind: Pod
      name: linkerd-0-0
      namespace: mongodb
      uid: a61525c6-b931-4007-a81d-e7fd053aa132
  ports:
  - port: 27017
    protocol: TCP
```

### How should the problem be solved?

In cluster_watcher_headless.go, function createOrUpdateHeadlessEndpoints has a continue statement when the address.Hostname == "" ([Reference link](https://github.com/linkerd/linkerd2/blob/9c9b4349469049deac88f4407665213ef67eecd1/multicluster/service-mirror/cluster_watcher_headless.go#L103-L105))

Rather than using the hostname for the exported service name, could the cluster watcher mirror it using the targetRef.name instead?

### Any alternatives you've considered?

Create individual services for each statefulset member and label them for export.  In the other cluster, create traffic splits to route the original hostname back to the matching exported name.

### Would you like to work on this feature?

maybe
