### ISSUE TITLE
Dynamic request routing fails across namespaces

### ISSUE THREAD

**Issue by andrewwdye** [linkerd/linkerd2#10955]
### What is the issue?

Routing a request to a namespace different than the route fails with "Service not found"

### How can it be reproduced?

This is a modified version of the [dynamic request routing sample](https://linkerd.io/2.13/tasks/configuring-dynamic-request-routing/)

```
kubectl create ns test --dry-run -o yaml \
  | linkerd inject - \
  | kubectl apply -f -
```

Install backends (including an additional `backend-c` in namespace `test2`) and frontend
```
helm install backend-a -n test \
  --set ui.message='A backend' podinfo/podinfo
helm install backend-b -n test \
  --set ui.message='B backend' podinfo/podinfo
helm install backend-c -n test2 --create-namespace \
  --set ui.message='C backend' podinfo/podinfo
helm install frontend -n test \
  --set backend=http://backend-a-podinfo:9898/env podinfo/podinfo
```

Create a simple route to forward requests from `backend-a-podinfo` to `backend-c-pod-info`
```
cat <<EOF | kubectl -n test apply -f -
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: backend-router
  namespace: test
spec:
  parentRefs:
    - name: backend-a-podinfo
      kind: Service
      group: core
      port: 9898
  rules:
    - backendRefs:
      - name: "backend-c-podinfo"
        namespace: test2
        port: 9898
EOF
```

Port forward
```
kubectl -n test port-forward svc/frontend-podinfo 9898
```

Hit `backend-a-podinfo`
```
❯ curl -X POST localhost:9898/echo
```

### Logs, error output, etc

Hit `backend-a-podinfo`
```
❯ curl -X POST localhost:9898/echo
[
  "backend http://backend-a-podinfo:9898/env response status code 500"
]%
```

Check linkerd-proxy logs to find `Service not found` error
```
frontend-podinfo-976c94d58-rxj95 linkerd-proxy [  1174.296339s]  INFO ThreadId(01) outbound:proxy{addr=10.101.139.182:9898}:rescue{client.addr=10.244.0.33:50904}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=logical service 10.101.139.182:9898: HTTP request configured to fail with 500 Internal Server Error: Service not found backend-c-podinfo error.sources=[HTTP request configured to fail with 500 Internal Server Error: Service not found backend-c-podinfo]
```

Verify that hitting `backend-b-podinfo` in the `test` namespace works fine

Create a simple route to forward requests from `backend-a-podinfo` to `backend-b-pod-info`
```
cat <<EOF | kubectl -n test apply -f -
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: backend-router
  namespace: test
spec:
  parentRefs:
    - name: backend-a-podinfo
      kind: Service
      group: core
      port: 9898
  rules:
    - backendRefs:
      - name: "backend-b-podinfo"
        namespace: test
        port: 9898
EOF
```

```
❯ curl -sX POST localhost:9898/echo \
  | grep -o 'PODINFO_UI_MESSAGE=. backend'
PODINFO_UI_MESSAGE=B backend
```

### output of `linkerd check -o short`

❯ linkerd check -o short
Status check results are √

### Environment

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}
```

Cluster: minikube

Host: macOS

Linkerd:
```
Client version: stable-2.13.3
Server version: stable-2.13.3
```

### Would you like to work on fixing this bug?

None
