### ISSUE TITLE
Request routing doesn't work if HTTPRoute is in different namespace than parentRef service

### ISSUE THREAD

**Issue by andrewwdye** [linkerd/linkerd2#10956]
### What is the issue?

The documentation for `parentReference.namespace` implies that the HTTPRoute resource namespace and parentRef namespace can be different
> The namespace of the referent. When unspecified (or empty string), this refers to the local namespace of the Route.

However, in this configuration the request is not proxied

Note: I'm using `edge-23.5.3` with the latest HTTPRoute cross-namespace fixes

### How can it be reproduced?

This is a modified version of the [dynamic request routing sample](https://linkerd.io/2.13/tasks/configuring-dynamic-request-routing/)
```
kubectl create ns test --dry-run -o yaml \
  | linkerd inject - \
  | kubectl apply -f -
```

Install backends (including `backend-c` in the namespace `test2`) and frontend
```
helm install backend-a -n test \
  --set ui.message='A backend' podinfo/podinfo
helm install backend-c -n test2 --create-namespace \
  --set ui.message='C backend' podinfo/podinfo
helm install frontend -n test \
  --set backend=http://backend-c-podinfo.test2.svc.cluster.local:9898/env podinfo/podinfo
```

Create a simple route to forward requests from backend-c-podinfo to backend-a-pod-info
```
cat <<EOF | kubectl -n test apply -f -
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: backend-router
  namespace: test
spec:
  parentRefs:
    - name: backend-c-podinfo
      namespace: test2
      kind: Service
      group: core
      port: 9898
  rules:
    - backendRefs:
      - name: "backend-a-podinfo"
        namespace: test
        port: 9898
EOF
```

Port forward
```
kubectl -n test port-forward svc/frontend-podinfo 9898
```

Hit `backend-c-podinfo` and expect forward to `backend-a-podinfo`
```
curl -sX POST localhost:9898/echo \
  | grep -o 'PODINFO_UI_MESSAGE=. backend'
PODINFO_UI_MESSAGE=C backend
```

### Logs, error output, etc

❌  Hit `backend-c-podinfo` and expect forward to `backend-a-podinfo`
```
curl -sX POST localhost:9898/echo \
  | grep -o 'PODINFO_UI_MESSAGE=. backend'
PODINFO_UI_MESSAGE=C backend
```

Verify that installing route in the `test2` namespace works as expected
```
cat <<EOF | kubectl -n test apply -f -
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: backend-router
  namespace: test2
spec:
  parentRefs:
    - name: backend-c-podinfo
      namespace: test2
      kind: Service
      group: core
      port: 9898
  rules:
    - backendRefs:
      - name: "backend-a-podinfo"
        namespace: test
        port: 9898
EOF
```

✅  Hit `backend-c-podinfo` and expect forward to `backend-a-podinfo`
```
curl -sX POST localhost:9898/echo \
  | grep -o 'PODINFO_UI_MESSAGE=. backend'
PODINFO_UI_MESSAGE=A backend
```

### output of `linkerd check -o short`

```
❯ linkerd check -o short
Status check results are √
```

### Environment

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}
```

Cluster: minikube

Host: macOS

Linkerd
```
Client version: edge-23.5.3
Server version: edge-23.5.3
```

### Would you like to work on fixing this bug?

None
