### ISSUE TITLE
CRD schema doesn't match documentation for requestRedirect.path

### ISSUE THREAD

**Issue by andrewwdye** [linkerd/linkerd2#10954]
### What is the issue?

Attempting to use [httpRequestRedirectFilter.path](https://linkerd.io/2.13/reference/httproute/#httprequestredirectfilter) fails with
```
HTTPRoute in version "v1beta2" cannot be handled as a HTTPRoute: strict decoding error: 
unknown field "spec.rules[0].filters[0].requestRedirect.path.replacePrefixMatch", 
unknown field "spec.rules[0].filters[0].requestRedirect.path.type"
```

While [documentation](https://linkerd.io/2.13/reference/httproute/#httppathmodfier) notes that `requestRedirect.path` should be a `httpPathModifier`
> An [httpPathModfier](https://linkerd.io/2.13/reference/httproute/#httppathmodfier) which modifies the path of the incoming request and uses the modified path in the Location header.

the CRD schema [defines this as a string](https://github.com/linkerd/linkerd2/blob/release/2.13/charts/linkerd-crds/templates/policy/httproute.yaml#L346-L351).
> description: "Path defines parameters used to modify the path of the incoming request. The modified path is then used to construct the Location header. When empty, the request path is used as-is.
Support: Extended"
type: string

My attempt to treat `requestRedirect.path` as a string fail with
```
admission webhook "linkerd-policy-validator.linkerd.io" denied the request: invalid type: string "/echo", expected internally tagged enum HttpPathModifier
```

### How can it be reproduced?

Follow the [dynamic request routing example](https://linkerd.io/2.13/tasks/configuring-dynamic-request-routing/) and apply the following route
```
cat <<EOF | kubectl -n test apply -f -
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: backend-router
  namespace: test
spec:
  parentRefs:
    - name: backend-a-podinfo
      kind: Service
      group: core
      port: 9898
  rules:
    - backendRefs:
      - name: backend-a-podinfo
        port: 9898
      filters:
      - type: RequestRedirect
        requestRedirect:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: ""
      matches:
      - path:
          value: /foo
EOF
```

### Logs, error output, etc

```
HTTPRoute in version "v1beta2" cannot be handled as a HTTPRoute: strict decoding error: 
unknown field "spec.rules[0].filters[0].requestRedirect.path.replacePrefixMatch", 
unknown field "spec.rules[0].filters[0].requestRedirect.path.type"
```

### output of `linkerd check -o short`

```
❯ linkerd check -o short
Status check results are √
```

### Environment

Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.3", GitCommit:"9e644106593f3f4aa98f8a84b23db5fa378900bd", GitTreeState:"clean", BuildDate:"2023-03-15T13:33:12Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/arm64"}
```

Host
```
macOS
```

Linkerd
```
Client version: stable-2.13.3
Server version: stable-2.13.3
```

### Possible solution

Update CRD?

### Would you like to work on fixing this bug?

None
