### ISSUE TITLE
Prometheus metrics federation yields HTTP 403

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#11050]
### Discussed in https://github.com/linkerd/linkerd2/discussions/11044

<div type='discussions-op-text'>

<sup>Originally posted by **ngc4579** June 21, 2023</sup>
Using the Prometheus federation API as advertised in the [docs](https://linkerd.io/2.13/tasks/exporting-metrics/#federation) yields an HTTP 403 scrape error (`server returned HTTP status 403 Forbidden`). IIRC this used to work some time ago. Were there any (recent) changes that are possibly not reflected in the docs?

What might cause the described behaviour?</div>

**Comment by adleong** [comment]
Thanks for raising this, @ngc4579. It's possible that additional AuthorizationPolicies are needed for Prometheus federation.  This will require some investigation.

**Comment by wmorgan** [comment]
This policy was suggested by [Michelle B on the Linkerd Slack](https://linkerd.slack.com/archives/C89RTCWJF/p1687374011989189) (link will expire in 90 days):
```
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: prometheus-admin-federate
  namespace: linkerd-viz
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: prometheus-admin
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: NetworkAuthentication
      name: kubelet
```
