### ISSUE TITLE
Installing linkerD with helm chart on new cluster startup issues

### ISSUE THREAD

**Issue by rufreakde** [linkerd/linkerd2#11160]
### What is the issue?

identity pod is not starting up
And because of this no pod is starting up. Interestingly we have a very very similar setup (except for credentials exactly similar) on 5 other clusters but only this one cluster is not working. (All AWS)

### How can it be reproduced?

Install the following configuration (declarative argoCD installation in our case):
Order  Trust Anchors > CNI > CRD > Control Plane (those certificates are already obsolete I kept theme in here for biggest transparancy)

# linkerd control plane
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.teams: ms-cluster-scoped
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  project: default
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.9.6
    helm:
      releaseName: linkerd-control-plane
      values: |
        # -- Create PodDisruptionBudget resources for each control plane workload
        enablePodDisruptionBudget: true

        # -- Specify a deployment strategy for each control plane workload
        deploymentStrategy:
          rollingUpdate:
            maxUnavailable: 1
            maxSurge: 25%

        # -- add PodAntiAffinity to each control plane workload (only for production with at least 4 nodes)
        enablePodAntiAffinity: false

        # nodeAffinity:

        # proxy configuration
        proxy:
          resources:
            cpu:
              request: 50m
            memory:
              limit: 250Mi
              request: 20Mi

        # controller configuration
        controllerReplicas: 2
        controllerResources:
          cpu:
            limit: ""
            request: 50m
          memory:
            limit: 250Mi
            request: 50Mi
        destinationResources:
          cpu:
            limit: ""
            request: 50m
          memory:
            limit: 250Mi
            request: 50Mi

        # identity configuration
        identityResources:
          cpu:
            limit: ""
            request: 50m
          memory:
            limit: 250Mi
            request: 10Mi

        # heartbeat configuration
        heartbeatResources:
          cpu:
            limit: ""
            request: 50m
          memory:
            limit: 250Mi
            request: 10Mi

        # proxy injector configuration
        proxyInjectorResources:
          cpu:
            limit: ""
            request: 50m
          memory:
            limit: 250Mi
            request: 10Mi

        webhookFailurePolicy: Ignore

        # service profile validator configuration
        spValidatorResources:
          cpu:
            limit: ""
            request: 50m
          memory:
            limit: 250Mi
            request: 10Mi

        # Public certificate
        identityTrustAnchorsPEM: |
          -----BEGIN CERTIFICATE-----
          XXX
          -----END CERTIFICATE-----

        # TLS identity
        identity:
          issuer:
            scheme: kubernetes.io/tls

        # Allow proxy startup plugin instead of init container (needed for SecurityPodAdmission)
        cniEnabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSync=true
```

# crds
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.teams: ms-cluster-scoped
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: linkerd-crds
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.4.0
    helm:
      releaseName: linkerd-crds
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - Replace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/names/shortNames
```

# linkerd-cni
```
---
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd-cni
  labels:
    linkerd.io/cni-resource: "true"
    config.linkerd.io/admission-webhooks: disabled
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkerd-cni
  namespace: linkerd-cni
  labels:
    linkerd.io/cni-resource: "true"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-cni
  labels:
    linkerd.io/cni-resource: "true"
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "services"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-cni
  labels:
    linkerd.io/cni-resource: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-cni
subjects:
  - kind: ServiceAccount
    name: linkerd-cni
    namespace: linkerd-cni
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: linkerd-cni-config
  namespace: linkerd-cni
  labels:
    linkerd.io/cni-resource: "true"
data:
  dest_cni_net_dir: "/etc/cni/net.d"
  dest_cni_bin_dir: "/opt/cni/bin"
  # The CNI network configuration to install on each node. The special
  # values in this config will be automatically populated.
  cni_network_config: |-
    {
      "name": "linkerd-cni",
      "type": "linkerd-cni",
      "log_level": "info",
      "policy": {
          "type": "k8s",
          "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
          "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
      },
      "kubernetes": {
          "kubeconfig": "__KUBECONFIG_FILEPATH__"
      },
      "linkerd": {
        "incoming-proxy-port": 4143,
        "outgoing-proxy-port": 4140,
        "proxy-uid": 2102,
        "ports-to-redirect": [],
        "inbound-ports-to-ignore": ["4191","4190"],
        "simulate": false,
        "use-wait-flag": false
      }
    }
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: linkerd-cni
  namespace: linkerd-cni
  labels:
    k8s-app: linkerd-cni
    linkerd.io/cni-resource: "true"
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.13.5
    kube-score/ignore: container-security-context-user-group-id,container-resources,container-image-pull-policy,container-ephemeral-storage-request-and-limit,pod-networkpolicy
spec:
  selector:
    matchLabels:
      k8s-app: linkerd-cni
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: linkerd-cni
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.13.5
        linkerd.io/cni-resource: "true"
        linkerd.io/inject: disabled
    spec:
      tolerations:
        - operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      hostNetwork: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: linkerd-cni
      containers:
        # This container installs the linkerd CNI binaries
        # and CNI network config file on each node. The install
        # script copies the files into place and then sleeps so
        # that Kubernetes doesn't keep trying to restart it.
        - name: install-cni
          image: cr.l5d.io/linkerd/cni-plugin:v1.1.1
          env:
            - name: DEST_CNI_NET_DIR
              valueFrom:
                configMapKeyRef:
                  name: linkerd-cni-config
                  key: dest_cni_net_dir
            - name: DEST_CNI_BIN_DIR
              valueFrom:
                configMapKeyRef:
                  name: linkerd-cni-config
                  key: dest_cni_bin_dir
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: linkerd-cni-config
                  key: cni_network_config
            - name: SLEEP
              value: "true"
          lifecycle:
            # In some edge-cases this helps ensure that cleanup() is called in the container's script
            # https://github.com/linkerd/linkerd2/issues/2355
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - kill -15 1; sleep 15s
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /tmp
              name: linkerd-tmp-dir
          securityContext:
            readOnlyRootFilesystem: true
            privileged: false
      volumes:
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        - name: linkerd-tmp-dir
          emptyDir: {}
---
```

# certificate with cert manager
```
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJqakNDQVRPZ0F3SUJBZ0lRSUxqbEVjNk5NZ0YySUI5UHBoczhzakFLQmdncWhrak9QUVFEQWpBbE1TTXcKSVFZRFZRUURFeHB5YjI5MExteHBibXRsY21RdVkyeDFjM1JsY2k1c2IyTmhiREFlRncweU16QXpNVFF3TnpBMQpOREJhRncwek16QXpNVEV3TnpBMU5EQmFNQ1V4SXpBaEJnTlZCQU1UR25KdmIzUXViR2x1YTJWeVpDNWpiSFZ6CmRHVnlMbXh2WTJGc01Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRXV6STU0eVh3c0NobThONkQKZHB5cWtTQm8zTG1HUXJiV0ZUZHlxRzE2Qm90ZU02N1Bxa2hxb2ZIZ0VoNU1NMkxoa1llYk1jR2N6OHpIR3BqRwpKZzVHdmFORk1FTXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01CSUdBMVVkRXdFQi93UUlNQVlCQWY4Q0FRRXdIUVlEClZSME9CQllFRk9laTV1RDdVcTlGSU5tR2wySlRMVVNLLzVubE1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRREoKOUtMYjZ2VU5JN2xINjk5VEVVUWh0THhCWEVjYTU2bWN1QXFKRXVvQzl3SWhBTEtYWUx4bU1VbkxXRTBaUGo4MwprRzdmSDlFbHUvQWVhanhnZlZjbElvZGMKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUdWTnFsOVpOakFIQmYvajJlQ0lQeXNMVC9WZzExYXQyRlVqdmc4K2h6VS9vQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFdXpJNTR5WHdzQ2htOE42RGRweXFrU0JvM0xtR1FyYldGVGR5cUcxNkJvdGVNNjdQcWtocQpvZkhnRWg1TU0yTGhrWWViTWNHY3o4ekhHcGpHSmc1R3ZRPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-trust-anchor
  namespace: linkerd
type: kubernetes.io/tls
---
#  certificate manager configuration guide https://linkerd.io/2.13/tasks/automatically-rotating-control-plane-tls-credentials/#a-note-on-third-party-cert-management-solutions
#  step certificate create root.linkerd.cluster.local ca.crt ca.key --profile root-ca --no-password --insecure --not-after=87600h
#  step certificate create root.linkerd.cluster.local issuer.crt issuer.key --profile intermediate-ca --not-after 8760h --no-password --insecure --ca ca.crt --ca-key ca.key
#
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
  annotations:
    notifications.argoproj.io/subscribe.teams: ms-cluster-scoped
    argocd.argoproj.io/sync-wave: "0"
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  annotations:
    notifications.argoproj.io/subscribe.teams: ms-cluster-scoped
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: linkerd-identity-issuer
  duration: 730h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  dnsNames:
    - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
---
```

### Logs, error output, etc

# identity service
```
time="2023-07-24T14:13:56Z" level=info msg="running version stable-2.12.4"
8
time="2023-07-24T14:13:56Z" level=info msg="starting admin server on :9990"
7
time="2023-07-24T14:13:56Z" level=info msg="starting gRPC server on :8080"
6
time="2023-07-24T14:14:04Z" level=info msg="issued certificate for linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local until 2023-07-25 14:14:24 +0000 UTC: e939fa9f00ad5cdcc06bd1a0a673bb57b06e2b13a2267d3deaa337791cdc4bac"
5
time="2023-07-24T14:14:14Z" level=info msg="issued certificate for linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local until 2023-07-25 14:14:34 +0000 UTC: 01ab42f4cac679bb7685126e817f04194199ec42fae625edfcf4efb662bac92c"
4
time="2023-07-24T14:14:24Z" level=info msg="issued certificate for linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local until 2023-07-25 14:14:44 +0000 UTC: 20d9e897924405544d3c50337fa265c5dde9146e649c1f6bfe6eef74b3c67d93"
3
time="2023-07-24T14:14:34Z" level=info msg="issued certificate for linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local until 2023-07-25 14:14:54 +0000 UTC: 9265dc38b576ff62df18e535f2fbff58e0d112b32d6fd8495a97173ff4de0ff4"
2
time="2023-07-24T14:14:35Z" level=info msg="shutting down gRPC server on :8080"
1
time="2023-07-24T14:14:35Z" level=error msg="failed to start identity admin server: http: Server closed"
```

### output of `linkerd check -o short`

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
DEBU[0000] Retrying on error: pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready
/ pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready DEBU[0005] Retrying on error: pod/linkerd-destination-79965dfb47-8h7vz container sp-validator is not ready
...
SHORTENED
...
destination-79965dfb47-8h7vz container sp-validator is not ready
/ pod/linkerd-destination-79965dfb47-8h7vz container sp-validator is not ready DEBU[0288] Retrying on error: pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready
- pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready DEBU[0293] Retrying on error: pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready
| pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready DEBU[0299] Retrying on error: pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready
× control plane pods are ready
    pod/linkerd-destination-79965dfb47-d9zbq container sp-validator is not ready
    see https://linkerd.io/2.13/checks/#l5d-api-control-ready for hints
```

### Environment

Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.24.14
AWS
Gardenlinux

### Possible solution

Could not find anything I tried all kinds of changes with the certificate without any luck. Previously we used istio so I also checked if there might be any issues but no problems to be seen other deployments work totally fine.

### Additional context

I am at my wits and with the troubleshooting could not find anything what goes wrong (after hours and hours of investigation work).

Also upgrading linkerd version is not an option right now as this is our production cluster and we would need to do all of this testing etc on dev and staging again just to be able to test if it solved the problem in production. (all setups the same and working fine)

### Would you like to work on fixing this bug?

None
