### ISSUE TITLE
incomplete interaction scheme

### ISSUE THREAD

**Issue by Nello-Angelo** [linkerd/linkerd2#11238]
### What is the issue?

incomplete interaction scheme because of some components are daemonset or statefulset but on closer examination, this interaction can be seen

![Screenshot_14](https://github.com/linkerd/linkerd2/assets/82488489/56c48cee-ca28-4d38-9384-ad1f94a91769)

![Screenshot_13](https://github.com/linkerd/linkerd2/assets/82488489/40a0452d-41a4-487f-8b48-b21deff11da2)

### How can it be reproduced?

with any stack whose components will work as statefulset , daemonset and deployment

### Logs, error output, etc

-

### output of `linkerd check -o short`

-

### Environment

linkerd latest
kubernetes 1.25.8
OS debian 11

### Possible solution

-

### Additional context

-

### Would you like to work on fixing this bug?

maybe

**Comment by Nello-Angelo** [comment]
i can see complete interaction scheme only if components works are deployment

**Comment by Nello-Angelo** [comment]
i also cant understand why i see so incorrect visualization 

![Screenshot_21](https://github.com/linkerd/linkerd2/assets/82488489/23d62124-61b7-4054-b8b4-1621bafce416)
![Screenshot_17](https://github.com/linkerd/linkerd2/assets/82488489/112f00a7-8a59-48a3-a808-e14995934c97)
![Screenshot_19](https://github.com/linkerd/linkerd2/assets/82488489/1f9d3461-7b56-4cd5-8914-0694151f5ade)
![Screenshot_20](https://github.com/linkerd/linkerd2/assets/82488489/ef70a316-d379-47bf-982e-9b4e302dc794)

i go to the web and web shows me that voting has errors but when i go to the voting, voting shows me that web has errors

```
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: authors-policy
  namespace: emojivoto
spec:
  requiredAuthenticationRefs:
    - group: policy.linkerd.io
      kind: MeshTLSAuthentication
      name: authors-get-authn
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: emoji-grpc
```

```
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: authors-get-authn
  namespace: emojivoto
spec:
  identities:
    - '*'
```

```
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: emoji-grpc
  namespace: emojivoto
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - emoji-svc
          - web-svc
          - voting-svc
  port: 8080
  proxyProtocol: TLS
```
