### ISSUE TITLE
add connection support to an existing victoriametrics single and cluster installation

### ISSUE THREAD

**Issue by Nello-Angelo** [linkerd/linkerd2#11230]
### What problem are you trying to solve?

Victoria and Prometheus are like Linkerd and Istio. I want to interact with her

### How should the problem be solved?

add instructions on how to connect to victoria

### Any alternatives you've considered?

nothing

### How would users interact with this feature?

helm or additional keys in cli to choose connection 

### Would you like to work on this feature?

maybe

**Comment by Nello-Angelo** [comment]
```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: linkerd-proxy
  namespace: victoria-vm
spec:
  namespaceSelector:
    any: true
  podMetricsEndpoints:
    - relabelConfigs:
        - action: keep
          regex: ^linkerd-proxy;linkerd-admin;linkerd$
          sourceLabels:
            - __meta_kubernetes_pod_container_name
            - __meta_kubernetes_pod_container_port_name
            - __meta_kubernetes_pod_label_linkerd_io_control_plane_ns
        - action: replace
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: namespace
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_label_linkerd_io_proxy_job
          targetLabel: k8s_job
        - action: labeldrop
          regex: __meta_kubernetes_pod_label_linkerd_io_proxy_job
        - action: labelmap
          regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
        - action: labeldrop
          regex: __meta_kubernetes_pod_label_linkerd_io_proxy_(.+)
        - action: labelmap
          regex: __meta_kubernetes_pod_label_linkerd_io_(.+)
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
          replacement: __tmp_pod_label_$1
        - action: labelmap
          regex: __tmp_pod_label_linkerd_io_(.+)
          replacement: __tmp_pod_label_$1
        - action: labeldrop
          regex: __tmp_pod_label_linkerd_io_(.+)
        - action: labelmap
          regex: __tmp_pod_label_(.+)
```

```
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: linkerd-controller
  namespace: victoria-vm
spec:
  namespaceSelector:
    matchNames:
      - linkerd
      - linkerd-viz
  podMetricsEndpoints:
    - relabelConfigs:
        - action: keep
          regex: admin-http
          sourceLabels:
            - __meta_kubernetes_pod_container_port_name
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_container_name
          targetLabel: component
```
