### ISSUE TITLE
can`t inject node-exporter 

### ISSUE THREAD

**Issue by Nello-Angelo** [linkerd/linkerd2#11245]
### What is the issue?

can`t inject node-exporter 

### How can it be reproduced?

install node-exporter from chart

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vm-prometheus-node-exporter
  namespace: victoria-vm
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: vm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/version: 1.4.0
    helm.sh/chart: prometheus-node-exporter-4.7.1
    jobLabel: node-exporter
    k8slens-edit-resource-version: v1
  annotations:
    deprecated.daemonset.template.generation: '6'
    meta.helm.sh/release-name: vm
    meta.helm.sh/release-namespace: victoria-vm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: vm
      app.kubernetes.io/name: prometheus-node-exporter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: metrics
        app.kubernetes.io/instance: vm
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prometheus-node-exporter
        app.kubernetes.io/part-of: prometheus-node-exporter
        app.kubernetes.io/version: 1.4.0
        helm.sh/chart: prometheus-node-exporter-4.7.1
        jobLabel: node-exporter
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
        kubectl.kubernetes.io/restartedAt: '2023-08-11T23:00:14Z'
        linkerd.io/inject: enabled
    spec:
      volumes:
        - name: proc
          hostPath:
            path: /proc
            type: ''
        - name: sys
          hostPath:
            path: /sys
            type: ''
        - name: root
          hostPath:
            path: /
            type: ''
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:v1.4.0
          args:
            - '--path.procfs=/host/proc'
            - '--path.sysfs=/host/sys'
            - '--path.rootfs=/host/root'
            - '--web.listen-address=[$(HOST_IP)]:9100'
            - >-
              --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
            - >-
              --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
          ports:
            - name: metrics
              hostPort: 9100
              containerPort: 9100
              protocol: TCP
          env:
            - name: HOST_IP
              value: 0.0.0.0
          resources: {}
          volumeMounts:
            - name: proc
              readOnly: true
              mountPath: /host/proc
            - name: sys
              readOnly: true
              mountPath: /host/sys
            - name: root
              readOnly: true
              mountPath: /host/root
              mountPropagation: HostToContainer
          livenessProbe:
            httpGet:
              path: /
              port: 9100
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9100
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: vm-prometheus-node-exporter
      serviceAccount: vm-prometheus-node-exporter
      automountServiceAccountToken: false
      hostNetwork: true
      hostPID: true
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        fsGroup: 65534
      schedulerName: default-scheduler
      tolerations:
        - operator: Exists
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10
```

### Logs, error output, etc

-

### output of `linkerd check -o short`

-

### Environment

kubernetes - 1.25.8
OS - debian 11 
linkerd - stable-2.13.5

### Possible solution

-

### Additional context

-

### Would you like to work on fixing this bug?

no
