### ISSUE TITLE
Allow helm chart users to add extra relabelings and metricRelabelings for podmonitor

### ISSUE THREAD

**Issue by vanny96** [linkerd/linkerd2#11445]
### What problem are you trying to solve?

As it currently stands, users are only allowed to enable or disable pod metrics for `linkerd-controller`, `linkerd-service-mirror` and `linkerd-proxy`, without giving them the chance to customize which metrics would be scraped or injested.

### How should the problem be solved?

Add `relabelings` and `metricRelabelings` fields for all possible podmonitors, these fields would then be used to customize the helm template.

### Any alternatives you've considered?

Other solutions would be to configure prometheus directly, which kinda defeats the point of the podmonitor

### How would users interact with this feature?

```yaml
podMonitor:
  enabled: true
  controller: 
    relabelings:
       - example1
       - example2
    metricsRelabelings:
       - example3
  proxy:
    relabelings:
       - example4
```

### Would you like to work on this feature?

yes
