### ISSUE TITLE
linkerd-identity-issuer tls reference to existing secrets

### ISSUE THREAD

**Issue by YoucefGuichi** [linkerd/linkerd2#11500]
### What is the issue?

Since k8s encode key secrets by default at rest. I think no need to base64 encode at the helm chart level, because we are facing an issue with the certificates being double encoded.
```
{{ if and (.Values.identity.issuer) (eq .Values.identity.issuer.scheme "linkerd.io/tls") -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-identity-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    linkerd.io/control-plane-component: identity
    linkerd.io/control-plane-ns: {{.Release.Namespace}}
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  annotations:
    {{ include "partials.annotations.created-by" . }}
data:
  crt.pem: {{b64enc (required "Please provide the identity issuer certificate" .Values.identity.issuer.tls.crtPEM | trim)}}
  key.pem: {{b64enc (required "Please provide the identity issue private key" .Values.identity.issuer.tls.keyPEM | trim)}}
```

### How can it be reproduced?

/

### Logs, error output, etc

/

### output of `linkerd check -o short`

/

### Environment

/

### Possible solution

Since k8s first check wether you provided encoded secrets or not and then act accordingly as follow:

- if the keys are base64 it doesn't encode them again  
- if provided on plain text it do encode them.

So we base64 encode our secrets to preserve multilines and then apply them, but it get's double encoded because it gets also encoded at helm chart level as well, resulting in wrong values.

The proposed solution is to remove the base64 encoding from the chart since k8s is taking care of it.

### Would you like to work on fixing this bug?

yes

**Comment by kflynn** [comment]
@YoucefGuichi, great to hear that you're interested in working on this one! 

Can you show what, exactly, you're doing with base64 in your use case? I've rarely seen people messing with base64'ing PEM files, so I'd like to understand more about what you're doing exactly.

**Comment by YoucefGuichi** [comment]
Yes sure! 

So basically we use gitops with flux and for secrets we use sealed secrets.

let's say we have a sealed secret that have some common encrypted keys:
```
#sealed_secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: common-secrets
  namespace: flux-system
spec:
  encryptedData:
     tls_certificate: Alskjdvhs+-9340wkwiegherbjh-=24hgerhebndbebnryn #encrypted
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: common-secrets
      namespace: flux-system
```
the following secret will be generated from the sealedsecret above:
```
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
data:
  tls_certificate: dmFsdWUtMg0KDQo= #dycrypted
```
then flux will substitue `tls_certificate`on the helm release, and will paste the actuall value not the encoded one, at this phase flux doesn't respect newlines and will remove it.

```
# helm release 
identity:
  issuer:
    tls:
      crtPEM: ${tls_certificate}
```

Causing the certificate to be like this:
```
-----BEGIN CERTIFICATE----lwkjgherkgjhekrghkjrgewwoghweroigerwqpiejwiorjglwkjgherkgjhekrghkjrgewwoghweroigerwqpiejwiorjglwkjgherkgjhekrghkjrgewwoghweroigerwqpiejwiorjg-----END CERTIFICATE-----
```
### the proposed solution:

we were thinking to use the following:

```
tls:
      existingSecret: my-secret
```

by doing so we can create a proper sealed secret for my-secret

**Comment by kflynn** [comment]
@YoucefGuichi My apologies for taking so long to get back to you! 🙁 

I think that the simplest way to deal with this is actually something you can do entirely in your Flux setup. You don't actually need to have Helm write the secrets when you install Linkerd: if the secrets are already present in the namespace, you can simply tell Helm to use the existing secrets in-place. The way to do that is:

1. Set up the `linkerd-identity-issuer` Secret and the `linkerd-identity-trust-roots` ConfigMap in the `linkerd` namespace.
2. In your Helm release, set

```yaml
identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
```

Let me know how that goes!
