### ISSUE TITLE
Probes respond with 403 if using URL redirect

### ISSUE THREAD

**Issue by channyein87** [linkerd/linkerd2#11590]
### What is the issue?

When URL redirects is used for HTTP probe, Linkerd's responds with HTTP 403.

### How can it be reproduced?

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: channyein87/sample-django:v3
          ports:
            - containerPort: 8000
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: django-service
spec:
  podSelector:
    matchLabels:
      app: django
  port: 8000
  proxyProtocol: unknown
```

### Logs, error output, etc

```text
[   684.792058s]  INFO ThreadId(01) inbound:server{port=8000}:rescue{client.addr=10.52.106.81:63872}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=client 10.52.106.81:63872: server: 10.52.106.151:8000: unauthori
zed request on route error.sources=[unauthorized request on route]
```

### output of `linkerd check -o short`

```text                        
linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-11-09T07:39:42Z
    see https://linkerd.io/2.13/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.13.5 but the latest stable version is 2.14.3
    see https://linkerd.io/2.13/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.13.5 but the latest stable version is 2.14.3
    see https://linkerd.io/2.13/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-5666986d5d-7zz7h (stable-2.13.5)
        * linkerd-destination-5666986d5d-kgqkk (stable-2.13.5)
        * linkerd-destination-5666986d5d-klcn2 (stable-2.13.5)
        * linkerd-destination-5666986d5d-ntd6t (stable-2.13.5)
        * linkerd-destination-5666986d5d-wn5wv (stable-2.13.5)
        * linkerd-identity-856dd87fd7-2928w (stable-2.13.5)
        * linkerd-identity-856dd87fd7-87pg7 (stable-2.13.5)
        * linkerd-identity-856dd87fd7-8sls5 (stable-2.13.5)
        * linkerd-identity-856dd87fd7-bnlk8 (stable-2.13.5)
        * linkerd-identity-856dd87fd7-ssjpm (stable-2.13.5)
        * linkerd-proxy-injector-85dfbdb96f-5tb29 (stable-2.13.5)
        * linkerd-proxy-injector-85dfbdb96f-7hbmz (stable-2.13.5)
        * linkerd-proxy-injector-85dfbdb96f-92jfg (stable-2.13.5)
        * linkerd-proxy-injector-85dfbdb96f-h98vm (stable-2.13.5)
        * linkerd-proxy-injector-85dfbdb96f-mhfvt (stable-2.13.5)
    see https://linkerd.io/2.13/checks/#l5d-cp-proxy-version for hints

linkerd-viz
-----------
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
        * metrics-api-844657c8f8-pnclw (stable-2.13.5)
        * prometheus-5f4d74b4bf-45pzb (stable-2.13.5)
        * tap-6bff7d5486-nfvzv (stable-2.13.5)
        * tap-6bff7d5486-tfjvd (stable-2.13.5)
        * tap-6bff7d5486-vhlg7 (stable-2.13.5)
        * tap-injector-75c5f45475-7cz6w (stable-2.13.5)
        * web-58c878cb94-wxbjl (stable-2.13.5)
        * web-58c878cb94-xsmt7 (stable-2.13.5)
    see https://linkerd.io/2.13/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

Kubernetes version: `1.25`
Environment: `eks`
Linkerd version: `stable-2.13.5`

### Would you like to work on fixing this bug?

None

**Comment by channyein87** [comment]
We do use it with [ServerAuthorization](https://linkerd.io/2.14/reference/authorization-policy/#serverauthorization) like below.

```yaml
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: django-service
spec:
  server:
    name: django-service
  client:
    meshTLS:
      identities:
        - "foo.shared.serviceaccount.identity.linkerd.cluster.local"
```

**Comment by alpeb** [comment]
Is the `foo` service account associated to the deployment you posted above? Please try providing a complete manifest so we can try reproducing the issue.

**Comment by channyein87** [comment]
yeah, it is just an arbitory value of identity from source service. you should be able to reproduce the error with the below manifest. the pod has a health check probe in path `/health` which redirects to `/health/`. as per my research, [`HTTP probes` follows the redirect](https://stackoverflow.com/questions/65885654/do-kubernetes-http-probes-follow-redirects).

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: default
spec:
  selector:
    app: django
  ports:
    - name: http
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: channyein87/sample-django:v3
          ports:
            - containerPort: 8000
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: django-service
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: django
  port: 8000
  proxyProtocol: unknown
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  name: django-service
  namespace: default
spec:
  server:
    name: django-service
  client:
    meshTLS:
      identities:
        - "*.default.serviceaccount.identity.linkerd.cluster.local"
```

**Comment by alpeb** [comment]
The problem here is that, as per your ServerAuthorization, only connections coming from a meshed source are allowed. Probes come from the kubelet, which is not meshed, so those connections get denied.

**Comment by channyein87** [comment]
Linkerd allows probe in above setup based on the [documentation](https://linkerd.io/2.14/features/server-policy/#default-authorizations).

> In order to simplify default-deny setups, Linkerd automatically authorizes probes to pods.

**Comment by kflynn** [comment]
@channyein87 There's more information in that paragraph in the docs:

> In order to simplify default-deny setups, Linkerd automatically authorizes probes to pods. These default authorizations apply only when no [Server](https://linkerd.io/2.14/reference/authorization-policy/#server) is configured for a port, or when a [Server](https://linkerd.io/2.14/reference/authorization-policy/#server) is configured but no [HTTPRoute](https://linkerd.io/2.14/features/httproute/)s are configured for that [Server](https://linkerd.io/2.14/reference/authorization-policy/#server). If any [HTTPRoute](https://linkerd.io/2.14/features/httproute/) matches the Server, these automatic authorizations are not created and you must explicitly create them for health and readiness probes.

So _as soon as you create the Server_, the default access for probes goes away. This is necessary to control who has access to the probe ports. I suspect that if you add authorization for unmeshed traffic, you'll be fine.

**Comment by kflynn** [comment]
Closing this one – feel free to reopen if needed!

**Comment by channyein87** [comment]
Not sure what is the correct way of creating "authorization for unmeshed traffic".
But I tried adding the below policies `HTTPRoute`, `NetworkAuthentication`,  `AuthorizationPolicy` and it is working. 👍🏻

```yaml
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: django-healthcheck-route
spec:
  parentRefs:
    - name: django-service
      kind: Server
      group: policy.linkerd.io
  rules:
    - matches:
      - path:
          value: "/health"
          type: "PathPrefix"
        method: GET
---
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: cluster-network
spec:
  networks:
  - cidr: 10.0.0.0/8
  - cidr: 100.64.0.0/10
  - cidr: 172.16.0.0/12
  - cidr: 192.168.0.0/16
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: django-healthcheck-policy
spec:
  targetRef:
    group: policy.linkerd.io
    kind: HTTPRoute
    name: django-healthcheck-route
  requiredAuthenticationRefs:
    - name: cluster-network
      kind: NetworkAuthentication
      group: policy.linkerd.io
```
