### ISSUE TITLE
linkerd-viz deletion leads to hanging state 

### ISSUE THREAD

**Issue by wibed** [linkerd/linkerd2#11681]
### What is the issue?

the apiservice v1alpha1.tap.linkerd.io 
leads to meshed services stuck in terminating state.

```
v1alpha1.tap.linkerd.io                linkerd/tap   False (ServiceNotFound)   12m
```

deleting the apiservvice manually, leads to the resolution of the freeze

### How can it be reproduced?

tried it with edge aswell... same outcome

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../base/linkerdviz

helmCharts:
- name: linkerd-viz
  releaseName: cluster0
  namespace: linkerd
  includeCRDs: true
  valuesInline:
  repo: https://helm.linkerd.io/stable
```

### Logs, error output, etc

-

### output of `linkerd check -o short`

-

### Environment

talos cluster

### Would you like to work on fixing this bug?

maybe

**Comment by kflynn** [comment]
@wibed When I try the obvious thing here, everything seems to work fine (using Linkerd 2.14.6). Can you tell me more about what, exactly, you're doing here?

**Comment by kflynn** [comment]
(To be more clear: the "obvious thing" is

- Install Linkerd
- `helm install linkerd-viz -n linkerd-viz --create-namespace linkerd/linkerd-viz`
- Install a meshed application
- Verify that `linkerd viz tap` works for my meshed workloads
- `helm uninstall linkerd-viz -n linkerd-viz`

and at that point I see no hanging resources.)

**Comment by kflynn** [comment]
@wibed Happy new year! We're still looking more a little more info here, if you can provide any... 🙂

**Comment by wibed** [comment]
certainly! i am relying on hierarchical namespaces to manage environments within a cluster:
- development
- production
- etc.

deleting a hns including the linkerd and the linkerd-viz deployments and whatnot leads to the terminating state afore mentioned earlier. the only resolve is to delete the apiservice `v1alpha1.tap.linkerd.io` to resolve the terminating state.

i am not sure it is because of the order of the services in which they are deleted or other reasons is the culprit of this behaviour.

**Comment by kflynn** [comment]
@wibed Ahhh, got it! Can you show the YAML for a minimal HNS setup that'll show this problem? (I'd rather start with your configuration, rather than creating something from scratch, so that I can know we're both testing the same thing.)

**Comment by kflynn** [comment]
@wibed Any chance of getting more of your config set?

**Comment by wibed** [comment]
There is not a lot to add on to it.

-  a namespace for hns root ie.: staging  
- patch label management for linkerd such as privileged enforce and what not
- add your subnamespaceanchors for linkerd and linkerd-viz including desired labels.

i am currently inmidst another thing if you require specific configuration ill gladly will provide it for you

**Comment by wibed** [comment]
there is not a lot to it really, 


install hnc and add labels
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/namespace.yaml
  - https://github.com/kubernetes-sigs/hierarchical-namespaces/releases/download/v1.1.0-rc2/default.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --managed-namespace-label=pod-security.kubernetes.io/enforce
    target:
      kind: Deployment
      name: hnc-controller-manager
      namespace: hnc-system
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --managed-namespace-label=linkerd.io/is-control-plane
  target:
    kind: Deployment
    name: hnc-controller-manager
    namespace: hnc-system
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --managed-namespace-label=config.linkerd.io/admission-webhooks
  target:
    kind: Deployment
    name: hnc-controller-manager
    namespace: hnc-system
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --managed-namespace-label=linkerd.io/control-plane-ns
  target:
    kind: Deployment
    name: hnc-controller-manager
    namespace: hnc-system
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --managed-namespace-label=linkerd.io/cni-resource
  target:
    kind: Deployment
    name: hnc-controller-manager
    namespace: hnc-system
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --managed-namespace-annotation=linkerd.io/inject
  target:
    kind: Deployment
    name: hnc-controller-manager
    namespace: hnc-system
```


add your namespace
```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: staging
  name: staging
```


add your subnamespace
```yaml
apiVersion: hnc.x-k8s.io/v1alpha2
kind: SubnamespaceAnchor
metadata:
  labels:
    kubernetes.io/metadata.name: linkerd
  namespace: staging
  name: linkerd
spec:
  labels:
  - key: pod-security.kubernetes.io/enforce
    value: privileged
  - key: linkerd.io/is-control-plane
    value: "true"
  - key: config.linkerd.io/admission-webhooks
    value: disabled
  - key: linkerd.io/control-plane-ns
    value: "linkerd"
  annotations:
  - key: linkerd.io/inject
    value: disabled
 ```    
 
 
 match and repeat
