### ISSUE TITLE
linkerd-viz chart -- RBAC failure due to build time metadata namespace injection (.Release.Namespace)

### ISSUE THREAD

**Issue by wibed** [linkerd/linkerd2#11700]
### What is the issue?
Roles and Rolebindings must be within the same namespace.

the helm chart literally overwrites my value, at metadata.namespace for rolebinding resources.
resulting in an rbac failure

input:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: linkerd-{{.Release.Namespace}}-tap-auth-reader
  namespace: kube-system
  labels:
    linkerd.io/extension: viz
    component: tap
    namespace: kube-system
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: tap
  namespace: {{.Release.Namespace}}
```

output:
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    component: tap
    linkerd.io/extension: viz
    namespace: kube-system
  name: linkerd-linkerd-viz-tap-auth-reader
  namespace: linkerd-viz  # THIS SHOULD BE kube-system BUT ENDS UP BECOMING linkerd-viz
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: tap
  namespace: linkerd-viz
```

### How can it be reproduced?

the command to build:
```shell
kustomize build -o second.yaml --enable-helm --load-restrictor=LoadRestrictionsNone .
```

the kustomization
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd-viz

helmGlobals:
  chartHome: ../../../../base/linkerdviz

helmCharts:
- name: linkerd-viz
  releaseName: cluster0
  namespace: linkerd-viz
  includeCRDs: true
  valuesInline:
  repo: https://helm.linkerd.io/stable
```

### Logs, error output, etc

no error

### output of `linkerd check -o short`

this is during build time of the kubernetes resources.

### Environment

not relevant

### Additional context

if the definition on `.Release.Namespace` is removed at `kustomization.yaml.namespace`
this behaviour is surpressed. yet it is unpractical because i would like to use the feature.

### Would you like to work on fixing this bug?

yes

**Comment by wibed** [comment]
same goes for

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.linkerdNamespace }}
  labels:
    linkerd.io/extension: viz
    {{- with .Values.commonLabels }}{{ toYaml . | trim | nindent 4 }}{{- end }}
  annotations:
    {{ include "partials.annotations.created-by" . }}
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  name: viz-namespace-metadata-linkerd-config
roleRef:
  kind: Role
  name: ext-namespace-metadata-linkerd-config
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: namespace-metadata
  namespace: {{.Release.Namespace}}
```

**Comment by deusxanima** [comment]
Hi @wibed , could you provide some additional info about what you're trying to do and how the install process is set up between kustomize and helm? Are you trying to install linkerd-viz in the kube-system namespace, or just create the role and rolebindings in this ns? Are any other helm values being modified via kustomize (and if so, do you see the same behavior for those values) or is this the only one you're modifying?

**Comment by wibed** [comment]
@deusxanima the rolebinding and the role have to be in the same namespace the serviceaccount has to be in the namespace the resource is demanded for.

therefor if there is a resource in the kube-system namespace which has to be accessible from the namespace, lets say linkerd-viz, the serviceaccount is located in linkerd-viz.
role and rolebinding on the other hand should be located in kube-system.

in this particular case it is the configmap within kubesystem that matters to the pod within linkerd-viz. 
the namespace of the rolebinding though is overriden by some mysterious process i dont understand.

on the part of reproduction is clearly stated with a kustomization.yaml above.
just copy paste the file, install kustomization cli, adjust the home path kustomize will store the downloaded chart in  
and run the command from above.

ill add the repo part right away, missed that one.

**Comment by mikutas** [comment]
**Your kustomization** literally overwrites your value.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linkerd-viz # See https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/namespace/

helmGlobals:
  chartHome: ../../../../base/linkerdviz

helmCharts:
- name: linkerd-viz
  releaseName: cluster0
  namespace: linkerd-viz
  includeCRDs: true
  valuesInline:
  repo: https://helm.linkerd.io/stable
```
