### ISSUE TITLE
linkerd HTTPRoute doesn't work with Traefik IngressRoute

### ISSUE THREAD

**Issue by 5279314** [linkerd/linkerd2#11937]
### What is the issue?

We have deployed all required deployments but Service failover or HTTPRoute is not working as expected.

configs
```
---
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: emoji-route
  namespace: emojivoto
spec:
  parentRefs:
    - name: web-svc
      kind: Service
      group: core
      port: 80
  rules:
    - backendRefs:
      - name: web-svc
        port: 80
        weight: 0
      - name: web-svc-2
        port: 80
        weight: 100
```
and we have an ingressroute config with following rules.
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: emoji-middleware
  namespace: emojivoto
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: "web-svc.emojivoto.svc.cluster.local:80"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: emojivoto-web
  namespace: emojivoto
spec:
  entryPoints:
  - web   # secure
  routes:
  - match: Host(`emoji.od.com`) && PathPrefix(`/`)
    kind: Rule
    middlewares:
    - name: emoji-middleware
    priority: 1000
    services:
    - name: web-svc
      port: 80
```
and Handling ingress traffic
```
kubectl get deployments.apps -n traefik traefik-v2 -o yaml|linkerd inject --ingress -|kubectl apply -f -
```
and if call emoji.od.com the request is still going to web-svc pod and it doesn't split the traffic.

### How can it be reproduced?

Install linkerd, traefik proxy and create a sample ingressrout and HTTPRoute.
pod `https://run.linkerd.io/emojivoto.yml`
v2pod: whoami

### Logs, error output, etc

No logs

### output of `linkerd check -o short`

```
$ linkerd check -o short
Status check results are √
```

### Environment

kubectl version --short
Client Version: v1.23.6
Server Version: v1.23.6

linkerd version
Client version: stable-2.14.8
Server version: stable-2.14.8

### Would you like to work on fixing this bug?

None

**Comment by kflynn** [comment]
@5279314 Hey, thanks for chiming in here – my first thought here is to wonder whether you meshed Traefik in ingress mode, as described in https://linkerd.io/2.14/tasks/using-ingress/#traefik ? 🙂  Without that, none of Linkerd's advanced routing features will work for you...

**Comment by 5279314** [comment]
@kflynn `kubectl get deployments.apps -n traefik traefik-v2 -o yaml|linkerd inject --ingress -|kubectl apply -f -` Injection has been completed through this command.

**Comment by 5279314** [comment]
@kflynn

**Comment by 5279314** [comment]
@kflynn When I add a serviceprofile, HTTPRoute becomes invalid

```
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: web-svc.emojivoto.svc.cluster.local
  namespace: emojivoto
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /api/list
    name: GET /api/list
  - condition:
      method: GET
      pathRegex: /api/vote
    name: GET /api/vote
```

**Comment by plpetkov-tech** [comment]
Did you get to any resolution here? I am trying to achieve canary rollouts with Argo Rollouts Linkerd and Traefik ingressroutes v2, no success for now in getting a demo to work

**Comment by 5279314** [comment]
Hello @plpetkov-tech 
If you don't add `ServiceProfile` configuration, Canary deployment is not a problem, but adding `ServiceProfile` is not enough.

**Comment by plpetkov-tech** [comment]
> Hello @plpetkov-tech 
> If you don't add `ServiceProfile` configuration, Canary deployment is not a problem, but adding `ServiceProfile` is not enough.

What is it needed to be enough?

**Comment by 5279314** [comment]
> > Hello @plpetkov-tech
> > If you don't add `ServiceProfile` configuration, Canary deployment is not a problem, but adding `ServiceProfile` is not enough.
> 
> What is it needed to be enough?

It cannot be used

**Comment by kflynn** [comment]
(@5279314 ^ and so sorry for the delay here!)

**Comment by 5279314** [comment]
@kflynn 
I have set `l5d-dst-override` request evidence in the log
![](https://github.com/linkerd/linkerd2/assets/27267683/7a4aaecd-017e-4ad8-903b-33884738f347)

**Comment by faraonc** [comment]
I am almost sure this is related to the annotation. I just had the issue of having the wrong `enabled` annotation instead of `ingress`. it worked after I fixed it and followed the docs. Also, my test used `websecure` as entry point with TLS.

![image](https://github.com/linkerd/linkerd2/assets/16410475/0f0c8cee-5e7b-478f-a04e-73d3250e4bdc)


I got this to work with the following:
- helm - `traefik/traefik         28.0.0          v3.0.0          A Traefik based Kubernetes ingress controller`
```
# values i used
  values:
#    ingressRoute:
#      dashboard:
#        enabled: false
    logs:
      general:
        level: "DEBUG"
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik-v3
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
    deployment:
      replicas: 1
      podAnnotations:
        linkerd.io/inject: ingress
      minReadySeconds: 10
#    experimental:
#      kubernetesGateway: true

    providers:
      kubernetesGateway: { }
```
- linkerd
```
❯ linkerd version  
Client version: stable-2.14.10
Server version: stable-2.14.10
```

**Comment by kflynn** [comment]
@5279314, circling back here to see if you got this working?

**Comment by FredrikAugust** [comment]
Hey, I think we're also running into this issue. We have the same setup using traefik v3 and linkerd v2.16-enterprise with HTTPRoutes and GRPCRoutes, and can't see any metrics indicating that the routes are being used, not for HTTPRoutes nor for GRPCRoutes.

Our traefik setup has the following annotations:

```yaml
            linkerd.io/inject: ingress
            config.alpha.linkerd.io/proxy-enable-native-sidecar: "true"
            # Ingress mode _only_ supports http so health checks to kubelet fail without this.
            # See more here: https://github.com/linkerd/linkerd2/discussions/7387#discussioncomment-1727253
            config.linkerd.io/skip-outbound-ports: "443"
```

All the metrics show `endpoint` as the `route_name`. We forcefully unset the `l5d-dst-override` based on [the documentation here](https://linkerd.io/2.16/tasks/using-ingress/#ingress-mode), but to be honest I'm not sure if that's right as [the traefik documentation says that it _should_ be set](https://linkerd.io/2.16/tasks/using-ingress/#traefik-2x).
