### ISSUE TITLE
Override namespace per Helm Chart

### ISSUE THREAD

**Issue by mullermateus** [linkerd/linkerd2#12048]
### What is the issue?

Linkerd is being installed using ArgoCD with [multiple sources](https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/), but only **one** destination namespace can be informed.

This causes `linkerd-viz` and others to be installed on `linkerd` namespace.

I'd like to have a way to override the namespace from every Helm Chart.

### How can it be reproduced?

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  sources:
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-control-plane
      targetRevision: 1.16.10
      helm:
        valueFiles:
          - $values/tools/linkerd/linkerd-control-plane/values.yaml
    - repoURL: https://helm.linkerd.io/stable
      chart: linkerd-viz
      targetRevision: 30.12.10
      helm:
        valueFiles:
          - $values/tools/linkerd/linkerd-viz/values.yaml
```

Both charts will be installed on the same namespace.

### Logs, error output, etc

N/A

### output of `linkerd check -o short`

N/A

### Environment

N/A

### Possible solution

Currently the namespaces is defined as:

`namespace: {{ .Release.Namespace }}`

My suggestion is to create a helper inside `_helpers.tpl` that renders the namespace value. If `namespaceOverride` is not informed, then use `.Release.Name`. This way we can override through values.yaml.

### Would you like to work on fixing this bug?

yes

**Comment by deusxanima** [comment]
Hi @mullermateus ,

The recommended path for installing multiple charts/deploys in separate namespaces is to use the ArgoCD [app of apps pattern](https://argo-cd.readthedocs.io/en/stable/operator-manual/cluster-bootstrapping/#app-of-apps-pattern). This will essentially create a single parent application that will then orchestrate the remaining applications and allow for namespace flexibility according to each deployment's need. 

As an example, it would look something like this:

### Parent App

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  labels:
    type: main
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: linkerd
  source:
    path: your/repo/linkerd/path
    repoURL: git@github.com:user/repo.git
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

From here, you will then want to put the individual control-plane/crd/viz app definitions in the `your/repo/linkerd/path/` directory and structure each like so:

#### Linkerd Control Plane
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  labels:
    type: child
spec:
  project: linkerd
  source:
    chart: linkerd-control-plane
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 1.16.10
    helm:
      parameters:
      - name: identity.externalCA
        value: "true"
      - name: identity.issuer.scheme
        value: kubernetes.io/tls
      valueFiles:
      - values.yaml
  destination:
    namespace: linkerd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name:  linkerd-proxy-injector-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-sp-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: ""
    kind: Secret
    name:  linkerd-policy-validator-k8s-tls
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: admissionregistration.k8s.io/v1
    kind: MutatingWebhookConfiguration
    name:  linkerd-proxy-injector-webhook-config
    jqPathExpressions:
    - '.webhooks[0].clientConfig.caBundle'
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-sp-validator-webhook-config
    jqPathExpressions:
    - '.webhooks[0].clientConfig.caBundle'
  - group: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    name:  linkerd-policy-validator-webhook-config
    jqPathExpressions:
    - '.webhooks[0].clientConfig.caBundle'
```

#### Linkerd CRDs

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-crds
  namespace: argocd
  labels:
    type: child
spec:
  project: linkerd
  source:
    chart: linkerd-crds
    repoURL: 'https://helm.linkerd.io/stable'
    targetRevision: 1.8.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

(add other linkerd apps as needed)

The overall repo structure should look something like this:

```
.
├── control-plane
│   ├── linkerd-control-plane.yaml
│   ├── linkerd-crds.yaml
│   ├── linkerd_ca_bundle.yaml
│   └── linkerd_issuers_and_certs.yaml
└── linkerd_argocd_parent_app.yaml
```
