### ISSUE TITLE
Auto-Generate Identity Certs During Helm Install

### ISSUE THREAD

**Issue by the-wondersmith** [linkerd/linkerd2#12046]
### What problem are you trying to solve?

Per the [current docs](https://linkerd.io/2.14/tasks/install-helm/#prerequisite-generate-identity-certificates), the required mTLS trust anchor and issuer certificate/key pairs cannot be autogenerated when using helm to install `linkerd`, but that's not strictly speaking accurate.

### How should the problem be solved?

I've worked out the required manifests to accomplish auto-generation using helm's builtin [hooks](https://v2.helm.sh/docs/developing_charts/#:~:text=explain%20that%20process.-,Hooks,-Helm%20provides%20a) feature. The hooks create a cluster role and binding with the required  permissions, as well as a `job` that does the actual work. The job leverages kubernetes' [linear execution guarantees for init containers](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#understanding-init-containers) to (in order):

1) delete any previously created secrets
2) generate the trust anchor cert and key [[ref](https://linkerd.io/2.14/tasks/generate-certificates/#trust-anchor-certificate)]
3) generate the issuer cert and key [[ref](https://linkerd.io/2.14/tasks/generate-certificates/#issuer-certificate-and-key)]
4) create kubernetes secrets for the created cert/key pairs
5) apply labels to the created secrets that uniquely identify them as being created as part of a new/fresh `linkerd` installation
6) delete the created cluster role binding (as a general security best practice)

Each step of the above is dependent upon the previous step, making the entire creation process atomic (more or less 😅) and dead simple to troubleshoot if anything goes wrong. Also, if the hook fails, the install fails, so it preserves the existing "`linkerd` requires these certs to work" behavior.

#### `ClusterRole`

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-helm-installer
  labels:
    hook: create-linkerd-helm-installer-role
    app.kubernetes.io/name: linkerd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - patch
      - create
      - delete
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - delete
```

#### `ClusterRoleBinding`

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-helm-installer
  labels:
    hook: create-linkerd-helm-installer-role-binding
    app.kubernetes.io/name: linkerd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-helm-installer
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
```

#### `Job`

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-linkerd-mtls-cert-chain
  labels:
    hook: create-linkerd-mtls-cert-chain
    app.kubernetes.io/name: linkerd
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: default
      volumes:
        - name: certificates
          emptyDir: {}
      initContainers:
        - name: remove-existing-secrets
          image: docker.io/rancher/kubectl:v1.29.0
          command:
            - kubectl
          args:
            - delete
            - secret
            - --selector
            - install.linkerd.io/mtls-secret==true
            - --ignore-not-found=true
        - name: generate-trust-anchor
          image: docker.io/smallstep/step-cli:latest
          command:
            - step
          args:
            - certificate
            - create
            - root.linkerd.cluster.local
            - /var/run/certificates/ca.crt
            - /var/run/certificates/ca.key
            - --profile
            - root-ca
            - --no-password
            - --insecure
          volumeMounts:
            - name: certificates
              mountPath: /var/run/certificates
        - name: generate-issuer-cert-and-key
          image: docker.io/smallstep/step-cli:latest
          command:
            - step
          args:
            - certificate
            - create
            - identity.linkerd.cluster.local
            - /var/run/certificates/issuer.crt
            - /var/run/certificates/issuer.key
            - --profile
            - intermediate-ca
            - --not-after
            - 8760h
            - --no-password
            - --insecure
            - --ca
            - /var/run/certificates/ca.crt
            - --ca-key
            - /var/run/certificates/ca.key
          volumeMounts:
            - name: certificates
              mountPath: /var/run/certificates
        - name: create-ca-secret
          image: docker.io/rancher/kubectl:v1.29.0
          command:
            - kubectl
          args:
            - create
            - secret
            - tls
            - linkerd-trust-anchor
            - --cert
            - /var/run/certificates/ca.crt
            - --key
            - /var/run/certificates/ca.key
          volumeMounts:
            - name: certificates
              mountPath: /var/run/certificates
        - name: create-issuer-secret
          image: docker.io/rancher/kubectl:v1.29.0
          command:
            - kubectl
          args:
            - create
            - secret
            - tls
            - linkerd-identity-issuer
            - --cert
            - /var/run/certificates/issuer.crt
            - --key
            - /var/run/certificates/issuer.key
          volumeMounts:
            - name: certificates
              mountPath: /var/run/certificates
        - name: apply-trust-anchor-labels
          image: docker.io/rancher/kubectl:v1.29.0
          command:
            - kubectl
          args:
            - label
            - secret
            - linkerd-trust-anchor
            - install.linkerd.io/mtls-secret=true
        - name: apply-issuer-labels
          image: docker.io/rancher/kubectl:v1.29.0
          command:
            - kubectl
          args:
            - label
            - secret
            - linkerd-identity-issuer
            - install.linkerd.io/mtls-secret=true
      containers:
        - name: remove-role-binding
          image: docker.io/rancher/kubectl:v1.29.0
          command:
            - kubectl
          args:
            - delete
            - clusterrolebindings/linkerd-helm-installer
            - --wait
            - --ignore-not-found=false
```

### Any alternatives you've considered?

It's *technically* possible to accomplish the same thing using `helmfile`'s builtin [DAG-aware installation ordering](https://helmfile.readthedocs.io/en/latest/#dag-aware-installationdeletion-ordering-with-needs), but I'd bet vanilla `helm` usage is much more common than `helmfile`. 

### How would users interact with this feature?

Hook-based identity certificate creation should be added to the extant `linkerd/linkerd-control-plane` helm chart as a `values`-toggled behavior, set to `false` by default at initial rollout. Assuming no negative user feedback, the default value can be set to `true` after a suitable time window.

I'm not *positive*, but I think either the proposed manifests would need to be updated/tweaked to match the existing chart's expectations (or possibly vice versa?) so that the deployed workload(s) know to look for their expected values in the created secret(s) rather than create new ones.

I _have_ checked the `"Would you like to work on this feature?"` box, but just to be extra clear I'd be more than happy to work with someone from the linkerd team to get this functionality merged in.

### Would you like to work on this feature?

yes
