### ISSUE TITLE
Resources in policy controller manifest aren't getting properly defaulted when empty

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#12131]
Ref #12104 

Currently the resources config for the Policy controller are declared to fall back to the ones for the destination controller if they're empty:
https://github.com/linkerd/linkerd2/blob/f0d861ea9b927eed308d66fa64a08a5861c028d2/charts/linkerd-control-plane/templates/destination.yaml#L347
However, the `.Values.policyController.resources` entry will never be falsy, because it's an object with fields, even the fields are empty:
https://github.com/linkerd/linkerd2/blob/f0d861ea9b927eed308d66fa64a08a5861c028d2/charts/linkerd-control-plane/values.yaml#L92-L107

## Repro

Render the templates setting a value for `destinationResources`:
```
helm template linkerd/linkerd-control-plane --devel -f ~/src/k8s/helm/linkerd-overrides.yaml --set destinationResources.resources.cpu.request=100m
```
You'll see that the policy controller still has its `resources` entry empty:
```yaml
...
        name: policy
        ports:
        - containerPort: 8090
          name: grpc
        - containerPort: 9990
          name: admin-http
        - containerPort: 9443
          name: policy-https
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: admin-http
          initialDelaySeconds: 10
        resources:
        securityContext:
...
```

It should be noted that recently the values.yaml entry `policyControllerResources` (that does fall back to `controllerResources`) was added, but it's not used in the templates. So we should remove it and fix the defaulting logic above.
