### ISSUE TITLE
Allow custom metric_relabel_config for Prometheus

### ISSUE THREAD

**Issue by hvoigt** [linkerd/linkerd2#12194]
### What problem are you trying to solve?

Linkerd proxy metrics tend to have quite high cardinality. E.g. see [this Medium article](https://itnext.io/optimizing-linkerd-metrics-in-prometheus-de607ec10f6b) suggests to drop some `le` values to reduce cardinality:
```
metric_relabel_configs:
  - action: drop
    source_labels: [le]
    regex: "2.*|3.*|4.*|5.*"
```
We also experience that `response_latency_ms_bucket` has too high cardinality.

### How should the problem be solved?

Provide a custom configuration for `metric_relabel_configs` in the _linkerd-viz helm chart_. E.g.

```
prometheus:
[...]
  proxyMetricRelabelConfigs:
  - action: keep
    source_labels: [le]
    regex: "(?i)(|10|50|100|500|1000|10000|30000|\\+Inf)"
```

### Any alternatives you've considered?

We are currently copying the linkerd-viz helm chart and manually applying this change locally. This is annoying in case of an update as we have to reapply this change and release our own local version.

### How would users interact with this feature?

If they use the Prometheus that comes with linkerd they define their wanted `metric_relabel_configs` using the helm charts values.

### Would you like to work on this feature?

yes
