### ISSUE TITLE
Different route behavior between gateway and sidecar under several same HTTPRouteMatch

### ISSUE THREAD

**Issue by qts0312** [linkerd/linkerd2#12267]
### What is the issue?

Here is the configuration. Traffic from gateway with path `/test` skips the first rule and goes to productpage service. For reference, traffic from sidecar with path `/test` goes to ratings service correctly.
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr
spec:
  parentRefs:
  - name: gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  - kind: Service
    name: back
    port: 80
    group: core
  hostnames:
  - www.example.com
  rules:
  - matches:
    - path:
        type: Exact
        value: /test
    backendRefs:
    - name: ratings
      port: 8080
  - matches:
    - path:
        type: Exact
        value: /test
    backendRefs:
    - name: productpage
      port: 9080
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
spec:
  gatewayClassName: contour
  listeners:
  - name: port-1
    port: 80
    protocol: HTTP
    hostname: www.example.com
    allowedRoutes:
      namespaces:
        from: All 
```

### How can it be reproduced?

Under configuration above, try `curl -H"host:www.example.com" http://<gateway service external ip>:80/test` from outside.

### Logs, error output, etc

Logs of `envoy-gateway-8fjhj` pod
```text
[     0.001010s]  INFO ThreadId(01) linkerd2_proxy: release 2.210.4 (5a910be) by linkerd on 2023-11-22T17:01:44Z
[     0.001399s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.001966s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.001971s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.001972s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.001973s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
[     0.001974s]  INFO ThreadId(01) linkerd2_proxy: Local identity is envoy-gateway.default.serviceaccount.identity.linkerd.cluster.local
[     0.001977s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.001978s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.010591s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity id=envoy-gateway.default.serviceaccount.identity.linkerd.cluster.local
[     2.052353s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.244.1.27:34788 server.addr=10.96.223.183:8001
[     3.185338s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.244.1.27:34796 server.addr=10.96.223.183:8001
[     3.925316s]  INFO ThreadId(01) inbound:server{port=8002}:rescue{client.addr=10.244.1.1:49138}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     4.465535s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.244.1.27:54014 server.addr=10.96.223.183:8001
[     4.684876s]  INFO ThreadId(01) inbound:server{port=8002}:rescue{client.addr=10.244.1.1:49146}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     7.221756s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.244.1.27:54026 server.addr=10.96.223.183:8001
[     8.686185s]  INFO ThreadId(01) inbound:server{port=8002}:rescue{client.addr=10.244.1.1:49160}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     9.091440s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=connect timed out after 1s client.addr=10.244.1.27:54048 server.addr=10.96.223.183:8001
[    12.683625s]  INFO ThreadId(01) inbound:server{port=8002}:rescue{client.addr=10.244.1.1:49170}: linkerd_app_core::errors::respond: HTTP/1.1 request failed error=error trying to connect: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
```

### output of `linkerd check -o short`

```text
Status check results are √
```

### Environment

- Kubernetes Version: 1.28.2
- Linkerd Version: stable-2.14.10
- Gateway Implementation: Contour

### Would you like to work on fixing this bug?

None
