### ISSUE TITLE
Inconsistent route choice between gateway and sidecar under HTTPRoutes with same parent

### ISSUE THREAD

**Issue by qts0312** [linkerd/linkerd2#12288]
### What is the issue?

Here is the configuration, traffic from sidecar chooses `hr-0` and goes to the ratings service, while traffic from gateway chooses `hr-1` and goes to the productpage service, implying inconsistency between the route choice of sidecar and gateway.
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr-0
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gw
  - group: core
    port: 80
    name: back
    kind: Service
  hostnames:
  - www.bookinfo.com
  rules:
  - backendRefs:
    - name: ratings
      port: 9090
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr-1
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gw
  - group: core
    port: 80
    name: back
    kind: Service
  hostnames:
  - www.bookinfo.com
  rules:
  - backendRefs:
    - name: productpage
      port: 9080
```

### How can it be reproduced?

Create services `ratings`, `productpage` and `back` in the proper ports, and then create gateway as below.
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gw
spec:
  gatewayClassName: contour
  listeners:
  - name: port-0
    port: 9080
    protocol: HTTP
    hostname: www.bookinfo.com
    allowedRoutes:
      namespaces:
        from: All
```
`curl -H"host:www.bookinfo.com" http://back.default.svc.cluster.local:80` from one of the pods will go to ratings service, and `curl -H"host:www.bookinfo.com" http://<gateway service external ip>:9080` from gateway will go to productpage service.

### Logs, error output, etc

Behavior is described above, and details can be provided if need.

### output of `linkerd check -o short`

```test
Status check results are √
```

### Environment

- Kubernetes Version: 1.28.2
- Linkerd Version: stable-2.14.10
- Gateway Implementation: Contour

### Would you like to work on fixing this bug?

None
