### ISSUE TITLE
Linkerd implementation of Gateway API not follow GAMMA spec

### ISSUE THREAD

**Issue by qts0312** [linkerd/linkerd2#12295]
### What is the issue?

I am using Gateway API in Linkerd and find inconsistency between route behavior in Linkerd and GAMMA specification. In [GEP](https://gateway-api.sigs.k8s.io/geps/gep-1426/#hostnames-field), it says that GAMMA implementation should not infer any functionality from the `hostnames` field on HTTPRoute. But actually, `hostnames` in HTTPRoute makes effect in Linkerd.

### How can it be reproduced?

For example, as configuration below, `curl -H"host:www.bookinfo.com" http://back:80` can get correct service while `curl -H"host:www.example.com" http://back:80` cannot.
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hr-1
spec:
  parentRefs:
    - port: 80
      group: ''
      kind: Service
      name: back
  hostnames:
    - www.bookinfo.com
  rules:
    - backendRefs:
        - name: productpage
          port: 9090
```

### Logs, error output, etc

There are no specific logs.

### output of `linkerd check -o short`

```text
Status check results are √
```

### Environment

- Kubernetes Version: 1.28.2
- Linkerd Version: stable-2.14.10

### Would you like to work on fixing this bug?

None
