### ISSUE TITLE
linkerd2/client image cannot be found on cr.l5d.io (ghcr.io) 

### ISSUE THREAD

**Issue by frankramke** [linkerd/linkerd2#12897]
### What is the issue?

following along the guide for adding non-kubernetes workloads to your mesh, one step includes pulling an image from ghcr.io:
```
kubectl apply -f - <<EOF
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client
  namespace: mixed-env
---
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: mixed-env
  annotations:
    linkerd.io/inject: enabled
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: client
    image: cr.l5d.io/linkerd/client:current
    command:
      - "sh"
      - "-c"
      - >
        while true; do
          sleep 3600;
        done        
  serviceAccountName: client
EOF
```

The image **cr.l5d.io/linkerd/client:current** cannot be found.  resulting in client POD failure

### How can it be reproduced?

1. Login to github with personal access token (PAT)
2. docker pull  cr.l5d.io/linkerd/client:current
Error response from daemon: manifest unknown

### Logs, error output, etc

docker pull  cr.l5d.io/linkerd/client:current
Error response from daemon: manifest unknown

### output of `linkerd check -o short`

linkerd check -o short
Status check results are √

### Environment

 kubectl version
Client Version: v1.29.6+k3s2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.6+k3s2

### Would you like to work on fixing this bug?

None
