### ISSUE TITLE
Why Conduit doesn't work in this scenario?

### ISSUE THREAD

**Issue by jeroenjacobs1205** [linkerd/linkerd2#1299]
Hello,

Can someone shed a light on why the following scenario breaks Conduit functionality? I have two deployments, one acts as a loadbalancer, and the other as the actual application.

nginx-lb.yml:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-lb-config
data:
  nginx.conf: |
    user  nginx;

    worker_processes 1;
    events {
        worker_connections 1024;
        use epoll;
    }

    http {
        server {
            listen 81;
            server_name  _;
            server_tokens off;
            sendfile on;
            tcp_nopush on;
            tcp_nodelay on;
            access_log off;
            location / {
              proxy_pass http://nginx-app;
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
            }
            location /healthz/ {
                return 200 'OK';
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
spec:
  selector:
    matchLabels:
      app: nginx-lb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - image: nginx:1.13.12
        name: nginx-lb
        ports:
          - containerPort: 81
        livenessProbe:
          httpGet:
            path: /healthz/
            port: 81
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
        volumeMounts:
        - mountPath: /etc/nginx
          name: nginx-lb-config
      volumes:
      - configMap:
          name: nginx-lb-config
        name: nginx-lb-config

```

nginx-app.yml

```
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx:1.13.12
        name: nginx-app
        ports:
        - containerPort: 80

```

Without Conduit, I'm starting a shell in the nginx-lb pod, and everythink runs fine:

```
kubectl exec -ti  nginx-lb-7cc6688ddf-j5nwp  -- /bin/sh
# apt-get update && apt-get install curl
...
# curl http://localhost:81
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

Now, when I install nginx-app with Conduit like this, everything still works:

`conduit inject  --tls=optional nginx-app.yaml | kubectl apply -f - `

No change in behaviour, the curl command still works, but TLS not working (not a surprise, as the nginx-lb has not been injected yet, and doesn't have the conduit proxy pod yet).

So, now I inject the nginx-lb pod:

`conduit inject  --tls=optional nginx-lb.yaml | kubectl apply -f - `

And now requests start the fail, and it seems nginx-lb is unable to forward requests to the lb-app pods anymore:

```
# curl -v http://localhost:81
* Rebuilt URL to: http://localhost:81/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 81 (#0)
> GET / HTTP/1.1
> Host: localhost:81
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Server: nginx
< Date: Tue, 10 Jul 2018 07:41:54 GMT
< Content-Length: 0
< Connection: keep-alive
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

The conduit-proxy container reports the following:

`[nginx-lb-5c865fc99-mn5ws conduit-proxy] ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.46.0.10:59092} conduit_proxy turning Error caused by underlying HTTP/2 error: protocol error: unexpected internal error encountered into 500`

What is the reason for this behaviour, and how I can fix this? I really want to encrypt the entire request chain with TLS, so disabling it on the lb pod is not an option.
