### ISSUE TITLE
linkerd-destination: failed to read TLS key: could not load private key

### ISSUE THREAD

**Issue by iarlyy** [linkerd/linkerd2#13017]
### What is the issue?

I am trying to get linkerd up and running, however destination and destination-policy containers crash on startup, and I am unable to move forward:  

```
$ kubectl logs deploy/linkerd-destination policy -n linkerd        
Error: failed to read TLS key: could not load private key

Caused by:
    could not load private key
```

I am unsure whether this is something missing on the cert-manager side, or on the helm values level/linkerd configuration. I've tweaked both of them, but still no luck.

Any help would be appreciated.

### How can it be reproduced?

```bash
# helm template command:

helm template linkerd-control-plane linkerd/linkerd-control-plane --namespace linkerd --version 1.18.10-edge -f custom.yaml
```

```yaml
# custom.yaml
clusterDomain: cluster.local
clusterNetworks: "10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16"
imagePullPolicy: IfNotPresent
controllerLogLevel: info
controllerLogFormat: plain
controlPlaneTracing: false
controlPlaneTracingNamespace: linkerd
linkerdVersion: edge-24.2.4
deploymentStrategy:
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%
enableEndpointSlices: true
enablePodAntiAffinity: false
enablePprof: false
enablePodDisruptionBudget: false
cniEnabled: false
identityTrustAnchorsPEM: |
identityTrustDomain: ""
kubeAPI: &kubeapi
  clientQPS: 100
  clientBurst: 200
podAnnotations: {}
podLabels: {}
commonLabels: {}
priorityClassName: ""
runtimeClassName: ""

policyController:
  image:
    name: cr.l5d.io/linkerd/policy-controller
    pullPolicy: ""
    version: ""
  logLevel: info
  probeNetworks:
    - 0.0.0.0/0
  resources:
    cpu:
      limit: ""
      request: ""
    memory:
      limit: ""
      request: ""
    ephemeral-storage:
      limit: ""
      request: ""

proxy:
  enableExternalProfiles: false
  outboundConnectTimeout: 1000ms
  inboundConnectTimeout: 100ms
  outboundDiscoveryCacheUnusedTimeout: "5s"
  inboundDiscoveryCacheUnusedTimeout: "90s"
  disableOutboundProtocolDetectTimeout: false
  disableInboundProtocolDetectTimeout: false
  image:
    name: cr.l5d.io/linkerd/proxy
    pullPolicy: ""
    version: ""
  logLevel: warn,linkerd=info,trust_dns=error
  logFormat: plain
  ports:
    admin: 4191
    control: 4190
    inbound: 4143
    outbound: 4140
  cores: 0
  resources:
    cpu:
      limit: ""
      request: ""
    memory:
      limit: ""
      request: ""
    ephemeral-storage:
      limit: ""
      request: ""
  uid: 2102
  waitBeforeExitSeconds: 0
  await: true
  requireIdentityOnInboundPorts: ""
  opaquePorts: "25,587,3306,4444,5432,6379,9300,11211"
  shutdownGracePeriod: ""
  defaultInboundPolicy: "all-unauthenticated"
  nativeSidecar: false
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 2
    timeoutSeconds: 1
  startupProbe:
    initialDelaySeconds: 0
    periodSeconds: 1
    failureThreshold: 120
  control:
    streams:
      initialTimeout: "3s"
      idleTimeout: "5m"
      lifetime: "1h"

proxyInit:
  iptablesMode: "legacy"
  ignoreInboundPorts: "4567,4568"
  ignoreOutboundPorts: "4567,4568"
  kubeAPIServerPorts: "443,6443"
  skipSubnets: ""
  logLevel: ""
  logFormat: ""
  image:
    name: cr.l5d.io/linkerd/proxy-init
    pullPolicy: ""
    version: v2.2.4
  resources:
    cpu:
      limit: 100m
      request: 100m
    memory:
      limit: 20Mi
      request: 20Mi
    ephemeral-storage:
      limit: ""
      request: ""
  closeWaitTimeoutSecs: 0
  privileged: false
  runAsRoot: false
  runAsUser: 65534
  xtMountPath:
    mountPath: /run
    name: linkerd-proxy-init-xtables-lock

networkValidator:
  logLevel: debug
  logFormat: plain
  connectAddr: "1.1.1.1:20001"
  listenAddr: "0.0.0.0:4140"
  timeout: "10s"
  enableSecurityContext: true

imagePullSecrets: []
enableH2Upgrade: true
enablePSP: false
webhookFailurePolicy: Ignore
controllerImage: cr.l5d.io/linkerd/controller
controllerImageVersion: ""
controllerReplicas: 1
controllerUID: 2103

debugContainer:
  image:
    name: cr.l5d.io/linkerd/debug
    pullPolicy: ""
    version: ""

identity:
  externalCA: true
  serviceAccountTokenProjection: true
  issuer:
    scheme: kubernetes.io/tls #linkerd.io/tls
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s
    tls:
      crtPEM: |
      keyPEM: |
  kubeAPI: *kubeapi

disableHeartBeat: false

proxyInjector:
  timeoutSeconds: 10
  externalSecret: true
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - cert-manager
  objectSelector:
    matchExpressions:
    - key: linkerd.io/control-plane-component
      operator: DoesNotExist
    - key: linkerd.io/cni-resource
      operator: DoesNotExist
  crtPEM: |
  keyPEM: |
  caBundle: |
  injectCaFrom: ""
  injectCaFromSecret: "linkerd/linkerd-identity-trust-roots"

profileValidator:
  externalSecret: true
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
  crtPEM: |
  keyPEM: |
  caBundle: |
  injectCaFrom: ""
  injectCaFromSecret: "linkerd/linkerd-identity-trust-roots"

policyValidator:
  externalSecret: true
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
  crtPEM: |
  keyPEM: |
  caBundle: |
  injectCaFrom: ""
  injectCaFromSecret: "linkerd/linkerd-identity-trust-roots"

nodeSelector:
  kubernetes.io/os: linux

prometheusUrl: ""

podMonitor:
  enabled: false
  scrapeInterval: 10s
  scrapeTimeout: 10s
  labels: {}
  controller:
    enabled: true
    namespaceSelector: |
      matchNames:
        - {{ .Release.Namespace }}
        - linkerd-viz
        - linkerd-jaeger
  serviceMirror:
    enabled: true
  proxy:
    enabled: true
```

```yaml
# CA configuration
# Root Certificate Authority
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-self-signed-issuer
  namespace: cert-manager
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  isCA: true
  duration: 87660h
  renewBefore: 360h
  commonName: root.linkerd.svc.cluster.local
  secretName: linkerd-identity-trust-roots
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: linkerd-self-signed-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-identity-trust-roots
# Linkerd CA
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 8766h
  renewBefore: 720h
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: identity.linkerd.svc.cluster.local
  dnsNames:
  - identity.linkerd.svc.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 8766h
  renewBefore: 720h
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: linkerd-proxy-injector.linkerd.svc.cluster.local
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 8766h
  renewBefore: 720h
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: linkerd-sp-validator.linkerd.svc.cluster.local
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 8766h
  renewBefore: 720h
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: linkerd-policy-validator.linkerd.svc.cluster.local
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
spec:
  sources:
  - secret:
      name: "linkerd-identity-trust-roots"
      key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
```

### Logs, error output, etc

```
$ kubectl logs deploy/linkerd-destination policy -n linkerd                                                                  

Error: failed to read TLS key: could not load private key

Caused by:
    could not load private key
```

```
$kubectl logs deploy/linkerd-destination destination -n linkerd

time="2024-09-03T14:20:27Z" level=info msg="running version edge-24.2.4"
time="2024-09-03T14:20:27Z" level=info msg="starting admin server on :9996"
time="2024-09-03T14:20:27Z" level=info msg="Using default opaque ports: map[25:{} 587:{} 3306:{} 4444:{} 5432:{} 6379:{} 9300:{} 11211:{}]"
time="2024-09-03T14:20:27Z" level=fatal msg="Failed to initialize K8s API: the server could not find the requested resource"
```

Not sure if this is relevant, but posting anyways:
```
$ kubectl logs deploy/linkerd-destination linkerd-proxy -n linkerd
[     0.000797s]  INFO ThreadId(01) linkerd2_proxy: release 2.221.0 (098dd0d) by linkerd on 2024-02-16T19:36:34Z
[     0.002359s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.002752s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.002915s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.002917s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.002917s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
[     0.002918s]  INFO ThreadId(01) linkerd2_proxy: SNI is linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
[     0.002919s]  INFO ThreadId(01) linkerd2_proxy: Local identity is linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
[     0.002920s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via localhost:8086
[     0.002952s]  INFO ThreadId(01) dst:controller{addr=localhost:8086}: linkerd_pool_p2c: Adding endpoint addr=127.0.0.1:8086
[     0.002999s]  INFO ThreadId(01) policy:controller{addr=localhost:8090}: linkerd_pool_p2c: Adding endpoint addr=127.0.0.1:8090
[     0.003061s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     0.003067s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     0.003489s]  INFO ThreadId(02) identity:identity{server.addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}:controller{addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}: linkerd_pool_p2c: Adding endpoint addr=10.42.0.46:8080
[     0.111593s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     0.113727s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     0.330910s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     0.332018s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     0.502923s]  INFO ThreadId(02) daemon:identity: linkerd_app: Certified identity id=linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
[     0.749462s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     0.758575s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     1.250221s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     1.260282s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     1.752423s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     1.761632s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     2.253018s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     2.263123s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     2.754653s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     2.763769s]  WARN ThreadId(01) dst:controller{addr=localhost:8086}:endpoint{addr=127.0.0.1:8086}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8086: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
[     3.257821s]  WARN ThreadId(01) policy:controller{addr=localhost:8090}:endpoint{addr=127.0.0.1:8090}: linkerd_reconnect: Failed to connect error=endpoint 127.0.0.1:8090: Connection refused (os error 111) error.sources=[Connection refused (os error 111)]
```

```
linkerd-destination-9f9678b9d-9w9mk       2/4     CrashLoopBackOff   18 (90s ago)   22m
linkerd-identity-777788bcf7-ml2d6         2/2     Running            0              80m
linkerd-proxy-injector-7749f5d7f8-pb4sp   2/2     Running            0              22m
```

```
Name:             linkerd-destination-9f9678b9d-9w9mk
Namespace:        linkerd
Priority:         0
Service Account:  linkerd-destination
Node:             colima-dev/192.168.5.3
Start Time:       Tue, 03 Sep 2024 16:04:36 +0200
Labels:           linkerd.io/control-plane-component=destination
                  linkerd.io/control-plane-ns=linkerd
                  linkerd.io/proxy-deployment=linkerd-destination
                  linkerd.io/workload-ns=linkerd
                  pod-template-hash=9f9678b9d
Annotations:      checksum/config: 4303fe85486b24687f4d576093cc991316cb5e7e7486d5c4bf7c4d5bb22507f6
                  cluster-autoscaler.kubernetes.io/safe-to-evict: true
                  config.linkerd.io/default-inbound-policy: all-unauthenticated
                  linkerd.io/created-by: linkerd/helm edge-24.2.4
                  linkerd.io/proxy-version: edge-24.2.4
                  linkerd.io/trust-root-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Status:           Running
SeccompProfile:   RuntimeDefault
IP:               10.42.0.53
IPs:
  IP:           10.42.0.53
Controlled By:  ReplicaSet/linkerd-destination-9f9678b9d
Init Containers:
  linkerd-init:
    Container ID:    containerd://35d6615de89c10fc7659ecf900558c233744c56852e805cb6ff5d1c8486cd9e7
    Image:           cr.l5d.io/linkerd/proxy-init:v2.2.4
    Image ID:        cr.l5d.io/linkerd/proxy-init@sha256:5f25b4e34c6707b435aef8a17c4615ad114680fc0d5121994ae0b2fdbf9103c2
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Args:
      --incoming-proxy-port
      4143
      --outgoing-proxy-port
      4140
      --proxy-uid
      2102
      --inbound-ports-to-ignore
      4190,4191,4567,4568
      --outbound-ports-to-ignore
      443,6443
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 03 Sep 2024 16:04:37 +0200
      Finished:     Tue, 03 Sep 2024 16:04:37 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  20Mi
    Requests:
      cpu:        100m
      memory:     20Mi
    Environment:  <none>
    Mounts:
      /run from linkerd-proxy-init-xtables-lock (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lvt6m (ro)
Containers:
  linkerd-proxy:
    Container ID:    containerd://9ee4136666dea843d96d29745d434c68aaf8b43f715aee0edf3e2fdcd0eadc43
    Image:           cr.l5d.io/linkerd/proxy:edge-24.2.4
    Image ID:        cr.l5d.io/linkerd/proxy@sha256:74c4e8b5d4b192d78b1f39ff21babf5d8231b44aecaf3bddfd23e95dce3380c7
    Ports:           4143/TCP, 4191/TCP
    Host Ports:      0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    State:           Running
      Started:       Tue, 03 Sep 2024 16:04:38 +0200
    Ready:           True
    Restart Count:   0
    Liveness:        http-get http://:4191/live delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:       http-get http://:4191/ready delay=2s timeout=1s period=10s #success=1 #failure=3
    Environment:
      _pod_name:                                                linkerd-destination-9f9678b9d-9w9mk (v1:metadata.name)
      _pod_ns:                                                  linkerd (v1:metadata.namespace)
      _pod_nodeName:                                             (v1:spec.nodeName)
      LINKERD2_PROXY_LOG:                                       warn,linkerd=info,trust_dns=error
      LINKERD2_PROXY_LOG_FORMAT:                                plain
      LINKERD2_PROXY_DESTINATION_SVC_ADDR:                      localhost.:8086
      LINKERD2_PROXY_DESTINATION_PROFILE_NETWORKS:              10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      LINKERD2_PROXY_POLICY_SVC_ADDR:                           localhost.:8090
      LINKERD2_PROXY_POLICY_WORKLOAD:                           {"ns":"$(_pod_ns)", "pod":"$(_pod_name)"}
                                                                
      LINKERD2_PROXY_INBOUND_DEFAULT_POLICY:                    all-unauthenticated
      LINKERD2_PROXY_POLICY_CLUSTER_NETWORKS:                   10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      LINKERD2_PROXY_CONTROL_STREAM_INITIAL_TIMEOUT:            3s
      LINKERD2_PROXY_CONTROL_STREAM_IDLE_TIMEOUT:               5m
      LINKERD2_PROXY_CONTROL_STREAM_LIFETIME:                   1h
      LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT:                   100ms
      LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT:                  1000ms
      LINKERD2_PROXY_OUTBOUND_DISCOVERY_IDLE_TIMEOUT:           5s
      LINKERD2_PROXY_INBOUND_DISCOVERY_IDLE_TIMEOUT:            90s
      LINKERD2_PROXY_CONTROL_LISTEN_ADDR:                       0.0.0.0:4190
      LINKERD2_PROXY_ADMIN_LISTEN_ADDR:                         0.0.0.0:4191
      LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR:                      127.0.0.1:4140
      LINKERD2_PROXY_INBOUND_LISTEN_ADDR:                       0.0.0.0:4143
      LINKERD2_PROXY_INBOUND_IPS:                                (v1:status.podIPs)
      LINKERD2_PROXY_INBOUND_PORTS:                             8086,8090,8443,9443,9990,9996,9997
      LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES:              svc.cluster.local.
      LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE:                  10000ms
      LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE:                10000ms
      LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION:  25,587,3306,4444,5432,6379,9300,11211
      LINKERD2_PROXY_DESTINATION_CONTEXT:                       {"ns":"$(_pod_ns)", "nodeName":"$(_pod_nodeName)", "pod":"$(_pod_name)"}
                                                                
      _pod_sa:                                                   (v1:spec.serviceAccountName)
      _l5d_ns:                                                  linkerd
      _l5d_trustdomain:                                         cluster.local
      LINKERD2_PROXY_IDENTITY_DIR:                              /var/run/linkerd/identity/end-entity
      LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS:                    <set to the key 'ca-bundle.crt' of config map 'linkerd-identity-trust-roots'>  Optional: false
      LINKERD2_PROXY_IDENTITY_TOKEN_FILE:                       /var/run/secrets/tokens/linkerd-identity-token
      LINKERD2_PROXY_IDENTITY_SVC_ADDR:                         linkerd-identity-headless.linkerd.svc.cluster.local.:8080
      LINKERD2_PROXY_IDENTITY_LOCAL_NAME:                       $(_pod_sa).$(_pod_ns).serviceaccount.identity.linkerd.cluster.local
      LINKERD2_PROXY_IDENTITY_SVC_NAME:                         linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local
      LINKERD2_PROXY_DESTINATION_SVC_NAME:                      linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
      LINKERD2_PROXY_POLICY_SVC_NAME:                           linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
    Mounts:
      /var/run/linkerd/identity/end-entity from linkerd-identity-end-entity (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lvt6m (ro)
      /var/run/secrets/tokens from linkerd-identity-token (rw)
  destination:
    Container ID:    containerd://03beea69672cd480cd3ea86ae3f6f8f1088719fa032aa8598f4860f53c0f5f1d
    Image:           cr.l5d.io/linkerd/controller:edge-24.2.4
    Image ID:        cr.l5d.io/linkerd/controller@sha256:ea5a052b31d84718d82aa67a0b37d7115965f1058a133e7bb5532a25116879ce
    Ports:           8086/TCP, 9996/TCP
    Host Ports:      0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      destination
      -addr=:8086
      -controller-namespace=linkerd
      -enable-h2-upgrade=true
      -log-level=info
      -log-format=plain
      -enable-endpoint-slices=true
      -cluster-domain=cluster.local
      -identity-trust-domain=cluster.local
      -default-opaque-ports=25,587,3306,4444,5432,6379,9300,11211
      -enable-pprof=false
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 03 Sep 2024 16:25:38 +0200
      Finished:     Tue, 03 Sep 2024 16:25:38 +0200
    Ready:          False
    Restart Count:  9
    Liveness:       http-get http://:9996/ping delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:9996/ready delay=0s timeout=1s period=10s #success=1 #failure=7
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lvt6m (ro)
  sp-validator:
    Container ID:    containerd://35c2790f1d12978dc1c663f29cd849f10ac7952958d7d47c06e6fa923c64667f
    Image:           cr.l5d.io/linkerd/controller:edge-24.2.4
    Image ID:        cr.l5d.io/linkerd/controller@sha256:ea5a052b31d84718d82aa67a0b37d7115965f1058a133e7bb5532a25116879ce
    Ports:           8443/TCP, 9997/TCP
    Host Ports:      0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      sp-validator
      -log-level=info
      -log-format=plain
      -enable-pprof=false
    State:          Running
      Started:      Tue, 03 Sep 2024 16:04:39 +0200
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:9997/ping delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:9997/ready delay=0s timeout=1s period=10s #success=1 #failure=7
    Environment:    <none>
    Mounts:
      /var/run/linkerd/tls from sp-tls (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lvt6m (ro)
  policy:
    Container ID:    containerd://370ea52b5f3b5b9d911cb01cb9dec2d14f4ef60bcfe86028b02aebc26bc636f0
    Image:           cr.l5d.io/linkerd/policy-controller:edge-24.2.4
    Image ID:        cr.l5d.io/linkerd/policy-controller@sha256:d5ef1a4437ae20ab3942fce17590ac4c5932b6c93852a5997070d1b45f87097d
    Ports:           8090/TCP, 9990/TCP, 9443/TCP
    Host Ports:      0/TCP, 0/TCP, 0/TCP
    SeccompProfile:  RuntimeDefault
    Args:
      --admin-addr=0.0.0.0:9990
      --control-plane-namespace=linkerd
      --grpc-addr=0.0.0.0:8090
      --server-addr=0.0.0.0:9443
      --server-tls-key=/var/run/linkerd/tls/tls.key
      --server-tls-certs=/var/run/linkerd/tls/tls.crt
      --cluster-networks=10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
      --identity-domain=cluster.local
      --cluster-domain=cluster.local
      --default-policy=all-unauthenticated
      --log-level=info
      --log-format=plain
      --default-opaque-ports=25,587,3306,4444,5432,6379,9300,11211
      --probe-networks=0.0.0.0/0
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 03 Sep 2024 16:25:38 +0200
      Finished:     Tue, 03 Sep 2024 16:25:38 +0200
    Ready:          False
    Restart Count:  9
    Liveness:       http-get http://:admin-http/live delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:      http-get http://:admin-http/ready delay=10s timeout=1s period=10s #success=1 #failure=7
    Environment:    <none>
    Mounts:
      /var/run/linkerd/tls from policy-tls (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lvt6m (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  sp-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  linkerd-sp-validator-k8s-tls
    Optional:    false
  policy-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  linkerd-policy-validator-k8s-tls
    Optional:    false
  linkerd-proxy-init-xtables-lock:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  linkerd-identity-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  linkerd-identity-end-entity:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  kube-api-access-lvt6m:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  23m                    default-scheduler  Successfully assigned linkerd/linkerd-destination-9f9678b9d-9w9mk to colima-dev
  Normal   Pulled     23m                    kubelet            Container image "cr.l5d.io/linkerd/proxy-init:v2.2.4" already present on machine
  Normal   Created    23m                    kubelet            Created container linkerd-init
  Normal   Started    23m                    kubelet            Started container linkerd-init
  Normal   Pulled     23m                    kubelet            Container image "cr.l5d.io/linkerd/proxy:edge-24.2.4" already present on machine
  Normal   Created    23m                    kubelet            Created container linkerd-proxy
  Normal   Started    22m                    kubelet            Started container linkerd-proxy
  Normal   Created    22m (x2 over 22m)      kubelet            Created container destination
  Normal   Pulled     22m (x2 over 22m)      kubelet            Container image "cr.l5d.io/linkerd/controller:edge-24.2.4" already present on machine
  Normal   Pulled     22m                    kubelet            Container image "cr.l5d.io/linkerd/controller:edge-24.2.4" already present on machine
  Normal   Created    22m                    kubelet            Created container sp-validator
  Normal   Started    22m                    kubelet            Started container sp-validator
  Normal   Started    22m (x2 over 22m)      kubelet            Started container destination
  Normal   Pulled     22m (x2 over 22m)      kubelet            Container image "cr.l5d.io/linkerd/policy-controller:edge-24.2.4" already present on machine
  Normal   Created    22m (x2 over 22m)      kubelet            Created container policy
  Normal   Started    22m (x2 over 22m)      kubelet            Started container policy
  Warning  BackOff    22m (x2 over 22m)      kubelet            Back-off restarting failed container policy in pod linkerd-destination-9f9678b9d-9w9mk_linkerd(8fd453e7-4177-4411-bdc9-2cd4c4b06d8b)
  Warning  BackOff    2m49s (x109 over 22m)  kubelet            Back-off restarting failed container destination in pod linkerd-destination-9f9678b9d-9w9mk_linkerd(8fd453e7-4177-4411-bdc9-2cd4c4b06d8b)
```

### output of `linkerd check -o short`

linkerd-existence
-----------------
× control plane pods are ready
    pod/linkerd-destination-66888c7597-z9l2s container policy is not ready
    see https://linkerd.io/2.14/checks/#l5d-api-control-ready for hints

Status check results are ×

### Environment

kubernetes version: v1.28 (k3s)
helm chart appVersion: edge-24.2.4

### Would you like to work on fixing this bug?

yes
