### ISSUE TITLE
ability to set automountServiceAccountToken to false

### ISSUE THREAD

**Issue by EliranTurgeman** [linkerd/linkerd2#13108]
### What problem are you trying to solve?

To Meet Security Standards for not automatically mounting service accounts
for be compliance in Gov Clouds 

### How should the problem be solved?

Helm Chart should by default, set automountServiceAccountToken to true for all Linkerd Pods (to not change the current behavior)
but will have the option to change it to "false"

### Any alternatives you've considered?

None; its part of compliance tasks 
https://learn.microsoft.com/en-us/azure/governance/policy/samples/built-in-policies
https://www.azadvertizer.net/azpolicyadvertizer/kubernetes_block-automount-token.html

### How would users interact with this feature?

Set it to true in the helm chart for LInkerd in order to harden the security of the cluster to

### Would you like to work on this feature?

maybe

**Comment by alpeb** [comment]
The pod's in linkerd's control plane require that token in order to connect to the kube-api, as do the proxies in the data plane in order to bootstrap their identity. If mounting those is disabled, I understand they could be mounted manually, but how would you get them? Retrieving them from the SA's secrets? Can you clarify what would the process be and what's the benefit of doing that manually? Wouldn't this be applicable only for those cases where the token is not used?

**Comment by EliranTurgeman** [comment]
The main reason we want this feature is to mount the same staff that auto mount needed, so the behavior will remain 

This will help in terms of security, since the mounting are explicitly set and its help to avoid any malicious attacks by this section 

As said before the want to be in compliance with some FedRamp regulations and this is one of them

**Comment by olix0r** [comment]
Can you elaborate on what you mean by:

> Note: That the service account token can be mounted manually as a volume

Are you asking that the Linkerd helm charts do this? If so, would it make sense to simply always use a [projected volume](https://kubernetes.io/docs/concepts/storage/projected-volumes/#serviceaccounttoken) without adding new configuration?

Or are you suggesting that the helm chart should leave control plane components with no kube api token and you'd like to handle volume mounting yourself?

**Comment by Aransh** [comment]
@olix0r the standard approach we've seen with other charts is to allow disabling automountServiceAccountToken, and allow adding additional volumes and volumeMounts, and by that add a projected volume for the service account token.

This basically has the same exact outcome, but for government cloud compliance purposes, this would pass validation as it's more explicit ("This pod needs Kube API access to function, so it is supplied directly", as opposed to "This pod has Kube API access coincidentally as this is default behavior, leaving it potentially vulnerable").

Example:
 ```
 automountServiceAccountToken: false
 volumes:
  - name: kube-api-access
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
  volumeMounts:
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
    name: kube-api-access
    readOnly: true
```
