### ISSUE TITLE
HTTPRoute Weight Not Honored for Pod-to-Pod Communication via ClusterIP Service

### ISSUE THREAD

**Issue by Manikkumar1988** [linkerd/linkerd2#13238]
### What is the issue?

In minikube with latest linkerd installed, 

Expectation is
HTTPRoute - should honour the weightage when routing the traffic to desired service for the communication happening through ClusterIP type Service.

Actual is
HTTPRoute - doesn't honour the weightage when routing the traffic to desired service. Its alway directing to the non-desired service. Even when weightage of desired service has 100% while the other has 0%

### How can it be reproduced?

1. Create a Namespace and Label it for Linkerd Injection
```
kubectl create namespace test-app
kubectl annotate namespace test-app linkerd.io/inject=enabled
```
2. Create two deployments and expose it by service of clusterIP type. 
`sample-app-v1.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v1
  namespace: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      version: v1
  template:
    metadata:
      labels:
        app: sample-app
        version: v1
    spec:
      containers:
        - name: http-app
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from v1"
          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-v1
  namespace: test-app
spec:
  selector:
    app: sample-app
    version: v1
  ports:
    - port: 80
      targetPort: 5678
```

`sample-app-v2.yaml`
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-v2
  namespace: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
      version: v2
  template:
    metadata:
      labels:
        app: sample-app
        version: v2
    spec:
      containers:
        - name: http-app
          image: hashicorp/http-echo:latest
          args:
            - "-text=Hello from v2"
          ports:
            - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  name: sample-app-v2
  namespace: test-app
spec:
  selector:
    app: sample-app
    version: v2
  ports:
    - port: 80
      targetPort: 5678
```

3. Create one HTTPRoute with two backends(v2 service & v1 service) and one parentRef(v1 service) and set value of weight for the v2 service as 100%. 
`route.yaml`
```
apiVersion: policy.linkerd.io/v1beta2
kind: HTTPRoute
metadata:
  name: bb-route
  namespace: test-app
spec:
  parentRefs:
    - name: sample-app-v1
      kind: Service
      group: core
      port: 80
  rules:
    - backendRefs:
      - name: sample-app-v1
        port: 80
        weight: 0
      - name: sample-app-v2
        port: 80
        weight: 100
```

4. Run a nginx pod  
`kubectl run my-pod --image=nginx -n test-app`

5. Run curl request to v1 service. 
`kubectl exec -it -n test-app my-pod -c my-pod -- curl -s -o - sample-app-v1`

Expected:
`Hello from v2`

Actual:
`Hello from v1`

### Logs, error output, etc

Expected:
`Hello from v2`

Actual:
`Hello from v1`

### output of `linkerd check -o short`

<img width="498" alt="image" src="https://github.com/user-attachments/assets/f087baa1-e7ac-48d2-a2c4-529b40af1d33">

### Environment

Kubernetes Version:
  Client Version: v1.30.2
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.30.0

Cluster Version: 
minikube version: v1.33.1
commit: 5883c09216182566a63dff4c326a6fc9ed2982ff

Host OS: 
Mac Sonoma 14.5

Linkerd Version: 
  Client version: edge-24.10.4
  Server version: edge-24.10.4

### Would you like to work on fixing this bug?

maybe
