### ISSUE TITLE
Able to reach services via IP but not hostname

### ISSUE THREAD

**Issue by andzdroid** [linkerd/linkerd2#1405]
Client version: v18.7.3
Server version: v18.7.3

A pod injected with linkerd2 is not able to reach any kubernetes services via hostname. Making a request directly via service IP is fine.

```
/tmp # wget 10.97.0.127/_ready
Connecting to 10.97.0.127 (10.97.0.127:80)
/tmp # ls
_ready
/tmp # cat _ready
OK
/tmp # rm _ready
/tmp # wget arsenal/_ready
Connecting to arsenal (10.97.0.127:80)
^C
/tmp # ls
```

nslookup gives the correct result, and the hostname resolves to the correct IP, but the request hangs indefinitely.

A regular pod without linkerd2 injected is able to reach other services, even services that are running with the linkerd2 proxy. So it seems it's only an issue with outgoing requests from injected pods.

**Comment by klingerf** [comment]
@andzdroid Thanks for reporting this. Can you paste the logs from the `linkerd-proxy` container in one of your affected pods? Hopefully there's something in the log that will clue us into what's happening.

**Comment by andzdroid** [comment]
```
INFO linkerd2_proxy using controller at Some(HostAndPort { host: DnsName(DnsName(DNSName("proxy-api.linkerd.svc.cluster.local"))), port: 8086 })
INFO linkerd2_proxy routing on V4(127.0.0.1:4140)
INFO linkerd2_proxy proxying on V4(0.0.0.0:4143) to None
INFO linkerd2_proxy serving Prometheus metrics on V4(0.0.0.0:4191)
INFO linkerd2_proxy protocol detection disabled for inbound ports {25, 3306}
INFO linkerd2_proxy protocol detection disabled for outbound ports {25, 3306}
INFO admin={bg=resolver} linkerd2_proxy::transport::connect DNS resolved DnsName(DnsName(DNSName("proxy-api.linkerd.svc.cluster.local"))) to 10.97.8.132
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.36.2.17:55184} linkerd2_proxy turning operation timed out after 10s into 500
ERR! proxy={server=out listen=127.0.0.1:4140 remote=10.36.2.17:55726} linkerd2_proxy turning operation timed out after 10s into 500
```

I get this on a fresh gke cluster, with 2 services and 1 pod in each service. It happens in both pods trying to reach each other by the service's hostname.

**Comment by andzdroid** [comment]
I installed the emojivoto demo onto the cluster and everything's fine there.
All of the entries in my namespace's 'authorities' have IPs, and there is one authority for each pod. But comparing to the emojivoto namespace, there is only one authority for each service, and they are listed as hostnames. Could this be related?

**Comment by andzdroid** [comment]
I think I figured out the issue.

This is what my service looked like:

```
apiVersion: v1
kind: Service
metadata:
  name: arsenal
  namespace: live
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: arsenal
```

Either changing the targetPort to be a number or adding `name: http` to the port will fix the problem.

**Comment by hawkw** [comment]
I can confirm I've reproduced this issue with a fairly simple configuration:
<details>
<summary>Repro YAML</summary>
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: http
  selector:
    app: nginx-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx:1.13.12
        name: nginx-app
        ports:
        - containerPort: 80
          name: http
```
</details>

Noting that the only timeout in the proxy that's set to 10 seconds by default is the bind timeout, which usually occurs when the Destination service doesn't give the proxy an endpoint for a destination, I checked the logs from the Destination service. I saw the following:
```
time="2018-08-07T22:33:24Z" level=info msg="Establishing watch on endpoint nginx-app.default:80"
time="2018-08-07T22:33:24Z" level=error msg="Port http not found"
time="2018-08-07T22:33:48Z" level=error msg="Port http not found"
time="2018-08-07T22:36:14Z" level=info msg="Stopping watch on endpoint nginx-app.default:80"
```
It looks like the "Port ... not found" message is logged here: https://github.com/linkerd/linkerd2/blob/f738d7c3b91809c809a9d7aaeeaec8956fabaa39/controller/destination/endpoints_watcher.go#L414-L425
