### ISSUE TITLE
admission webhook "linkerd-policy-validator.linkerd.io" denied the request: unsupported authentication kind(s): NetworkAuthentication

### ISSUE THREAD

**Issue by matt-mercer** [linkerd/linkerd2#14127]
### What is the issue?

Creating a basic policy with NetworkAuthentication is denied by the policy controller.

but when applying via Helm, I receive the error:

```text
UPGRADE FAILED: failed to create resource: admission webhook "linkerd-policy-validator.linkerd.io" denied the request: unsupported authentication kind(s): NetworkAuthentication
```

I have the following the policy resources below

```yaml

apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  namespace: {{ $.Release.Namespace }}
  name: myapp-ingress
spec:
  podSelector:
    matchLabels:
      "app.kubernetes.io/name": myapp
  port: 3000
---
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: public-alb-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  networks:
    - cidr: 172.11.0.0/20
    - cidr: 172.11.16.0/20
    - cidr: 172.11.32.0/20
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: myapp-ingress
  namespace: {{ $.Release.Namespace }}
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: myapp-ingress
  requiredAuthenticationRefs:
    - name: public-alb-ingress
      kind: NetworkAuthentication
      namespace: {{ $.Release.Namespace }}


```

### How can it be reproduced?

run:
```shell
kubectl create namespace ingress-test

kubectl create -f - <<EOF
apiVersion: policy.linkerd.io/v1beta3
kind: Server
metadata:
  namespace: ingress-test
  name: myapp-ingress
spec:
  podSelector:
    matchLabels:
      "app.kubernetes.io/name": myapp
  port: 3000
---
apiVersion: policy.linkerd.io/v1alpha1
kind: NetworkAuthentication
metadata:
  name: public-alb-ingress
  namespace: ingress-test
spec:
  networks:
    - cidr: 172.11.0.0/20
    - cidr: 172.11.16.0/20
    - cidr: 172.11.32.0/20
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: myapp-ingress
  namespace: ingress-test
spec:
  targetRef:
    group: policy.linkerd.io
    kind: Server
    name: myapp-ingress
  requiredAuthenticationRefs:
    - name: public-alb-ingress
      kind: NetworkAuthentication
      namespace: ingress-test
EOF
```

### Logs, error output, etc

from kubectl 
```text
admission webhook "linkerd-policy-validator.linkerd.io" denied the request: unsupported authentication kind(s): NetworkAuthentication
```

from policy controller logs
```text
2025-06-12T13:15:17.702650Z  INFO server{port=9443}:conn{client.ip=172.11.207.42 client.port=36322}: linkerd_policy_controller_runtime::admission: Denied error=unsupported authentication kind(s): NetworkAuthentication ns=ingress-test name=myapp-ingress kind=AuthorizationPolicy
```

### output of `linkerd check -o short`

```text
Status check results are √
```

### Environment

- Kubernetes Version: 1.33
- Cluster Environment: AWS EKS
- Host OS:  Bottlerocket
- Linkerd version:  edge-25.6.1

### Possible solution

unknown

### Additional context

control plane helm config:

```yaml

linkerd-control-plane:
  disableHeartBeat: true
  clusterNetworks: "10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16,fd00::/8,172.11.160.0/20,172.11.192.0/20"
  proxy:
    nativeSidecar: true
    metrics:
      hostnameLabels: true
    defaultInboundPolicy: audit
```

### Would you like to work on fixing this bug?

None
