### ISSUE TITLE
Missing Per-Route Metrics After Migrating to GRPCRoute

### ISSUE THREAD

**Issue by Lowsplix** [linkerd/linkerd2#14167]
### What is the issue?

We recently migrated from ServiceProfile to Gateway API resources (specifically GRPCRoute). Since our observability heavily depends on the route_request_total and route_response_total metrics from linkerd-proxy, we expected equivalent per-route metrics to be emitted under the new configuration.

However, after migrating to the following GRPCRoute definition:
```
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: time-service
  namespace: default
spec:
  parentRefs:
    - name: time-service
      group: ""
      kind: Service
      port: 9090
  rules:
    - matches:
        - method:
            service: smpl.api.time.v1.TimeService
            method: GetCurrentTime
            type: Exact
      backendRefs:
        - kind: Service
          name: time-service
          port: 9090
```
The per-route metrics (route_request_total, route_response_total) are no longer being generated.

This worked as expected under the previous ServiceProfile configuration:
```
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: time-service.default.svc.cluster.local
  namespace: default
spec:
  routes:
    - name: GetCurrentTime
      condition:
        method: POST
        pathRegex: /smpl\.api.time\.v1\.TimeService/GetCurrentTime
```
Retries, timeouts, and routing function correctly under the new configuration — the issue is solely with missing per-route metrics from the proxy.
Faced this in versions: edge-2025.06.01, edge-2025.01.01

### How can it be reproduced?

the issue can be consistently reproduced using this minimal github repo:
https://github.com/Lowsplix/linkerd-route-metrics-repro/tree/main

To reproduce:
- Clone the repo.
- Run `task setup` to deploy the environment.
- Observe the metrics from the linkerd-proxy containers in the time-client and time-service pods.

per-route metrics like route_request_total will be missing when using GRPCRoute.

### Logs, error output, etc

No response.

### output of `linkerd check -o short`

`Status check results are √`

### Environment

- Present in both local (k3d/k3s) cluster and in production (GKE)
```
k3d version v5.8.3
k3s version v1.31.5-k3s1 (default)
```

### Possible solution

No response.

### Additional context

No response.

### Would you like to work on fixing this bug?

None
