### ISSUE TITLE
Add pre-install check to validate that user has permissions to install linkerd

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1472]
We should add an additional pre-install check (depends on #1470) to validate that the user has the right permissions to install linkerd. Based on the current linkerd install, the user must be able to create

* namespaces
* serviceaccounts
* clusterroles
* clusterrolebindings
* services
* deployments
* configmaps

**Comment by rmars** [comment]
From @grampelberg: there's a `kubectl` `cani` that we maybe can use.

**Comment by adleong** [comment]
This seems tricky because we want to check that the user has permission to create resources in the control plane namespace, but that namespace doesn't exist at check time.  So what we *really* want to check is: "Can the user create these resources in namespaces that they create".  I'm not sure if that is expressible.

Would it be sufficient to just check that the user is allowed to create namespaces?  Is there any scenario where a users is allowed to create a namespace, but not allowed to create resources in that namespace?

**Comment by grampelberg** [comment]
@adleong I think that `kubectl auth can-i` takes care of all this for us? It is working for me (fwiw).

**Comment by adleong** [comment]
`can-i` takes a `-n` namespace flag but the control plane namespace doesn't exist yet.

**Comment by grampelberg** [comment]
Yeah, but it works for non-existent namespaces for me 🤷‍♂️

**Comment by adleong** [comment]
Probably because you have permissions to create those objects in any namespace.  Presumably a user might only have permissions to create resources in certain namespaces?  

Am I overthinking this?

**Comment by grampelberg** [comment]
Well, you've successfully nerd sniped me at the bare minimum. I've created the following service account (with accompanying roles and bindings):

```yaml
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: only-ns
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: only-ns
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: only-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: only-ns
subjects:
  - kind: ServiceAccount
    name: only-ns
    namespace: default
---
```

And testing `can-i`:

```bash
➜  kubectl --as=system:serviceaccount:default:only-ns auth can-i create ns -n linkerd
yes
➜  kubectl --as=system:serviceaccount:default:only-ns auth can-i create pods -n linkerd
no - Unknown user "system:serviceaccount:default:only-ns"
```
