### ISSUE TITLE
Disconnected installation Documentation and notes

### ISSUE THREAD

**Issue by wadeholler** [linkerd/linkerd2#1532]
# linkerd2 disconnected installation notes

1. Download and install linkerd2, add to PATH
2. get images via `linkerd install` and upload to private registry
3. customize image location in linkerd install output

    registry=registry.mydomain.com\/ ; linkerd install  | sed 's|image:\ |image:\ '"$registry"'|g' | kubectl apply -f -

4. Internal Load Balancer
   
If you are following this guide you probably need internal only load balancers.  Therefore, if following the emojivoto example
make sure to use the internal annotaion for your cloud.  AWS example:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
  namespace: emojivoto
spec:
  type: LoadBalancer
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 80
```
