### ISSUE TITLE
Having install issue with Linkerd 2.0 on OpenShift

### ISSUE THREAD

**Issue by mhausenblas** [linkerd/linkerd2#1655]
To reproduce my install issue, please use this [Katacoda scenario](https://www.katacoda.com/mhausenblas/scenarios/linkerd2-openshift).  It seems like the pod security contexts need to be aligned with OpenShift's security context constraints. Certain caps are not set or allowed. I could monkey patch as I did with stuff in previous steps but I think a dedicated version might be more sustainable?

CC: @grampelberg

**Comment by kinash000** [comment]
oc adm policy add-scc-to-user privileged -z linkerd-controller -n linkerd 
oc adm policy add-scc-to-user privileged -z linkerd-prometheus -n linkerd

**Comment by grampelberg** [comment]
Awesome, I'll open an issue to get that added to the docs!

**Comment by lostiniceland** [comment]
Having the same problem. Executing the provided commands works for controller and prometheus, but the grafana pod is not starting. I tried adjusting the command to grafana, since the error message is the same, but without any luck.

**Comment by grampelberg** [comment]
@lostiniceland there's probably a more specific policy that we can use. I went down the podsecuritypolicy hole last week. If there was a SCC YAML we could add to the docs, that would be ideal ... I just don't have an openshift cluster around to play with right now.

**Comment by mhausenblas** [comment]
@grampelberg https://learn.openshift.com/playgrounds/ :P

**Comment by mshutt** [comment]
Here is what I am working with... It's restricted + NET_ADMIN...  and I just change the uid from 2102 to something in the valid range for the namespace.

We are going to test more tomorrow to see if this is an approach that will work.

THAT SAID, I am still quite reticent to give out cap NET_ADMIN to any individual user who is sharing a cluster with other projects, other business units, and other applications...  It's clearly not "all about the multitenancy"

```
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: false
allowedCapabilities: null
apiVersion: security.openshift.io/v1
defaultAddCapabilities: ['NET_ADMIN']
fsGroup:
  type: MustRunAs
groups:
- system:authenticated
kind: SecurityContextConstraints
metadata:
  annotations:
  name: linkerd2
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
- configMap
- downwardAPI
- emptyDir
- persistentVolumeClaim
- projected
- secret
```
