### ISSUE TITLE
NATS support

### ISSUE THREAD

**Issue by kfreiman** [linkerd/linkerd2#1715]
Does linkerd2 supports NATS?
If deployment or NATS is meshed, i have error `read tcp 192.168.1.90:39822->10.109.101.184:4222: i/o timeout`. I tryed standalone deployment of nats like this
```yml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name:  nats
        image: nats:1.3.0
        imagePullPolicy: Always
        ports:
        - containerPort: 4222
          protocol: TCP
        - containerPort: 8222
          protocol: TCP
```
and cluster, based on [nats-operator](https://github.com/nats-io/nats-operator). In both cases conection is works without linkerd injection.

My go code looks like
```go
import (
	"log"
	"github.com/nats-io/go-nats"
)

uri := "nats://nats:4222"
conn, err := nats.Connect(uri)
if err != nil {
  log.Fatal(err)
}
```
