### ISSUE TITLE
Adjust controller and proxy livenessProbe and readinessProbe

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#1804]
The values for `livenessProbe` and `readinessProbe` set by `linkerd install` and `linkerd inject` are more permissive than Kubernetes defaults. While this increases the likelihood all pods will come up healthy without pod restart, it also increases startup time, and may paper over other issues related to slow startup.

## Default probe values

```yaml
livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3
```

### grafana

```yaml
readinessProbe:
  failureThreshold: 10
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 30
```

### prometheus

```yaml
livenessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 30
readinessProbe:
  initialDelaySeconds: 30
  timeoutSeconds: 30
```

### public-api, destination, proxy-api, tap

```yaml
livenessProbe:
  initialDelaySeconds: 10
readinessProbe:
  failureThreshold: 7
```

### proxy
```yaml
livenessProbe:
  initialDelaySeconds: 10
readinessProbe:
  initialDelaySeconds: 10
```

## Proposal

Set `failureThreshold: 10` on all controller and proxy pods, use Kubernetes defaults for all other settings. This should decrease time to readiness, while still permitting 100 seconds for pods to come up.

```yaml
livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
```
