### ISSUE TITLE
Support an annotation that prevents a resource from being injected

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#1820]
When injecting a set of resources, it may be desirable to opt out of certain resources (for instances, short-lived Jobs). The injector should be able to ignore certain resources. Perhaps a new, dedicated annotation that causes resources to be ignored by injectors.

**Comment by klingerf** [comment]
Heya @ffd2subroutine, right now the project has two injection code paths (#1748 tracks standardizing them to use the same code path). But in the meantime, here are the two implementations.

* CLI / [cli/cmd/inject.go](https://github.com/linkerd/linkerd2/blob/master/cli/cmd/inject.go)
* Auto-injection / [controller/proxy-injector/webhook.go](https://github.com/linkerd/linkerd2/blob/master/controller/proxy-injector/webhook.go)

Both implementations already address a few instances where we skip injecting a resource, e.g. when the pod spec already has a known proxy sidecar, here:

https://github.com/linkerd/linkerd2/blob/557dca5a56299eb2bb5f31269938816cf7c737ff/cli/cmd/inject.go#L177-L184

And here:

https://github.com/linkerd/linkerd2/blob/557dca5a56299eb2bb5f31269938816cf7c737ff/controller/proxy-injector/webhook.go#L205-L216

So if we add a new convention for bypassing injection, we'd want to update both code paths.

It's also worth noting that the auto-inject code path already has a convention for bypassing injection if the `linkerd.io/auto-inject: disabled` label is present on the target resource's namespace. I'd expect the label that we use to fix this issue to work similarly.

**Comment by alenkacz** [comment]
@klingerf so ultimately the ignored resource type will be also specified as a label on the resource's namespace?

**Comment by ffd2subroutine** [comment]
heya @klingerf, thanks for this great explanation but sorry I've been really busy lately. If someone else wants to work on this one, please do!

**Comment by klingerf** [comment]
@ffd2subroutine No worries! Can definitely understand being busy this time of year.

@alenkacz I'm thinking that the label would go on the object that contains the pod spec that we don't want to inject. So for instance, if I wanted to configure this [example Job from the Kubernetes docs](https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#running-an-example-job) to not be injected, I could define it like this:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  labels:
    linkerd.io/inject: disabled
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

**Comment by grampelberg** [comment]
@klingerf I was thinking about getting it on the pod spec itself. What do you think?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: pi

spec:
  template:
    metadata:
      labels:
        linkerd.io/inject: disabled
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

**Comment by klingerf** [comment]
@grampelberg That works for me -- fewer places to check is always better :)

**Comment by alenkacz** [comment]
@grampelberg @klingerf what do you guys think about unifying auto-inject and inject? We would have just `inject` on any resource level (deployment, pod, namespace). Right now we would be having `auto-inject` as well as `inject` and to me those two seems like the same thing...

**Comment by petr-k** [comment]
Just to chime in, I believe that flagging a `Pod` as not to be subject to injection should be modeled using _annotations_ instead of _labels_.

Citing the [Kubernetes docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/):
> You can use either labels or annotations to attach metadata to Kubernetes objects. Labels can be used to select objects and to find collections of objects that satisfy certain conditions. In contrast, annotations are not used to identify and select objects.

Expanding on the previous example, it would read:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: pi

spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
```

More explanation here, for example: [Labels and Annotations in Kubernetes](https://vsupalov.com/kubernetes-labels-annotations-difference/)
