### ISSUE TITLE
Named targedPort in Service not working

### ISSUE THREAD

**Issue by tsupertramp** [linkerd/linkerd2#1853]
### What is the issue?
During research with @kforsthoevel on linkerd2, we could not get it working on our aws / kops cluster. The problem seems to be lying in ClusterIp services where the targetPort is a named Port and not an integer. We added two configs which only differ in targetPort definition.

### How can it be reproduced?
Working Example:
```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linkerd-debugging-receive
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: linkerd-debugging-receive
    spec:
      containers:
        - name: hello
          image: tutum/hello-world
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-debugging-receive
  labels:
    name: linkerd-debugging-receive
spec:
  type: ClusterIP
  ports:
    - name: svc
      port: 8080
      targetPort: 80
  selector:
    name: linkerd-debugging-receive
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linkerd-debugging-sent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: linkerd-debugging-sent
    spec:
      containers:
        - name: alpine
          image: alpine
          command:
            - "/bin/ash"
            - "-c"
            - "while true; do wget -qO- http://linkerd-debugging-receive:8080;sleep 0.5;done"
          imagePullPolicy: Always
```

Not Working Example:
```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linkerd-debugging-receive
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: linkerd-debugging-receive
    spec:
      containers:
        - name: hello
          image: tutum/hello-world
          imagePullPolicy: Always
          ports:
            - name: app
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-debugging-receive
  labels:
    name: linkerd-debugging-receive
spec:
  type: ClusterIP
  ports:
    - name: svc
      port: 8080
      targetPort: app
  selector:
    name: linkerd-debugging-receive
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: linkerd-debugging-sent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: linkerd-debugging-sent
    spec:
      containers:
        - name: alpine
          image: alpine
          command:
            - "/bin/ash"
            - "-c"
            - "while true; do wget -qO- http://linkerd-debugging-receive:8080;sleep 0.5;done"
          imagePullPolicy: Always
```

### Logs, error output, etc

Logs in linkerd2 proxy of linkerd-debugging-sent container:
```wget: server returned error: HTTP/1.1 500 Internal Server Error```

#### `linkerd check` output

```text
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[ok]
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[ok]
linkerd-version: control plane is up-to-date...............................[ok]

Status check results are [ok]
```

### Environment

- Kubernetes Version: 1.10.x
- Cluster Environment: AWS + KOPS
- Host OS: Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64    docker://17.3.2
- Linkerd version:
```
Client version: stable-2.0.0
Server version: stable-2.0.0
```

### Possible solution
It seems that a named targetPort can not be evaluated.
