### ISSUE TITLE
Service profile route regex is confusing

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1874]
### What problem are you trying to solve?

I'm writing a tutorial for using service profiles with emojivoto as the example. Using the `web` service, I created the following profile:

```yaml
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: web-svc.emojivoto.svc.cluster.local
  namespace: linkerd
spec:
  routes:
  - name: '/'
    condition:
      path: '/'
      method: GET
  - name: '/leaderboard'
    condition:
      path: '/leaderboard'
      method: GET
  - name: '/api/list'
    condition:
      path: '/api/list'
      method: GET
  - name: '/api/vote'
    condition:
      path: '/api/vote'
      method: GET
  - name: '/api/leaderboard'
    condition:
      path: '/api/leaderboard'
      method: GET
```

Applying this to my cluster resulted in the following:

```bash
$ bin/go-run cli -n emojivoto routes web-svc
    ROUTE   SUCCESS      RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TLS
        /    85.59%   2.0rps           6ms          10ms          10ms    0%
[UNKNOWN]     0.00%   0.0rps           0ms           0ms           0ms    0%
```

I expected to see my other routes, in particular the `/api/list` and `/api/vote` ones. 

### How should the problem be solved?

Add an optional field to `condition` that says whether the route is an exact match or not. Default that to `true`.

```yaml
  - name: '/'
    condition:
      path: '/'
      method: GET
  - name: '/api/list'
    condition:
      path: 'list$'
      method: GET
      exact: false
```

### Any alternatives you've considered?

- Leave it the way it is and explain via documentation. This, honestly, isn't an awful solution. I do think there should be more debugging tooling in place for this solution to be usable. Even something that says partial and full match so that I know to look elsewhere.
- Make `path` always be a complete match. I can come up with some theoretical downsides to this. The primary one is that it is nice to have catch-alls ordered at the bottom. `[UNKNOWN]` is there right now, but I might want multiple catch-alls for certain paths. It is also nice to do right matching instead of left (eg `foo$`).

**Comment by adleong** [comment]
One thing to watch out for is that in the above examples `path` and `method` have an explicit `AND` combining them.  Adding an `exact` field would work differently... it would be a modifier on the path field.  So it probably need to be a subfield on the path object?

```
method: GET
path:
  regex: 'list$'
  exact: false
```
