### ISSUE TITLE
Remove namespace definition from `--single-namespace`

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1889]
### What is the issue?

When using `--single-namespace`, the namespace definition shows up:

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd
```

While this makes sense for global installs, in the `--single-namespace` world, it requires extra permissions (assuming it was created, patch). That's not great! It should just be removed from the install output.
