### ISSUE TITLE
RBAC issues with service profiles

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1890]
### What problem are you trying to solve?

With the introduction of service profiles, the required RBAC for installing linkerd has grown larger. In particular, these two definitions are troublesome:

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-linkerd-controller
  namespace: linkerd
rules:
- apiGroups: ["linkerd.io"]
  resources: ["serviceprofiles"]
  verbs: ["list", "get", "watch"]

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: serviceprofiles.linkerd.io
  namespace: linkerd
  annotations:
    linkerd.io/created-by: linkerd/cli edge-18.11.2
spec:
  group: linkerd.io
  version: v1alpha1
  scope: Namespaced
  names:
    plural: serviceprofiles
    singular: serviceprofile
    kind: ServiceProfile
    shortNames:
    - sp
```

### How should the problem be solved?

It would be nice to have an `--exclude-service-profile` option for `install`. These should be default, but optionally be disabled.

### Any alternatives you've considered?

This feels like moving further down the addon path. Adding more and more options to `install` is starting to feel like it is going to require some in-depth understanding to know which options to use. These should *definitely* be on by default, but maybe a better option would be to allow users to list which addons they'd like to install, perhaps:

```bash
linkerd install --addons=grafana,serviceprofile,inject
```

These could also be added post install via:

```bash
linkerd addon serviceprofile
```
