### ISSUE TITLE
Add anti-afinity settings for controller pod when `--ha` flag is present

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#1895]
In order to ensure that the control plane is HA, we need a way to guarantee that a node failure will not remove all replicas of Linkerd's `controller` deployment. We can accomplish by adding `affinity` settings to the pod spec when the `--ha` flag is specified at install time. More info about that here:

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#never-co-located-in-the-same-node

**Comment by grampelberg** [comment]
@klingerf what do you think about just putting affinity in there by default? While it'll only be useful if you're running more than one replica, it shouldn't hurt in a non-HA setup and reduces the differences between the two.

**Comment by klingerf** [comment]
That could work for me, but I'm not all that familiar with affinity settings, and I don't fully understand the implications of "preferred" versus "required". It seems like making anti-affinity required is better for HA, but (I think) that would break single node clusters where `--controller-replicas` is set to something larger than 1.

**Comment by zknill** [comment]
There are a series of well known labels that are set on nodes automatically in cloudprovider environments;
https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

To my understanding the most useful ones here would be:
* `kubernetes.io/hostname`
* `failure-domain.beta.kubernetes.io/zone`

The first could be used to ensure controller replicas are not scheduled on the same node, and the second to spread controller replicas across availability zones.

It's hard to choose between the `required` and `preferred` affinity rules because it's not immediately obvious what setups the controllers would be run in, but could we pick one (perhaps `preferred`) and include it in `--ha`, then follow the example of `--ha` vs. `--controller-replicas` to allow setting the other.

At the moment, if you  `linkerd install --ha --controller-replicas 5` you'd get 5 replicas, even though `--ha` has a default of 3.

If we followed the same pattern, we could include _some_ affinity by default and allow another flag to change it? This way there are at least some sensible defaults

Something like:

* `--ha`: `preferred` affinity on hostname / zone
* `--ha --required-affinity`: `required` affinity on hostname / zone

**Comment by grampelberg** [comment]
I'm on board, `preferred` feels like the right default. Should be able to do it for both hostname and zone? Theoretically, with clusters in a single zone, the scheduler would just give up trying.

Adding another flag (`--required-affinity`) doesn't feel great, but it is the only option right now. This is definitely related to #2129, #452, #2029 and #2156.

**Comment by Pothulapati** [comment]
I'm willing to take this issue :)

**Comment by Pothulapati** [comment]
I'm working on this today. 

As I discussed with @grampelberg , We will be using **anti-affinity** here, as **The pod anti-affinity rule says that the pod prefers not to be scheduled onto a node if that node is already running a pod with a specified label** The label selector here would be **linkerd.io/control-plane-component: controller** . So, the flag would be `--required-anti-affinity`

We will also be not supporting the anti-affinity flag only with the `--controller-replicas` flag

For the topology keys, As @zknill commented, we have two important ones. We can have both of them to be specified. 

If the the anti-affinity is `required` i.e hard, We don't have to specify any weights, as the topologykey should not have any pod with the given label directly for the scheduler to choose it.

but if the requirement is `preffered` (the default), We have to specify weights to denote the significance of each constraint, and it will choose the node with the Highest Aggregated Weight. Are there any prorities for us between the two labels?

@ihcsim @alpeb

**Comment by alpeb** [comment]
> but if the requirement is `preffered` (the default), We have to specify weights to denote the significance of each constraint, and it will choose the node with the Highest Aggregated Weight. Are there any prorities for us between the two labels?

It seems to me weights don't matter in this case because both labels are dependent (if there's a match on hostname then there's a match on zone), so it's not like one is more important than the other.

**Comment by Pothulapati** [comment]
Hmm, Right. I was considering the case where only one label would be present. As its unlikely it happens, I'm giving both of them weights 100.

Alsom which, there are two ways to go when going with the required flag,

`requiredDuringSchedulingRequiredDuringExecution`, which means it will evict the pods from nodes that cease to satisfy the condition.
`requiredDuringSchedulingIgnoredDuringExecution`, once scheduled it wont consider the changes during execution. 

Which one would be best for us?

**Comment by ihcsim** [comment]
@Pothulapati Thanks for taking this on! A few questions:

> The label selector here would be linkerd.io/control-plane-component: controller

So is the idea to use `--require-anti-affinity` to ensure all the other control plane components (that use a different value for `linkerd.io/control-plane-component`) to not be scheduled on the same node or zone as the controller?

And the default for `--ha` is `preferred`?

[IIUC](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity), when working with `required` pod anti-affinity, it looks like the topology key is limited to just `kubernetes.io/hostname`. So even with `--require-anti-affinity`, zone will still end up being a _preferred_ anti-affinity.

> If the the anti-affinity is required i.e hard, We don't have to specify any weights

`requiredDuringSchedulingIgnoredDuringExecution` doesn't support `weight`.

> Are there any prorities for us between the two labels?... As its unlikely it happens, I'm giving both of them weights 100.

Are you thinking of something like this?
```
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: linkerd.io/control-plane-component
              operator: In
              values:
              - controller
          topologyKey: kubernetes.io/hostname
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: linkerd.io/control-plane-component
              operator: In
              values:
              - controller
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

You'll probably need to do some experimentation to determine the behaviour. But the priority is always to not schedule the next pod on a node that already has a controller pod, regardless of zone. Then if possible, put in it another zone. So sounds like more weight on host anti-affinity?

**Comment by ihcsim** [comment]
> requiredDuringSchedulingRequiredDuringExecution, which means it will evict the pods from nodes that cease to satisfy the condition.

Unless I missed it from the [docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#podantiaffinity-v1-core), I don't think `requiredDuringSchedulingRequiredDuringExecution` is a thing yet.

> It seems to me weights don't matter...

Ah.. right, I think I misunderstand its definition; weight is used to choose the preferred node from among those that already satisfy the `matchExpressions`, not deciding which anti-affinity rules are more important.

**Comment by Pothulapati** [comment]
> @Pothulapati Thanks for taking this on! A few questions:
> 
> > The label selector here would be linkerd.io/control-plane-component: controller
> 
> So is the idea to use `--require-anti-affinity` to ensure all the other control plane components (that use a different value for `linkerd.io/control-plane-component`) to not be scheduled on the same node or zone as the controller?
> 

My Initial Idea was to only maintain high availibility between replicas of a single controller component i.e controller, So, that other controller components can also run on a node along with the replica of the controller. If we choose high availibility btw all controller components (this will include replica's of `identity` and `controller`), then this would need 3 (controller replicas) + 3 (identity replicas) + 1 (grafana) + 1 (prometheus) + 2 (sp_validator, proxy_injector) nodes in the case case.

One optimisation in this case would be to only choose identity and controller components to be ha, as they are the only ones who have 3 replicas, but to maintain ha between them would also cost us 6 min nodes in the hard case.

The best way I'm thinking is to have ha btw replicas of `controller` deployment and ha btw replicas of `identity` separately. This can make one replica of controller and identity stay on a single node.


> And the default for `--ha` is `preferred`?
> 

Yes, Here the pods wont fail when the affinity dosent satisy.

> [IIUC](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#an-example-of-a-pod-that-uses-pod-affinity), when working with `required` pod anti-affinity, it looks like the topology key is limited to just `kubernetes.io/hostname`. So even with `--require-anti-affinity`, zone will still end up being a _preferred_ anti-affinity.
> 

Zone key should also be allowed, I see no reason why it should not be allowed? , as the `requiredDuringSchedulingIgnoredDuringExecution` is an array I tried it like this (for the controller component), and it did work as expected.
```
requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: linkerd.io/control-plane-component
                operator: In
                values:
                - controller
            topologyKey: kubernetes.io/hostname
          - labelSelector:
              matchExpressions:
              - key: linkerd.io/control-plane-component
                operator: In
                values:
                - controller
            topologyKey: failure-domain.beta.kubernetes.io/zone
```
> > If the the anti-affinity is required i.e hard, We don't have to specify any weights
> 
> `requiredDuringSchedulingIgnoredDuringExecution` doesn't support `weight`.
> 

Yes, Weights are required only in the `preferred` case.

> > Are there any prorities for us between the two labels?... As its unlikely it happens, I'm giving both of them weights 100.
> 
> Are you thinking of something like this?
> 
> ```
> spec:
>   affinity:
>     podAntiAffinity:
>       preferredDuringSchedulingIgnoredDuringExecution:
>       - weight: 100
>         podAffinityTerm:
>           labelSelector:
>             matchExpressions:
>             - key: linkerd.io/control-plane-component
>               operator: In
>               values:
>               - controller
>           topologyKey: kubernetes.io/hostname
>       - weight: 100
>         podAffinityTerm:
>           labelSelector:
>             matchExpressions:
>             - key: linkerd.io/control-plane-component
>               operator: In
>               values:
>               - controller
>           topologyKey: failure-domain.beta.kubernetes.io/zone
> ```
> 

Yes, this will the yaml in the preferred case for the controller.

> You'll probably need to do some experimentation to determine the behaviour. But the priority is always to not schedule the next pod on a node that already has a controller pod, regardless of zone. Then if possible, put in it another zone. So sounds like more weight on host anti-affinity?

Hmm True, I think zone will get a lesser priority here. I will do some experimentation and we can fix on the weights.
