### ISSUE TITLE
Update profile API to match k8s

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#1908]
### What problem are you trying to solve?

Right now, there is a name and path section for each route:

```yaml
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: web-svc.emojivoto.svc.cluster.local
  namespace: linkerd
spec:
  routes:
  - name: '/leaderboard'
    condition:
      path: '/leaderboard'
      method: GET
```

For most of my use cases, I just end up typing the name and path twice. 

### How should the problem be solved?

Instead of requiring name, it would be nice to match the k8s style a little bit more:

```yaml
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: web-svc.emojivoto.svc.cluster.local
  namespace: linkerd
spec:
  routes:
  - labels:
       name: '/leaderboard'
       method: GET
       owner: foobar
    condition:
      path: '/leaderboard'
      method: GET
```

This has the added benefit of allowing multiple labels and being able to search (or tie things together, think dependencies).

### Any alternatives you've considered?

- Just remove name entirely - it seems valuable for some use cases. In particular, any kind of regex will be tough to understand when looking at metrics.
- Make name optional - because it becomes implicit, I need to think about it for awhile to figure out what it'll look like.
