### ISSUE TITLE
Liveness probe fails under mTLS

### ISSUE THREAD

**Issue by vic3lord** [linkerd/linkerd2#1990]
## Bug Report

Liveness probe fails if proxy is injected with mTLS

### What is the issue?

The pod keeps restarting due to failing liveness probe

### How can it be reproduced?

Inject proxy with mTLS, use the application port (containerPort) for exposing the /healtz as well on the same port.

### Logs, error output, etc

I ran `kubectl -n linkerd get ev` as @olix0r recommended on Slack but there was no events to list.

#### `linkerd check` output

```text
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[ok]
linkerd-api: no invalid service profiles...................................[ok]
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[ok]
linkerd-version: control plane is up-to-date...............................[ok]

Status check results are [ok]
```

### Environment

- Kubernetes Version: 1.11.2
- Cluster Environment: GKE
- Host OS: COS
- Linkerd version: 2.1 stable

**Comment by klingerf** [comment]
@vic3lord If at all possible, can you paste the Kubernetes config that you're using to deploy the pod that's failing liveliness checks? I'd be interested to see how your probes are configured, so see if I canr reproduce this in my own environment.

**Comment by vic3lord** [comment]
Sure:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: someservice
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: somecontainer
          image: someimage
          ports:
            - name: http
              containerPort: 8080
            - name: admin
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
```

**Comment by stvnwrgs** [comment]
For us, the container is not failing, but the health check is done without mTLS. It is currently not possible to see what happens exactly as mTLS only supports the flag value "optional". If this would be set to something like enforce, we would see the container not starting. Are there plans to implement an enforce flag for testing reasons?

A way istio is currently doing it (https://raw.githubusercontent.com/istio/istio/release-1.0/samples/health-check/liveness-http.yaml) is not really nice solution for us, as this means an application must be capable of assigning `/healthz` to another port. 

This might be helpful: https://github.com/istio/istio/issues/9150

K8S Resource Files: 
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: emojivoto
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: emoji
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emoji-svc
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        image: buoyantio/emojivoto-emoji-svc:v5
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        resources:
          requests:
            cpu: 100m
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: emojivoto
spec:
  selector:
    app: emoji-svc
  clusterIP: None
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: voting
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: voting-svc
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        image: buoyantio/emojivoto-voting-svc:v5
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        resources:
          requests:
            cpu: 100m
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: emojivoto
spec:
  selector:
    app: voting-svc
  clusterIP: None
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: web
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-svc
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "80"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: buoyantio/emojivoto-web:v5
        name: web-svc
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
        periodSeconds: 3
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: 100m
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto
spec:
  type: LoadBalancer
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: vote-bot
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vote-bot
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc.emojivoto:80
        image: buoyantio/emojivoto-web:v5
        name: vote-bot
        resources:
          requests:
            cpu: 10m
status: {}
---

`linkerd inject --tls "optional" emojivoto.yml | kubectl  apply -f -`


Result:
```
![image](https://user-images.githubusercontent.com/1257443/50176937-037ec100-0301-11e9-83b1-3546449f73e4.png)
![image](https://user-images.githubusercontent.com/1257443/50176990-2315e980-0301-11e9-9690-f3ddc91b1fc8.png)

**Comment by klingerf** [comment]
@stvnwrgs Thanks for the additional info. It's expected that the probe requests won't use TLS -- they'll fall back to plaintext since the we don't have a certificate for the Host header that's sent with the probe request. You're right that this won't work in a TLS-mandatory setup. There's some discussion of approaches to remediate this in #1250.

@vic3lord Interesting. I'm not able to repro the failed liveliness probes on a GKE v1.11.5 cluster with linkerd v2.1.0. I'm using the following conifg, based off the config you pasted, and not seeing any pod restarts:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: someservice
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - name: somecontainer
          image: buoyantio/helloworld:0.1.6
          args:
            - "-addr=:8080"
          ports:
            - name: http
              containerPort: 8080
            - name: admin
              containerPort: 9000
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            limits:
              cpu: '0.1'
              memory: 100Mi
```

Can you try injecting that config with TLS and applying it in your cluster to see if passes its liveliness checks?
