### ISSUE TITLE
continues error with message tcp forward duplex error: Transport endpoint is not connected (os error 107)

### ISSUE THREAD

**Issue by etsrepo** [linkerd/linkerd2#2022]
we are receving this error continuely, I seached for unable to any solutions

`E  INFO proxy={server=out listen=127.0.0.1:4140 remote=10.44.2.3:56630} linkerd2_proxy::proxy::tcp forward duplex error: Transport endpoint is not connected (os error 107)`

verson info 

```
Client version: stable-2.1.0
Server version: stable-2.1.0

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.4-gke.12", GitCommit:"d48a38d6599484b4b98c39d1c584a3662a67d486", GitTreeState:"clean", BuildDate:"2018-12-07T00:26:53Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by klingerf** [comment]
@etsrepo Thanks for reporting this. Can you provide a minimal Kubernetes config that reproduces the issue you're seen when it's injected with the linkerd proxy?

**Comment by etsrepo** [comment]
https://gist.github.com/etsrepo/528055728afd1e86aa5b7f26a19bdf9c

the above link has deployment and service file for above-mentioned error, the same error is showing in all deployments

**Comment by klingerf** [comment]
@etsrepo Thanks for providing those configs! I deployed slightly modified versions of them to a GKE 1.11.5 cluster, but I didn't see the same issue that you're seeing.

Can you provide us with more details about your GKE cluster? Do you have any CNI plugins enabled that might be preventing the linkerd proxies from talking to the control plane? Are you able to successfully run the [demo app from the getting started guide](https://linkerd.io/2/getting-started/#step-5-install-the-demo-app) on your cluster?

---

Btw, here's the exact version of the config that I applied if you want to try it yourself:

<details><summary><code>kltest.yaml</code></summary>

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kltest
  name: kltest
  namespace: default
spec:
  clusterIP: 10.11.240.38
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: kltest
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kltest
  name: kltest
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kltest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.1.0
        linkerd.io/proxy-version: stable-2.1.0
      creationTimestamp: null
      labels:
        app: kltest
        linkerd.io/control-plane-ns: linkerd
        linkerd.io/proxy-deployment: kltest
    spec:
      containers:
      - image: buoyantio/helloworld:0.1.6
        imagePullPolicy: IfNotPresent
        name: kltest
        args:
        - "-addr=:50051"
        - "-text=Hello"
        ports:
        - containerPort: 50051
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 5G
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: LINKERD2_PROXY_LOG
          value: warn,linkerd2_proxy=info
        - name: LINKERD2_PROXY_BIND_TIMEOUT
          value: 10s
        - name: LINKERD2_PROXY_CONTROL_URL
          value: tcp://linkerd-proxy-api.linkerd.svc.cluster.local:8086
        - name: LINKERD2_PROXY_CONTROL_LISTENER
          value: tcp://0.0.0.0:4190
        - name: LINKERD2_PROXY_METRICS_LISTENER
          value: tcp://0.0.0.0:4191
        - name: LINKERD2_PROXY_OUTBOUND_LISTENER
          value: tcp://127.0.0.1:4140
        - name: LINKERD2_PROXY_INBOUND_LISTENER
          value: tcp://0.0.0.0:4143
        - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
          value: .
        - name: LINKERD2_PROXY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gcr.io/linkerd-io/proxy:stable-2.1.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 4191
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: linkerd-proxy
        ports:
        - containerPort: 4143
          name: linkerd-proxy
          protocol: TCP
        - containerPort: 4191
          name: linkerd-metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 4191
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          runAsUser: 2102
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - --incoming-proxy-port
        - "4143"
        - --outgoing-proxy-port
        - "4140"
        - --proxy-uid
        - "2102"
        - --inbound-ports-to-ignore
        - 4190,4191
        image: gcr.io/linkerd-io/proxy-init:stable-2.1.0
        imagePullPolicy: IfNotPresent
        name: linkerd-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```
</details>
