### ISSUE TITLE
`linkerd routes` only maps traffic to the http method, not the path

### ISSUE THREAD

**Issue by jon-walton** [linkerd/linkerd2#2060]
### What is the issue?

After creating a service profile and generating a small load against the service (10RPS):

`echo "GET https://example.com/api/hello/world" | vegeta attack -timeout 5s -rate 10 | tee | vegeta report --every 500ms`

I can clearly see that 

`linkerd routes deploy/myapp -n myappns -t 1m`

is mapping the traffic (in this case 10RPS) against the first matching http method in the service profile.

if we take an example service profile spec (generated via `--open-api` , but changing the route names to protect the innocent 😉 ):

```yaml
  spec:
    routes:
    - condition:
        method: GET
        path_regex: /api/user/profile
      name: GET /api/user/profile
      response_classes:
      - condition:
          status:
            max: 200
            min: 200
    - condition:
        method: POST
        path_regex: /api/something/[^/]*
      name: POST /api/something/{id}
      response_classes:
      - condition:
          status:
            max: 200
            min: 200
    - condition:
        method: PUT
        path_regex: /api/something/[^/]*
      name: PUT /api/something/{id}
      response_classes:
      - condition:
          status:
            max: 200
            min: 200
    - condition:
        method: GET
        path_regex: /api/hello/world
      name: GET /api/hello/world
      response_classes:
      - condition:
          status:
            max: 200
            min: 200
```

`linkerd routes deploy/myapp -n myappns -t 1m`

will print 10RPS against `GET /api/user/profile` and not display anything for `/api/hello/world`

this holds true for other methods in our application all POST requests will be registered against `POST /api/something/{id}`

doing a `linkerd tap deploy/myapp -n myappns` shows the traffic hitting the expected routes

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
$ l check
kubernetes-api: can initialize the client..................................[ok]
kubernetes-api: can query the Kubernetes API...............................[ok]
kubernetes-api: is running the minimum Kubernetes API version..............[ok]
linkerd-api: control plane namespace exists................................[ok]
linkerd-api: control plane pods are ready..................................[ok]
linkerd-api: can initialize the client.....................................[ok]
linkerd-api: can query the control plane API...............................[ok]
linkerd-api[kubernetes]: control plane can talk to Kubernetes..............[ok]
linkerd-api[prometheus]: control plane can talk to Prometheus..............[ok]
linkerd-api: no invalid service profiles...................................[ok]
linkerd-version: can determine the latest version..........................[ok]
linkerd-version: cli is up-to-date.........................................[ok]
linkerd-version: control plane is up-to-date...............................[warning] -- is running version 884ae673 but the latest edge version is 18.12.4
```

### Environment

- Kubernetes Version: 1.13.1
- Cluster Environment: AKS-Engine
- Host OS:
- Linkerd version:

```text
Client version: edge-18.12.4
Server version: git-884ae673
```

The server is running git-884ae673 to resolve memory leaks. I'll try to repro this once the next edge is release :+1:
