### ISSUE TITLE
edge-19.1.2 --single-namespace still using ServiceProfile

### ISSUE THREAD

**Issue by djeeg** [linkerd/linkerd2#2119]
### What is the issue?

19.1.2 with single-namespace seems to still be using ServiceProfile somewhere

linkerd-controller fails to start with error (below)

the rest of the pods do start
linkerd-grafana
linkerd-prometheus
linkerd-web
linkerd-deploy

### How can it be reproduced?

Latest release edge-19.1.2, use single-namespace, not full cluster permissions

### Logs, error output, etc

E0121 12:34:21.464259       1 reflector.go:205] github.com/linkerd/linkerd2/controller/gen/client/informers/externalversions/factory.go:117: Failed to list *v1alpha1.ServiceProfile: serviceprofiles.linkerd.io is forbidden: User "system:serviceaccount:NAMESPACE:linkerd-controller" cannot list serviceprofiles.linkerd.io in the namespace "NAMESPACE"

### Environment

- Kubernetes Version: 1.10
- Cluster Environment: EKS
- Host OS:
- Linkerd version: edge-19.1.2 

### Additional context

--single namespace manifest is:
 
```
### Controller RBAC ###
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-NAMESPACE-controller
  namespace: NAMESPACE
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods", "endpoints", "services", "replicationcontrollers"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  resourceNames: ["NAMESPACE"]
  verbs: ["list", "get", "watch"]
```
