### ISSUE TITLE
Error once injected into nginx-ingress-controller, possibly related to letsencrypt

### ISSUE THREAD

**Issue by sjdweb** [linkerd/linkerd2#2136]
### What is the issue?
500 errors. Logs below.

### How can it be reproduced?
Inject into nginx-controller deployment

### Logs, error output, etc
```
[nginx-ingress-controller-7df9f8c55b-5dfpj linkerd-proxy] WARN linkerd2_proxy::app::profiles error fetching profile for cert.int-x3.letsencrypt.org:80: Inner(Upstream(Inner(Inner(Error { kind: Timeout(3s) }))))
[nginx-ingress-controller-7df9f8c55b-5dfpj linkerd-proxy] WARN linkerd2_proxy::app::profiles error fetching profile for apps.identrust.com:80: Inner(Upstream(Inner(Inner(Error { kind: Timeout(3s) }))))
[nginx-ingress-controller-7df9f8c55b-5dfpj linkerd-proxy] WARN linkerd2_proxy::app::profiles error fetching profile for ocsp.int-x3.letsencrypt.org:80: Inner(Upstream(Inner(Inner(Error { kind: Timeout(3s) }))))
[nginx-ingress-controller-7df9f8c55b-5dfpj linkerd-proxy] WARN linkerd2_proxy::app::profiles error fetching profile for shift-apigateway.default.svc.cluster.local:80: Inner(Upstream(Inner(Inner(Error { kind: Timeout(3s) }))))
```

#### `linkerd check` output

```text
kubernetes-api
--------------
✔ can initialize the client
✔ can query the Kubernetes API

kubernetes-version
------------------
✔ is running the minimum Kubernetes API version

linkerd-existence
-----------------
✔ control plane namespace exists
✔ controller pod is running
✔ can initialize the client
✔ can query the control plane API

linkerd-api
-----------
✔ control plane pods are ready
✔ can query the control plane API
✔ [kubernetes] control plane can talk to Kubernetes
✔ [prometheus] control plane can talk to Prometheus

linkerd-service-profile
-----------------------
✔ no invalid service profiles

linkerd-version
---------------
✔ can determine the latest version
✔ cli is up-to-date

control-plane-version
---------------------
✔ control plane is up-to-date

Status check results are ✔
```

**Comment by grampelberg** [comment]
Can you post your ingress?

**Comment by sjdweb** [comment]
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  name: xxx-nginx-ingress
  namespace: default
spec:
  rules:
  - host: api.dev.xxx.xxx
    http:
      paths:
      - backend:
          serviceName: apigateway
          servicePort: 8080
        path: /
  - host: dev.xxx.xxx
    http:
      paths:
      - backend:
          serviceName: xxx-ui
          servicePort: 80
        path: /
      - backend:
          serviceName: apigateway-portal
          servicePort: 8080
        path: /api
  tls:
  - hosts:
    - api.dev.xxx.xxx
    - dev.xxx.xxx
    secretName: shift-app-tls
status:
  loadBalancer:
    ingress:
    - {}
```
