### ISSUE TITLE
Debug container

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2199]
### What problem are you trying to solve?

The current proxy and control plane containers are stripped down to reduce size. While that's awesome, it makes debugging (especially network level stuff) a little bit of a pain. 

### How should the problem be solved?

I would like to have a new flag for `inject` and `install` that adds a new sidecar container which contains a whole bunch of debugging tooling and the correct permissions to run. The flow could be:

```bash
$ linkerd install --debug-mode
$ linkerd inject --debug-mode
```

The container should have raised privileges and mount some host volumes. What other paths on the host would be valuable? Maybe 

```yaml
apiVersion: v1
kind: Pod
metadata: 
  name: linkerd-debug
spec: 
  volumes:
    - name: host-config
      hostPath:
        path: /etc/default
    - name: proc
      hostPath:
        path: /proc
  containers: 
    - name: linkerd-debug
      image: gcr.io/linkerd-io/debug:stable-2.2.0
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: /etc/default
          name: host-config
        - mountPath: /host/proc
          name: proc
```

I would like the base container to have the following packages pre-installed:

- tcpdump
- netstat
- strace
- bpftrace
- lsof
- telnet
- curl
- nghttp
- tar

### Open questions

- It would be nice to make sure https://github.com/eldadru/ksniff works for the tcpdump use cases with this container in the pod.
- It seems like it'd be cool to have a `linkerd debug deploy/foobar` that automates some of this. Not sure there's any real benefit over the top of `kubectl exec` though.
