### ISSUE TITLE
Endpoint load balancing weighting

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#2300]
## What problem are you trying to solve?

I would like to provide weights for endpoints behind a service. This can be 
used to do things such as canary deploys, A/B testing and saturation testing.

## How should the problem be solved?

An addition to `ServiceProfile`s. The `Service` selector will be 
maintained as a superset, with weights sub-selecting groups inside that set.

```yaml
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: nginx.emojivoto.svc.cluster.local
  namespace: emojivoto
spec:
  weights:
    - selector:
        version: 2
      weight: 100m
```

Things I like about this:

- Annotation isn't nested YAML.
- Won't always require a redeploy of pods on weight changes.

Things I dislike about this:

- Overloads the concept of a selector for services and requires a little bit of
  extra thought.
- An extra resource to think about is always a challenge.

Using a helm chart to drive this, you would have values that look like:

```yaml
versions:
- tag: 1.0.0
  weight: 900m
- tag: 1.1.0
  weight: 100m
```

And a chart that looks like:

```yaml
{{- range .Values.versions }}
apiVersion: apps/v1
kind: Deployment
...
spec:
  template:
    metadata:
      labels:
        app: nginx
        version: {{ .tag }}
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: emojivoto
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: nginx
---
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: nginx.emojivoto.svc.cluster.local
  namespace: emojivoto
spec:
  weights:
  {{- range .Values.versions }}
    - selector:
        version: .tag
      weight: .weight
  {{ end }}
```

This would create multiple deployments, one for each version, a single service
and a single serviceprofile. It would be driven by running 
`helm upgrade -f my-state.yaml` each time the weight changes until the old
version is removed entirely.

### Annotating the service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: emojivoto
  annotations:
    linkerd.io/weight: |
      - selector:
          version: 2
        weight: 100m
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
```

Things I like about this:

- Configuration lives mostly where I'd expect it to be.
- Reasoning about the weights of two groups in a single place is convenient.

Things I dislike about this:

- Overloads the concept of a selector for services and requires a little bit of
  extra thought.
- Nesting YAML inside strings (annotations) is ugly.

### Annotating the pod

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: emojivoto
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        linkerd.io/weight: 100m # 10%
    spec:
      containers:
        - name: nginx
          image: nginx
```

Things I like about this:

- Annotation isn't nested YAML.

Things I dislike about this:

- Hard to reason about what % of traffic this pod will get.
- Will require a redeploy of pods when changing the weight.

### Annotating the deployment (job, statefulset, ...)

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: emojivoto
  labels:
    app: nginx
  annotations:
    linkerd.io/weight: 100m # 10%
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
```

Things I like about this:

- Annotation isn't nested YAML.
- Won't always require a redeploy of pods on weight changes.

Things I dislike about this:

- Hard to reason about what % of traffic this deployment will get as you need to
  look at all the deployments in a service's selector to understand.
- Might require a redeploy of pods on weight changes. Any poorly written helm
  chart, for example will roll the pods because of annotation changes.
- Will require integration with each resource type.

**Comment by olix0r** [comment]
I am not particularly thrilled about the ServiceProfile suggestion -- it doesn't feel like the correct abstraction to me, and I think it complicates discovery logic...

What is the logic that the destination service needs to implement to resolve a name?

**Comment by grampelberg** [comment]
@olix0r I'm not a huge fan of it either. The recommendation changed about 4 times as I thought it through. 

> What is the logic that the destination service needs to implement to resolve a name?

Hmm?

**Comment by adleong** [comment]
I initially didn't like this, but the more I think about it, the more it makes sense to me.

The common scenario that I'm imagining is that pods may already have labels on them (e.g. version) and users will want to apply some mapping of labels to weights (e.g. 90% on v1, 10% on v2).  Furthermore, users will want to be able to apply this mapping and dynamically change the mapping (shift traffic) without restarting the pods.  Since pod labels are immutable (I think?) it makes sense to store this mapping somewhere (instead of putting weights directly on pods).

Service profiles inform client policy such as retries and timeouts, so it semantically fits that they could inform client load balancing behavior as well.  

A slight variation on @grampelberg suggestion above would be a structure like this in the service profile:

```
weighting:
  label: version
  weights:
    v1: 80
    v2: 20
```

This is a bit less expressive (only one label can be used for weighting for that service) but feels a bit more ergonomic and it avoids the potentially confusing scenario where a pod could be in more than one weight class.
