### ISSUE TITLE
"linkerd routes" fails due to non-.default.svc.cluster.local Host header

### ISSUE THREAD

**Issue by philwhln** [linkerd/linkerd2#2323]
Most of our traffic comes via an AWS ELB (created using `Service` of `type: LoadBalancer` with annotations - see below). Therefore the `Host` header in requests is not generally in the `foo.default.svc.cluster.local` format. 

This means that even _after_ adding a `ServiceProfile` and running `linkerd routes` we see this error...
```
linkerd routes deploy/foo
Error: No Service Profiles found for selected resources 
```

Looking at the code, it seems that we're silently ignoring errors from `topRoutesFor` (see https://github.com/linkerd/linkerd2/blob/master/controller/api/public/top_routes.go#L72), which would give more context to the problem, and then falling back to this outputted error due to `len(tables) == 0`.

`linkerd routes deploy/foo` began working once we logged into an adjacent pod and made a `curl` request to the target service passing the host header as `-H 'Host: foo.default.svc.cluster.local'`.

Here's an example of our Service definition...

```
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  labels:
    app: foo
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${AWS_CERT_ID}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    external-dns.alpha.kubernetes.io/hostname: ${APP_EXTERNAL_HOSTNAME}
spec:
  type: LoadBalancer
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: app-port
  selector:
    app: foo
```
