### ISSUE TITLE
Merging of PUTS and POSTS route metrics

### ISSUE THREAD

**Issue by jamesallen-vol** [linkerd/linkerd2#2404]
## Feature Request
Merge specific requests in a service profile. (e.g. totaling all PUTS and POSTS to a specific route)

### What problem are you trying to solve?
This would allow requests that commonly result in a write to a database (PUTS, POSTS, DELETES) to be tracked with route metrics. Likewise read requests (GETS) could be tracked separately as well.

### How should the problem be solved?
Add the ability to add an aggregation for a specific route to the service profile definition

### Any alternatives you've considered?
Having a grafana dashboard that would give rps for PUTS, POSTS, DELETES by using a proxy metric recording the http method.

### How would users interact with this feature?
Through the linkerd dashboard or grafana dashboard for the deployment.

**Comment by klingerf** [comment]
@jamesallen-vol Thanks for reporting this. I agree that it could be useful to rollup multiple request methods into a single route.

**Comment by adleong** [comment]
@jamesallen-vol have you tried constructing a route like:

```
- name: write
  condition:
    pathRegex: "/some/path"
    any:
    - method: POST
    - method: PUT
    - method: DELETE
```
