### ISSUE TITLE
Linkerd 19.2.5 not auto-injecting into all containers

### ISSUE THREAD

**Issue by christianhuening** [linkerd/linkerd2#2418]
### What is the issue?
When using Linkerd 19.2.5 with mTLS and auto-inject it does work for some Deployments in an annotated namespace and for some not. 

The deployments are almost the same except for some command args of the starting container. Also both do not contain disabled annotations. Here are some specs:

Working:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 9588b3336733648253c899ec818098b639b2cb7d0fdb9ebad66be1b0aa072b7d
    kubernetes.io/psp: restricted
    linkerd.io/created-by: linkerd/proxy-injector edge-19.2.5
    linkerd.io/identity-mode: optional
    linkerd.io/proxy-version: edge-19.2.5
  creationTimestamp: "2019-02-28T13:32:02Z"
(...)
```

vs. not working

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    checksum/config: 9588b3336733648253c899ec818098b639b2cb7d0fdb9ebad66be1b0aa072b7d
    kubernetes.io/psp: restricted
  creationTimestamp: "2019-02-28T13:32:00Z"
(...)
```

And here are excerpts from the proxy-injector pod:
working:
```
time="2019-02-28T13:32:00Z" level=info msg="working on v1/deployment fu-figo-api-task-sync-payment-parameter.."
time="2019-02-28T13:32:00Z" level=info msg="patch generated:
```

vs not working:

```
time="2019-02-28T13:31:59Z" level=info msg="working on v1/deployment fu-figo-api-task-register.."
time="2019-02-28T13:31:59Z" level=info msg="skipping deployment fu-figo-api-task-register"
```

so it seems the injector simply skips this deployment for some reason.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.13.3
- Cluster Environment: (GKE, AKS, kops, ...): bare-metal
- Host OS: ContainerLinux 1967.6.0
- Linkerd version: edge-19.2.5

**Comment by ihcsim** [comment]
Following our _slack_ convo, please let us know if this is reproducible in another namespace on your cluster. For the record, the proxy injector will skip the mutation if either:

1. There is another proxy sidecar or proxy init container (including istio and envoy) in the same workload
1. There is a `linkerd.io/inject: disabled` explicitly defined either at the namespace or pod level. (This doesn't seem to be the case here.)

**Comment by christianhuening** [comment]
It's reproducible in another namespace as well. Interestingly enough it's always the same deployments. I double checked they don't have `linkerd.io/inject: disabled` defined and we certainly do not have istio in the cluster.

**Comment by ihcsim** [comment]
> Interestingly enough it's always the same deployments

Strange :thinking: Are you able to send me a stripped down version of the deployment YAML?

**Comment by christianhuening** [comment]
@ihcsim sure, where to?

**Comment by christianhuening** [comment]
Working:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fu-redacted-api-task-register
  labels:
    app.kubernetes.io/name: redacted-api-task-register
    app.kubernetes.io/instance: fu
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redacted-api-task-register
      app.kubernetes.io/instance: fu
  template:
    metadata:
      annotations:
        checksum/config: 9588b3336733648253c899ec818098b639b2cb7d0fdb9ebad66be1b0aa072b7d
      labels:
        app.kubernetes.io/name: redacted-api-task-register
        app.kubernetes.io/instance: fu
    spec:
      containers:
        - name: fu-redacted-api-task
          image: <redacted>
          imagePullPolicy: IfNotPresent
          args: ["register"]
          volumeMounts:
            - name: config
              mountPath: /etc/redacted/redacted.ini
              subPath: redacted.ini
              readOnly: true
            - name: certificates
              mountPath: /etc/pki/tls/
              readOnly: true
          resources:
            {}
      imagePullSecrets:
        - name: redacted-api-pull
      volumes:
        - name: config
          configMap:
            name: fu-redacted-api
        - name: certificates
          secret:
            secretName: redacted-api-certificates
```

**Comment by christianhuening** [comment]
So i found that I am still running on an older version of the MutatingWebhookConfiguration (https://github.com/linkerd/linkerd2/blob/d805cb9a2b1a0636869cf60cc01b8dfe9b261d3f/controller/proxy-injector/tmpl/mutating_webhook_configuration.go#L19-L22) .

Mine still looks like so:
```yaml
apiVersion: v1
items:
- apiVersion: admissionregistration.k8s.io/v1beta1
  kind: MutatingWebhookConfiguration
  metadata:
    creationTimestamp: "2019-02-19T07:16:26Z"
    generation: 5
    name: linkerd-proxy-injector-webhook-config
  webhooks:
  - clientConfig:
      caBundle: <redacted>
      service:
        name: linkerd-proxy-injector
        namespace: linkerd
        path: /
    failurePolicy: Ignore
    name: linkerd-proxy-injector.linkerd.io
    namespaceSelector: {}
    rules:
    - apiGroups:
      - apps
      - extensions
      apiVersions:
      - v1
      - v1beta1
      - v1beta2
      operations:
      - CREATE
      resources:
      - deployments
    sideEffects: Unknown
kind: List
```
