### ISSUE TITLE
stabilize inject output

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2450]
For diff and debugging purposes, it's helpful if `linkerd inject` does not reorder the input k8s resources.

When injecting https://run.linkerd.io/emojivoto.yml, observe the `serviceAccountName` get moved within the pod spec:

```bash
$ diff <(curl -s https://run.linkerd.io/emojivoto.yml) <(curl -s https://run.linkerd.io/emojivoto.yml | bin/go-run cli inject - | bin/go-run cli uninject -)

namespace "emojivoto" skipped
serviceaccount "emoji" skipped
serviceaccount "voting" skipped
serviceaccount "web" skipped
deployment "emoji" injected
service "emoji-svc" skipped
deployment "voting" injected
service "voting-svc" skipped
deployment "web" injected
service "web-svc" skipped
deployment "vote-bot" injected


namespace "emojivoto" skipped
serviceaccount "emoji" skipped
serviceaccount "voting" skipped
serviceaccount "web" skipped
deployment "emoji" uninjected
service "emoji-svc" skipped
deployment "voting" uninjected
service "voting-svc" skipped
deployment "web" uninjected
service "web-svc" skipped
deployment "vote-bot" uninjected

43d42
<       serviceAccountName: emoji
55a55
>       serviceAccountName: emoji
90d89
<       serviceAccountName: voting
102a102
>       serviceAccountName: voting
137d136
<       serviceAccountName: web
155a155
>       serviceAccountName: web
```

**Comment by liquidslr** [comment]
@siggy  just had a small question although i didn't go in the details of this issue,but according to my knowledge the output of diff command takes the formatting of the input files, so in this case, the extra indent of serviceAccountName is coming from the yaml file I guess, Just asking out of curiosity.

**Comment by siggy** [comment]
Hi @liquidslr. Thanks for the question. The output diff is exhibiting changes to the order of the YAML elements, not the indents.

Consistent indentation between input and output of our inject/uninject commands is not currently supported (not impossible but more work).

The intent of this ticket is to stabilize the ordering of elements across inject/uninject commands, with the goal being that I can run inject on a yaml, diff the output, and easily identify what was injected. If our inject command reorders the yaml elements, it's harder to see what changed.

**Comment by liquidslr** [comment]
thanks @siggy I would like to work on this !

**Comment by liquidslr** [comment]
> The output diff is exhibiting changes to the order of the YAML elements, not the indents.

sorry for the delay, I went through the deployment files https://run.linkerd.io/emojivoto.yml and couldn't notice any difference in ordering of the elements, I think I still don't understand the exact issue.

**Comment by siggy** [comment]
@liquidslr the bash session in this issue's description demonstrates that given a yaml file, injecting and then uninjecting leaves the `serviceAccountName` elements in a different location in the yaml. Injecting a yaml with a proxy should not re-order elements that are unrelated to the elements being injected.

Here's a similar command with `stable-2.3.0`:
```bash
$ diff <(curl -s https://run.linkerd.io/emojivoto.yml) <(curl -s https://run.linkerd.io/emojivoto.yml | linkerd inject --ignore-cluster --disable-identity - | linkerd uninject -)

namespace "emojivoto" skipped
serviceaccount "emoji" skipped
serviceaccount "voting" skipped
serviceaccount "web" skipped
deployment "emoji" injected
service "emoji-svc" skipped
deployment "voting" injected
service "voting-svc" skipped
deployment "web" injected
service "web-svc" skipped
deployment "vote-bot" injected


namespace "emojivoto" skipped
serviceaccount "emoji" skipped
serviceaccount "voting" skipped
serviceaccount "web" skipped
deployment "emoji" uninjected
service "emoji-svc" skipped
deployment "voting" uninjected
service "voting-svc" skipped
deployment "web" uninjected
service "web-svc" skipped
deployment "vote-bot" uninjected

43d42
<       serviceAccountName: emoji
55a55
>       serviceAccountName: emoji
90d89
<       serviceAccountName: voting
102a102
>       serviceAccountName: voting
137d136
<       serviceAccountName: web
155a155
>       serviceAccountName: web
```

**Comment by olix0r** [comment]
Is this still relevant now that injection is handled by the proxy-injector?

**Comment by ihcsim** [comment]
Yes, it's still relevant because the proxy injector (more specifically, the `yaml` library) doesn't preserve the order of the keys inside the YAML block. E.g.,
```yaml
--- before-inject.yaml  2019-05-28 15:29:30.578087469 -0700
+++ after-inject.yaml   2019-05-28 15:32:20.024791349 -0700
@@ -36,11 +36,12 @@
   strategy: {}
   template:
     metadata:
+      annotations:
+        linkerd.io/inject: enabled
       creationTimestamp: null
       labels:
         app: emoji-svc
     spec:
-      serviceAccountName: emoji
       containers:
       - env:
         - name: GRPC_PORT
@@ -53,6 +54,7 @@
         resources:
           requests:
             cpu: 100m
+      serviceAccountName: emoji # the keys are now sorted alphabetically
```
