### ISSUE TITLE
stat: pod count can be mis-reported

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#2548]
```
:; linkerd stat deploy -n strest       
NAME                 MESHED   SUCCESS         RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99    TLS
strest-client         30/30         -           -             -             -             -      -
strest-server-fast    22/22   100.00%   7326.5rps          20ms          76ms          97ms   100%
strest-server-slow    22/22   100.00%    789.3rps          20ms          75ms          96ms   100%
```

This seems to indicate that there are 44 server instances, however:
```
NAME                 DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
strest-client        30        30        30           30          26m
strest-server-fast   20        20        20           20          26m
strest-server-slow   2         2         2            2           26m
```

**Comment by murarisumit** [comment]
@olix0r I would like to take it up.

So as I understand we need to update the stat output format here right ?

**Comment by grampelberg** [comment]
@murarisumit not the format, just the counts to match up.

**Comment by murarisumit** [comment]
oh sorry, thanks @grampelberg  yes missed `strest-server-slow` part. @olix0r can you share the yamls to replicate this up ? (not sure if it is a right ask)

**Comment by murarisumit** [comment]
@olix0r can you give me some way to replicate it, i tried with below specs, but wasn't able to replicate it. 

first deployment with 
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-v1
spec:
  replicas: 15
  selector:
    matchLabels:
      app: http-echo
      version: v1
  template:
    metadata:
      labels:
        app: http-echo
        version: v1
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.3
        args: ["-listen", ":8080", "-text", "Reply from v1"]
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-svc
  labels:
    app: http-echo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: http-echo
---
```

Second deployment
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo-v2
spec:
  replicas: 20
  selector:
    matchLabels:
      app: http-echo
      version: v2
  template:
    metadata:
      labels:
        app: http-echo
        version: v2
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:0.2.3
        args: ["-listen", ":8080", "-text", "Reply from v2"]
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: http-echo-svc
  labels:
    app: http-echo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: http-echo
---
```

Got this output:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/2667258/55797600-82834980-5aea-11e9-9383-facdfd46c977.png">


Can you share your specs, so that I can try playing with it.
