### ISSUE TITLE
Support service network policies

### ISSUE THREAD

**Issue by campbel** [linkerd/linkerd2#2746]
### What problem are you trying to solve?
One of the promised visions of Kubernetes is a single control plane to manage all of your workloads. Many applications rely on network isolation in their security model, so to realize this there needs to be a way to securely isolate workloads. Currently Kubernetes supports logical separation (namespaces), but it doesn't support secure isolation out of the box. If you want secure isolation you need a CNI that supports [NetworkPolicies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) (or a similar custom resource) such as [Calico](https://www.projectcalico.org/) or [Cilium](https://cilium.io/). A service mesh is also a natural place to enforce the secure isolation as all network traffic passes through the system. Istio supports [traffic policies](https://istio.io/docs/concepts/policies-and-telemetry/). 

With `v2.3` Linkerd introduced mTLS on by default. This should make it possible for the proxy to securely identify the source of incomming traffic if the source is meshed. This could allow the proxy to make decisions about whether to pass the request on to the application.

Beyond intra-mesh communication policies, egress rules could also be useful allowing administrators to deploy kubernetes in shared networks, but only granting access to resources explicitly (not sure if this is possible with Linkerd today as all egress traffic would have to be forced through the proxy).

### How should the problem be solved?

All traffic goes through the sidecar proxy (ingress & egress) so it is a natural location to enforce policies. This is a proven design in Istio and Cilium. A CRD can be used to configure the policies that can then be loaded into the sidecar, jut like `route` rules today.

### Any alternatives you've considered?

Yes there are a couple options:

1. **Use Istio**. This isn't ideal. Linkerd is appealing because of its focus on simplicity and high value features. Istio is featureful but complex and many teams don't have the operational bandwidth to support it.

2. **Use Cilium/Calico**. This is an option, however, neither have a Linkerd integration story in their documentation so it could be that the two services don't play nicely together. In the case of Cilium this means redundant features such as running two sidecars (`linkerd-proxy` and `envoy-proxy`) and duplicate encryption (mTLS and [Transparent Encryption](https://cilium.io/blog/2019/02/12/cilium-14))

### How would users interact with this feature?
The `ServiceProfile` is an ideal location for configuring the policies.
* Space in the spec for additional configuration.
* Policies are service specific which fits intuitively with the name ServiceProfile.
* Reduced complexity for end user.

Here are some possible configurations (AWS Security Groups for inspiration):
```yaml
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: foo.default.svc.cluster.local
spec:
  routes:
  ...
  policy:
    egress:
    - protocol: http
      service: bar.default.svc.cluster.local        # Support linkerd meshed services first class
    ingress:
    - protocol: http
      service: bar.default.svc.cluster.local
    - protocol: http
      service: gateway.ingress.svc.cluster.local
---
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: bar.default.svc.cluster.local
spec:
  routes:
  ...
  policy:
    egress:
    - protocol: https                               # Support non-meshed services on egress
      host: twitter.com
    - protocol: tcp
      port: 6379
      host: redis.default.svc.cluster.local         # Support TCP services 
    ingress:
    - protocol: http
      service: *.default.svc.cluster.local          # Suport wildcard (maybe regexp?)
```
