### ISSUE TITLE
Application can't connect via http to internal services for 10 mins or longer after creation

### ISSUE THREAD

**Issue by kforsthoevel** [linkerd/linkerd2#2794]
### What is the issue?
When a pod is created and injected with the linkerd proxy, the application container can't connect to any other services running on the kubernetes cluster no matter if the destination service is part of the service mesh or not. External services, e. g. google.com can be reached. After 10 mins or sometimes even longer, the internal services can be accessed.
 
When the deployment is not injected with the linkerd proxy, everything works as expected.

### How can it be reproduced?
Create this deployment:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: test
  name: test
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      name: test
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        name: test
    spec:
      containers:
        - name: test
          image: appropriate/curl
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]
          imagePullPolicy: IfNotPresent
```
Wait till pod is ready and then run this command:

```bash
$ kubectl exec -it test-584c994667-rzkck -c test -- curl -v -I http://test-svc:8080
* Rebuilt URL to: test-svc:8080/
*   Trying 100.65.55.18...
* TCP_NODELAY set
* Connected to test-svc (100.65.55.18) port 8080 (#0)
> GET / HTTP/1.1
> Host: test-svc:8080
> User-Agent: curl/7.59.0
> Accept: */*
>
```

Connect to external service: 
```bash
$ kubectl exec -it test-584c994667-rzkck -c test -- curl -v -I google.com
* Rebuilt URL to: google.com/
*   Trying 74.125.193.102...
* TCP_NODELAY set
* Connected to google.com (74.125.193.102) port 80 (#0)
> HEAD / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.59.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
HTTP/1.1 301 Moved Permanently
< location: http://www.google.com/
location: http://www.google.com/
< content-type: text/html; charset=UTF-8
content-type: text/html; charset=UTF-8
< date: Mon, 06 May 2019 14:22:41 GMT
date: Mon, 06 May 2019 14:22:41 GMT
< expires: Wed, 05 Jun 2019 14:22:41 GMT
expires: Wed, 05 Jun 2019 14:22:41 GMT
< cache-control: public, max-age=2592000
cache-control: public, max-age=2592000
< server: gws
server: gws
< content-length: 219
content-length: 219
< x-xss-protection: 0
x-xss-protection: 0
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN

<
* Connection #0 to host google.com left intact
```
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.11.9
- Cluster Environment: kops on AWS 
- Host OS: Debian GNU/Linux 9 (stretch)   4.9.0-7-amd64 docker: 17.3.2
- Linkerd version:
```bash
$ linkerd version
Client version: stable-2.3.0
Server version: stable-2.3.0
```

Please let me know if you need any further info. Thanks.
