### ISSUE TITLE
proxy-injector fails with a restricted psp

### ISSUE THREAD

**Issue by codeman9** [linkerd/linkerd2#2819]
### What is the issue?
We are noticing that the proxy-injector in our cluster is unable to successfully complete injection depending on the PSP that is in place. We are using the linkerd-cni plugin and the linkerd install command is as follows:
`linkerd install-cni --proxy-uid 12102 -l tram-linkerd` (our dest-cni-bin-dir and dest-cni-net-dir might be different than the default)
`linkerd install --ha --linkerd-cni-enabled --proxy-uid 12102 -l tram-linkerd`

### How can it be reproduced?
Set up PSP as follows:
restricted-psp
```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 10001
    rule: MustRunAs
  readOnlyRootFilesystem: true
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 10001
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

permissive-psp
```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: permissive
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  fsGroup:
    rule: RunAsAny
  hostIPC: true
  hostNetwork: true
  hostPID: true
  hostPorts:
  - max: 65535
    min: 0
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
```
When you have those in place, create roles and rolebindings that use the PSPs:
```yaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: hello-psp-permissive
    namespace: hello
  rules:
  - apiGroups:
    - policy
    resourceNames:
    - permissive
    resources:
    - podsecuritypolicies
    verbs:
    - use
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: hello-psp-restricted
    namespace: hello
  rules:
  - apiGroups:
    - policy
    resourceNames:
    - restricted
    resources:
    - podsecuritypolicies
    verbs:
    - use
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

```yaml
apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: hello-psp
    namespace: hello
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: hello-psp-restricted
  subjects:
  - kind: ServiceAccount
    name: hello
    namespace: hello
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

you can delete can recreate the above rolebinding and change the `hello-psp-restricted` to `hello-psp-permissive`

Then create a standard deployment and service:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  namespace: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - image: rivukis/helloworld:v6
        imagePullPolicy: IfNotPresent
        name: helloworld
        ports:
        - containerPort: 8081
        securityContext:
          runAsUser: 10002
      serviceAccountName: hello
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: hello
  labels:
    app: helloworld
spec:
  ports:
  - name: http
    port: 8081
  selector:
    app: helloworld
```

```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: hello
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello
  namespace: hello
```

and observe that when `restricted` is in use, the pods don't start and the replicaset has an error: `replicaset-controller  Error creating: pods "helloworld-6d8dd666c-flv47" is forbidden: unable to validate against any pod security policy: []` and when `permissive` is in use, all is well.

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist

linkerd-existence
-----------------
√ control plane components ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 19.5.1 but the latest edge version is 19.5.2
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 19.5.1 but the latest edge version is 19.5.2
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.11.9
- Cluster Environment: self-hosted ec2 cluster
- Host OS: CoreOS
- Linkerd version: edge-19.5.1

**Comment by codeman9** [comment]
Here is a slightly more restricted psp than permissive that works:

```yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: restricted-play
spec:
  allowPrivilegeEscalation: true # <------ This must be true
  fsGroup:
    ranges:
    - max: 65535
      min: 10001
    rule: MustRunAs
  readOnlyRootFilesystem: false # <------- This must be false
#  requiredDropCapabilities: # <------ This cannot be here
#  - ALL # <------ this cannot be here
  runAsUser:
    ranges:
    - max: 65535
      min: 10001
    rule: MustRunAs
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```
It seems like the commented lines above have to be as you see them here for the injection to work. I've tried all combinations of those 3 properties and only when they are in this state does it work.
