### ISSUE TITLE
rt_route label missing for ingress requests

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#2834]
### What is the issue?

Observed a `route_request_total` metric without a `rt_route` label, when requests are coming in via ingress. Route has a ServiceProfile.

#### ServiceProfile

```yaml
---
apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: events.apester.com
  namespace: data
spec:
  routes:
    - name: GET /tpe
      condition:
        all:
          - method: GET
          - pathRegex: /tpe

    - name: OPTIONS /event
      condition:
        method: OPTIONS
        pathRegex: /event

    - name: POST /event
      condition:
        method: POST
        pathRegex: /event

    - name: GET /px.jpg
      condition:
        method: GET
        pathRegex: /px.jpg
```

#### Ingress

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: events
  namespace: data
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  tls:
    - secretName: events-tls
      hosts:
        - events.apester.com
  rules:
    - host: events.apester.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: events
              servicePort: 8080
```

#### Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: events
  namespace: data
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9000'
spec:
  type: NodePort
  selector:
    app: events
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: admin
      port: 9000
      targetPort: 9000
```

### Logs, error output, etc

Relevant metric:
```
route_request_total{direction="inbound",dst="events.apester.com:80"} 7611
```

Full metrics:
https://gist.github.com/siggy/4983f6a6c41692b36329102c8cbf0d9a#file-ingress-metrics-txt-L163

### Environment

- Kubernetes Version: 1.12.6-gke.10 (master) 1.12.5-gke.10 (node)
- Cluster Environment: GKE, Container-Optimized OS (cos)
- Linkerd version: edge-19.5.2 and edge-19.5.3

/cc @vic3lord
