### ISSUE TITLE
Allow routing to multiple services from a single Ingress resource

### ISSUE THREAD

**Issue by matipan** [linkerd/linkerd2#2836]
### What problem are you trying to solve?
When injecting the linkerd2 proxy to the nginx ingress controller we need to update the ingress resource with the specified annotation for a particular service. This works well if the resource only has rules for one service, if you add rules to another service the routing wont work since the header will not be overwritten with the correct service route.
For example, this works:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-overrid web-svc.emojivoto.svc.cluster.local:80;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80
```

But this doesn't:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override web-svc.emojivoto.svc.cluster.local:80;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80
  - host: different.example.com
    http:
      paths:
      - backend:
          serviceName: other-svc
          servicePort: 80
```

### How should the problem be solved?
Ideally we could define some form of wildcard or set of values for all the services that need to be routed. I'm not sure how this can be done for each of the ingress controllers but I'll look up for a possible solution.

What do you want to happen? Add any considered drawbacks.

### Any alternatives you've considered?

Is there another way to solve this problem that isn't as good a solution?

There is. Users can still create separate files for each of ingress rules, they would use one file per service.

### How would users interact with this feature?
They will be able to write the routing rules on a single file no matter the service that is being routed.

If you can, explain how users will be able to use this. Maybe some sample CLI
output?
