### ISSUE TITLE
New PSP and RBAC resources for the control plane

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#2892]
In a cluster with PSP enabled, we need to grant enough privileges to the control plane components or else they won't be scheduled. The creation of these resources doesn't hurt even if the PSP admission controller is not enabled.

A PSP granting enough privileges for the Linkerd containers:
<details>

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: linkerd
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - NET_ADMIN
  fsGroup:
    rule: RunAsAny
  readOnlyRootFilesystem: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - ConfigMap
  - secret
  - emptyDir
```

</details>

A ClusterRole pointing to that PSP:
<details>

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:linkerd
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - linkerd
```
</details>

A ClusterRoleBinding binding that role to all the Linkerd ServiceAccounts:
<details>

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:linkerd
subjects:
- kind: ServiceAccount
  name: linkerd-controller
  namespace: linkerd
- kind: ServiceAccount
  name: linkerd-grafana
  namespace: linkerd
- kind: ServiceAccount
  name: linkerd-identity
  namespace: linkerd
- kind: ServiceAccount
  name: linkerd-prometheus
  namespace: linkerd
- kind: ServiceAccount
  name: linkerd-proxy-injector
  namespace: linkerd
- kind: ServiceAccount
  name: linkerd-web
  namespace: linkerd
- kind: ServiceAccount
  name: linkerd-sp-validator
  namespace: linkerd
- kind: ServiceAccount
  name: linkerd-tap
  namespace: linkerd

```
</details>

For CNI, we also need to create a separate PSP, ClusteRole and ClusterRoleBinding, given the CNI pod requires a bit more privileges.
