### ISSUE TITLE
Problems with CLI, Manual/Automatic sidecar injection and Pod scheduling in GKE

### ISSUE THREAD

**Issue by bzon** [linkerd/linkerd2#2940]
### What is the issue?

* Manual and automatic sidecar injection does not work. 
* **linkerd check** and **linkerd inject** times out (context deadline exceeded)
* Sidecar injection made my cluster Pods scheduling in any namespace be delayed for some reason. For example; when I deleted a Pod, it takes 3-5 seconds for it to be back on (ContainerCeating > Running) state. 
* After uninstalling linkerd, the above issue ^ was resolved.

All pods are running fine under the **linkerd** namespace.

### How can it be reproduced?

Create a Private GKE Cluster following the [official guide](https://cloud.google.com/nat/docs/gke-example).

Here are my GKE addons (I can provide more info):

```yaml
addonsConfig:
  horizontalPodAutoscaling: {}
  httpLoadBalancing:
    disabled: true
  istioConfig:
    auth: AUTH_MUTUAL_TLS
    disabled: true
  kubernetesDashboard:
    disabled: true
  networkPolicyConfig:
privateCluster: true
privateClusterConfig:
  enablePrivateNodes: true
  masterIpv4CidrBlock: 10.0.0.0/28
  privateEndpoint: 10.0.0.2
  publicEndpoint: x.x.x.x
```

Then follow https://linkerd.io/2/getting-started/.

Then follow https://linkerd.io/2/tasks/automating-injection/.

### Logs, error output, etc

I'm not sure if these are related to automatic sidecar injection.

```
linkerd-controller-59c9b6b554-6vz8d public-api time="2019-06-13T21:16:19Z" level=error msg="Query(sum(increase(response_total{direction=\"inbound\"}[1m])) by (namespace, daemonset, classification, tls)) failed with: Get http://linkerd-prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=sum%28increase%28response_total%7Bdirection%3D%22inbound%22%7D%5B1m%5D%29%29+by+%28namespace%2C+daemonset%2C+classification%2C+tls%29: context canceled"
linkerd-controller-59c9b6b554-6vz8d public-api time="2019-06-13T21:16:19Z" level=error msg="queryProm failed with: Get http://linkerd-prometheus.linkerd.svc.cluster.local:9090/api/v1/query?query=sum%28increase%28response_total%7Bdirection%3D%22inbound%22%7D%5B1m%5D%29%29+by+%28namespace%2C+daemonset%2C+classification%2C+tls%29: context canceled"
```

#### `linkerd check` output

```text
linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
× can query the control plane API
    Post https://x.x.x.x/api/v1/namespaces/linkerd/services/linkerd-controller-api:http/proxy/api/v1/Version: context deadline exceeded
    see https://linkerd.io/checks/#l5d-existence-api for hints
```

I followed the hint and it was ok.

### Environment

- Kubernetes Version: v1.12.7-gke.10
- Cluster Environment: GKE
- Host OS: MacOS
- Linkerd version: unavailable to get this. I just did `linkerd install` today.

```
Client version: stable-2.3.2
Server version: unavailable
```

### Possible solution

Do not use a private GKE Cluster?

### Additional context

My linkerd cli client have errors which I think relates to https://github.com/linkerd/linkerd2/pull/2757

**linkerd check** gives this error:

```txt
linkerd-existence
-----------------
√ control plane namespace exists
√ controller pod is running
√ can initialize the client
× can query the control plane API
    Post https://x.x.x.x/api/v1/namespaces/linkerd/services/linkerd-controller-api:http/proxy/api/v1/Version: context deadline exceeded
    see https://linkerd.io/checks/#l5d-existence-api for hints
```

**linkerd inject** gives this error:

```bash
Cannot find Linkerd: Post https://x.x.x.x/api/v1/namespaces/linkerd/services/linkerd-controller-api:http/proxy/api/v1/Version: context deadline exceeded
Validate the install with: linkerd check
error: no objects passed to apply
```

**kubectl describe mutatingwebhookconfigurations.admissionregistration.k8s.io linkerd-proxy-injector-webhook-config** output:

```yaml
Name:         linkerd-proxy-injector-webhook-config
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  admissionregistration.k8s.io/v1beta1
Kind:         MutatingWebhookConfiguration
Metadata:
  Creation Timestamp:  2019-06-13T21:29:23Z
  Generation:          1
  Resource Version:    10953728
  Self Link:           /apis/admissionregistration.k8s.io/v1beta1/mutatingwebhookconfigurations/linkerd-proxy-injector-webhook-config
  UID:                 4fff295d-8e22-11e9-8fa5-42010a00000b
Webhooks:
  Client Config:
    Ca Bundle: REDACTED
    Service:
      Name:        linkerd-proxy-injector
      Namespace:   linkerd
      Path:        /
  Failure Policy:  Ignore
  Name:            linkerd-proxy-injector.linkerd.io
  Namespace Selector:
  Rules:
    API Groups:

    API Versions:
      v1
    Operations:
      CREATE
      UPDATE
    Resources:
      pods
  Side Effects:  Unknown
Events:          <none>
```
