### ISSUE TITLE
GRPC client returning CANCELLED status after service pod goes away

### ISSUE THREAD

**Issue by suever** [linkerd/linkerd2#2947]
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:

We have Ruby-based GRPC clients (`v1.21.0`) communicating with a Go-based GRPC service (`v1.21.1`). Both the client pods and server pods are meshed by `linkerd` to perform GRPC load-balancing.

When any of the service pods go away (deploy, scale-down, etc.), the clients will error out with a `CANCELLED` status. If we retry the request, it then succeeds as the request *is* properly routed to another pod.

**What you expected to happen**:

I would expect `linkerd` to automatically detect that the service pod went away and instead route the request to one of the other available pods. Alternately, if there actually is a connectivity issue, I would expect to have seen an `UNAVAILABLE` status or something indicating that connection error.

**How to reproduce it (as minimally and precisely as possible)**:

For us, we can reproduce this with one client pod and two service pods and removing one of the service pods will cause this error once after which the next request *will* be sent to the other service pod.

**Anything else we need to know?**:

**Environment**:
- linkerd v2.3.2-stable
- EKS, Kubernetes 1.12

Server Configuration:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service
  namespace: grpc-service
  labels:
    app: grpc-service
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: grpc-service
  template:
    metadata:
      labels:
        app: grpc-service
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: grpc-service
          image: IMAGE:tag
          ports:
            - containerPort: 8099
              name: http-health
            - containerPort: 8098
              name: http-ready
            - containerPort: 3000
              name: grpc
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          readinessProbe:
            httpGet:
              path: /system/ready
              port: http-ready
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /system/health
              port: http-health
            initialDelaySeconds: 10
            periodSeconds: 30
```
