### ISSUE TITLE
linkerd upgrade: cannot change roleRef

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#2957]
I just ran `linkerd upgrade | kubectl apply -f -` on one of my AKS clusters, to upgrade the control plane from `edge-19.5.3` to `edge-19.6.2`. It printed:

```
The ClusterRoleBinding "linkerd-linkerd-tap" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"linkerd-linkerd-tap"}: cannot change roleRef
```

I think this relates to the recent change that moves tap to its own deployment. In my `edge-19.5.3` install, i have the following cluster role binding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: linkerd-linkerd-tap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-linkerd-controller
subjects:
- kind: ServiceAccount
  name: linkerd-tap
  namespace: linkerd
```

But `linkerd upgrade` is attempting to change it this:

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-linkerd-tap
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-linkerd-tap
subjects:
- kind: ServiceAccount
  name: linkerd-tap
  namespace: linkerd
```

And that fails with the invalid role ref error. I guess it's not possible to change role ref for previously created cluster role bindings?
