### ISSUE TITLE
upgrade and install templates have empty strategy/status fields

### ISSUE THREAD

**Issue by cppforlife** [linkerd/linkerd2#2962]
## Feature Request

Remove `status: {}` and `spec.strategy: {}` fields from Deployment configurations produced by install/upgrade commands.

### What problem are you trying to solve?

I am using kapp (from https://k14s.io/; I'm one of the authors for these tools) to deploy produced YAML configuration from install/upgrade commands. It looks something like this: `linkerd upgrade | kapp deploy -a linkerd -f- -c -y`. This works brilliantly with one exception. Currently both install/upgrade commands produce empty `status` and `strategy` fields, which makes kapp consider Deployments as changed since on the server side these fields were populated (example output: https://gist.github.com/cppforlife/59bce65ed38dcfa6612b661707f50f85).

To bypass this annoyance I am currently using ytt (also from k14s) to remove those fields before piping output into kapp, but ideally this would not be necessary.

```bash
linkerd upgrade | ytt -f-  -f /tmp/linkerd-patches.yml --ignore-unknown-comments=true | kapp deploy -a linkerd -f- -c -y
```

```yaml
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Deployment"}),expects="1+"
---
spec:
  #@overlay/remove
  strategy: null
#@overlay/remove
status: null
```

When empty fields are removed diff output is a lot better. Example output from 2.3.1 to 2.3.2 update: https://gist.github.com/cppforlife/114e41f964a1ddd821a38d0c08f0f508

Is there a reason why these fields are present in the configuration output? And can we remove them? I would be happy to provide a PR if removal is OK-ed.
