### ISSUE TITLE
linkerd appears to mislabel incoming traffic from GKE ingresses

### ISSUE THREAD

**Issue by memory** [linkerd/linkerd2#3103]
### What is the issue?
Inbound traffic to deployments in the "default" namespace is, somehow, being marked as coming from the fluentd-gcp pod in the kube-system namespace in Google Kubernetes Engine clusters.

![image](https://user-images.githubusercontent.com/394064/61468796-1798a880-a94c-11e9-90e1-fa8dd528daf2.png)

The "live calls" view generates a tap link with a source of the fluentd-gcp pod and a destination of the deployment in question:

```
linkerd tap pod/fluentd-gcp-v3.1.1-svgcw --namespace kube-system --to deployment/auth --to-namespace default --path /ping
```

...but no traffic is ever seen in the tap.  (To be clear the lack of output in the tap is, I believe, _correct_: fluentd-gcp is the log aggregator to stackdriver for GKE clusters, and would not be sending REST queries to our microservices.)

### How can it be reproduced?

Slightly elided, here are our ingress, service and deployment configs:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: ingress-cert-1
    kubernetes.io/ingress.global-static-ip-name: auth-address
  name: auth
  namespace: default
spec:
  backend:
    serviceName: auth
    servicePort: service-port
---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: auth
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: service-port
    nodePort: 32163
    port: 54323
    protocol: TCP
    targetPort: pod-port
  selector:
    app: auth
  sessionAffinity: None
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '8'
  labels:
    app: auth
  name: auth
  namespace: default
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth
    spec:
      containers:
        image: gcr.io/project-id/image:version
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 80
          name: pod-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: pod-port
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

### Logs, error output, etc

I don't have anything to add here but let me know if there are specific linkerd pod logs that would be helpful to get.

#### `linkerd check` output

```text
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version:
```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.9-gke.7", GitCommit:"b6001a5d99c235723fc19342d347eee4394f2005", GitTreeState:"clean", BuildDate:"2019-06-24T19:37:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.7-gke.25", GitCommit:"d4c79083ab6dea5d26ef4ed8d50b145268349bc3", GitTreeState:"clean", BuildDate:"2019-06-22T16:10:31Z", GoVersion:"go1.10.8b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster Environment: GKE
- Host OS: Google COS
- Linkerd version:
```
Client version: stable-2.4.0
Server version: stable-2.4.0
```
