### ISSUE TITLE
Linkerd fails to route if port mapping is incorrect

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3117]
It is possible to define a port-mapping which maps to a port where no server is listening.  Consider the following:

```yaml

---
kind: Namespace
apiVersion: v1
metadata:
  name: bb

---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: bb
spec:
  clusterIP: None
  selector:
    app: server
  ports:
  - name: http
    port: 8080
    targetPort: http

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
  namespace: bb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:

      - name: pause
        image: gcr.io/google_containers/pause-amd64:3.0

      - name: bb
        image: buoyantio/bb:v0.0.3
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          exec /out/bb terminus \
            --h1-server-port=8080 \
            --response-text=IAMABANANA
        ports:
        - containerPort: 6666
          name: http

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
  namespace: bb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:

      - name: slow-cooker
        image: buoyantio/slow_cooker:1.1.0
        imagePullPolicy: IfNotPresent
        command:
        - "/bin/bash"
        args:
        - "-c"
        - |
          exec slow_cooker \
            -concurrency 10 \
            -qps 20 \
            -interval 1s \
            -metric-addr 0.0.0.0:9990 \
            http://server.bb.svc.cluster.local:8080
        ports:
        - name: admin-http
          containerPort: 9990
```

Notice that the service defines a port called `http` which maps port `8080` to the container's `http` port.  The server defines its `http` port to be port `6666` where there is no listener.

Deploying this and watching the client's logs, we can see that requests are flowing successfully, which means that the client has connected to the server's port 8080, ignoring the port-mapping.

If we then inject Linkerd, requests start to fail as Linkerd will respect the port-mapping and attempt to connect to port 6666:

```
ERR! [     5.772211s] proxy={server=in listen=0.0.0.0:4143 remote=10.0.0.86:50000} linkerd2_proxy::app::errors unexpected error: error trying to connect: Connection refused (os error 111) (address: 127.0.0.1:6666)
```

It seems that Kubernetes will fall back to the unmapped port if it cannot establish a connection to the mapped port.  Is this a bug in Kubernetes?  Or a feature?  Applications which rely on this behavior will stop working when injected with Linkerd.

I don't think we should necessarily replicate this functionality in Linkerd, but I wanted to file this issue so that we could be aware of this behavior.
