### ISSUE TITLE
Question regarding TrafficSplit backend service validation

### ISSUE THREAD

**Issue by cpretzer** [linkerd/linkerd2#3124]
While following the TrafficSplit instructions in the [smi-spec repository](https://github.com/deislabs/smi-spec/blob/master/traffic-split.md) to test the traffic split feature of linkerd 2.4.0, I mistyped the name of a backend service and the traffic was not split, which is not surprising.

The purpose of this issue is to answer the question: 
> Should linkerd be responsible for validating the existence of services that are configured as backends?

The SMI Spec page follows this deployment sequence:
- Deploy the `Service` and `Deployment` resources for version 1 (v1) of the service
- Deploy the `TrafficSplit` resource
- Deploy the `Service` and `Deployment` resources for version 2 (v2) of the service

One of the challenges I see here is the timing around validation of the backend service defined in the `TrafficSplit` resource. The example below includes modified examples of the resources to implement the traffic split feature. Since the TrafficSplit resource is deployed before `v2` of the service is created, attempting to validate the backend service upon creation will not be effective.

One approach would be to write a more detailed message when a service times out or is unreachable. This would apply to a set of issues/errors larger than just a misconfigured TrafficSplit resource.

While debugging the issue, the messages that I received from the default log level of the proxy were similar to this:
`
proxy={server=out listen=127.0.0.1:4140 remote=10.10.45.84:41846} linkerd2_proxy::app::errors request aborted because it reached the configured dispatch deadline`

## Deployment and Services for v1
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar-dep-v1
  labels:
    app: foobar
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar
      version: v1
  template:
    metadata:
      labels:
        app: foobar
        version: v1
    spec:
      containers:
        image: hashicorp/http-echo
        imagePullPolicy: Always
        name: foobar-container-v1
        ports:
        - containerPort: 5678
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: foobar-svc-v1
spec:
  type: LoadBalancer
  selector:
    app: foobar
    version: v1
  ports:
  - name: http
    port: 5678
    targetPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: foobar-svc
spec:
  type: LoadBalancer
  selector:
    app: foobar
  ports:
  - name: http
    port: 5678
    targetPort: 5678
```

## TrafficSplit Resource
```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: foobar-rollout
spec:
  service: foobar-svc
  backends:
  - service: foobar-svc-v1
    weight: 500m
  - service: foobar-svc-v2
    weight: 500m
```

## Deployment and Services for v2
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar-dep-v2
  labels:
    app: foobar
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foobar
      version: v2
  template:
    metadata:
      labels:
        app: foobar
        version: v2
    spec:
      containers:
        image: hashicorp/http-echo
        imagePullPolicy: Always
        name: foobar-container-v2
        ports:
        - containerPort: 5678
          name: http
        resources:
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: foobar-svc-v2
spec:
  type: LoadBalancer
  selector:
    app: foobar
    version: v2
  ports:
  - name: http
    port: 5678
    targetPort: 5678
```

## Invalid TrafficSplit configuration
In my case, I used the deployment name for the service and the misconfiguration caused requests to one of the backend services to timeout:
## TrafficSplit Resource
```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: foobar-rollout
spec:
  service: foobar-svc
  backends:
  - service: foobar-dep-v1 # <- this was the issue
    weight: 500m
  - service: foobar-svc-v2
    weight: 500m
```
