### ISSUE TITLE
Missing outbound proxy stats when traffic split is in effect

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#3136]
When a traffic split is in effect, the outbound request stats (e.g. `response_total`) stop updating.  For example, consider the following prometheus graphs:

![Screen Shot 2019-07-24 at 1 34 01 PM](https://user-images.githubusercontent.com/3979810/61830785-ea9f3680-ae20-11e9-8b0c-151b25393334.png)

The trough on the left half of the graph is the duration in which a traffic split existed for the books service.  Notice that the outbound `route_response_total` from webapp to books dropped significantly and the inbound `response_total` on books dropped a corresponding amount.  This is not surprising because we have shifted traffic away from this service.  

However, also notice that during this period the outbound `response_total` from webapp to books dropped to zero.  This is not expected.  As we can see in the previous stats, requests are clearly flowing from web to books, but this stat is not reporting them.

Removing the traffic split returns the situation to normal and all stats resume updating correctly.

## Reproduction

Install Linkerd stable 2.4.0 and then

```bash
linkerd inject https://run.linkerd.io/booksapp.yml | kubectl apply -f -
linkerd apply -f error-split.yaml
```

error-split.yaml:
```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: error-split
spec:
  service: books
  backends:
  - service: books
    weight: 900m
  - service: error-injector
    weight: 100m
```
