### ISSUE TITLE
Consider ClusterRole for tap.linkerd.io

### ISSUE THREAD

**Issue by siggy** [linkerd/linkerd2#3177]
PR #3167 introduced a TAP APIService, authorized via RBAC. Aside from cluster-admins, tapping resources now requires new explicit RBAC privileges.

Consider introducing a ClusterRole to give users tap privileges.

Context: https://github.com/linkerd/linkerd2/pull/3167#pullrequestreview-269306856

**Comment by grampelberg** [comment]
This is a little nonsensical because it theoretically allows tapping secrets, but it works:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: foobar
rules:
- apiGroups: ["tap.linkerd.io"]
  resources: ["*/tap"]
  verbs: ["watch"]
```
