### ISSUE TITLE
Auto-Inject does not work with PSPs that include profile names

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3201]
### What is the issue?

When using a PSP that includes profile names, injection prevents pods from ever being created:

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: default
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
```

### Possible solution

- `linkerd inject --manual`
- Wait for k8s 1.16
