### ISSUE TITLE
Don't call the proxy-injector for pods in the kube-system namespace

### ISSUE THREAD

**Issue by dwj300** [linkerd/linkerd2#3305]
### What is the issue?
On AKS, if the tunnelfront pod is not scheduled, very bad things happen with the cluster. In our case, we had an unhealthy node, which happened to contain both tunnelfront and one of our proxy-injectors. When the pods were deleted from the unhealthy node, tunnelfront could not be rescheduled since we were running linkerd in --HA mode, which sets the FailurePolicy on the MutatingAdmissionWebhook to Fail and the proxy-injector was not reachable. The proxy-injector was unable to be rescheduled on another node due to CPU resource constraints (something we are in the process of fixing now). We ran our cluster with `--HA --controller-replicas=2` since our cluster is so small, and we are currently working to identify why the second proxy-injector was either not reachable, or not scheduled.

I was wondering if either an option or a default setting to exclude the `kube-system` namespace from the admissions webhook could be added. From glancing at the docs, it seems like the following diff would would work:

```
webhooks:
- name: linkerd-proxy-injector.linkerd.io
  namespaceSelector:
    matchExpressions:
    - key: linkerd.io/is-control-plane
      operator: DoesNotExist
    - key: namespace
      operator: NotIn
      value: kube-system
```

Would this be something the team would be interested in? More than happy to send a PR :) 

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...) AKS
- Host OS: Ubuntu 16.04
- Linkerd version: stable-2.4.0

### Additional context
Unfortunately, our DRI applied many mitigations, and as a result we do not have many logs. We have the k8s master logs that we have been digging through.
