### ISSUE TITLE
Granular RBAC for statistics

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3312]
## What problem are you trying to solve?

Many organizations have teams sharing the same cluster which should not see each other's data. This was addressed for tap as part of #2725. Now that it is possible to have granular, Kubernetes based RBAC policies for tap, statistics should provide a similar benefit.

### How should the problem be solved?

- Create an APIService (ala #2725) that exposes an RBAC aware API through the api-server.
- Move the CLI commands that rely on stats to use the APIService.
- Move the dashboard's underlying stat implementation over to use the APIService.

The API should look like:

```bash
/apis/stat.linkerd.io/v1alpha1/namespaces/
/apis/stat.linkerd.io/v1alpha1/namespaces/<NS>/
/apis/stat.linkerd.io/v1alpha1/namespaces/<NS>/<RESOURCE>/
/apis/stat.linkerd.io/v1alpha1/namespaces/<NS>/<RESOURCE>/<NAME>/
```

The RBAC should look like:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap
rules:
- apiGroups:
  - stat.linkerd.io
  resources:
  - deployment
  - pod
  verbs:
  - get
  - list
```
