### ISSUE TITLE
Add selectors to MWC 

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3346]
## What problem are you trying to solve?

When running in `--ha` mode, it can be surprising to have your cluster broken by taking down the proxy injector. This usually happens because of ordering issues with kube-system pods coming up (tunnelfront, cni for example).

While it is not possible to modify kube-system to add a label and skip, it *is* possible without any real downsides to add a label to the `namespaceSelector` that skips any namespace. The MWC should be updated to look like:

```yaml
  namespaceSelector:
    matchExpressions:
    - key: linkerd.io/skip-webhook
      operator: DoesNotExist
    - key: linkerd.io/is-control-plane
      operator: DoesNotExist  
```

The docs then need to be updated for HA to point out that users should probably make this modification.
