### ISSUE TITLE
Service profile response classes for gRpc services

### ISSUE THREAD

**Issue by bourquep** [linkerd/linkerd2#3376]
### What problem are you trying to solve?

I have generated service profiles for my gRpc services by using `linkerd profile --proto` with my proto files. This works well, I can see per-route metrics and such.

Now, I'd like to configure some of those routes to treat specific grpc status codes as success (to remove a few false-negatives from my success rate metrics).

However, I am unable to do so. The current service profile spec expects status codes between 100 and 599, i.e. HTTP status codes.

### How should the problem be solved?

By allowing this, for example, in the service profile CRD (treat `7 - permission denied` and `16 - unauthorized` as successes):

```
  - condition:
      method: POST
      pathRegex: /xyz
    name: Xyz
    responseClasses:
      - isFailure: false
        condition:
          any:
            - status:
                min: 7
                max: 7
            - status:
                min: 16
                max: 16
```

Right now the above route definition yields:

>admission webhook "linkerd-sp-validator.linkerd.io" denied the request: ServiceProfile "schools.studyo-staging.svc.cluster.local" has a response class with an invalid condition: Range minimum must be between 100 and 599, inclusive
