### ISSUE TITLE
Controller CrashLoopBackoff in 2.5.0 with more than 3K pods

### ISSUE THREAD

**Issue by christianhuening** [linkerd/linkerd2#3379]
### What is the issue?

We updated from Linkerd 2.4.0 to Linkerd 2.5.0. After upgrading the controller pods started crashlooping and the linkerd proxy errored with "too many in-flight messages". We have a quite large setup with 50 nodes in our cluster, but 3400 Pods running, most of them meshed. 

We also noticed that Linkerd Prometheus crashlooped. First we thought this was due to resource limits, so we increase them from 8Gi to 48Gi. It consumed a fair amount of memory and then stopped crashing at around 28Gi. However the Controller Pods still crashlooped, apparantely the `destination` container was crashing frequently.

### How can it be reproduced?

Upgrade our cluster to 2.5.0... ;-) 

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

### Environment

- Kubernetes Version: 1.15.2
- Cluster Environment: (GKE, AKS, kops, ...): bare-metal
- Host OS: ContainerLinux
- Linkerd version: 2.4.0->2.5.0

**Comment by christianhuening** [comment]
I should add, that it worked flawlessly on our Dev Cluster, which has 7 nodes and something between 500 - 900 Pods.

**Comment by cpretzer** [comment]
@christianhuening I'm working on reproducing this now. Can you confirm that linkerd is running with the `--ha` flag set?

**Comment by christianhuening** [comment]
@cpretzer yes, i can confirm

**Comment by cpretzer** [comment]
thanks @christianhuening I've run a test using the _emojivoto_ application and scaled up to 3100 pods. 

I see the `CrashLoopBackOff` from _Prometheus_, but the `linkerd-controller` instances appear to be stable and there are no restarts.

Are you using the `linkerd-cni` plugin? If so, I'll run another test with that.

**Comment by christianhuening** [comment]
no, we're not yet using linkerd-cni plugin, but if you could test that anyways we would be graceful since we are interested in trying it out ;-) 
Can these load-tests be added to an automated pipeline for each release? That would be awesome.

**Comment by olix0r** [comment]
> Can these load-tests be added to an automated pipeline for each release?

I totally agree that we need to verify scale between releases. It's going to be tricky to automate this, though, because it means we need a k8s cluster hanging around that we trust to be stable at 3K pods, and we don't. However, it seems more likely that, as we make changes the prometheus scrape config, especially, that we ensure we have a very detailed understanding of how new metrics scale.

i.e. I think it's _most_ important for us to develop a more detailed performance model for prometheus, especially, so that we can at least _predict_ what resources will be needed at a given scale. A good model will allow us to scale beyond our ability to instrument specific tests.

Your point isn't lost, though. Even once we have a better model, we'll need a means to detect regressions against it.

**Comment by grampelberg** [comment]
@christianhuening if you happened to know someone would could donate a cluster of that size to the project for testing .... I'm sure we'd appreciate it!

**Comment by christianhuening** [comment]
@grampelberg good point ;-) Of course that's problematic and sadly I don't know anyone. Only possibility could be the official CNCF cluster, but I have no idea whether one can use that to run a 3000 pod test.

**Comment by cpretzer** [comment]
@christianhuening if you find a cluster let us know :)

With regard to this issue, my testing methodology involved slowly scaling up the pods over a period of a few hours.

In the scenario where you saw this behavior, can you tell me what the pod lifecycle profile was like in the environment? I'd like to know:
- Were pods being added and removed at the same? I'm specifically looking for pod lifecycles which would add load to the scheduler and its associated components.
- How quickly was the scale-out to 3k pods?

**Comment by cpretzer** [comment]
@christianhuening just checking in to see if you continue to see the "too many in-flight messages" errors. My last few tests haven't yielded similar results.

Regarding the prometheus conversation, there is some work being done on this. You can follow along here: https://github.com/linkerd/linkerd2/issues/3692

**Comment by christianhuening** [comment]
@cpretzer we're on 2.6 now and the last time the controller reported them was on Nov 30th. So still present, I would say.

As we're releasing quite a few times a day, we have a good amount of pod churn. I do not have any numbers handy sadly. the pod count itself is rather stable I would say

**Comment by cpretzer** [comment]
@christianhuening thanks for the update.

The next time that this happens, can you run `kubectl describe po <linkerd-controller-pod-name>` and send the output? If there is sensitive info in there, you can DM it to me on slack.

I'm looking specifically for the states of each of the containers in the pods, as well as any events that occurred to trigger the CrashLoopBackoff. In fact, `kubectl get ev --sort-by="{.lastTimestamp}"` in the Linkerd namespace should have the detailed event information.

It will also help to get the logs from the containers in the pod that have failed.

**Comment by christianhuening** [comment]
from my point of view we can close this issue. After tweaking the 2.6.x resource requests to our size it is working like a charm ever since.

**Comment by christianhuening** [comment]
```
controllerPublicAPIResources:
  limits:
    cpu: "500m"
    memory: "2Gi"
  requests:
    cpu: "100m"
    memory: "1Gi"

controllerDestinationResources:
  limits:
    cpu: "2"
    memory: "6Gi"
  requests:
    cpu: "100m"
    memory: "2Gi"

injectorResources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "512Mi"

tapResources:
  limits:
    cpu: "1"
    memory: "2Gi"
  requests:
    cpu: "100m"
    memory: "2Gi"

identityResources:
  limits:
    cpu: "1"
    memory: "250Mi"
  requests:
    cpu: "100m"
    memory: "50Mi"

destinationResources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "100m"
    memory: "250Mi"

prometheusResources:
  limits:
    cpu: "8"
    memory: "32Gi"
  requests:
    cpu: "5"
    memory: "16Gi"

prometheusLinkerdProxyResources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"
```

Here's what we run this with. Examples taken from custom helm chart
