### ISSUE TITLE
Templatize port number for nginx ingress sample definition

### ISSUE THREAD

**Issue by poochwashere** [linkerd/linkerd2#3422]
Problem: 
If you have more than one endpoint running on different ports you will need to generalize the port number for traffic to route to the destined service. 

The example on `using-ingress.md` lists the following...
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:80;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: 80
```
If you have multiple services behind the same ingress they would both need to be listening on port 80 for this to work (which our services were not). 

Suggestion: 
Use the nginx var `$service_port` with a multiple endpoints as a more expansive example. 
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        backend:
          serviceName: web-svc
          servicePort: 80
      - path: /another-endpoint
        backend:
          serviceName: another-svc
          servicePort: 8080
```
I would be happy to submit a PR if this is deemed helpful.
