### ISSUE TITLE
TLS nginx ingress of grpc request to linkerd-meshed grpc service errors with 502

### ISSUE THREAD

**Issue by mikeslemmer** [linkerd/linkerd2#3437]
### What is the issue?

TLS ingress of a grpc request to the emoji grpc service of the emojivoto demo app can be accessed fine using grpcurl until you add the service to linkerd mesh at which point it stops working.

### How can it be reproduced?

* Install linkerd-2.5.0 and the emojivoto demo app in the emojivoto namespace of a kubernetes cluster.
* A public IP will be assigned to the web-svc service, and accessing that via a browser works fine.
* Create an nginx ingress with a valid SSL cert which sends web traffic to the web-svc service and also allows grpc traffic to access the emoji-svc service directly. Here is a gist of the relevant yaml files: https://gist.github.com/mikeslemmer/3c27b028cbd9d7c843085cf2e9f35f2e -- note that you will need to replace the public hostname and tls certificate with your versions.
* The web-svc service should work properly through a browser if you navigate to https://whateverhostnameyouused.com
* The grpc service should also work fine using grpcurl. Here is a sample commandline: `./grpcurl -v -proto ./emoji.proto whateverhostnameyouused.com:443 emojivoto.v1.EmojiService/ListAll`  -- note that you need to make the emoji.proto file available to the command.
* Now, inject the annotations to put the `emoji` service into the linkerd mesh using a command line like : `ubectl -n emojivoto get deploy emoji -o json | ./linkerd2-cli-stable-2.5.0 inject - | kubectl apply -f -`
* Finally, try again the grpcurl command and it will fail.

### Logs, error output, etc

grpcurl output when it fails: 
ERROR:
  Code: Internal
  Message: transport: received the unexpected content-type "text/html"

nginx output when grpcurl succeeds:
{"upstreamStatus":"200","requestLength":97,"ingress":"sandbox-ingress-grpc","status":"200","service":"emoji-svc","requestTime":0.001,"namespace":"emojivoto","host":"whateverhostnameyouused.com","method":"POST","upstreamResponseTime":0.004,"upstreamResponseLength":2182,"responseLength":2288,"upstreamLatency":0.004,"path":"\/emojivoto.v1.EmojiService","endpoint":"10.240.0.19:8080"}

nginx output when grpcurl fails:
{"upstreamStatus":"502","requestLength":97,"ingress":"sandbox-ingress-grpc","status":"502","service":"emoji-svc","requestTime":0.001,"namespace":"emojivoto","host":"whateverhostnameyouused.com","method":"POST","upstreamResponseTime":0.004,"upstreamResponseLength":0,"responseLength":294,"upstreamLatency":0.004,"path":"\/emojivoto.v1.EmojiService","endpoint":"10.240.0.15:8080"}

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cluster Environment: AKS
- Host OS: Linux
- Linkerd version: 2.5.0

### Additional context

I discussed this issue with @grampelberg in the Slack, and he asked me to submit an issue so he could try to repro.

**Comment by grampelberg** [comment]
I can't replicate this at all. Here's all my config:

```yaml
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: default-cert
  namespace: emojivoto
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNxRENDQVpBQ0NRQzAyVWw2RGJCTEx6QU5CZ2txaGtpRzl3MEJBUXNGQURBV01SUXdFZ1lEVlFRRERBdGwKZUdGdGNHeGxMbU52YlRBZUZ3MHhPVEEyTVRReE56RTRNalphRncweU1EQTJNVE14TnpFNE1qWmFNQll4RkRBUwpCZ05WQkFNTUMyVjRZVzF3YkdVdVkyOXRNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDCkFRRUFwQitxaWF0aE45T1V2YjZxUDhDRk5IRjhYU2V6WmV4SzJrTzNnNEU4UnhoKzhmaGpYL3JmK0NqVmJVVUoKM2psWDN0ZGMxc1hQZ3NnN3ViNVFTNW1QQ3UzY2dieDZiQnpjQnRyd3U0Y0luRlllRmtGaGR3UllmNE5mNzZhSApXMnpkcnZna0tRSVB0cWUzVWlWcGkyeFJtMzRDSWRHMWR0ZVBWbWt4Sk4wbUgxVmlVaXlJcEFTK29FSWNyZGxFCjJ1NitMbWkwTEMxMzA4VzcvR21KdGEzYTFRM2F5eCtDSm5VUFU3Vm9RcHU4V3hyQU02ZllzUGJKYUh4Z0pOci8KdzlWR1VWTHpUMzJxRUJCTGM0RjVubHlCb0RYUVRPYTE4czh0OU1Ob1Bvd1pVZjk3NEhPNVVjU1FodW9TamxLVgpNUjlLemIrNDdla2JCN0lPYU5ZSFBkTGFKUUlEQVFBQk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnQ1Q1ZTCmZKNU5KL2hNOExtSCt0dWN5RW1ObmpMSk5IaFBaOVFzczlVNDh2Zkg1cEo1MjRRSjU2RFRyVWh6TWFtaDJLdTkKS0QrUkxuVzZ4SksralBsMFBZRkVBdlhvMmw1ZnpLVDhWbmVwSXBRdXJmRHdTWmpaZW81M0hLMitzRzdjUENldQphK0FPVForNHNNclQ4TWk0SGgrRnk4ZWxCZ3hCZ3BVa1Bnck1sMVFLbGRrWldyOWdnbzk0alExTFl1Z0tNaUduClBSZDBxQW9CK2tMMm9LSGZ2aDRVb05jeUtoR3FkZUczK1FpQlFheGNkK3N4QzFKSjdLRUE5Rll2U1YvMUQxTDQKUnVqaXZXRE1uK3RBd2YyZDgyVVNqZ2tOeDk0RmJ0T1VWaDNtQXU5U1FZU3p2WkpxTGZRYXl4RHpjYmxvU0xnMgpkQy9CY1g0UFpHbm5wcE1vCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRQ2tINnFKcTJFMzA1UzkKdnFvL3dJVTBjWHhkSjdObDdFcmFRN2VEZ1R4SEdIN3grR05mK3QvNEtOVnRSUW5lT1ZmZTExeld4YytDeUR1NQp2bEJMbVk4SzdkeUJ2SHBzSE53RzJ2Qzdod2ljVmg0V1FXRjNCRmgvZzEvdnBvZGJiTjJ1K0NRcEFnKzJwN2RTCkpXbUxiRkdiZmdJaDBiVjIxNDlXYVRFazNTWWZWV0pTTElpa0JMNmdRaHl0MlVUYTdyNHVhTFFzTFhmVHhidjgKYVltMXJkclZEZHJMSDRJbWRROVR0V2hDbTd4YkdzQXpwOWl3OXNsb2ZHQWsydi9EMVVaUlV2TlBmYW9RRUV0egpnWG1lWElHZ05kQk01clh5enkzMHcyZytqQmxSLzN2Z2M3bFJ4SkNHNmhLT1VwVXhIMHJOdjdqdDZSc0hzZzVvCjFnYzkwdG9sQWdNQkFBRUNnZ0VBQkFUMmd6cWNQZWJEbk1YL20ySVdvUXNxZFltVVhpbWtSNllpNTJpUjFsZm0KTy96T1NqcDFvN2swU09ISTlSVklicCt0bVdEc3pSSWtURTg1M2pBYmpiUDNrNEhQS2Jpbk5zL0QxNFBlRlI0Uwp6STY3V1ZQVTZ3S0hwZkhaSE1jVXdzVTI5WDRrYmwrN0lKcmo4OU1xU0htVWljbDkvVFFZUVpCLzhKd3Q0OVNFCmJ2d2YxOUw5TTVJbWdqS2ltdllUdi9HbkJVajBlMXpuM094MitxZ0pFV0RBMzhJTUZ1VE1qY29SRWVwbE5ndEIKcXVHRUg3cHN1TS8rT1hiUFUrUkZzcm1PZzkxelJUdDJ5ZWgrK0t2bkpZK0JaWUVNT1hRY3pqbHNaVDd0WkVEdgpNZlV5UnZGMGI3Z1hTY2hZRFNCb3RmNktmZXQzR05iVXhEbXNiSFpYSFFLQmdRRFlSeXFIZkR0TTQyZUhvQVNqCjlGZnp6RzBBNlBlcUZEMVgvQ080QjNkVEpCeDRBamFqOEhLU2dQYytISW9Vb0lQUVllSlZuaEVCSzA2UXc1MTkKclZjSGJJSjY1WUJma0NvS3ZGa050MWFmaWhaUDU3amdJS0gwVUhpOGk0VU9hZE9ZOWlIRFVkNzZvTmh5Szd3KwpkdW1LMzN0T0l2NWZPdzFNWnlJeWFzd0J3d0tCZ1FEQ1JGYmpCSkJXc1ZCSUhtVlQ3UVVOWHJxaEZ0OWtHNERiCnA0bWZhdzkvQXgxZVBMaG5aRWh2K0NCd3ByWm1iRE1paE56TVo5TU1kOEx3S2d3WWk2R1BtaUNBZXppYW5ybS8Kbm95YmtSSmFiNml1QXRyd0R3MXhhZUNwcmJaa2hKY295MUI4Nm1nb0lrYTlSbW9HR3FLT1F1d2luOXU4M2dwcwpXR2F3UnR6Tjl3S0JnRVBTelh0L2NmbEN0d3pKR2F0d3pNUWZyMjlCbjZrdWY2NC8yOU95UTdGRytjYUlxeW51CkZYL3NBWnp3eGp5QnVkUjNYY3NMcnJsM0kwUXlsQWo5ZXZWUkNmb1FUcG1wVkFYWjJ2TjZNeWdFM2NwaEdKRHcKcXRrN0F5SGRmdlJ1SzNVa2VxSU40cWNtR2JwMERLeHFEZ01HNGx3MmpSN0FIZ04vdERHclhCNlJBb0dCQUpqZgoySlFid2s1R2lNdklCNnNzeVI0RlhzNW54bkhyNXRKMEhDdjB2eVFQV213UFVub2lnNUtCYTEzYkE0ekVOdFZDClF0TWtIUVFodHFqeUhjU3ZGUHVCcVhRU0E3QkJtaUM5N3g1NDRqMkN3dlgwenorOFNMTG9RK0NqRC9ZNEZSQUkKTnhXbURVTVAvaVR5cFhxYU9UUEVYRGkvSGRlWjBCQUUzUUo1TVVkdkFvR0FSdjRsb1p5aGJ5NGdYTnovU0x5cApERzUvRFV0d1JkcW1JUDNpSE1mekxnYkFLWGpXVmswQ012Z3JkbWdiUUhXVTcxcFp1dTlCY200WG1aM3RhWGw5CnlFWVpOUDNpMWRHRXo4VjB2QjZhdHdMSzVtTWgzTHdZbUpZaTRpSW9XMU5kSDFIa0JDNVpBUmlKS1haWFFJWTIKcGdZZVJycHNDVzk3LzlrL0xjSWN5NXc9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header :authority $host;
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
  name: emoji
  namespace: emojivoto
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: emoji-svc
          servicePort: 8080
  tls:
  - secretName: default-cert
    hosts:
      - example.com
```

And the command that is working for me:

```bash
grpcurl -authority example.com -insecure -proto Emoji.proto \
                $(kubectl -n nginx get svc --no-headers | awk '{ print $4 }' | head -n1):443 \
                emojivoto.v1.EmojiService/ListAll
```
