### ISSUE TITLE
integration test: custom cluster domain

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#3517]
Now that users can change the cluster domain, we should setup an integration test that executes all of the standard behavior for alternate cluster domains. (Does kind support custom cluster names?)

**Comment by siggy** [comment]
There's some pretty fine-grained kubeadm control via kind, check out:
https://kind.sigs.k8s.io/docs/user/quick-start#enable-feature-gates-in-your-cluster
https://raw.githubusercontent.com/kubernetes-sigs/kind/master/site/content/docs/user/kind-example-config.yaml

**Comment by grampelberg** [comment]
```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    dnsDomain: "other.local"
```

That's the snippet that'll do the cluster domain for you. It took me awhile to find [all the options](https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2).
