### ISSUE TITLE
cert-manager integration

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3531]
## What problem are you trying to solve?

While linkerd-proxy manages certificate rotation for the actual proxy certs, the core certificate used by the built-in CA (identity) is not managed today. In addition, it can be difficult to create your own external trust root and keys.

### How should the problem be solved?

Many k8s clusters today use [cert-manager](https://github.com/jetstack/cert-manager) as a way to create and refresh certificates. It would be nice to use an existing community standard to solve certificate creation and rotation. To do this, a CLI option can be added:

```bash
linkerd install --self-managed-certs
```

This would assume `linkerd-identity-issuer` is already created in the `linkerd` namespace. If it is not, `install` should fail. The content of this secret should be:

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
    name: linkerd-identity-issuer
    namespace: linkerd
data:
    ca.crt:  {{ }}
    tls.crt: {{ }}
    tls.key: {{ }}
```

Note:

- The secret generated by cert-manager is a little bit different than the one that is there right now.
- Identity will need to reload the secret as it is rotated by cert-manager.
- `ca.crt` is the content of `linkerd-config.data.global.identityContext.trustAnchorsPem`.
- Documentation will need to explain the cert-manager configuration to get this all setup.

### Open Questions

- Kubernetes allows CSRs and has a root CA cert. Does it make sense to just use all that machinery instead?

### Example

After setting cert-manager up, you can get the cert created by adding the following to your cluster:

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
data:
  tls.crt:  {{ .Identity.TrustAnchorsPEM }}
  tls.key: {{ trust anchor key }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  keyAlgorithm: ecdsa
```

**Comment by zaharidichev** [comment]
@grampelberg @ihcsim 
So I read through all resources I could find and just wanted to make sure I understand the essence of it all. So pretty much what needs to happen is the following: 

**We assume that we have:** 
Cert manager installed and setup to manage the root cert. As a result of that we end up with a secret in the following form that gets periodically updated with the certificates that cert-manager is governing.

```
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
    name: linkerd-identity-issuer
    namespace: linkerd
data:
    ca.crt:  {{ }}
    tls.crt: {{ }}
    tls.key: {{ }}
```

**On the cli side:** 
We need to make sure that all the prerequsites are met when we install with an option `--self-managed-certs` (i.e. the secret is present). Additionally we probably want to ensure we do not create such a secret ourselves as part of the identity service yaml definition. I guess we also avoid generating or reading any kind of certs. 

**On the identity service side:** 
Configuring it to mount the desired secret and account for the difference in data format between what we have at the moment and what cert-manager produces. I also assume here we have to read the metadata of the Issuer resource of cert-manager in order to get an idea of when we should re-reload all the credentials data (duration + renewBefore). We then make use of that to make sure these are reloaded by the identity service periodically. 

**On the proxy side:** 
I see that currently we store the trust anchors as an env var in the proxy. Am I wrong in saying that this needs to be refreshed according to the same logic used by the identity service?  

Am I missing some major part of this all? If not, I can go ahead and put together separate issues for the work that needs to be carries out
