### ISSUE TITLE
Proxy Injector going crazy

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#3536]
### What is the issue?

The following yaml works fine, when deployed normally.
```yaml
---
###
### linkerd-collector RBAC
###
---
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd-tracing
---
###
### linkerd-collector RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-collector
  namespace: linkerd-tracing
  labels:
    linkerd.io/control-plane-component: linkerd-collector
    linkerd.io/control-plane-ns: linkerd-tracing
---
###
### linkerd-jaeger RBAC
###
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: linkerd-jaeger
  namespace: linkerd-tracing
  labels:
    linkerd.io/control-plane-component: linkerd-jaeger
    linkerd.io/control-plane-ns: linkerd-tracing
---
###
### Tracing Collector Service
###
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-collector-conf
  namespace: linkerd-tracing
  labels:
    linkerd.io/control-plane-component: linkerd-collector
    linkerd.io/control-plane-ns: linkerd-tracing
data:
  linkerd-collector-config: |
    receivers:
      opencensus:
        port: 55678
      zipkin:
        port: 9411
    queued-exporters:
      jaeger-all-in-one:
        num-workers: 4
        queue-size: 100
        retry-on-failure: true
        sender-type: jaeger-thrift-http
        jaeger-thrift-http:
          collector-endpoint: http://linkerd-jaeger.linkerd-tracing:14268/api/traces
          timeout: 5s
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-collector
  namespace: linkerd-tracing
  labels:
    linkerd.io/control-plane-component: linkerd-collector
    linkerd.io/control-plane-ns: linkerd-tracing
spec:
  ports:
  - name: opencensus
    port: 55678
    protocol: TCP
    targetPort: 55678
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    linkerd.io/control-plane-component: linkerd-collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-collector
  namespace: linkerd-tracing
  labels:
    linkerd.io/control-plane-component: linkerd-collector
    linkerd.io/control-plane-ns: linkerd-tracing
spec:
  selector:
    matchLabels:
      linkerd.io/control-plane-component: linkerd-collector
      linkerd.io/control-plane-ns: linkerd-tracing
  minReadySeconds: 5
  progressDeadlineSeconds: 120
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        linkerd.io/control-plane-component: linkerd-collector
        linkerd.io/control-plane-ns: linkerd-tracing
    spec:
      containers:
      - command:
          - "/occollector_linux"
          - "--config=/conf/linkerd-collector-config.yaml"
        env:
        - name: GOGC
          value: "80"
        image: omnition/opencensus-collector:0.1.10
        name: linkerd-collector
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 200m
            memory: 400Mi
        ports:
        - containerPort: 55678
        - containerPort: 9411
        volumeMounts:
        - name: linkerd-collector-config-vol
          mountPath: /conf
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: /
            port: 13133
      serviceAccountName: linkerd-collector
      volumes:
      - configMap:
          name: linkerd-collector-conf
          items:
            - key: linkerd-collector-config
              path: linkerd-collector-config.yaml
        name: linkerd-collector-config-vol
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: linkerd-jaeger
  namespace: linkerd-tracing
  labels:
    linkerd.io/control-plane-component: linkerd-jaeger
    linkerd.io/control-plane-ns: linkerd-tracing
spec:
  selector:
    matchLabels:
      linkerd.io/control-plane-component: linkerd-jaeger
      linkerd.io/control-plane-ns: linkerd-tracing
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8888"
        prometheus.io/scrape: "true"
      labels:
        linkerd.io/control-plane-component: linkerd-jaeger
        linkerd.io/control-plane-ns: linkerd-tracing
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.8
        ports:
        - name: collection
          containerPort: 14268
        - name: ui
          containerPort: 16686
      serviceAccountName: linkerd-jaeger
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-jaeger
  namespace: linkerd-tracing
  labels:
    linkerd.io/control-plane-component: linkerd-jaeger
    linkerd.io/control-plane-ns: linkerd-tracing
spec:
  selector:
    linkerd.io/control-plane-component: linkerd-jaeger
  ports:
  - name: collection
    port: 14268
  - name: ui
    port: 16686
```

but now when I enable injection to the namespace, by adding
```
  annotations:
    linkerd.io/inject: enabled
```

The proxy injector is going wild, and I'm seeing a lots and lots of those pods trying to be created. and the injection metrics are like
```
# HELP proxy_inject_admission_requests_total A counter for number of admission requests to proxy injector.
# TYPE proxy_inject_admission_requests_total counter
proxy_inject_admission_requests_total{admin_port="",annotation_at="",control_port="",disable_identity="",disable_tap="",enable_debug_sidecar="",enable_external_profiles="",image_pull_policy="",inbound_port="",init_image="",init_image_version="",namespace="linkerd-tracing",outbound_port="",owner_kind="deployment",proxy_cpu_limit="",proxy_cpu_request="",proxy_image="",proxy_log_level="",proxy_memory_limit="",proxy_memory_request="",proxy_uid="",proxy_version="",skip_inbound_ports="",skip_outbound_ports="",trace_collector=""} 2
proxy_inject_admission_requests_total{admin_port="",annotation_at="namespace",control_port="",disable_identity="",disable_tap="",enable_debug_sidecar="",enable_external_profiles="",image_pull_policy="",inbound_port="",init_image="",init_image_version="",namespace="linkerd-tracing",outbound_port="",owner_kind="deployment",proxy_cpu_limit="",proxy_cpu_request="",proxy_image="",proxy_log_level="",proxy_memory_limit="",proxy_memory_request="",proxy_uid="",proxy_version="",skip_inbound_ports="",skip_outbound_ports="",trace_collector=""} 1280
proxy_inject_admission_requests_total{admin_port="",annotation_at="workload",control_port="",disable_identity="",disable_tap="",enable_debug_sidecar="",enable_external_profiles="",image_pull_policy="",inbound_port="",init_image="",init_image_version="",namespace="linkerd-tracing",outbound_port="",owner_kind="deployment",proxy_cpu_limit="",proxy_cpu_request="",proxy_image="",proxy_log_level="",proxy_memory_limit="",proxy_memory_request="",proxy_uid="",proxy_version="",skip_inbound_ports="",skip_outbound_ports="",trace_collector=""} 446
# HELP proxy_inject_admission_responses_total A counter for number of admission responses from proxy injector.
# TYPE proxy_inject_admission_responses_total counter
proxy_inject_admission_responses_total{admin_port="",annotation_at="",control_port="",disable_identity="",disable_tap="",enable_debug_sidecar="",enable_external_profiles="",image_pull_policy="",inbound_port="",init_image="",init_image_version="",namespace="linkerd-tracing",outbound_port="",owner_kind="deployment",proxy_cpu_limit="",proxy_cpu_request="",proxy_image="",proxy_log_level="",proxy_memory_limit="",proxy_memory_request="",proxy_uid="",proxy_version="",skip="true",skip_inbound_ports="",skip_outbound_ports="",skip_reason="injection_enable_annotation_absent",trace_collector=""} 2
proxy_inject_admission_responses_total{admin_port="",annotation_at="namespace",control_port="",disable_identity="",disable_tap="",enable_debug_sidecar="",enable_external_profiles="",image_pull_policy="",inbound_port="",init_image="",init_image_version="",namespace="linkerd-tracing",outbound_port="",owner_kind="deployment",proxy_cpu_limit="",proxy_cpu_request="",proxy_image="",proxy_log_level="",proxy_memory_limit="",proxy_memory_request="",proxy_uid="",proxy_version="",skip="false",skip_inbound_ports="",skip_outbound_ports="",skip_reason="",trace_collector=""} 1280
proxy_inject_admission_responses_total{admin_port="",annotation_at="workload",control_port="",disable_identity="",disable_tap="",enable_debug_sidecar="",enable_external_profiles="",image_pull_policy="",inbound_port="",init_image="",init_image_version="",namespace="linkerd-tracing",outbound_port="",owner_kind="deployment",proxy_cpu_limit="",proxy_cpu_request="",proxy_image="",proxy_log_level="",proxy_memory_limit="",proxy_memory_request="",proxy_uid="",proxy_version="",skip="false",skip_inbound_ports="",skip_outbound_ports="",skip_reason="",trace_collector=""} 446  
```
It finally kills my minikube cluster.

As without the inject annotation, it is working fine. Looks like the proxy injector is doing something wrong here.

### How can it be reproduced?

kubectl apply -f https://gist.githubusercontent.com/Pothulapati/1c8bc2c58209b62f586b32e13b588510/raw/4f500c6022b23c634b2468b79685def213d984f7/proxy-injector-wild.yaml

### Environment

- Kubernetes Version: v1.15.0
- Cluster Environment: minikube
- Host OS:
- Linkerd version:

@ihcsim
