### ISSUE TITLE
RFC: Integration With Cert Manager

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#3548]
# Introduction
[Linkerd](https://linkerd.io) is a lightweight service mesh for Kubernetes, which provides zero-config, automatic mTLS between meshed workloads. The `identity` component serves as the service mesh's [Certificate Authority (CA)](https://en.wikipedia.org/wiki/Certificate_authority). It's responsible for handling [Certificate Signing Request (CSR)](https://en.wikipedia.org/wiki/Certificate_signing_request) from the data plane, by issuing TLS certificates with the correct identity. When the `identity` component is installed, it creates a trust anchor, and an issuer key/cert pair. The trust anchor is used by the `identity` component to confirm the identity of proxies requesting for certificates. It's also used among the proxies to confirm each other's identity. The issuer key/cert pair is used to sign the verified CSRs, and issue new certificates.

[cert-manager](https://docs.cert-manager.io/en/latest/index.html) is a Kubernetes certificate management controller, which can be used to manage and issue TLS certificates from different [issuer sources](https://docs.cert-manager.io/en/latest/tasks/issuers/index.html). It ensures that TLS certificates remain valid and are periodically renewed before they expire.

# Goals
The goal of this project is to provide Linkerd users with tools and documentation to ensure a seamless integration with cert-manager, so that cert-manager can manage the issuer key/cert pair.

As the issuer certificate expiry date approaches the predefined deadline, cert-manager will auto renew the certificate. The `identity` component should auto reload the issuer's key/cert pair without re-deployment. We will also provide users with tools to check the validity of their present issuer's certificate. If the cert-manager's renewal window is missed and the issuer certificate expired, it should be possible for users to manually rotate the key and certificate.

## Out of scope
1. Auto-renewal of the trust anchor is out of scope. We encourage users to separate their trust anchor from their issuer certificate, so that changes to one won't break the other.
1. Renewal of the issuer key/cert pair of pre-2.7 control planes. We will provide documentation on the required steps.
1. Integration with other cert-manager issuers like the ACME, Vault etc. If the users manage to expose the root certificate from these issuers to Linkerd during installation, then Linkerd won't get in the way.
1. Management of ingress certificates with cert-manager.

# Integration Design
To enable integration with cert-manager, the following resources must be provided by the user before installing Linkerd:

1. The Linkerd namespace. This is defaulted to `linkerd`.
1. cert-manager configured with sufficient permissions to create secrets in the Linkerd namespace.
1. The CA trust anchor. See [docs](https://linkerd.io/2/tasks/generate-certificates/) on how to generate CA trust root with `step`.
1. A `Secret` resource for the trust anchor.
1. A `CA` `Issuer` and the identity issuer `Certificate` resources. See below for YAML.

### install
Introduce the following new CLI option to the `install` command:

|      |    values  
| -----------------------  | ----------------------------
| Name                    |  `--identity-external-issuer`
| Supported values  | `true`, `false`
| Default                   | `false`
| Flagset                  | `recordable`
| Description            | Set to `true` when integrating with an external Kubernetes CA controller like cert-manager. In the `true` mode, Linkerd will not auto-generate an internal trust anchor nor issuer key/cert pair.

Usage:
```bash
linkerd install --identity-external-issuer=[true|false] --identity-trust-anchors-file=<path-to-ca-pem> [--identity-trust-domain=<trust-domain>]
```

UPDATE (10/16): The `--identity-trust-anchors-file=<path-to-ca-pem>` option is no longer required. See https://github.com/linkerd/linkerd2/pull/3552.

The above command will output the YAML manifest of all the control plane components and resources, except for the `linkerd-identity-issuer` secret. It should fail if the Linkerd namespace, `linkerd-identity-issuer` secret or identity trust anchor file don't exist, unless the `--ignore-cluster` option is provided.

The trust anchor and issuer key/cert should be [verified](https://github.com/linkerd/linkerd2/blob/cf69dedf9caaebb73f65709e8ac5668fdd9d97ac/controller/cmd/identity/main.go#L68-L79) as part of the installation process. In addition, the issuer certificate expiry date should also be [validated](https://github.com/linkerd/linkerd2/blob/cf69dedf9caaebb73f65709e8ac5668fdd9d97ac/pkg/tls/ca.go#L252). We can consider failing the validation if the certificate's expiry date is less than 30 days away.

In the `--identity-external-issuer=true` mode, the following CLI options will have no effects:
```
--identity-issuer-certificate-file string
--identity-issuer-key-file string
```

By adding the `--identity-external-issuer` to the `recordable` flagset, its value will be preserved across version upgrades.

### check
Relevant issues:

* https://github.com/linkerd/linkerd2/issues/3431
* https://github.com/linkerd/linkerd2/pull/3524

## Helm
The equivalence of the new CLI option should be added to the `charts/linkerd2/values.yaml` file.

## Identity
The `identity` component should be updated to watch for changes to its issuer key/cert pairs located at the default location of `/var/run/linkerd/identity/issuer`. When these assets are changed, the `identity` component should ensure that the new certificate:

1. Hasn't or about to expire
1. Remains valid with the trust anchor

And then reload them without needing a re-deployment.

## Open Questions

1. Do we want to support the `--identity-external-issuer` option during upgrade? This might be difficult. 

## YAML
As cert-manager is still in its pre-1.0 phase, it doesn't offer strong guarantee around API stability.
Hence, we will not bundle the issuer and certificate YAML with our Helm chart to reduce maintanence cost.

### Cert Manager Issuer and Certificate
The list of `usages` supported by cert-manager can be found [here](https://github.com/jetstack/cert-manager/blob/6081116295ac9f16de9153c00216bb38b08d2dd8/pkg/internal/apis/certmanager/types.go#L74-L96).

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
  labels:
    config.linkerd.io/admission-webhooks: disabled

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
data:
  tls.crt:  # user-provided PEM-encoded cert
  tls.key: # user-provided PEM-encoded private key

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor

---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 24h
  renewBefore: 1h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: identity.linkerd.cluster.local
  isCA: true
  keyAlgorithm: ecdsa
  usages: 
  - cert sign
  - crl sign
  - server auth
  - client auth
```

Related https://github.com/linkerd/linkerd2/issues/3531.
