### ISSUE TITLE
LoadBalancer does not work when "Getting Started" steps applied for a custom deployment with gRPC server

### ISSUE THREAD

**Issue by lwsanty** [linkerd/linkerd2#3712]
**Summary** I wanted to apply [Getting Started](https://linkerd.io/2/getting-started/) steps for a custom deployment with gRPC server, but load-balancing did not happen. I would appreciate any advice regarding to what am I doing wrong.

**Environment**
- linkerd version `stable-2.6.0`
- minikube version: `v1.5.1`
- ubuntu `18.04`

**Steps**
1) setup `linkered`
```
curl -sL https://run.linkerd.io/install | sh
linkerd check --pre
linkerd install | kubectl apply -f -
linkerd check
```
2) install 5 replicas deployment which contain a container with gRPC server
```yaml
kind: Namespace
apiVersion: v1
metadata:
  name: go-driver
---
kind: Service
apiVersion: v1
metadata:
  name: go-driver-service
  namespace: go-driver
spec:
  selector:
    app: go-driver-app
  ports:
    - protocol: TCP
      port: 9432
      targetPort: grpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-driver-deployment
  namespace: go-driver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: go-driver-app
  template:
    metadata:
      namespace: go-driver
      labels:
        app: go-driver-app
    spec:
      containers:
        - name: go-driver-server
          image: bblfsh/bblfshd:latest-drivers
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 9432
          env:
            - name: LOG_LEVEL
              value: debug
```
3) inject linkered
```
kubectl get -n go-driver deploy -o yaml \
  | linkerd inject - \
  | kubectl apply -f -

linkerd -n go-driver check --proxy
```
4) start logger
```
linkerd -n go-driver top deploy
```
5) port-forward service port
```
kubectl -n go-driver port-forward svc/go-driver-service 9432:9432
```
6) start bombing address `localhost:9432` with a gRPC client, which establishes the connection to endpoint and starts sending requests infinitely.

**results**
- no logs in `linkerd -n go-driver top deploy`
- from containers logs and linkerd dashboard  it is observed that only one pod receives all load

**note** I had some doubts about port forwarding so I created a separate deployment with the client to send request from inside the cluster, but the result was the same
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnny
  namespace: go-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-driver-app
  template:
    metadata:
      namespace: go-driver
      labels:
        app: go-driver-app
    spec:
      containers:
        - name: johnny
          image: johnny:latest
          imagePullPolicy: Never
          env:
            - name: ADDRESS
              value: go-driver-service.go-driver:9432
```
