### ISSUE TITLE
Service Discovery Mirroring

### ISSUE THREAD

**Issue by grampelberg** [linkerd/linkerd2#3734]
## Description

A common feature request for Linkerd is multi-cluster support. Users are running multiple Kubernetes clusters and struggling with connecting and securing the communication between them.

In preparation, an overview of how to solve these two problems without any service mesh whatsoever was written up - [Multicluster the Kubernetes Way with Linkerd](https://docs.google.com/document/d/1yDdd5nC348oNibvFAbxOwHL1dpFAEucpNuox1zcsOFg/edit). From this document, one of the primary difficulties identified was service discovery between clusters. While Kubernetes allows for easy discovery of services within a cluster, it is challenging to wire up public infrastructure such as DNS to make this work on a global scale.

## Details

- [Proposal](https://docs.google.com/document/d/1uzD90l1BAX06za_yie8VroGcoCB8F2wCzN0SUeA3ucw/edit#)
- [Engineering Notes](https://docs.google.com/document/d/1cMWjKpF4SFEj_3vx9Tt0YPTkDenGad84hy20LU0E38A/edit#heading=h.5d51c3niyeaf)
- [Project](https://github.com/orgs/linkerd/projects/41)

**Comment by grampelberg** [comment]
This might do everything we need - https://github.com/coredns/kubernetai

**Comment by zaharidichev** [comment]
Yes, all the cool things have been invented already... Looking at this more closely, I think there are (at least) two caveats: 
- Only works for headless services
- The pod ip of the service in the remote cluster needs to be reachable from the local cluster.

**Comment by zaharidichev** [comment]
Also, correct me if I am wrong here, but this would  most likely not work with the destination service as these remote services will not be visible to it. So no profiles for these services, no retries, no timeouts, etc... If we want that though, we might have to modify the dst service to connect to these remote clusters and fetch data for them. Does that make sense?

**Comment by grampelberg** [comment]
@zaharidichev that was the opinion I had reached as well after reading the code. It appears to assume a flat L3 network which isn't possible for most folks in my experience. The biggest downside is that because it isn't service based, it wouldn't be possible to do traffic splits across clusters - which is a major driver for the work on our side.

**Comment by grampelberg** [comment]
This is historical.

----

### What problem are you trying to solve?

One of the two main challenges with trying to operate multiple k8s clusters is that service discovery is not shared between the clusters. Towards this end, services should be mirrored between different clusters so they can be addressed natively.

### How should the problem be solved?

Create an operator that reads the services from a list of remote clusters and:

- Creates services locally with the cluster name added to the end.
- Adds an endpoint that is the address of the remote cluster's gateway.

When a client goes to send requests to the remote cluster's services:

- DNS lookup will return the ClusterIP
- iptables rewrites ClusterIP into remote cluster gateway IP

Note: this should work without any service mesh. The https component can be managed by simply sharing certificates.

#### Details

- Filtering - This should be configured via RBAC in the remote clusters. The Role/ClusterRole for each mirror client should be scoped to the services that it should mirror. This might manifest as a Role in a single namespace (instead of a ClusterRole) or using actual resource names in the Role itself.
- Identity - The Linkerd identity should *not* be end to end from a pod in the local cluster to a pod in the remote cluster. Instead, the local pod will expect the gateway's identity which is configured as an annotation in the mirror service.
- Trust Roots - The trust bundle must contain either a root cert that spans all clusters or a certificate for each cluster.
- Load Balancing - As the gateway is terminating the connections, it should use its local load balancing and policy configuration.
- TrafficSplit - This can be used to "split" between the local and remote services. For users who want the service name to be implicit for their clusters, they can create a TrafficSplit that manages whether the traffic is destined for the local or remote cluster. This works because the services live in the same namespace and splits operate on services.

#### Resources

- Remote Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: foobar
  namespace: default
spec:
  selector:
    app: foobar
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
```

- Local Service

```yaml
apiVersion: v1
kind: Service
metadata:
  name: foobar-remote
  namespace: default
  annotations:
    linkerd.io/remote-identity: linkerd-gateway-default.linkerd.serviceaccount.identity.linkerd.cluster.local
  labels:
    linkerd.io/mirror-service: true
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    # Port that the remote gateway is listening on
    targetPort: 443
```

- Endpoint

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    linkerd.io/mirror-service: true
  name: foobar-remote
  namespace: default
subsets:
- addresses:
  - ip: 23.10.11.93
  ports:
  - name: gateway
    port: 443
    protocol: TCP
```

#### Setup Workflow

1. Create a service account on the remote cluster with the following `ClusterRole`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: linkerd-mirror
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
```

1. Generate a [kubeconfig](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/) for the service account:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [redacted]
    server: [redacted]
  name: foobar
contexts:
- context:
    cluster: foobar
    user: foobar
  name: foobar
current-context: foobar
kind: Config
preferences: {}
users:
- name: foobar
  user:
    token: [redacted]
```

1. Create a secret on the local cluster that contains this file:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: foobar-kubeconfig
  namespace: linkerd
type: mirror.linkerd.io/kubeconfig
data:
    config: |
        [redacted]
```

### Open Questions

- Should the configuration be a secret or an additional CRD?
- How should the gateway's address be configured? Ideally it would be something in the remote cluster.
- Is it helpful to have something in the target ref for endpoints?

### Out of scope

- Policy - this will need to be sorted out, and decisions should not stop it from happening in the future.
