### ISSUE TITLE
Configure linkerd-proxy to ignore SIGTERM on a per-workload basis

### ISSUE THREAD

**Issue by kivagant-ba** [linkerd/linkerd2#3747]
## Feature Request

Disclaimer: 
- There was a similar question: https://github.com/linkerd/linkerd2/issues/1850 almost a year ago. I'm starting a new one but actually the problem is the same.
- There's an open issue in Kubernetes https://github.com/kubernetes/kubernetes/issues/65502 but it will take too long for the possible implementation to be shipped into production environments.

### What problem are you trying to solve?

When a pod have [a preStop hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) it stops slower than its Linkerd sidecar. This eliminates the idea of the preStop hook since the pod cannot communicate with other services when Linkerd exited.

### Use case example

1. AWS ALB has a target group that sends traffic to a pod **A**.
2. `kubectl rollout restart` is called and Kubernetes starts a new pod **B** and tries to terminate the previous pod **A.**
3. [ALB continues sending some traffic](https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/1064) even after the instance status changed from Healthy to Draining. There's not much we can do. Also there's a special option "Deregistration delay" which was designed to keep existing connection for a while to make sure all requests were processed.
4. An application container inside pod **A** has a `preStop` hook and waits for `N` second before exit to serve the existing requests and those new requests that still come from ALB for unknown reason.
5. Linkerd exits immediately and drops all connections.

Also the problem makes impossible to use "[Slow start duration](https://aws.amazon.com/about-aws/whats-new/2018/05/application-load-balancer-announces-slow-start-support/)" setting in the ALB.

### Logs example

```
# a new pod started and Kubernetes marks the old pod as Terminating
# Linkerd immediately says in its logs: 
linkerd-proxy INFO [   919.021686s] linkerd2_proxy::signal received SIGTERM, starting shutdown

# After that the application cannot connect to monitoring and to other services anymore:
E, [2019-11-21T14:09:25.634678 #2719] ERROR -- ddtrace: [ddtrace] (/usr/local/bundle/gems/ddtrace-0.22.0/lib/ddtrace/transport.rb:215:in `log_error_once') Failed to open TCP connection to 10.5.5.8:8126 (Connection refused - connect(2) for "10.5.5.8" port 8126)

# And at the and after N seconds the app exits as it was asked. But it does not make sense.
# ALB returns many 5xx errors to clients
```

### How should the problem be solved?

If there was a way how to inject a custom preStop hook into Linkerd container with a simple `sleep` command inside (the container probably does not have the command?..) it might solve the problem. In this case I would ask Linkerd to wait for enough long period and Kubernetes would eventually ask it to quit according [to the documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods:

> 1. one of the Pod’s containers has defined a preStop hook, it is invoked inside of the container. If the preStop hook is still running after the grace period expires, step 2 is then invoked with a small (2 second) extended grace period.
> 2. The container is sent the TERM signal. Note that not all containers in the Pod will receive the TERM signal at the same time and may each require a preStop hook if the order in which they shut down matters.

### Any alternatives you've considered?

I cannot find how to actually solve the problem. As a workaround, some tunning around liveness/readiness probes and health check thresholds can be performed. And the "Deregistration delay" can be set to something close to zero to fail faster. But 5xx errors will still be there.

### How would users interact with this feature?

It can be a flag for `linkerd inject --manual`, for example `--wait-before-exit 30` that will prevent linkerd-proxy from exiting for N seconds.

**Comment by kivagant-ba** [comment]
Hmmm... also I found this:

- https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md
But seems like it has not been released yet.

**Comment by kivagant-ba** [comment]
I guess this one of the similar ticket for Istio: https://github.com/istio/istio/issues/7136

**Comment by grampelberg** [comment]
Unfortunately the `pre-stop` solution wouldn't fix this issue. The proxy is receiving the SIGTERM from k8s and doing the correct thing. We'll need a configuration option to make the proxy ignore SIGTERM and continue operating until SIGKILL comes after the wait period.

Adding an annotation that does that for specific workloads having a tough time with this seems reasonable. Probably a good first proxy PR even! I've changed the title to keep folks from getting confused, but feel free to change it to something else (or close and open a new issue) if I've missed some of the details.

**Comment by kivagant-ba** [comment]
Actually I made it work today experimentally with the following sets of configurations that I injected manually:

```yaml
        # application container
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 130 && while pkill -QUIT -f "myapp"; do sleep 1; done
        # linkerd-proxy container 
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 133 # a little bit bigger period of waiting
    terminationGracePeriodSeconds: 160 # for entire pod

---
# ALB annotations:
...
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=10 # deregistration_delay must be less or equal to preStop delay if Linkerd supports it or it is injected manually
    # alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=1 # must be ZERO until Linkerd support preStop hooks
    alb.ingress.kubernetes.io/healthy-threshold-count: '2' # must be small and fast, K8s has already performed readiness probe
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '5' # must be bigger than K8s livenessProbe:(threshold * period) but not too big. K8s removes pod and ALB Ingress Controller notifies the target group that the pod's instance must be deregistered. If the Ingress Controller stuck/died, ALB must do it on its own.
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '5' # must be small and fast but take into account K8s livenessProbe settings
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '3' # similar to internal K8s setting
```

**Comment by grampelberg** [comment]
Woah, cool! There's something here that I'm not understanding, I'll have to take a look at it some more =)

**Comment by kivagant-ba** [comment]
> Configure linkerd-proxy to ignore SIGTERM on a per-workload basis

The title you have set shows one of the possible solutions for the issue. A good solution, but not the only one. There can be others:
1. an http API endpoint in proxy that can be called in `preStop`, like `/prepare_for_termination` or just `sleep/30` where `30` can be changed to any value.
2. a solution without `preStop` that checks a file on a file system and exists only if the file created [as suggested in the example](https://github.com/kubernetes/kubernetes/issues/25908#issuecomment-365924958)
3. just an ability to inject preStop into Linkerd with a random script where user can call `sleep` like I did and it works.
4. a variant when Linkerd knows how to check if his "main" pod is still alive and exists only after the application exited
5. an option based on [the enhancement](https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md) that adds `lifecycle.type: Sidecar` into the proxy's container definition (this won't work for old clusters for years).

I would prefer the variant that I suggested initially in the title because it is the simplest option and does not require code changes within the proxy but only within the proxy injector and, maybe, in the Helm chart.

**Comment by grampelberg** [comment]
@kivagant-ba I think you're right, I'm still just surprised that it works. I need to take a look and understand what I'm missing in the story.

**Comment by jon-walton** [comment]
@grampelberg

During pod termination, the following occurs:

- Pod status changed to `Terminating`
  - Asynchronously, the pod ip is removed from the endpoint (may take a few seconds)
- `preStop` is executed per container
- sigterm sent to each container

If we ignore linkerd for a moment, what usually happens is that the container receives a sigterm while it's ip is still in the endpoint (remember, the ep is updated asynchronously); there's a possibility that the container has completed in-flight requests and exited before the ep is updated and because the ip is still in the ep, requests will be sent to an unresponsive ip resulting in a timeout or 502

If we introduce a `preStop` sleep with the following example:

```yaml
        # application container
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 20

        # linkerd-proxy container 
        lifecycle:
          preStop:
            exec:
              command:
                - /bin/bash
                - -c
                - sleep 40
    terminationGracePeriodSeconds: 160 # for entire pod
```

The pod is still set to `Terminating` and the ip is still removed from the ep, but the container does not receive a sigterm for x period of time.

What I would like to see, is the ability to configure a preStop for the linkerd proxy, so that I can achieve the following:

- Pod status changes to `Terminating`
  - pod IP removed from ep (async)
- `preStop` executed in my app and linkerd proxy
- my app receives a sigterm after 20 seconds, which should be enough time for the ip to be removed from the ep
- my app begins connection drain. The linkerd proxy is still up so my app is able to send a response to the client
- my app terminates
- linkerd proxy receives sigterm after 40 seconds
- linkerd proxy terminates
