### ISSUE TITLE
Pod deletion stuck in TERMINATING

### ISSUE THREAD

**Issue by Enrico2** [linkerd/linkerd2#3751]
### What is the issue?

We have a stateful set (Kafka, probably should not have meshed it, I'm new to Linkerd) in a bad state, where trying to delete a pod gets stuck forever.
The only way around it was 
`delete pod foo --grace-period=0 --force`
or to `ssh` into the actual node and run `docker stop` on the linkerd-proxy container.

### How can it be reproduced?

I don't know unfortunately.

### Logs, error output, etc

The linkerd proxy logs: https://gist.github.com/Enrico2/6ad11da43fa53bd7bee1034449bfe53a
although those seem to have stopped fairly quickly.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.13.11-gke.14
- Cluster Environment: GKE
- Host OS: linux
- Linkerd version: 2.6.0

**Comment by Enrico2** [comment]
when the `delete pod` is issued, the proxy prints
```
INFO [  8705.368228s] linkerd2_proxy::signal received SIGTERM, starting shutdown
```
but is stuck there.

**Comment by ihcsim** [comment]
> INFO [   272.456143s] linkerd2_proxy::proxy::tcp forward connect failure: Custom { kind: ConnectionRefused, error: "Connection refused (os error 111) (address: 10.51.250.56:2181)" }
> INFO [  3176.758255s] linkerd2_proxy::proxy::tcp forward connect failure: Custom { kind: ConnectionRefused, error: "Connection refused (os error 111) (address: 10.51.250.211:2181)" }

I assume it was Zookeeper that was listening at port 2181? Were both Kafka and Zookeeper healthy when the `kubectl delete pod` command was issued? Is it possible that the `delete` command was issued when Kafka and ZooKeeper were still trying to figure each other out?

**Comment by Enrico2** [comment]
Yes, zookeeper, and it was very possible, yes.

**Comment by ihcsim** [comment]
@Enrico2 So sounds like this isn't a problem with the Linkerd proxy, is it? Can we close this issue then?

**Comment by Enrico2** [comment]
I'm not sure, you really hit the nail on the head with your question, but I'm not aware of a reason that a pod deletion would not work when Kafka and ZK are in a weird state with each other. I realize it might not be related, but can you point me to some information about that? (or if you know yourself ;))

However, I do still find it odd that the `linkerd-proxy` pod is the one that causes the block. We've not seen this happen before linkerd, and the fact that `docker stop` on the **proxy** container released the block makes me think it's somehow at play here.

**Comment by ihcsim** [comment]
I see that @grampelberg has tagged this as a `bug`; we will look into it. Thanks!

**Comment by cpretzer** [comment]
I'll see if I can reproduce this. Thanks for the report @Enrico2

**Comment by cpretzer** [comment]
@Enrico2 can you share the YAML files that you used to deploy kafka and zookeeper?

I've attempted to reproduce this using the helm chart distributed by bitnami and everything is working, so far.

I'd like to see if there are any unique configurations in your deployment files.

**Comment by cpretzer** [comment]
@Enrico2 I deployed kafka and zookeeper to a GKE 1.13.11-gke.15 cluster and have been unable to reproduce the behavior that you describe.

The YAML files for the repro case are here: https://github.com/cpretzer/demos/tree/master/kafka-on-k8s

You can deploy them with this command:

```
kubectl apply -f https://raw.githubusercontent.com/cpretzer/demos/master/kafka-on-k8s/kafka.yml -f https://raw.githubusercontent.com/cpretzer/demos/master/kafka-on-k8s/zookeeper.yml
```

After confirming that the pods are running, I've attempted to delete the pods individually and at the same time.

Does this test case look similar to yours?

**Comment by Enrico2** [comment]
Fwiw, we can't reproduce it either. It only happened once more since I reported this issue.
@jsegaran Can you provide @cpretzer with the info he's asking for minus any sensitive information we have in those manifests?

**Comment by cpretzer** [comment]
@Enrico2 thanks for the update. I'll take a look at whatever you have to send over.

**Comment by Enrico2** [comment]
Kafka:
```
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: prod
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      name: server
  clusterIP: None
  selector:
    name: kafka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka
  namespace: prod
spec:
  selector:
    matchLabels:
      name: kafka
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: prod
spec:
  serviceName: kafka
  # In prod we run 5 brokers, but we still only replicate topics 3 ways.
  # We primarily use 4 brokers in staging because that let us test scaling up to 4.
  replicas: 5
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "name"
                    operator: In
                    values:
                      - kafka
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 3600
      containers:
        - name: k8skafka
          imagePullPolicy: Always
          image: gcr.io/mdg-services/kafka:v3 # 2.2.0
          resources:
            requests:
              memory: 12288Mi
              cpu: 7
            limits:
              memory: 12288Mi
              cpu: 7
          ports:
            - containerPort: 9092
              name: server
            - containerPort: 10004
              name: jmx
          command:
            - sh
            - -c
            # Note: set KAFKA_DEBUG here so that when we ssh in to the node
            # and run shell scripts they don't try to listen on the same port.
            - "mkdir -p /var/lib/kafka/logs && KAFKA_DEBUG=true exec kafka-server-start.sh /opt/kafka/config/server.properties --override broker.id=${HOSTNAME##*-} \
          --override listeners=PLAINTEXT://:9092 \
          --override listeners=PLAINTEXT://:9092 \
          --override zookeeper.connect=zk-0.prod.svc.cluster.local:2181,zk-1.prod.svc.cluster.local:2181,zk-2.prod.svc.cluster.local:2181 \
          --override zookeeper.session.timeout.ms=12000 \
          --override zookeeper.set.acl=false \
          --override log.dirs=/var/lib/kafka/logs \
          --override auto.create.topics.enable=true \
          --override auto.leader.rebalance.enable=true \
          --override background.threads=10 \
          --override compression.type=producer \
          --override delete.topic.enable=false \
          --override leader.imbalance.check.interval.seconds=300 \
          --override leader.imbalance.per.broker.percentage=10 \
          --override log.flush.interval.messages=9223372036854775807 \
          --override log.flush.offset.checkpoint.interval.ms=60000 \
          --override log.flush.scheduler.interval.ms=9223372036854775807 \
          --override log.message.format.version=2.2-IV1 \
          --override log.retention.bytes=-1 \
          --override log.retention.hours=168 \
          --override log.roll.hours=168 \
          --override log.roll.jitter.hours=0 \
          --override log.segment.bytes=1073741824 \
          --override log.segment.delete.delay.ms=60000 \
          --override message.max.bytes=33554432 \
          --override min.insync.replicas=1 \
          --override num.io.threads=8 \
          --override num.network.threads=3 \
          --override num.recovery.threads.per.data.dir=1 \
          --override num.replica.fetchers=1 \
          --override offset.metadata.max.bytes=4096 \
          --override offsets.commit.required.acks=-1 \
          --override offsets.commit.timeout.ms=5000 \
          --override offsets.load.buffer.size=5242880 \
          --override offsets.retention.check.interval.ms=600000 \
          --override offsets.retention.minutes=1440 \
          --override offsets.topic.compression.codec=0 \
          --override offsets.topic.num.partitions=50 \
          --override offsets.topic.replication.factor=3 \
          --override offsets.topic.segment.bytes=104857600 \
          --override queued.max.requests=500 \
          --override quota.consumer.default=9223372036854775807 \
          --override quota.producer.default=9223372036854775807 \
          --override replica.fetch.min.bytes=1 \
          --override replica.fetch.wait.max.ms=500 \
          --override replica.high.watermark.checkpoint.interval.ms=5000 \
          --override replica.lag.time.max.ms=10000 \
          --override replica.socket.receive.buffer.bytes=102400 \
          --override replica.socket.timeout.ms=30000 \
          --override request.timeout.ms=30000 \
          --override socket.receive.buffer.bytes=102400 \
          --override socket.request.max.bytes=104857600 \
          --override socket.send.buffer.bytes=102400 \
          --override unclean.leader.election.enable=true \
          --override broker.id.generation.enable=true \
          --override connections.max.idle.ms=600000 \
          --override controlled.shutdown.enable=true \
          --override controlled.shutdown.max.retries=3 \
          --override controlled.shutdown.retry.backoff.ms=5000 \
          --override controller.socket.timeout.ms=30000 \
          --override default.replication.factor=1 \
          --override fetch.purgatory.purge.interval.requests=1000 \
          --override group.max.session.timeout.ms=300000 \
          --override group.min.session.timeout.ms=6000 \
          --override inter.broker.protocol.version=2.2-IV1 \
          --override log.cleaner.backoff.ms=15000 \
          --override log.cleaner.dedupe.buffer.size=134217728 \
          --override log.cleaner.delete.retention.ms=86400000 \
          --override log.cleaner.enable=true \
          --override log.cleaner.io.buffer.load.factor=0.9 \
          --override log.cleaner.io.buffer.size=524288 \
          --override log.cleaner.io.max.bytes.per.second=1.7976931348623157E308 \
          --override log.cleaner.min.cleanable.ratio=0.5 \
          --override log.cleaner.min.compaction.lag.ms=0 \
          --override log.cleaner.threads=1 \
          --override log.cleanup.policy=delete \
          --override log.index.interval.bytes=4096 \
          --override log.index.size.max.bytes=10485760 \
          --override log.message.timestamp.difference.max.ms=9223372036854775807 \
          --override log.message.timestamp.type=CreateTime \
          --override log.preallocate=false \
          --override log.retention.check.interval.ms=300000 \
          --override max.connections.per.ip=2147483647 \
          --override num.partitions=1 \
          --override producer.purgatory.purge.interval.requests=1000 \
          --override replica.fetch.backoff.ms=1000 \
          --override replica.fetch.max.bytes=33554432 \
          --override replica.fetch.response.max.bytes=10485760 \
          --override reserved.broker.max.id=1000 "
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xms2048M -Xmx2048M"
            - name: KAFKA_OPTS
              value: "-Dlogging.level=INFO -Dsun.net.inetaddr.ttl=10"
            - name: JAVA_DEBUG_PORT
              value: "10003"
            - name: JMX_PORT
              value: "10004"
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/kafka
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 10
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "fast"
        resources:
          requests:
            storage: 3Ti
```
zk:
```
---
# A service per-pod with a stable (proxied) IP, because so many Zookeeper client
# libraries (eg Kafka's) fail horribly if DNS names change their mapping over
# time. Do not delete these services in production clusters or everything (eg
# Kafka) will break. Services have names zk-N.NAMESPACE (not to be confused with
# zk-N.zk.NAMESPACE which is the pod name created by StatefulSet, whose IPs do
# change over time).
apiVersion: v1
kind: Service
metadata:
  name: zk-0
  namespace: prod
  labels:
    name: zk-0
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    statefulset.kubernetes.io/pod-name: zk-0
  
---
# A service per-pod with a stable (proxied) IP, because so many Zookeeper client
# libraries (eg Kafka's) fail horribly if DNS names change their mapping over
# time. Do not delete these services in production clusters or everything (eg
# Kafka) will break. Services have names zk-N.NAMESPACE (not to be confused with
# zk-N.zk.NAMESPACE which is the pod name created by StatefulSet, whose IPs do
# change over time).
apiVersion: v1
kind: Service
metadata:
  name: zk-1
  namespace: prod
  labels:
    name: zk-1
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    statefulset.kubernetes.io/pod-name: zk-1
  
---
# A service per-pod with a stable (proxied) IP, because so many Zookeeper client
# libraries (eg Kafka's) fail horribly if DNS names change their mapping over
# time. Do not delete these services in production clusters or everything (eg
# Kafka) will break. Services have names zk-N.NAMESPACE (not to be confused with
# zk-N.zk.NAMESPACE which is the pod name created by StatefulSet, whose IPs do
# change over time).
apiVersion: v1
kind: Service
metadata:
  name: zk-2
  namespace: prod
  labels:
    name: zk-2
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  selector:
    statefulset.kubernetes.io/pod-name: zk-2
  
---
# A single name that can be used to connect to all pods, including the A records
# for each individual pod. We are required to create this in order to have a
# StatefulSet but you should prefer to use the individual pod services for
# connections because they have stable IPs.
apiVersion: v1
kind: Service
metadata:
  name: zk
  namespace: prod
  labels:
    name: zk
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    name: zk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zk
  namespace: prod
data:
  jvm.opts: "-Dsun.net.inetaddr.ttl=10"
  jvm.heap: 512M
  tick: "2000"
  init: "10"
  sync: "5"
  client.cnxns: "60"
  snap.retain: "3"
  purge.interval: "0"
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk
  namespace: prod
spec:
  selector:
    matchLabels:
      name: zk
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: prod
spec:
  serviceName: zk
  replicas: 3
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      name: zk
  template:
    metadata:
      labels:
        name: zk
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - zk
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8szk
          imagePullPolicy: Always
          image: gcr.io/mdg-services/zk # zk version 3.4.14
          resources:
            requests:
              memory: 1Gi
              cpu: 0.5
            limits:
              memory: 1Gi
              cpu: 0.5
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
          env:
            - name: ZK_REPLICAS
              value: "3"
            - name: ZK_HEAP_SIZE
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: jvm.heap
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: jvm.opts
            - name: ZK_TICK_TIME
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: tick
            - name: ZK_INIT_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: init
            - name: ZK_SYNC_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: tick
            - name: ZK_MAX_CLIENT_CNXNS
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: client.cnxns
            - name: ZK_SNAP_RETAIN_COUNT
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: snap.retain
            - name: ZK_PURGE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: zk
                  key: purge.interval
            - name: ZK_CLIENT_PORT
              value: "2181"
            - name: ZK_SERVER_PORT
              value: "2888"
            - name: ZK_ELECTION_PORT
              value: "3888"
          command:
            - sh
            - -c
            - zkGenConfig.sh && zkServer.sh start-foreground
          readinessProbe:
            exec:
              command:
                - "zkOk.sh"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - "zkOk.sh"
            initialDelaySeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: datadir
              mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 50Gi
```

**Comment by cpretzer** [comment]
@Enrico2 thanks for sharing these files. The deployment is certainly more sophisticated than the test case that I set up.

Specifically, I didn't use the `PodDisruptionBudget` resource, although, I have no evidence that could be causing the intermittent issue.

The last time that it happened did you observe any specific events that took place? Something like a deployment or traffic spike? Perhaps a node restarting and pods being rescheduled to a new node?

If the behavior isn't reliably reproducible, I think we can close this issue until we get more details around the behavior.

**Comment by Enrico2** [comment]
When it happened to me, I believe I was restarting zk and Kafka at the same time. But yeah, it's not consistently reproducible.

**Comment by cpretzer** [comment]
@Enrico2 I haven't been able to reproduce after trying different combinations of deleting kafka and zookeeper pods.

If this happens again, please reopen this issue with any additional information that you collect.

**Comment by Enrico2** [comment]
This just happened again, not while zk was rolling or anything.
Both Kafka and linkerd logs grabbed. Manually killing the linkerd-proxy container from the node released things.

```
$ klp logs kafka-0 -c linkerd-proxy
time="2020-02-19T18:50:45Z" level=info msg="running version stable-2.7.0"
[     0.16203430s]  INFO linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.16241875s]  INFO linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.16268985s]  INFO linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.16294694s]  INFO linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.16298489s]  INFO linkerd2_proxy: Local identity is default.prod.serviceaccount.identity.linkerd.cluster.local
[     0.16337785s]  INFO linkerd2_proxy: Identity verified via linkerd-identity.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.16343516s]  INFO linkerd2_proxy: Destinations resolved via linkerd-dst.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.17233167s]  INFO inbound: linkerd2_app_inbound: serving listen.addr=0.0.0.0:4143
[     0.63644723s]  INFO daemon:identity: linkerd2_app: Certified identity: default.prod.serviceaccount.identity.linkerd.cluster.local
[  1217.649346321s]  INFO linkerd2_proxy::signal: received SIGTERM, starting shutdown
```

**Comment by Enrico2** [comment]
We were in a reproducible state, I managed to change the log level of the proxy to debug before attempting to delete the node. Got some more data, but it doesn't look too interesting:

```
[  2601.416530510s] DEBUG inbound:accept{peer.addr=10.48.53.16:45130}: linkerd2_proxy_transport::connect: connection established to 127.0.0.1:9092
[  2601.416566650s] DEBUG inbound:accept{peer.addr=10.48.53.16:45130}: linkerd2_proxy_transport::metrics: client connection open
[  2601.536329580s] DEBUG inbound:accept{peer.addr=10.48.67.1:40998}: linkerd2_proxy_transport::tls::accept: attempting TLS handshake
[  2601.536694611s] DEBUG inbound:accept{peer.addr=10.48.67.1:40998}: linkerd2_app_core::accept_error: Connection failed error=error shutting down connection: Transport endpoint is not connected (os error 107)
[  2602.14318163s]  INFO linkerd2_proxy::signal: received SIGTERM, starting shutdown
[  2617.122623416s] DEBUG inbound:accept{peer.addr=10.48.63.16:56190}: linkerd2_app_core::accept_error: Connection failed error=Connection reset by peer (os error 104)
[  2617.123048818s] DEBUG inbound:accept{peer.addr=10.48.54.14:47484}: linkerd2_app_core::accept_error: Connection failed error=Broken pipe (os error 32)
[  2617.123930388s] DEBUG inbound:accept{peer.addr=10.48.54.12:59454}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.127559831s] DEBUG inbound:accept{peer.addr=10.48.75.73:56234}: linkerd2_app_core::accept_error: Connection failed error=Connection reset by peer (os error 104)
[  2617.128034102s] DEBUG inbound:accept{peer.addr=10.48.56.14:59934}: linkerd2_app_core::accept_error: Connection failed error=Connection reset by peer (os error 104)
[  2617.129930705s] DEBUG inbound:accept{peer.addr=10.48.41.35:43168}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.130805528s] DEBUG inbound:accept{peer.addr=10.48.67.37:35910}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.132452246s] DEBUG inbound:accept{peer.addr=10.48.56.15:44532}: linkerd2_app_core::accept_error: Connection failed error=Broken pipe (os error 32)
[  2617.134420551s] DEBUG inbound:accept{peer.addr=10.48.57.21:42306}: linkerd2_app_core::accept_error: Connection failed error=Broken pipe (os error 32)
[  2617.136330145s] DEBUG inbound:accept{peer.addr=10.48.41.35:43178}: linkerd2_app_core::accept_error: Connection failed error=Connection reset by peer (os error 104)
[  2617.136702695s] DEBUG inbound:accept{peer.addr=10.48.55.19:42288}: linkerd2_app_core::accept_error: Connection failed error=Broken pipe (os error 32)
[  2617.137965787s] DEBUG inbound:accept{peer.addr=10.48.71.51:53660}: linkerd2_app_core::accept_error: Connection failed error=Connection reset by peer (os error 104)
[  2617.138462069s] DEBUG inbound:accept{peer.addr=10.48.13.37:48978}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.138566712s] DEBUG inbound:accept{peer.addr=10.48.21.4:58732}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.138723948s] DEBUG inbound:accept{peer.addr=10.48.41.3:33202}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.138882327s] DEBUG inbound:accept{peer.addr=10.48.44.29:40680}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.138976599s] DEBUG inbound:accept{peer.addr=10.48.6.45:51676}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.139076005s] DEBUG inbound:accept{peer.addr=10.48.71.55:38542}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.139487970s] DEBUG inbound:accept{peer.addr=10.48.53.16:35820}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.139604694s] DEBUG inbound:accept{peer.addr=10.48.54.5:53686}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.139866269s] DEBUG inbound:accept{peer.addr=10.48.43.33:34504}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.140178036s] DEBUG inbound:accept{peer.addr=10.48.58.4:40972}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.140296464s] DEBUG inbound:accept{peer.addr=10.48.67.37:39944}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.140485023s] DEBUG inbound:accept{peer.addr=10.48.86.60:44474}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.141032530s] DEBUG inbound:accept{peer.addr=10.48.93.12:33740}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.141956771s] DEBUG inbound:accept{peer.addr=10.48.54.12:40142}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.142122097s] DEBUG inbound:accept{peer.addr=10.48.47.4:46462}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.144127717s] DEBUG inbound:accept{peer.addr=10.48.30.4:56882}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.144362501s] DEBUG inbound:accept{peer.addr=10.48.55.18:38262}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.145050533s] DEBUG inbound:accept{peer.addr=10.48.57.25:46466}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.145480683s] DEBUG inbound:accept{peer.addr=10.48.86.60:51662}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.145691988s] DEBUG inbound:accept{peer.addr=10.48.72.17:47174}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.145765564s] DEBUG inbound:accept{peer.addr=10.48.21.4:59286}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.145947221s] DEBUG inbound:accept{peer.addr=10.48.83.6:40630}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.146026019s] DEBUG inbound:accept{peer.addr=10.48.41.35:43056}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.146305142s] DEBUG inbound:accept{peer.addr=10.48.13.38:43412}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.146841776s] DEBUG inbound:accept{peer.addr=10.48.41.37:59618}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.534398104s] DEBUG outbound:accept{peer.addr=10.48.67.39:44644}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.534534262s] DEBUG outbound:accept{peer.addr=10.48.67.39:50438}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2617.534654336s] DEBUG outbound:accept{peer.addr=10.48.67.39:35574}: linkerd2_app_core::accept_error: Connection failed error=Broken pipe (os error 32)
[  2618.462885769s] DEBUG inbound:accept{peer.addr=10.48.63.13:40258}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2621.286042708s] DEBUG inbound:accept{peer.addr=10.48.54.11:45510}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2623.908260764s] DEBUG inbound:accept{peer.addr=10.48.41.28:47694}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2625.462870305s] DEBUG inbound:accept{peer.addr=10.48.63.13:40176}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2629.286798246s] DEBUG inbound:accept{peer.addr=10.48.54.11:45626}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2630.798139310s] DEBUG inbound:accept{peer.addr=10.48.41.28:47134}: linkerd2_app_core::accept_error: Connection failed error=Transport endpoint is not connected (os error 107)
[  2635.135015851s] DEBUG inbound:accept{peer.addr=10.48.47.4:45084}: linkerd2_app_core::accept_error: Connection failed error=Connection reset by peer (os error 104)
[  2678.268617046s] DEBUG inbound:accept{peer.addr=10.48.47.4:45236}: linkerd2_app_core::accept_error: Connection failed error=Connection reset by peer (os error 104)
```

It's stuck there now.

**Comment by Enrico2** [comment]
I don't have permissions to re-open the issue.

**Comment by Enrico2** [comment]
It seems we can consistently reproduce it right now.

**Comment by ihcsim** [comment]
> after a long pause, 

Taking a random stab here: any idea if that duration corresponds to this particular kafka setting: `--override connections.max.idle.ms=600000`?

**Comment by Enrico2** [comment]
`2864.101614251 - 2678.268617046 = 185.832997205`, so, not 600 seconds.

Got an Update though!

we gave the proxy some sleep time before getting the SIGTERM and the pod didn't get stuck! (we gave it 60 seconds but Kafka was done in about 5)

```
config.alpha.linkerd.io/proxy-wait-before-exit-seconds: "60"
```

**Comment by grampelberg** [comment]
Linkerd doesn't actually provide much value for this kind of traffic, so you might just be better of skipping inbound/outbound ports for all the deployments that use kafka/zookeeper.

**Comment by Enrico2** [comment]
We've discussed this, and the consensus seems to be that people want the # connections and bytes/sec data.

**Comment by cpretzer** [comment]
@Enrico2 If Linkerd is giving you the metrics that you want and you can work around the issue with the `proxy-wait-before-exist-seconds` annotation, then it sounds like you're in good shape.

Once Kubernetes officially [supports sidecar containers](https://github.com/kubernetes/enhancements/issues/753), then we'll re-test with the version of Kubernetes that supports those containers to make sure that your application can successfully migrate to that version.

**Comment by Enrico2** [comment]
Totally understand.
Although since we have a reproducible environment, if you're curious to
find the root cause let me know, I don't mind spending some time with you
debugging this.

**Comment by cpretzer** [comment]
@Enrico2 sorting this out together would be AWESOME!

I'll ping you on Slack tomorrow

**Comment by cpretzer** [comment]
Just writing an update here for the folks who may be following this issue.

@Enrico2 and I have held a couple of meetings and have been using [Slack](https://slack.linkerd.io) to discuss this issue.

I've been working to reproduce the behavior with a [simple kafka/zookeeper configuration](https://github.com/cpretzer/demos/tree/master/kafka-on-k8s).

So far, I've not been able to reproduce the behavior. One thing that we are looking to track down is whether using DataDog through the JMX and Java debug ports could be causing this issue.

We've determined that the kafka process stops, and the linkerd proxy process continues to run inside the container. The current hypothesis is that there is an outstanding connection that isn't closing, and the proxy process is staying active.

At the moment, there are two potential connections that could be causing this:
- zookeeper
- DataDog through JMX or Java Debug

@Enrico2 is going to run a test with the JMX and Java Debug ports added to the Linkerd skip ports configuration:

```yaml
...
    annotations:
    ...
       config.linkerd.io/skip-inbound-ports: "10003,10004"
       config.linkerd.io/skip-outbound-ports: "10003,10004"
    ...
```
