### ISSUE TITLE
HTTP throughput big downgradation with linkerd-proxy

### ISSUE THREAD

**Issue by ukcuf** [linkerd/linkerd2#3755]
## Bug Report

This comes from the discussion at: 
https://linkerd.slack.com/archives/C89RTCWJF/p1574340470004700

### What is the issue?
We observed http throughput from pod that runs a simple web service downgrades a lot after linkerd-proxy is injected to it and takes over its incoming/outgoing traffic. 

The background is we have 2 micro-service deployments running on Kubernetes. The *service-client* can create hundreds of connections to the *service-server* and do request with no pause. And initially, we found the single *server* pod's throughput without linkerd can keep at `10k` RPS, but with linkerd injected to both sides (which enables mTLS per `linkerd tap` tells), the throughput downgrades to around `3k` RPS. 

### How can it be reproduced?
I worked out a simple way to reproduce the problem. 

1. find a Kube cluster and create a new namespace, e.g. `bug`
```
kubectl create ns bug
```

2. apply below specs to the namespace `bug`, which:
  - deploys 2 nginx deployments with replica at `1`, and one of them is injected with linkerd-proxy, and configured the linkerd-proxy's resource request&limit to `2` CPU and `4Gi` memory.
  - create 2 services for above deployments.
  - deploys 1 client pod

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lkd
spec:
  selector:
    matchLabels:
      app: nginx-lkd
  replicas: 1
  template:
    metadata:
      annotations:
        config.linkerd.io/proxy-cpu-limit: "2"
        config.linkerd.io/proxy-cpu-request: "2"
        config.linkerd.io/proxy-memory-limit: 4Gi
        config.linkerd.io/proxy-memory-request: 4Gi
        linkerd.io/inject: enabled
      labels:
        app: nginx-lkd
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-lkd
  name: nginx-lkd
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-lkd
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  clusterIP: None
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: debian:stretch-slim
        args: ["sleep", "3600"]
```

3. kube exec to the client pod and then:

```sh
apt update && apt install -y wrk
wrk -d 10s -c 100 http://nginx.bug.svc.cluster.local:80
wrk -d 10s -c 100 http://nginx-lkd.bug.svc.cluster.local:80
```

4. compare the output. In my dev environment, it shows:

```
root@client-84fbf7449-sdml2:/# wrk -d 10s -c 100 http://nginx-lkd.bug.svc.cluster.local:80
Running 10s test @ http://nginx-lkd.bug.svc.cluster.local:80
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    21.28ms    2.36ms  63.92ms   94.97%
    Req/Sec     2.36k   211.43     2.76k    83.50%
  47067 requests in 10.04s, 37.03MB read
Requests/sec:   4689.84
Transfer/sec:      3.69MB

root@client-84fbf7449-sdml2:/# wrk -d 10s -c 100 http://nginx.bug.svc.cluster.local:80
Running 10s test @ http://nginx.bug.svc.cluster.local:80
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   116.96ms  176.66ms 944.92ms   81.23%
    Req/Sec     6.31k     1.60k   10.57k    69.00%
  125542 requests in 10.01s, 101.64MB read
Requests/sec:  12546.34
Transfer/sec:     10.16MB
```

So it is `4.7k` V.S. `12.5k`, which shows similar throughput downgrade we observed from our own application deployment environment. 

### Logs, error output, etc

I observed the CPU usage of linkerd-proxy container in the pod, and it always shows like a single core is fully used even in case I have already configured the spec to allocate it 2 CPUs. In below chart, the orange line is the CPU usage of `linkerd-proxy` when the server pod was stressed.

![image](https://user-images.githubusercontent.com/13572784/69426940-5bbc0f80-0d69-11ea-8a3d-c8ee63c36535.png)

I also build a linkerd-proxy image with `procps` based on stable-2.6.0 tag, and with `top` in linkerd-proxy container, I see the CPU usage was keeping at 100%. 

![image](https://user-images.githubusercontent.com/13572784/69427075-b3f31180-0d69-11ea-92a4-b18fc9f6b848.png)

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: 1.14.8
- Cluster Environment: IBM Kubernetes Service
- Host OS: Ubuntu 18.04
- Linkerd version: stable-2.6.0

### Possible solution
Not found yet.

### Additional context

What I am seeing with `linkerd-proxy` are:
  (1). it does not use additional cpu core I allocated for it.
  (2). my server serves at 10k rps only uses 80% cpu cycles, but a 3k rps is already draining linkerd-proxy. So does this mean I will have to allocate more CPU cores just for the meshing sidecars rather than my own application?
