### ISSUE TITLE
Remove namespace refs from Pod/spec/container/args 

### ISSUE THREAD

**Issue by dayglojesus** [linkerd/linkerd2#3772]
## Feature Request

Remove reliance on `-controller-namespace` args in `Pod/spec/containers` so that it's easier to overlay a Namespace on linkerd using `kustomize`.

### What problem are you trying to solve?

At present, one cannot fully `kustomize` the linkerd Namespace without post-processing the  `args` array nested in `Pod/spec/containers`. Eschewing namespace refs in CLI args would mitigate this condition and offer users the ability to create a fully namespace-neutral `base` for any `kustomize` workflow. Such bases could then be re-used by anyone in any context.

### How should the problem be solved?

Suggested solution would be to supply the required value via `ConfigMap` OR environment variable.

### Any alternatives you've considered?

Presently, the only remediation is post-processing (essentially re-writing the manifest rendered by `kustomize`). As alternatives go, it means shelling-out or writing custom transforms for what is something that is otherwise ostensibly simple.

### How would users interact with this feature?

n/a

**Comment by dayglojesus** [comment]
An additional, albeit utterly brittle and unsustainable alternative are JSON patches:
```yaml
patchesJson6902:
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: linkerd-controller
    namespace: linkerd
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - public-api
      - -prometheus-url=http://linkerd-prometheus.linkerd.svc.cluster.local:9090
      - -tap-addr=linkerd-tap.linkerd.svc.cluster.local:8088
      - -controller-namespace=core-services
      - -log-level=info
    - op: replace
      path: /spec/template/spec/containers/1/args
      value:
      - destination
      - -addr=:8086
      - -controller-namespace=core-services
      - -enable-h2-upgrade=true
      - -log-level=info
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: linkerd-web
    namespace: linkerd
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - -api-addr=linkerd-controller-api.linkerd.svc.cluster.local:8085
      - -grafana-addr=linkerd-grafana.linkerd.svc.cluster.local:3000
      - -controller-namespace=core-services
      - -log-level=info
- target:
    group: extensions
    version: v1beta1
    kind: Deployment
    name: linkerd-tap
    namespace: linkerd
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - tap
      - -controller-namespace=core-services
      - -log-level=info
```
blergh 🔥
