### ISSUE TITLE
Registry flag does not set registry for debug container

### ISSUE THREAD

**Issue by Timboo89** [linkerd/linkerd2#3851]
### What is the issue?
When using the registry flag the registry of the debug container is not changed.

### How can it be reproduced?
During installation:
```
linkerd install --registry my.custom.registry/linkerd-io | kubectl apply -f -
```
Running linkerd:
```
$ kubectl edit cm -n linkerd linkerd-config
....
  install: |
    {"uuid":"620b0744-fb40-4761-9411-09e875bfdc21","cliVersion":"stable-2.5.0","flags":[{"name":"registry","value":"my.custom.registry/linkerd-io"}]}
....
kubectl delete po -n linkerd linkerd-proxy-injector-* linkerd-controller-*
```

Enable the debug pod for a deployment:
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: busybox1
  namespace: coms-e2e2
  labels:
    app: busybox1
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      annotations:
        config.linkerd.io/enable-debug-sidecar: "true"
      labels:
        app: busybox
    spec:
      containers:
        - image: my.custom.registy/busybox
          command:
            - sleep
            - "3600"
          imagePullPolicy: IfNotPresent
          name: busybox
      restartPolicy: Always
      imagePullSecrets:
        - name: artifactory

```
### Logs, error output, etc

```
LAST SEEN   TYPE      REASON      KIND   MESSAGE
11m         Normal    Scheduled   Pod    Successfully assigned coms-e2e2/busybox1-5bc7bbd75c-5v8lr to ip-100-64-2-244.eu-central-1.compute.internal
11m         Normal    Pulled      Pod    Container image "my.custom.registy/linkerd-io/proxy-init:v1.1.0" already present on machine
11m         Normal    Created     Pod    Created container
11m         Normal    Started     Pod    Started container
11m         Normal    Pulled      Pod    Container image "my.custom.registy/busybox" already present on machine
11m         Normal    Created     Pod    Created container
11m         Normal    Started     Pod    Started container
11m         Normal    Pulling     Pod    pulling image "gcr.io/linkerd-io/debug:stable-2.5.0"
11m         Warning   Failed      Pod    Failed to pull image "gcr.io/linkerd-io/debug:stable-2.5.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: x509: certificate signed by unknown authority
11m         Warning   Failed      Pod    Error: ErrImagePull
11m         Normal    Pulled      Pod    Container image "my.custom.registy/linkerd-io/proxy:stable-2.5.0" already present on machine
11m         Normal    Created     Pod    Created container
11m         Normal    Started     Pod    Started container
11m         Normal    BackOff     Pod    Back-off pulling image "gcr.io/linkerd-io/debug:stable-2.5.0"
105s        Warning   Failed      Pod    Error: ImagePullBackOff
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ no invalid service profiles

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.5.0 but the latest stable version is 2.6.1
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.5.0 but the latest stable version is 2.6.1
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.13.12-eks-c500e1
- Cluster Environment: (EKS)
- Host OS: AmazonLinux2 (CentOS 7)
- Linkerd version: stable-2.5.0
