### ISSUE TITLE
Check reports about non-valid certificate in case of \n at the end of it

### ISSUE THREAD

**Issue by StupidScience** [linkerd/linkerd2#3907]
### What is the issue?

As I mentioned before in #3880 there is bug with certificate comparison related to `\n` symbol at the end of certificate. And I believe it was misleading in those case with root cause investigation.

### How can it be reproduced?

* Install linkerd with helm so there will be no `\n` symbol in the end trust anchor certificate but `ca.crt` in certificate that was generated by cert-manager will have this certificate. In my case it looked like:
```yaml
identity:
  trustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    ...
    -----END CERTIFICATE-----
  issuer:
    scheme: kubernetes.io/tls
```
* Run `linkerd check`
* Got 
```text
linkerd-identity
----------------
× certificate config is valid
    IdentityContext.TrustAnchorsPem does not match ca.crt in linkerd-identity-issuer
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version: `edge-19.12.3`

### Possible solution

Before comparing of certificates just encode them and decode back to string so certificates will be in the same format.

### Additional context

I can implement it and send a PR if you confirm this possible solution.
