### ISSUE TITLE
Multicluster Work Breakdown

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#3917]
This is a meta issue to dicuss how the work around multicluster needs to be broken down. Each section in my mind needs to be a mergable PR. This follows from #3762 and #3858 Scrutiny is encouraged.

### Provide CLI tools to setup cross - cluster api access
What we need here is a command that given two cluster` A (local)` and `B (remote)` creates service account credentials in `B` and provides them to `A` in some manner (a secret most likely). So the way this might actually work from UX perspective is this: 
- as a prerequisite there are two clusters `A` and `B` and we have defined contexts for them
- the user does something like `linkerd pair A B`, where A and B are the contexts of the clusters
- a service account with the needed permissions is created in cluster B
- the information to use this service account from cluster `A` is encoded into a secret and added to cluster `A`. It can look something like: 

```
apiVersion: v1
kind: Secret
metadata:
  name: cluster-b-remote-config
  annotations:
    linkerd.io/remote-cluster-config: "true"
type: Opaque
data:
  config: ...
```
An interesting piece of work that we can borrow some know-how from can be found [here](https://github.com/admiraltyio/multicluster-service-account)

### Provide CLI tools  to setup cluster gateways
This has to do with getting an ingress setup on the remote cluster. This would involve two things: 
- Installing nginx
- Adding a resource of kind Ingress to the cluster

### Provide CLI tools to expose/unexpose a service as a remote one
This CLI command will take a service or a list of services and make them available for mirroring. It can be in the form of `linkerd expose my-service <ingress name?>`
- will add the necessary rules to the gateway to route a request to the corresponding service. In case of nginx and using a host header this can add a rule such as: 

```
spec:
  rules:
  - host: my-service-cluster-b-remote.default.svc.cluster.local
    http:
      paths:
      - path: /
        backend:
          serviceName: my-service
          servicePort: <port-of-svc>
```

- will also add annotations to the service that indicate what its gateway is, so when picked up by the local cluster, it is clear where the request needs to be sent
- additionally we can provide tools to unexpose or update the expose configuration setup (i.e. different gateway, etc)
- the point here is that it would be great if we can automate the the whole headers/rules routing creating deletion. I wonder how this should be done. Should we do it for a set of supporeted ingress controllers or just nginx or just ditch the whole concept and leave it be a manual thing (does not sound very user friendly)

### Provide a controller to drive the service mirroring
At the point we can take care of actually writing the component that will be mirroring the services on the local cluster. A POC of this can be seen in #3762. This can be a component that is part of the `linkerd install`command and is enabled with `--service-mirroring-enabled` flag. In its essence it does the following things: 

- continuously watches for secrets that have the  `linkerd.io/remote-cluster-config: "true"`
- when such secret is creates/updated uses the information to connect to the k8s API of the remote cluster and establish a watch for services that have the needed metadata, indicating that they are "exposed" for mirroring
- will create the corresponding service and endpoint locally that allow the remote service to be accessed as if it was living locally: 

```
apiVersion: v1
kind: Service
metadata:
  name: my-service-cluster-b-remote
  namespace: default
  annotations:
    linkerd.io/remote-identity: <the remote identity>
  labels:
    linkerd.io/mirror-service: true
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    # Port that the remote gateway is listening on
    targetPort: 443
```

```
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    linkerd.io/mirror-service: true
  name: my-service-cluster-b-remote
  namespace: default
subsets:
- addresses:
  - ip: <ip-of-the-gateway...>
  ports:
  - name: gateway
    port: 443
    protocol: TCP
```

- the component will also be responsible for accounting for any changes in the remote cluster. If a service is deleted, etc this needs to be reflected locally. Additionally if the secret is deleted either manually or the cluster is "un-paired" through the CLI, we need to tear the whole thing down and delete all locally created services. Simply put - life-cycle management.

### Provide tools for figuring out the state of the remoteness: 
- provide a tool such as `linkerd list-remote-clusters` that gives a list of all paired clusters and the current number of services that are mirrored from each of them
- provide a tool such as `linkerd list-remote-services --cluster <some paired cluster>` that provides details about services that are currently mirrored

### Provide a tutorial that demonstrates this functionality
I really like the idea that @grampelberg proposed in #3858 that uses a concept of a staging and local environment to traffic split between a local dev k8s cluster and a staging one that is running remotely. I think this will demo the functionality in a nice way.

There are some details around identity that are still a bit unclear to me so this is why I have not put them in explicitly.
