### ISSUE TITLE
protocol detection for keycloak

### ISSUE THREAD

**Issue by ArgTang** [linkerd/linkerd2#3936]
## Bug Report

Seems like protocol detection for keycloak-cluster discovery is not supported:

Adding skip-port for clustering traffic fixes the issue:
```
  keycloak:
    podAnnotations:
      config.linkerd.io/skip-inbound-ports: "7600" # skip keycloak cluster discovery
      config.linkerd.io/skip-outbound-ports: "7600"
```

### What is the issue?

When deploying keycloak in a clustered manner, linkerd seems to break keycloaks clustering traffic

### How can it be reproduced?

Deploy keycloak with replicas >1 (we use the [helm chart](https://github.com/codecentric/helm-charts/tree/master/charts/keycloak)), when you log into the service, an error will occur and you are logged out. If you are fast you will see some 401 in the browser before you are redirected to the loginscreen. This happens because the other node dont know that you are logged inn.

### Environment

- Kubernetes Version: 1.15.7
- Cluster Environment: AKS
- Host OS:
- Linkerd version: 2.6.1
