### ISSUE TITLE
"linkerd inject --manual" changes types of label values (string becomes float64)

### ISSUE THREAD

**Issue by KIVagant** [linkerd/linkerd2#3983]
### What is the issue?

After `linkerd inject --manual` is applied, all Deployment labels lose double quotes around label values which causes problems with unobvious types.

### How can it be reproduced?

1. Create the deployment:

```yaml
# tmp-2.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "1493e89"
    commit: "1493e89"
  name: "1493e89"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "1493e89"
  template:
    metadata:
      labels:
        app: "1493e89"
        commit: "1493e89"
      name: "1493e89"
    spec:
      containers:
        - image: nginx
          name: "1493e89"
```

2. Apply it using `kubectl apply -f tmp-2.yaml` and make sure it works. New pods will start, for example:

```
NAME                                       READY   STATUS    RESTARTS   AGE
1493e89-7946985fdc-7zx2w                   1/1     Running   0          2m31s
```

3. Inject Linkerd Proxy `linkerd inject --manual tmp-2.yaml`

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: 1493e89
    commit: 1493e89
  name: 1493e89
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 1493e89
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli edge-19.9.3 # actually, there's edge-20.1.2 on server side which behaves the same
        linkerd.io/identity-mode: default
        linkerd.io/proxy-version: edge-20.1.2
      creationTimestamp: null
      labels:
        app: 1493e89
        commit: 1493e89
        linkerd.io/control-plane-ns: linkerd
        linkerd.io/proxy-deployment: 1493e89
      name: 1493e89
    spec:
      containers:
      - image: nginx
        name: 1493e89
        resources: {}
...
```

As you can see here, all labels (and not only labels) lost double quotes around values. Now try to apply it:

```
linkerd inject --manual tmp-2.yaml | kubectl apply -f -
```

### Logs, error output, etc

```
deployment "1493e89" injected

error: error when retrieving current configuration of:
...
Object: &{map["apiVersion":"apps/v1" "kind":"Deployment" ...
:map["app":%!q(float64=+1.493e+92) "commit":%!q(float64=+1.493e+92)] "name":%!q(float64=+1.493e+92)
...
from server for: "STDIN": resource name may not be empty

// or even more unclear error:

for: "./tmp-2.yaml": unrecognized type: string

```

### Environment

- Kubernetes Version: v1.14.9-eks-c0eccc
- Cluster Environment: EKS
- Host OS: Amazon Linux
- Linkerd version: **edge-20.1.2**

### Possible solution

Add quotes in yaml templates everywhere by default when possible.

### Workaround:

Update the commit id in any way, if it is a commit id causing the problem.
