### ISSUE TITLE
Linkerd Injection Priority

### ISSUE THREAD

**Issue by Tharun-Sabbu** [linkerd/linkerd2#4175]
### What is the issue?

Labeling kube-system namespace with config.linkerd.io/admission-webhooks:disabled after cluster restart is working however if we want to inject to a specific deployment in kube-system then it doesn't work.

We are running nginx ingress controller and prometheus in kube-system namespace and injection isn't happening as the label mentioned on namespace to disable injection is taking priority than annotation on deployment.

### Environment

- Kubernetes Version: v1.15.5
- Cluster Environment: (kops)
- Linkerd version: 2.7

**Comment by grampelberg** [comment]
Would you mind sharing the yaml you're using?

**Comment by Tharun-Sabbu** [comment]
Namespace yaml:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"kube-system"}}
  labels:
    config.linkerd.io/admission-webhooks: disabled
  name: kube-system
```

Nginx Deployment yaml:

```
kind: Deployment
metadata:
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"cluster-autoscaler.kubernetes.io/safe-to-evict":"true","deployment.kubernetes.io/revision":"29","prometheus.io/port":"10254","prometheus.io/scrape":"true"},"creationTimestamp":"2020-01-29T17:03:24Z","generation":29,"labels":{"app":"nginx-ingress-tcp","component":"controller"},"name":"nginx-ingress-controller-tcp","namespace":"kube-system","resourceVersion":"6853180","selfLink":"/apis/extensions/v1beta1/namespaces/kube-system/deployments/nginx-ingress-controller-tcp","uid":"dd5de77d-c3b3-4bc0-b571-2412c7afdce8"},"spec":{"progressDeadlineSeconds":2147483647,"replicas":1,"revisionHistoryLimit":2147483647,"selector":{"matchLabels":{"app":"nginx-ingress-tcp","component":"controller"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"cluster-autoscaler.kubernetes.io/safe-to-evict":"true","date":"2020-02-03 13:59:29.191892","linkerd.io/inject":"enabled","prometheus.io/port":"10254","prometheus.io/scheme":"http","prometheus.io/scrape":"true"},"creationTimestamp":null,"labels":{"app":"nginx-ingress-tcp","component":"controller"}},"spec":{"affinity":{"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchLabels":{"app":"nginx-ingress-tcp"}},"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"containers":[{"args":["/nginx-ingress-controller","--v=1","--default-backend-service=kube-system/nginx-ingress-default-backend-tcp","--election-id=ingress-controller-leader","--ingress-class=nginx-tcp","--configmap=$(POD_NAMESPACE)/nginx-ingress-controller-tcp","--tcp-services-configmap=$(POD_NAMESPACE)/tcp-services-tcp","--udp-services-configmap=$(POD_NAMESPACE)/udp-services-udp"],"env":[{"name":"POD_NAME","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.name"}}},{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"}}}],"image":"docker.io/nginx-ingress-controller:0.28.0","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":10254,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"nginx-ingress-controller","ports":[{"containerPort":80,"name":"http","protocol":"TCP"},{"containerPort":443,"name":"https","protocol":"TCP"},{"containerPort":9000,"name":"9000-port","protocol":"TCP"},{"containerPort":53,"name":"53-port","protocol":"TCP"},{"containerPort":10254,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":10254,"scheme":"HTTP"},"initialDelaySeconds":10,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{},"securityContext":{"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"runAsUser":101},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","nodeSelector":{"beta.kubernetes.io/os":"linux"},"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"nginx-ingress-tcp","serviceAccountName":"nginx-ingress-tcp","terminationGracePeriodSeconds":60}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2020-02-05T14:36:06Z","lastUpdateTime":"2020-02-05T14:36:06Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":29,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
    prometheus.io/port: "10254"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-01-29T17:03:24Z"
  generation: 33
  labels:
    app: nginx-ingress-tcp
    component: controller
  name: nginx-ingress-controller-tcp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-ingress-tcp
      component: controller
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        config.linkerd.io/enable-debug-sidecar: "true"
        date: "2020-02-03 13:59:29.191892"
        linkerd.io/inject: enabled
        prometheus.io/port: "10254"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
      labels:
        app: nginx-ingress-tcp
        component: controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: nginx-ingress-tcp
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - args:
        - /nginx-ingress-controller
        - --v=1
        - --default-backend-service=kube-system/nginx-ingress-default-backend-tcp
        - --election-id=ingress-controller-leader
        - --ingress-class=nginx-tcp
        - --configmap=$(POD_NAMESPACE)/nginx-ingress-controller-tcp
        - --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services-tcp
        - --udp-services-configmap=$(POD_NAMESPACE)/udp-services-udp
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: docker.io/nginx-ingress-controller:0.28.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: nginx-ingress-controller
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 9000
          name: 9000-port
          protocol: TCP
        - containerPort: 53
          name: 53-port
          protocol: TCP
        - containerPort: 10254
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 10254
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsUser: 101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nginx-ingress-tcp
      serviceAccountName: nginx-ingress-tcp
      terminationGracePeriodSeconds: 60
```

I edited the namespace by adding webhook disable label, then when I restarted nginx pod, pod did not get injected with linkerd-proxy container. 

Then I removed the label from namespace kube-system and after restarting nginx pod, pod was injected with linkerd-proxy.
