### ISSUE TITLE
There's are no integration tests running with PSP

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#4196]
A full run of the integration tests would help catch issues like what #4193 fixed. We could add another [matrix element](https://github.com/linkerd/linkerd2/blob/d6c588f6830f70b563d7d38b333d562dc6ac84fe/.github/workflows/kind_integration.yml#L69) into our kind_integration.yaml workflow.

Unfortunately, it's not obvious to set up KinD to run with PSP, so I'd like to list below some caveats to consider before embarking into this effort, taking into account PSP as a whole in k8s is planned to be deprecated.

## Possible Solution
We could enable the PSP admission controller by passing a kubadm config like this:

```yaml
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  apiServer:
    extraArgs:
      enable-admission-plugins: NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeClaimResize,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority,PodSecurityPolicy
```
And right after the cluster starts, set up one permissive PSP bound to the `system:serviceaccounts` and `system:nodes` groups.

## Downsides
Since the cluster requires extra setup after it becomes respondent, we can't rely on a simple invocation of the `engineerd/setup-kind` Github action like we do now. We'd have to manually start the cluster, setup PSP, and then wait till it becomes available before triggering the tests.

Additionally, some integration tests would require to be updated with additional data-plane PSP setups as well.
