### ISSUE TITLE
l5d-dst-override + ingress-nginx doesn't work with string servicePort

### ISSUE THREAD

**Issue by praseodym** [linkerd/linkerd2#4211]
### What is the issue?

With ingress-nginx set up [according to the Linkerd documentation](https://linkerd.io/2/tasks/using-ingress/#nginx), requests made to an ingress with `servicePort` set to a string value fail. The `$service_port` is not resolved to a numeric value and instead Linkerd falls back to port 80, which is not necessarily the correct port.

### How can it be reproduced?

Install Linkerd, emojivoto with web-svc on port 8080, ingress-nginx, and the following ingress definition:

```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: emojivoto
  namespace: emojivoto
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: web-svc
          servicePort: http
        path: /
```
Then make a request for `http://localhost`, which fails with a `502 Bad Gateway`.

### Logs, error output, etc

ingress-nginx:
```
127.0.0.1 - - [28/Mar/2020:21:32:03 +0000] "GET / HTTP/1.1" 502 0 "-" "curl/7.68.0" 73 0.001 [emojivoto-web-svc-http] [] 10.96.230.199:8080 0 0.000 502 c06ee101ae82673dc5115267b7d569a1
```
`linkerd tap` for the pod:
```
req id=3:8 proxy=in  src=172.17.0.1:57006 dst=10.244.0.24:80 tls=not_provided_by_remote :method=GET :authority=localhost :path=/
req id=3:9 proxy=out src=10.244.0.24:52948 dst=10.244.0.22:80 tls=true :method=GET :authority=localhost :path=/
rsp id=3:9 proxy=out src=10.244.0.24:52948 dst=10.244.0.22:80 tls=true :status=502 latency=719µs
end id=3:9 proxy=out src=10.244.0.24:52948 dst=10.244.0.22:80 tls=true duration=6µs response-length=0B
rsp id=3:8 proxy=in  src=172.17.0.1:57006 dst=10.244.0.24:80 tls=not_provided_by_remote :status=502 latency=1695µs
end id=3:8 proxy=in  src=172.17.0.1:57006 dst=10.244.0.24:80 tls=not_provided_by_remote duration=3µs response-length=0B
```

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2020-03-28T22:43:26Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √
```

### Environment

- Kubernetes Version: v1.18.0
- Cluster Environment: kind
- Host OS: Debian Bullseye
- Linkerd version: edge-20.3.4

### Possible solution

- Resolve string `$service_port` to the correct numeric port
or:
- Document that `$service_port` should be a numeric value
- Log a warning when `$service_port` is invalid
