### ISSUE TITLE
Add support for configuration of per-component resources configuration for proxy in Helm chart.

### ISSUE THREAD

**Issue by cypherfox** [linkerd/linkerd2#4225]
### What problem are you trying to solve?
Currently only one cluster-wide confguration for the resources the proxy requests and is limited to are available. This is far from optimal, as the the really high values for the prometheus proxy are not needed for e.g. the web UI. 

Especially as the settings are also used for the injected proxies, this will break our cluster injecting 900+ pods.

### How should the problem be solved?
Allow per-component setting of proxy resources based on the value of `.Values.global.proxy.component` (additionally e.g. `injected-proxy` for the configuration for the injector) in `.Values.global.proxy.perComponentResources` 

### Any alternatives you've considered?
I do not know of any.

### How would users interact with this feature?
setting `.Values.global.proxy.perComponentResources` in their `values.yaml` file

**Comment by cypherfox** [comment]
MR coming up.

**Comment by alpeb** [comment]
> Especially as the settings are also used for the injected proxies, this will break our cluster injecting 900+ pods.

IIUC, you'd like to set specific requests and limits for the proxies injected into your own pods. Have you considered using annotations to specify that?
For example you can add any of the following annotations into any specific deployment in your Helm templates, specifying the exact limits/requests you want:
```yaml
linkerd.io:/inject: enabled
config.linkerd.io/proxy-cpu-limit: 12m                                                                                                                                                                                            
config.linkerd.io/proxy-cpu-request: 5m                                                                                                                                                                                           
config.linkerd.io/proxy-memory-limit: 15Mi                                                                                                                                                                                        
config.linkerd.io/proxy-memory-request: 10Mi 
```
(Note these annotations go under `spec.template.metadata.annotation` in the case of Deployments)

These and other annotations are documented [here](https://linkerd.io/2/reference/proxy-configuration/).
