### ISSUE TITLE
Service mirroring - remote gateway receives short service name in the request host header

### ISSUE THREAD

**Issue by lstyles** [linkerd/linkerd2#4255]
### What is the issue?

I'm trying to get multiple azure k8s clusters connected using service mirroring for exploratory purposes and I'm seeing issues with remote linkerd-gateway receiving non fqdn host in the header which it doesn't know how to resolve.

My understanding is that nginx doesn't use libc dns resolution and therefore ignores /etc/resolv.conf search domains.

Also, it's my understanding that with service mirroring, requests should be send with fqdn and port in the host header to the remote gateway.

### Logs, error output, etc

Services appear to be mirrored correctly:

```
PS C:\Users\lucas> kubectl get service --context uksk8s
NAME                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
backend-svc           ClusterIP      172.20.66.173    <none>        9090/TCP       5h44m
backend-svc-ukwk8s    ClusterIP      172.20.185.253   <none>        9090/TCP       5h11m
frontend-svc          ClusterIP      172.20.49.215    <none>        8888/TCP       5h44m
frontend-svc-ukwk8s   ClusterIP      172.20.26.158    <none>        8888/TCP       5h11m
kubernetes            ClusterIP      172.20.0.1       <none>        443/TCP        8h
linkerd-gateway       LoadBalancer   172.20.176.115   10.0.0.35     80:30690/TCP   6h
PS C:\Users\lucas> kubectl get service --context ukwk8s
NAME                  TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
backend-svc           ClusterIP      172.21.58.146    <none>        9090/TCP       5h44m
backend-svc-uksk8s    ClusterIP      172.21.230.26    <none>        9090/TCP       5h12m
frontend-svc          ClusterIP      172.21.142.151   <none>        8888/TCP       5h44m
frontend-svc-uksk8s   ClusterIP      172.21.117.26    <none>        8888/TCP       5h12m
kubernetes            ClusterIP      172.21.0.1       <none>        443/TCP        8h
linkerd-gateway       LoadBalancer   172.21.102.232   10.1.0.35     80:30585/TCP   6h

```

with correct remote fqdn and endpoints set:

```
PS C:\Users\lucas> kubectl describe service backend-svc-ukwk8s --context=uksk8s
Name:              backend-svc-ukwk8s
Namespace:         default
Labels:            mirror.linkerd.io/cluster-name=ukwk8s
                   mirror.linkerd.io/mirrored-service=true
                   mirror.linkerd.io/remote-gateway-name=linkerd-gateway
                   mirror.linkerd.io/remote-gateway-ns=default
Annotations:       mirror.linkerd.io/remote-gateway-resource-version: 11172
                   mirror.linkerd.io/remote-resource-version: 31142
                   mirror.linkerd.io/remote-svc-fq-name: backend-svc.default.svc.cluster.local
Selector:          <none>
Type:              ClusterIP
IP:                172.20.185.253
Port:              http  9090/TCP
TargetPort:        9090/TCP
Endpoints:         10.1.0.35:80
Session Affinity:  None
Events:            <none>
```

I'm using gateway defined here: https://github.com/linkerd/website/blob/445225ba393775ad3e5f52e7986f9ec2a6a4a62f/run.linkerd.io/public/multicluster-gateway.yml
with the only addition being the following service metadata annotation: `service.beta.kubernetes.io/azure-load-balancer-internal: "true"`

I'm using mockup services like below:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--h1-server-port=9090"
        - "--response-text=backend-<region specific response>"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: buoyantio/bb:v0.0.5
        args:
        - point-to-point-channel
        - "--h1-server-port=8888"
        - "--h1-downstream-server=http://backend-svc:9090"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: default
spec:
  selector:
    app: frontend
  ports:
  - name: http
    port: 8888
    targetPort: 8888

```

and traffic split:

```
kubectl get trafficsplit cluster-split --context=uksk8s -o yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  annotations:
  creationTimestamp: "2020-04-13T13:20:17Z"
  generation: 1
  name: cluster-split
  namespace: default
  resourceVersion: "16587"
  selfLink: /apis/split.smi-spec.io/v1alpha1/namespaces/default/trafficsplits/cluster-split
  uid: 09f0a3aa-0480-4dab-8f4f-8530922a4c0d
spec:
  backends:
  - service: backend-svc
    weight: 500m
  - service: backend-svc-ukwk8s
    weight: 500m
  service: backend-svc
```

After that, hitting frontend service works if the chosen backend is local and fails when sent to remote gateway in another cluster. The gateway logs the following in nginx log:

```
2020/04/13 18:00:49 [error] 6#6: *5025 backend-svc could not be resolved (3: Host not found), client: 127.0.0.1, server: , request: "POST / HTTP/1.1", host: "backend-svc:9090"
127.0.0.1 - - [13/Apr/2020:18:00:49 +0000] "POST / HTTP/1.1" 502 157 "-" "Go-http-client/1.1"
```

So it would look like the request received by the remote gateway has a short host instead of fqdn.

### Environment

- Kubernetes Version: 1.15.7/10
- Cluster Environment: AKS
- Host OS: Linux
- Linkerd version: edge-20.4.1
