### ISSUE TITLE
linkerd upgrade produces invalid proxy config when original cli install specified `--skip-outbound-ports`

### ISSUE THREAD

**Issue by dayglojesus** [linkerd/linkerd2#4257]
### What is the issue?

The `linkerd upgrade` sub-command produces an invalid proxy config when original cli install specified `--skip-outbound-ports`.

Instead of independently appending the previously specified ports to the CLI args in CSV format, it appends what appears to be string literal from a JSON list. As a result, the proxy crashes and pods enter a crashloop.

### How can it be reproduced?

You can repro it thusly:

initial deploy
```
# linkerd version 2.6.1
linkerd install --ignore-cluster --ha \
    --skip-outbound-ports 4222 | kubectl apply -f -
```
upgrade
```
# linkerd version 2.7.1
linkerd upgrade | kubectl apply --prune \
    -l linkerd.io/control-plane-ns=linkerd -f -
```

But the problem is visible in the manifests, scattered throughout:

```yaml
      initContainers:
      - args:
        - --incoming-proxy-port
        - "4143"
        - --outgoing-proxy-port
        - "4140"
        - --proxy-uid
        - "2102"
        - --inbound-ports-to-ignore
        - 4190,4191
        - --outbound-ports-to-ignore
        - 443,[4222]
```

### Logs, error output, etc

```
Controlled By:  DaemonSet/internal-nginx-ingress-controller
Init Containers:
  linkerd-init:
    Container ID:  docker://0596c3e4f0eef3ca3035c9bfd3afaba6a3579ffba25e02235145c440ee56bc1b
    Image:         gcr.io/linkerd-io/proxy-init:v1.3.2
    Image ID:      docker-pullable://gcr.io/linkerd-io/proxy-init@sha256:e1d81404c653b8479df0316f68dfa0cbbb2c34f4e987483d4cb832a9b1d9cd0a
    Port:          <none>
    Host Port:     <none>
    Args:
      --incoming-proxy-port
      4143
      --outgoing-proxy-port
      4140
      --proxy-uid
      2102
      --inbound-ports-to-ignore
      4190,4191
      --outbound-ports-to-ignore
      [4222]
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   4/14 01:00:56 > iptables -t nat -F PROXY_INIT_OUTPUT
2020/04/14 01:00:56 < iptables: No chain/target/match by that name.
2020/04/14 01:00:56 > iptables -t nat -X PROXY_INIT_OUTPUT
2020/04/14 01:00:56 < iptables: No chain/target/match by that name.
2020/04/14 01:00:56 Ignoring uid 2102
2020/04/14 01:00:56 Invalid port configuration of "[4222]": "[4222]" is not a valid lower-bound
```

#### `linkerd check` output

The linkerd check output is 💯 clean.

### Environment

- Kubernetes Version: 1.14
- Cluster Environment: EKS
- Host OS: AMZN Linux
- Linkerd version: 2.6.1/2.7.1

### Possible solution

Looks like an installer bug:
https://linkerd.slack.com/archives/C89RTCWJF/p1586827690251500

### Additional context

Thanks to linkerd team for all your hard work on getting 2.7.1 rolled out! 🎉
