### ISSUE TITLE
TAP auto-generated SERVICE PROFILE high cardinality

### ISSUE THREAD

**Issue by naseemkullah** [linkerd/linkerd2#4268]
### What problem are you trying to solve?

Smooth out auto creation of service profiles as per https://linkerd.io/2/tasks/setting-up-service-profiles/#auto-creation.

The generated YAML today:

```yaml
  - condition:
      method: PUT
      pathRegex: /v1/users/1234

  - condition:
      method: PUT
      pathRegex: /v1/users/4567
```
### How should the problem be solved?

@grampelberg hinted at https://github.com/linkerd/linkerd2/blob/e962bf19687dcc8343a8411333552538f7302f4a/pkg/profiles/tap.go#L116

What do you want to happen? Add any considered drawbacks.

Would like generate yaml to have this instead:

```
  - condition:
      method: PUT
      pathRegex: /v1/users/.*
```

### Any alternatives you've considered?

Yes, will create openapi spec and generate service profile from it.

### How would users interact with this feature?

https://linkerd.io/2/tasks/setting-up-service-profiles/#auto-creation
