### ISSUE TITLE
cluster get-credentials provides no means to configure api service address

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4398]
When setting up a cluster in k3d, I need to do some extra work to configure the kubeconfig. get-credentials makes this pretty awkward. If it supported `-o json`, i could at least throw `jq` at it. but really, it would help to have documentation/tooling for providing credentials when `get-credentials` cannot Just Work (i.e. because api servers are not addressable on same networks)

**Comment by olix0r** [comment]
Could this command be changed to something more like `kubectl config ... |linkerd ... cluster gen-mirror-credentials | kubectl apply ..`?

**Comment by olix0r** [comment]
Also, the credentials secret is not namespaced:

```
:; linkerd --context=k3d-multi1 cluster get-credentials --cluster-name=multi1 --remote-cluster-domain=multi1.olix0r.net

apiVersion: v1
data:
  kubeconfig: ...
kind: Secret
metadata:
  annotations:
    mirror.linkerd.io/cluster-name: multi1
    mirror.linkerd.io/remote-cluster-domain: multi1.olix0r.net
    mirror.linkerd.io/remote-cluster-l5d-ns: linkerd
  creationTimestamp: null
  name: cluster-credentials-multi1
type: mirror.linkerd.io/remote-kubeconfig
```

So it ends up in _default_ by default
