### ISSUE TITLE
service-mirror cannot require global secret access

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4401]
install-service-mirror currently emits rbac like:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: linkerd-service-mirror
  namespace: linkerd-service-mirror
  labels:
    linkerd.io/control-plane-component: linkerd-service-mirror
rules:
- apiGroups: [""]
  resources: ["endpoints", "services", "secrets", "namespaces"]
  verbs: ["list", "get", "watch", "create", "delete", "update"]
```

Which permits the service-mirror to read and write all secrets in the cluster. This isn't a suitable default for production environments.

What secret access does this pod need?
