### ISSUE TITLE
service-mirror: Incorrect service export with multiple gateways

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4451]
I've got a _dev_ cluster running, splitting services between two remote clusters, _east_ and _west_ (as configured by https://github.com/olix0r/l2-k3d-multi/tree/f54d406b1061ba6d9455f92100ec9bea8f57151b).

I notice that the _west_ gateway sees requests destined for the _east_ cluster (i.e. with the cluster domain `east.k3d.example.com`).

Inspecting the _dev_ cluster (where the service-mirror is running), I see:
```
:; kubectl --context=k3d-dev -n emojivoto get endpoints emoji-svc-{east,west}
NAME             ENDPOINTS                         AGE
emoji-svc-east   172.24.0.6:4180,172.24.0.6:4180   6h37m
emoji-svc-west   172.24.0.6:4180,172.24.0.6:4180   6h37m
```
So, both service's endpoints are configured with the same gateway IP!

Inspecting the secrets, I see that the secrets have the correct configuration:
```
:; kubectl --context=k3d-dev -n linkerd-multicluster get secrets cluster-credentials-{east,west} -o yaml | sed -ne 's/.*  kubeconfig: //p' | base64 -d
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://172.24.0.4:6443
  name: k3d-east
contexts:
- context:
    cluster: k3d-east
    user: linkerd-service-mirror
  name: k3d-east
current-context: k3d-east
kind: Config
preferences: {}
users:
- name: linkerd-service-mirror
  user:
    token: ...
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://172.24.0.6:6443
  name: k3d-west
contexts:
- context:
    cluster: k3d-west
    user: linkerd-service-mirror
  name: k3d-west
current-context: k3d-west
kind: Config
preferences: {}
users:
- name: linkerd-service-mirror
  user:
    token: ...
```

Furthermore, the _east_ service is configured with the identity of the _west_ gateway:
```
:; kubectl --context=k3d-dev -n emojivoto describe endpoints emoji-svc-east
Name:         emoji-svc-east
Namespace:    emojivoto
Labels:       mirror.linkerd.io/cluster-name=east
              mirror.linkerd.io/mirrored-service=true
              mirror.linkerd.io/remote-gateway-name=linkerd-gateway
              mirror.linkerd.io/remote-gateway-ns=linkerd-multicluster
Annotations:  mirror.linkerd.io/remote-gateway-identity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.west.k3d.example.com
              mirror.linkerd.io/remote-svc-fq-name: emoji-svc.emojivoto.svc.east.k3d.example.com
Subsets:
  Addresses:          172.24.0.6
  NotReadyAddresses:  <none>
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    prom  4180  TCP
    grpc  4180  TCP

Events:  <none>
```
