### ISSUE TITLE
multicluster: support per-mirror credentials

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#4461]
#4457 raises an issue I didn't notice -- `setup-remote` currently creates an SA/RBAC to be used by all remote gateways. This makes it impossible to revoke access to any one cluster. It's all-or-nothing. It also creates some unnecessary install-time-concerns.

Can we change the way that Service Accounts are allocated to do this at link-time rather than at install-time?

Basically, something like:

```
# Create new SA/RBAC for the _west_ service-mirror to discover services in the _east_ cluster.
linkerd --context=east multicluster allow west |
    kubectl apply -f - --context=east

# Get the raw SA and prepare for use in the _west_ cluster
linkerd --context=east multicluster link east |
    kubectl apply -f - --context=west
```

This could also support reusing credentials for folks who are unconcerned:
```
linkerd --context=east multicluster allow all-the-mirrors |
    kubectl apply -f - --context=east

linkerd --context=east multicluster link all-the-mirrors |
    kubectl apply -f - --context=west1
linkerd --context=east multicluster link all-the-mirrors |
    kubectl apply -f - --context=west2
```

Note that `link` should support a `--cluster-server` flag to override the value in the kubeconfig (for private networks, primarily).

**Comment by olix0r** [comment]
To be clear, I think the above should replace the current `setup-remote` and `get-credentials` behavior.

**Comment by grampelberg** [comment]
```yaml
# linkerd multicluster allow -h
Output Kubernetes configs to allow a mirror to connect to this cluster.

Usage:
  linkerd multicluster allow [flags] [NAME]

Examples:
    # Add a SA using the default name
    linkerd --context=east multicluster allow | kubectl --context=east apply -f -

    # Specify the SA, ClusterRole and ClusterRoleBinding names
    linkerd --context=east multicluster allow foobar | kubectl --context=east apply -f -

Flags:
    --namespace       The destination namespace for the service account. (default "linkerd-multicluster")
    --ignore-cluster   Ignore cluster configuration (default false).
```

Note: `allow` should exit if a SA of the name trying to be created already exists

```yaml
# linkerd multicluster link -h
Output Kubernetes configs to link a mirror on one cluster with another.

Usage:
  linkerd multicluster link [flags] [NAME]

Examples:
    # Get the default credentials
    linkerd --context=east multicluster link | kubectl --context=west apply -f -

    # Specify the account
    linkerd --context=east multicluster link foobar | kubectl --context=west apply -f -

    # Specify the cluster server connection details
    linkerd --context=east multicluster link --cluster-server https://my-k8s-cluster.example | \
        kubectl --context=west apply -f -

Flags:
    --namespace       The destination namespace for the service account. (default "linkerd-multicluster")
    --cluster-name   The name to use when referring to this cluster in service names. (default local context)
    --cluster-server  The connection details for the API server of this cluster. (default local context)
  -h, --help                               help for get-credentials
      --remote-cluster-domain string       custom remote cluster domain (default "cluster.local")
```
