### ISSUE TITLE
Upgrading from edge version does not set Grafana control plane version corrrectly

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#4556]
This only happens when the server version is edge. If the server version is stable, this does not happen.

## Reproduction:

```bash
❯ linkerd version
Client version: edge-20.6.1
```

```
❯ linkerd install |kubectl apply -f -
```

Use new version of linkerd. In this example I just pull the current master:

```
❯ bin/docker-pull-binaries master
..
❯ ./target/release/linkerd2-cli-master-darwin version
Client version: git-108b383a
Server version: edge-20.6.1
```

Now, upgrade the control plane and examine the output.

```
❯ ./target/release/linkerd2-cli-master-darwin upgrade control-plane | rg 'version: edge-20.6.1'
        version: edge-20.6.1
```

## Expected

This should display `git-654839e6`. The `grep` command should not have matched
anything

```yaml
..
data:
  values: |-
    global:
      grafanaUrl:
    grafana:
      enabled: true
      image:
        name: gcr.io/linkerd-io/grafana
        version: edge-20.6.1
      name: linkerd-grafana
    tracing:
      enabled: false
..
```

**Comment by kleimkuhler** [comment]
This doesn't happen when upgrading with manifests:

```
kubectl get -n linkerd cm/linkerd-config secrets/linkerd-identity-issuer -o yaml |./target/release/linkerd2-cli-git-654839e6-darwin upgrade control-plane --from-manifests -
```

```yaml
..
data:
  values: |-
    global:
      grafanaUrl:
    grafana:
      enabled: true
      image:
        name: gcr.io/linkerd-io/grafana
        version: git-654839e6
      name: linkerd-grafana
    tracing:
      enabled: false
..
```
