### ISSUE TITLE
ExternalName services in multicluster

### ISSUE THREAD

**Issue by zaharidichev** [linkerd/linkerd2#4590]
One way to do service mirroring with ExternalName services is to have all service mirrors be ExternalName services pointing to a gateway mirror that lives in the linkerd-multicluster namespace. This might look like:

Gateway without concrete IP address:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: linkerd-gateway-east
  namespace: linkerd-multicluster
spec:
  type: ExternalName
  externalName: my.lb.fqdn.com
  ports:
  - name: probe-port
    port: 4181
    protocol: TCP
  - name: incoming-port
    port: 4143
    protocol: TCP
```

Gateway with concrete IP address:

```yaml
kind: Service
metadata:
  name: linkerd-gateway-east
  namespace: linkerd-multicluster
spec:
  clusterIP: 10.43.96.192
  ports:
  - name: probe-port
    port: 4181
    protocol: TCP
    targetPort: 4181
  - name: incoming-port
    port: 4143
    protocol: TCP
    targetPort: 4143

apiVersion: v1
kind: Endpoints
metadata:
  name: linkerd-gateway-east
  namespace: linkerd-multicluster
subsets:
- addresses:
  - ip: 172.19.0.6
  ports:
  - name: probe-port
    port: 4181
    protocol: TCP
  - name: incoming-port
    port: 4143
    protocol: TCP
```

Service mirror:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    mirror.linkerd.io/remote-svc-fq-name: emoji-svc.emojivoto.svc.east.k3d.example.com
  labels:
    mirror.linkerd.io/cluster-name: east
    mirror.linkerd.io/mirrored-service: "true"
    mirror.linkerd.io/remote-gateway-name: linkerd-gateway
    mirror.linkerd.io/remote-gateway-ns: linkerd-multicluster
  name: emoji-svc-east
  namespace: emojivoto
spec:
  type: ExternalName
  externalName: linkerd-gateway-east.linkerd-multicluster.svc.cluster.local
  ports:
  - name: grpc
    port: 8080
    protocol: TCP
  - name: prom
    port: 8801
    protocol: TCP
```

One thing that is important to consider is that when we hit emoji-svc-east.east, on any port, we need to resolve the incoming-port of the gateway as the target one in order to make all this work. And ofcourse, we need to actually support `ExternalName` in discovery
