### ISSUE TITLE
ReadTimeouts on the api if used with linkerd2 injection

### ISSUE THREAD

**Issue by mittalsuraj18** [linkerd/linkerd2#4592]
Linkerd in causing connections to be dropped or timed out in python fastapi server on kubernetes.

### How can it be reproduced?

Create a simple async fastapi server using the below code
```python
from fastapi import FastAPI
from fastapi.background import BackgroundTasks
import asyncio
import httpx

app = FastAPI()


async def sleep():
    async with httpx.AsyncClient(timeout=60) as client:
         _ = await client.get("https://httpbin.org/delay/10")
    await asyncio.sleep(10)

@app.get("/")
def root():
    return "okay"

@app.get("/health")
def health():
    return "okay"

@app.get("/background")
async def background(bk:BackgroundTasks):
    bk.add_task(sleep)
    return "running in background"

if __name__=="__main__":
    import uvicorn
    uvicorn.run(app=app, host="0.0.0.0", port=8080)


```

The Dockerfile contents would be as follows

```Dockerfile
FROM python:3.7
RUN pip install fastapi[all] uvicorn httpx --no-cache-dir
RUN mkdir /app
WORKDIR /app
COPY server.py ./
CMD ["python","server.py"]
```

The kubernetes deployment as the linkerd sidecar proxy injection enabled

the yaml is as follows

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: test-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: test-app
        image: "<REPO_URL>"
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: "test-app"
spec:
  type: NodePort
  selector:
    app: "test-app"
  ports:
    - port: 8080
      targetPort: 8080
```

Try to hit `/backgound` api from another deployment running linkerd proxy injection or from outside using virtual machine assigned nodeport and ip.

### Expected Behavior

- the api returns immediately and runs the sleep in background.
- hitting the api second time should result in the same case as above where the api returns the response immediately and runs in the background async task

### Observed Behavior

- the first call returns immediately. but the second calls hangs or timeouts.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match
   
linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √
```

### Environment

- Kubernetes Version: 
    - Client: v1.16.6-beta.0
    - Server: v1.16.8-gke.15
- Cluster Environment: GKE
- Host OS: Container-Optimized OS (cos)
- Linkerd version: 2.8.0

### Additional Context

- `exec` ing into the `test-app` container and hitting the api via `http://localhost:8000/backgound` causes the expected behavior.
- Hitting the pod from another pod or from external system causes the observed behavior.
- Disabling linkerd by removing the injection causes the issue to disappear
