### ISSUE TITLE
Investigate avoiding ingress loops when using nodeport service and default backend

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#4636]
As described in #4585, when ingress-nginx is exposed as a NodePort service, outbound requests from the ingress-nginx will still have the NodePort address as the request authority.  This causes the outbound proxy to send the request back to ingress-nginx, resulting in a loop.

#4608 adds one potential resolution to the problem by allowing operators to customize the networks for which Linkerd will do discovery.  If the node network is excluded from this then Linkerd will not do discovery on the NodePort address and will instead forward to original destination: the backend.

However, because Linkerd is not doing discovery for this request, it will not get the metadata necessary to do identity (mTLS) or http metrics.  Furthermore, excluding the NodeNetwork from destination get addresses means that traffic to all NodePort services will similarly not get identity or http metrics.

Linkerd supports an `l5d-dst-override` header which should be set by the ingress controller to prevent this kind of looping behavior: https://linkerd.io/2/tasks/using-ingress/#nginx
However, further investigation is required to determine:

* Is there a way to configure ingress-nginx to set l5d-dst-override when no Ingress resource exists?
* Will ingress-nginx set the l5d-dst-override when no Ingress rules match and the gloabl default backend is used?
* What happens if both a global default backend and a default backend in an Ingress resource are configured?

**Comment by adleong** [comment]
I've done some experiments and if `--default-backend-service` is set AND there exists an Ingress resource with a default backend configured, the backend from the Ingress resource will take precedence.  Furthermore, the `l5d-dst-override` header will be applied, allowing for correct routing to this backend with identity, metrics, and no looping.

To get this working, all that is necessary is to create an ingress resource in the default backend's namespace:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-ingress
  namespace: backends
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;

spec:
  backend:
    serviceName: default-backend
    servicePort: 80
```

**Comment by adleong** [comment]
Documented in https://github.com/linkerd/website/pull/751

**Comment by mavrick** [comment]
Just for clarity; I've installed nginx-ingress via helm and it has created `nginx-ingress-default-backend` in the `default` namespace.

so, should my config should look like:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  backend:
    serviceName: nginx-ingress-default-backend
    servicePort: 80
```

cheers
