### ISSUE TITLE
Handle incompatible automount token setting In service account YAML

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#4651]
Following https://github.com/linkerd/linkerd2/pull/4145, the `inject` command will return an error with pods YAML that has the `automountServiceAccountToken` property set to `false`. The same validation should be applied to service accounts YAML. E.g., `linkerd inject` should return an error with the following YAML:

```
kind: ServiceAccount
apiVersion: v1
metadata:
  name: emoji
  namespace: emojivoto
automountServiceAccountToken: false
```
