### ISSUE TITLE
Fail when the addon config is not in the correct format

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#4665]
## Bug Report

Recently, One of the user tried to pass a full k8s add-on cm (including the k8s metadata) as the config through `--addon-config` and obviously it did not work, as it needs to follow the format as per `values.yaml`.

But the command did not fail, and just did not consider the config and emitted the manifests.

### What is the issue?

Ideally, the command should fail indicating that the configuration is not as per the specified format

### How can it be reproduced?

``` 
cat >> grafana-config.yaml << EOF
apiVersion: v1
data:
  values: |-
    global:
      grafanaUrl: ""
    grafana:
      enabled: false
      image:
        name: gcr.io/linkerd-io/grafana
      name: linkerd-grafana
    tracing:
      enabled: true
kind: ConfigMap
metadata:
  annotations:
  labels:
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-config-addons
  namespace: linkerd
EOF

linkerd install --addon-config ./grafana-config.yaml | k apply -f -
```

WIth the above config, the manifests are still emitted, even though the format does not match with the expected addon-config format.
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS:
- Linkerd version:
