### ISSUE TITLE
Setting the l5d-dst-overrides header configuration for Kong gateway

### ISSUE THREAD

**Issue by Wihrt** [linkerd/linkerd2#4721]
### What is the issue?

Linkerd doesn't work

### How can it be reproduced?

Using Helm :
- Install Linkerd 2.8.1, using self-signed certificates for every component needing one (Helm does not generate them)
- Install Kong
- Install Dummy Nginx with ingress

### Logs, error output, etc

You have the log of linkerd-proxy of Kong for the v2.7.1 and v2.8.1
https://gist.github.com/Wihrt/93f74ab26aa79ba788641181aeacb1a8

Logs of Kong when returning 502
https://gist.github.com/Wihrt/639658f715a21b0081c116ca77ea2b82

You have also the result of Helm with Linkerd v2.8.1 with Helm chart v2.7.1 and v2.8.1 + Kong Manifest + Nginx Manifest
https://gist.github.com/Wihrt/9fca502c587d757a177adf4dc6fe6895

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust roots are using supported crypto algorithm
√ trust roots are within their validity period
√ trust roots are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust root

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.7.1 but the latest stable version is 2.8.1
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
√ control plane is up-to-date
‼ control plane and cli versions match
    control plane running stable-2.8.1 but cli running stable-2.7.1
    see https://linkerd.io/checks/#l5d-version-control for hints
```

### Environment

- Kubernetes Version: 1.14.9
- Cluster Environment: Deployed with kubeadm
- Host OS: Ubuntu
- Linkerd version: 2.8.1

### Possible solution

Currently, none found

### Additional context

I have tested different cases of deployments :

| Helm Chart Version | Linkerd Controller version | Linkerd Proxy version | Status |
| --- | --- | --- | --- |
| 2.7.1 | 2.7.1 | 2.7.1 | OK |
| 2.7.1 | 2.8.1 | 2.8.1 | OK |
| 2.8.1 | 2.8.1 | 2.8.1 | KO |
| 2.8.1 | 2.7.1 | 2.7.1 | OK |

**Comment by ihcsim** [comment]
@Wihrt For repro purposes, can you attach your Nginx and Kong YAML manifest? You mentioned on Slack that this caused Kong to reply with 502 errors, right? Do you have those logs?

**Comment by adleong** [comment]
Hi @Wihrt!

This looks like an infinite loop.  This can happen with ingresses because they receive requests that have the ingress' address in the Host or Authority header.  When the ingress tries to send that request to a backend, the Linkerd proxy sees that the Host or Authority header targets the ingress and sends it back, resulting in a loop.

The Linkerd [ingress docs](https://linkerd.io/2/tasks/using-ingress/) describe how to avoid this by configuring your ingress to set the `l5d-dst-override` header.

Unfortunately, we don't have any docs specifically for Kong, so you'll have to look at the Kong documentation to find out how to do this.

**Comment by Wihrt** [comment]
I have updated this gist https://gist.github.com/Wihrt/9fca502c587d757a177adf4dc6fe6895, to add Kong and Nginx manifests
You can also find the logs of Kong here : https://gist.github.com/Wihrt/639658f715a21b0081c116ca77ea2b82

I have tried also differents things :

| Helm Chart Version | Linkerd Controller version | Linkerd Proxy version | Kong Meshed | Nginx Meshed | Status |
| --- | --- | --- | --- | --- | --- |
| 2.7.1 | 2.8.1 | 2.8.1 | Yes | Yes | OK |
| 2.8.1 | 2.8.1 | 2.8.1 | Yes | Yes | KO |
| 2.8.1 | 2.8.1 | 2.8.1 | No | Yes | OK |

For adding the header `l5d-dst-override`, it is done by using the request-transformer plugin
You need to create a `KongPlugin` object

```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
config:
  add:
    headers:
    - l5d-dst-override:security-manager-security-drm-gateway.security-manager.svc.cluster.local:8080
metadata:
  name: kong-crds-linkerd
plugin: request-transformer
```
And you need to link this KongPlugin by using an annotation inside your Ingress

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: "true"
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: kong-crds-linkerd  # This line is to add
  name: nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: http
        path: /nginx
```

**Comment by ihcsim** [comment]
@Wihrt Can you try setting the `l5d-dst-override` in the ingress resource, which I assume is the ingress resource for your kong gateway, since it's annotated with `kubernetes.io/ingress.class: kong`? (The ingress is named `nginx-ingress` though.) To confirm if the `l5d-dst-override` header is added, you can use `linkerd tap -ojson` on the downstream service.

**Comment by Wihrt** [comment]
Yeah, for the naming, it's not the best, I agree, but yes, Kong is my ingress Controller. Nginx is just a dummy web server.

I have created/updated the correct objects

KongPlugin
```yaml
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: nginx-linkerd
  namespace: security-manager
plugin: request-transformer
config:
  add:
    headers:
    - l5d-dst-override:nginx.security-manager.svc.cluster.local:80
```

Ingress
```yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: security-manager
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "true"
    konghq.com/plugins: "nginx-linkerd"
spec:
  rules:
  - http:
      paths:
      - path: /nginx
        backend:
          serviceName: nginx
          servicePort: http
```

Result of the command : `linkerd tap deploy/nginx -n security-manager -o json`
```json
{
  "source": {
    "ip": "10.39.0.2",
    "port": 52092,
    "metadata": {
      "client_id": "kong-kong.security-manager.serviceaccount.identity.linkerd.cluster.local",
      "control_plane_ns": "linkerd",
      "deployment": "kong-kong",
      "namespace": "security-manager",
      "pod": "kong-kong-55bb9567f7-lkrxt",
      "pod_template_hash": "55bb9567f7",
      "serviceaccount": "kong-kong",
      "tls": "true"
    }
  },
  "destination": {
    "ip": "10.40.0.2",
    "port": 8080,
    "metadata": {
      "control_plane_ns": "linkerd",
      "deployment": "nginx",
      "namespace": "security-manager",
      "pod": "nginx-65fb47cbd-ttjnv",
      "pod_template_hash": "65fb47cbd",
      "serviceaccount": "default"
    }
  },
  "routeMeta": null,
  "proxyDirection": "INBOUND",
  "requestInitEvent": {
    "id": {
      "base": 1,
      "stream": 0
    },
    "method": "GET",
    "scheme": "",
    "authority": "172.20.178.113:32080",
    "path": "/",
    "headers": [
      {
        "name": "host",
        "valueStr": "172.20.178.113:32080"
      },
      {
        "name": "if-none-match",
        "valueStr": "W/\"5f04bb5a-264\""
      },
      {
        "name": "x-forwarded-for",
        "valueStr": "127.0.0.1"
      },
      {
        "name": "x-forwarded-proto",
        "valueStr": "http"
      },
      {
        "name": "x-forwarded-host",
        "valueStr": "172.20.178.113"
      },
      {
        "name": "x-forwarded-port",
        "valueStr": "8000"
      },
      {
        "name": "x-real-ip",
        "valueStr": "127.0.0.1"
      },
      {
        "name": "if-modified-since",
        "valueStr": "Tue, 07 Jul 2020 18:13:46 GMT"
      },
      {
        "name": "cache-control",
        "valueStr": "max-age=0"
      },
      {
        "name": "upgrade-insecure-requests",
        "valueStr": "1"
      },
      {
        "name": "user-agent",
        "valueStr": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.191"
      },
      {
        "name": "accept",
        "valueStr": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"
      },
      {
        "name": "accept-encoding",
        "valueStr": "gzip, deflate"
      },
      {
        "name": "accept-language",
        "valueStr": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7"
      },
      {
        "name": "l5d-dst-canonical",
        "valueStr": "nginx.security-manager.svc.cluster.local:80"
      }
    ]
  }
}
{
  "source": {
    "ip": "10.39.0.2",
    "port": 52092,
    "metadata": {
      "client_id": "kong-kong.security-manager.serviceaccount.identity.linkerd.cluster.local",
      "control_plane_ns": "linkerd",
      "deployment": "kong-kong",
      "namespace": "security-manager",
      "pod": "kong-kong-55bb9567f7-lkrxt",
      "pod_template_hash": "55bb9567f7",
      "serviceaccount": "kong-kong",
      "tls": "true"
    }
  },
  "destination": {
    "ip": "10.40.0.2",
    "port": 8080,
    "metadata": {
      "control_plane_ns": "linkerd",
      "deployment": "nginx",
      "namespace": "security-manager",
      "pod": "nginx-65fb47cbd-ttjnv",
      "pod_template_hash": "65fb47cbd",
      "serviceaccount": "default"
    }
  },
  "routeMeta": null,
  "proxyDirection": "INBOUND",
  "responseInitEvent": {
    "id": {
      "base": 1,
      "stream": 0
    },
    "sinceRequestInit": {
      "nanos": 1171821
    },
    "httpStatus": 304,
    "headers": [
      {
        "name": "server",
        "valueStr": "nginx"
      },
      {
        "name": "date",
        "valueStr": "Wed, 15 Jul 2020 09:41:01 GMT"
      },
      {
        "name": "last-modified",
        "valueStr": "Tue, 07 Jul 2020 18:13:46 GMT"
      },
      {
        "name": "x-frame-options",
        "valueStr": "SAMEORIGIN"
      },
      {
        "name": "etag",
        "valueStr": "\"5f04bb5a-264\""
      }
    ]
  }
}
{
  "source": {
    "ip": "10.39.0.2",
    "port": 52092,
    "metadata": {
      "client_id": "kong-kong.security-manager.serviceaccount.identity.linkerd.cluster.local",
      "control_plane_ns": "linkerd",
      "deployment": "kong-kong",
      "namespace": "security-manager",
      "pod": "kong-kong-55bb9567f7-lkrxt",
      "pod_template_hash": "55bb9567f7",
      "serviceaccount": "kong-kong",
      "tls": "true"
    }
  },
  "destination": {
    "ip": "10.40.0.2",
    "port": 8080,
    "metadata": {
      "control_plane_ns": "linkerd",
      "deployment": "nginx",
      "namespace": "security-manager",
      "pod": "nginx-65fb47cbd-ttjnv",
      "pod_template_hash": "65fb47cbd",
      "serviceaccount": "default"
    }
  },
  "routeMeta": null,
  "proxyDirection": "INBOUND",
  "responseEndEvent": {
    "id": {
      "base": 1,
      "stream": 0
    },
    "sinceRequestInit": {
      "nanos": 1202058
    },
    "sinceResponseInit": {
      "nanos": 30237
    },
    "responseBytes": 0,
    "trailers": null,
    "grpcStatusCode": 0
  }
}
```

Still, I don't really understand why this header is mandatory when deploying with the Helm Chart 2.8.1, since it's the only difference between the deployments I have made. But I'm okay to add it everywhere
