### ISSUE TITLE
Regenerate webhook TLS credentials during Linkerd upgrade

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#4813]
When running the `linkerd upgrade` command, the CLI will read the TLS credentials of the webhooks (such as the proxy-injector) and copy them into the `linkerd upgrade` output which has the effect of leaving these credentials intact and unchanged by the upgrade.  However, there isn't really any reason why these credentials need to remain unchanged during an upgrade.  

One problem here is that when these credentials expire (i.e. once the not-after date has passed) the Linkerd CLI does not provide a mechanism for regenerating them.

Rather than copying the existing credentials, the `linkerd upgrade` command should regenerate them.  This has the effect of refreshing the lifetime of these certificates each time that `linkerd upgrade` is performed.

**Comment by MaT1g3R** [comment]
I tried to get the helm chart to use certificates provisioned via cert-manager with some success.

The steps I've taken:

- Create issuer for `proxy-injector`, `sp-validator`, and `tap`, I'm reusing the issuer per this document: https://linkerd.io/2/tasks/automatically-rotating-control-plane-tls-credentials/

```yaml
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor

```

- Create certificate resources:

```yaml
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-proxy-injector-tls
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-tls
  duration: 24h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-sp-validator-tls
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-tls
  duration: 24h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: linkerd-tap-tls
  namespace: linkerd
spec:
  secretName: linkerd-tap-tls
  duration: 24h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-tap.linkerd.svc
  isCA: true
  keyAlgorithm: ecdsa
  usages:
  - cert sign
  - crl sign
  - server auth
  - client auth
```

- Modify the helm chart to work around https://github.com/linkerd/linkerd2/issues/3831:

This is for `templates/tap.yaml`, you need to do the same for `templates/proxy-injector.yaml` and `templates/sp-validator.yaml`

We need to add an init container to fix the file names for the cert. The reason we don't want to use `subPath` for this is Kubernetes won't restart the pod when the secret changes.

Add an init container:

```yaml
      initContainers:
      - {{- include "partials.proxy-init" . | indent 8 | trimPrefix (repeat 7 " ") }}
      {{ end -}}
      - image: busybox
        name: fix-cert-paths
        volumeMounts:
        - mountPath: /var/run/linkerd/tls-tmp
          name: tls
          readOnly: true
        - mountPath: /var/run/linkerd/tls
          name: tls-fixed
        command:
        - "sh"
        - "-c"
        - |
          cp /var/run/linkerd/tls-tmp/tls.crt /var/run/linkerd/tls/crt.pem &&
          cp /var/run/linkerd/tls-tmp/tls.key /var/run/linkerd/tls/key.pem
```

Add an emptyDir volume to hold the fixed files:

```yaml
      volumes:
      - emptyDir: {}
        name: tls-fixed
```

Finally use `tls-fixed` as the volume mount in the main container:

```yaml
      - args:
        - tap
        - -controller-namespace={{.Values.global.namespace}}
        - -log-level={{.Values.controllerLogLevel}}

........omitted........

        volumeMounts:
        - mountPath: /var/run/linkerd/tls
          name: tls-fixed
          readOnly: true
```

- Finally, this is the `values.yaml` I'm using to deploy linkerd. The `caBundles` and `identityTrustAnchorsPEM` have the exact same values, since I'm just using the same issuer for all of them.

```yaml
global:
  grafanaUrl: foo.bar.com
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
proxyInjector:
  externalSecret: true
  caBundle: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
profileValidator:
  externalSecret: true
  caBundle: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
tap:
  externalSecret: true
  caBundle: |
    -----BEGIN CERTIFICATE-----

    -----END CERTIFICATE-----
```
