### ISSUE TITLE
Grafana links not updated when leveraging external grafana

### ISSUE THREAD

**Issue by imdhruva** [linkerd/linkerd2#4838]
### What is the issue?
Using the helm-chart I have specified following values:
```yaml
global:
  cniEnabled: true
  grafanaUrl: https://externalurl.com
enforcedHostRegexp: '^linkerd\.(int|qa|stagin|prod)*\.io$'
installNamespace: false
grafana:
  enabled: false
```
On opening the page-source of the linkerd-web we do see the html body being updated as (check label `data-grafana`):
```

  <!doctype html>
  <html lang="en">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>Linkerd</title>
  <meta name="description" content="Linkerd">
  <meta name="keywords" content="Linkerd">
  <link rel="icon" type="image/png" href="/dist/img/favicon.png">
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
     
  <script type="text/javascript" src="/dist/index_bundle.js" async></script>
   
   
  </head>
   <body>
    
   <div class="main" id="main"
   <data-release-version="stable-2.8.1"
   <data-go-version="go1.14.2"
   <data-controller-namespace="linkerd"
   <data-uuid="abd18360-3053-45fe-b9b7-e55001ec4c44"
   <data-grafana="https://externalurl.com"
   <data-jaeger="">
    
   </div>
    
   </body>
   </html>
 
```
however the grafana link still points to the old dashboard (copying element from html - check `href="/grafana/dashboard/db/linkerd-namespace?var-namespace=int"`):
```
<a target="_blank" href="/grafana/dashboard/db/linkerd-namespace?var-namespace=int">&nbsp;&nbsp;<svg version="1.1" id="Layer_1" x="0px" y="0px" width="15px" height="15px" viewBox="0 0 351 365" xml:space="preserve"><g id="Layer_1_1_"></g><linearGradient id="SVGID_1_grafana" gradientUnits="userSpaceOnUse" x1="175.5" y1="445.4948" x2="175.5" y2="114.0346"><stop offset="0" style="stop-color: rgb(255, 241, 0);"></stop><stop offset="1" style="stop-color: rgb(240, 90, 40);"></stop></linearGradient><path class="grafana-st0" d=".."></path></svg></a>
```

### How can it be reproduced?

update helm-chart values file as:
```yaml
global:
  cniEnabled: true
  grafanaUrl: https://externalurl.com
enforcedHostRegexp: '^linkerd\.(int|qa|stagin|prod)*\.io$'
installNamespace: false
grafana:
  enabled: false
```
and check service `linkerd-web`

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version: 1.16
- Cluster Environment: EKS
- Host OS: 5.4.38-17.76.amzn2.x86_64
- Linkerd version: stable-2.8.1

### Possible solution

Prepend all the links to grafana in linkerd2 web UI with external grafana endpoints
