### ISSUE TITLE
Expose Dashboard via Amabassador 400 Error

### ISSUE THREAD

**Issue by vikas027** [linkerd/linkerd2#4929]
## Bug Report
I have used Linkerd with Traefik and Nginx successfully but attempting with Ambassador this time which works on Service annotations. 

My ambassador mapping works fine on `default` namespace, not sure if I have to do anything special for services on `linkerd` namespace.

### What is the issue?
Unable to expose linkerd dashboard. 

### How can it be reproduced?
- Install Ambassador on Node port (30080 for HTTP and 30443 for HTTPS)
- Install Linkerd
- Edit `linkerd-web` Service annotations

```
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: linkerd-web-mapping
      host: linkerd-web.example.com
      prefix: /
      service: linkerd-web.linkerd.svc.cluster.local:8084
      add_linkerd_headers: true
```

### Logs, error output, etc

```bash
 ~ # curl -H 'Host: linkerd-web.example.com' https://<NODE_IP>:30443 -k
It appears that you are trying to reach this service with a host of 'linkerd-web.example.com'.
This does not match /^(localhost|127\.0\.0\.1|linkerd-web\.linkerd\.svc\.cluster\.local|linkerd-web\.linkerd\.svc|\[::1\])(:\d+)?$/ and has been denied for security reasons.
Please see https://linkerd.io/dns-rebinding for an explanation of what is happening and how to fix it.
 ~ #
```

#### `linkerd check` output

```text
 ~ # linkerd check      
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
 ~ # 
```

### Environment

- Kubernetes Version: 1.18.8
- Cluster Environment: a VM on GCP
- Host OS: Debian 9
- Linkerd version: stable-2.8.1

### Additional context
May be it is a good idea to add an example in the [documentation](https://linkerd.io/2/tasks/exposing-dashboard/)?

**Comment by ihcsim** [comment]
@vikas027 See https://linkerd.io/dns-rebinding, per the error message. You will have to either rewrite the header or  update the `-enforced-host` argument of the `linkerd-web` service.

>  curl -H 'Host: linkerd-web.example.com' https://<NODE_IP>:30443 -k

Try with:

```
 # curl -H 'Host: linkerd-web.linkerd.svc' https://<NODE_IP>:30443 -k
```

**Comment by vikas027** [comment]
Thanks @ihcsim . I have got it working, [host_rewrite](https://www.getambassador.io/docs/pre-release/topics/using/headers/host/#using-host_rewrite) was the key.

```
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: linkerd-web-mapping
      host: linkerd-web.example.com
      prefix: /
      host_rewrite: linkerd-web.linkerd.svc.cluster.local:8084
      service: linkerd-web.linkerd.svc.cluster.local:8084
```

**Logs**
```
 ~ # curl -H 'Host: linkerd-web.example.com' https://<NODE_IP>:30443 -k
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title>Linkerd</title>
    <meta name="description" content="Linkerd">
    <meta name="keywords" content="Linkerd">
    <link rel="icon" type="image/png" href="/dist/img/favicon.png">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    
  
    <script type="text/javascript" src="/dist/index_bundle.js" async></script>
  

  </head>
  <body>
    
  <div class="main" id="main"
    data-release-version="stable-2.8.1"
    data-go-version="go1.14.2"
    data-controller-namespace="linkerd"
    data-uuid="518eda1b-634b-4167-943c-fba971efca00"
    data-grafana="linkerd-grafana.linkerd.svc.cluster.local:3000"
    data-jaeger="linkerd-jaeger.linkerd.svc.cluster.local:16686">
    
  </div>

  </body>
</html>
 ~ # 
```
