### ISSUE TITLE
Traffic Split not working externally (Ambassador Ingress)

### ISSUE THREAD

**Issue by vikas027** [linkerd/linkerd2#4948]
## Bug Report
I am using Ambassador as ingress controller and trying to get basic traffic split using SMI Spec.

This is my complete yaml with two versions of apps (and their services), traffic split, and service for traffic split.
```yaml
###### APP v1
---
apiVersion: v1
kind: Service
metadata:
  name: site-counter-v1
  labels:
    app: site-counter
    version: v1
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: site-counter-1-mapping
      host: linkerd-app-1.example.com
      prefix: /
      service: site-counter-v1.default.svc.cluster.local:80
spec:
  type: ClusterIP
  selector:
    app: site-counter
    version: v1
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-counter-v1
  labels:
    app: site-counter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-counter
      version: v1
  template:
    metadata:
      labels:
        version: v1
        app: site-counter
    spec:
      containers:
      - image: vikas027/site-counter:dev
        name: site-counter

###### APP v2
---
apiVersion: v1
kind: Service
metadata:
  name: site-counter-v2
  labels:
    app: site-counter
    version: v2
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: site-counter-2-mapping
      host: linkerd-app-2.example.com
      prefix: /
      service: site-counter-v2.default.svc.cluster.local:80
spec:
  type: ClusterIP
  selector:
    app: site-counter
    version: v2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-counter-v2
  labels:
    app: site-counter
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site-counter
      version: v2
  template:
    metadata:
      labels:
        version: v2
        app: site-counter
    spec:
      containers:
      - image: vikas027/site-counter:dev
        name: site-counter
        env:
        - name: SHOW_IP
          value: "false"

##### TRAFFIC SPLIT
---
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: traffic-split-site-counter
spec:
  service: site-counter
  backends:
  - service: site-counter-v1
    weight: 0m
  - service: site-counter-v2
    weight: 1000m

---
apiVersion: v1
kind: Service
metadata:
  name: site-counter
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: site-counter-mapping
      host: linkerd-app.example.com
      prefix: /
      service: site-counter.default.svc.cluster.local:80
      add_linkerd_headers: true # <-- I have tried both with and without this line
spec:
  selector:
    app: site-counter
  ports:
    - port: 80
      targetPort: 80
```

In this example, I have to apps `v1` shows the IP of the pod and `v2` doesn't
```bash
bash-5.0# curl http://site-counter-v1.default.svc.cluster.local:80/counter
site-counter-v1-85d57fccf9-m872j  -  [10.32.0.19]  -  View Count:  1
bash-5.0# 
bash-5.0# curl http://site-counter-v2.default.svc.cluster.local:80/counter
site-counter-v2-559447fc96-74rrq  -  View Count:  1
bash-5.0# 
```

And the third service is for traffic splitting, in my example, 100% of the traffic is going to app `v2` which is also working fine internally
```bash
bash-5.0# for i in $(seq 1 10); do curl http://site-counter.default.svc.cluster.local:80/counter; done
site-counter-v2-559447fc96-74rrq  -  View Count:  45
site-counter-v2-559447fc96-74rrq  -  View Count:  46
site-counter-v2-559447fc96-74rrq  -  View Count:  47
site-counter-v2-559447fc96-74rrq  -  View Count:  48
site-counter-v2-559447fc96-74rrq  -  View Count:  49
site-counter-v2-559447fc96-74rrq  -  View Count:  50
site-counter-v2-559447fc96-74rrq  -  View Count:  51
site-counter-v2-559447fc96-74rrq  -  View Count:  52
site-counter-v2-559447fc96-74rrq  -  View Count:  53
site-counter-v2-559447fc96-74rrq  -  View Count:  54
bash-5.0#
```

### What is the issue?
The issue occurs when I am trying to hit the third service externally. As per my SMI specification, the third service should go to application `v2` but looks like it is doing a round-robin. Ideally, all requests should go to application `v2` which does not show pod's IP.

I have also tried TCP passthrough on Ambassador HTTPS node ports thinking maybe GCP load balancer is doing something funny 

```bash
✦ ❯ for i in $(seq 1 10); do curl -sH 'Host: linkerd-app.example.com' https://<GCP_TCP_LoadBalancer_IP>:30443/counter -k; done  # <-- TCP passthrough on Ambassador HTTPS node ports
OR
✦ ❯ for i in $(seq 1 10); do curl -sH 'Host: linkerd-app.example.com' https://<NODE_IP>:30443/counter -k; done
OR
✦ ❯ for i in $(seq 1 10); do curl https://linkerd-app.example.com/counter; done
site-counter-v2-559447fc96-74rrq  -  View Count: 468
site-counter-v2-559447fc96-74rrq  -  View Count:  469
site-counter-v2-559447fc96-74rrq  -  View Count:  470
site-counter-v1-85d57fccf9-m872j  -  [10.32.0.19]  -  View Count:  482
site-counter-v1-85d57fccf9-m872j  -  [10.32.0.19]  -  View Count:  483
site-counter-v2-559447fc96-74rrq  -  View Count:  471
site-counter-v2-559447fc96-74rrq  -  View Count:  472
site-counter-v1-85d57fccf9-m872j  -  [10.32.0.19]  -  View Count:  484
site-counter-v2-559447fc96-74rrq  -  View Count:  473
site-counter-v1-85d57fccf9-m872j  -  [10.32.0.19]  -  View Count:  485
✦ ❯
```

### How can it be reproduced?
- Spin up Kubernetes 1.18.8 one node cluster using `kubeadm`
- Install Ambassador on Node port (30080 for HTTP and 30443 for HTTPS)
- Install Linkerd
- Set up a TCP load balancer on GCP which listens on port 443 and forwards the traffic on 30443
- Use the YAML to create the resources

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
 ~ # linkerd check                             
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

linkerd-tracing
---------------
√ collector service account exists
√ jaeger service account exists
√ collector config map exists
√ collector pod is running
√ jaeger pod is running

Status check results are √
 ~ # 
```

### Environment

- Kubernetes Version: 1.18.8
- Cluster Environment: Single VM on GCP
- Host OS: Debian 9
- Linkerd version: stable-2.8.1
