### ISSUE TITLE
Tap isn't showing the correct mTLS status

### ISSUE THREAD

**Issue by ihcsim** [linkerd/linkerd2#4992]
### What is the issue?

When using `curl` to send multiple requests from an injected client to an injected server, `linkerd tap` always reports mTLS isn't working for the **first call**, with the `tls=no_tls_from_remote` field in its output. Subsequent calls from the same client to the same server shows that `tls=true`.

### How can it be reproduced?

Deploy the following an injected `httpbin` backend service:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```

Deploy the following injected `curl` client:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
spec:
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: curl
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: appropriate/curl
        name: curl-inject
```

Tap the `httpbin` pod:

```sh
linkerd -n httpbin tap po/httpbin-d86f58cf6-chnbk
```

Tap the `curl` pod:

```sh
linked tap po/curl-85bcfccf97-qjrzk
```

Use the `curl` pod to issue a HTTP `GET` to the `httpbin` endpoint:

```sh
kubectl exec curl-85bcfccf97-qjrzk -- curl httpbin.httpbin:8000/status/200
```

Notice that the `tap` outputs on both inbound and outbound sides show mTLS isn't working:

E.g. on the inbound side,

```sh
req id=0:0 proxy=in  src=10.244.0.18:53070 dst=10.244.0.17:80 tls=no_tls_from_remote :method=GET :authority=httpbin.httpbin:8000 :path=/status/200
rsp id=0:0 proxy=in  src=10.244.0.18:53070 dst=10.244.0.17:80 tls=no_tls_from_remote :status=200 latency=4330µs
end id=0:0 proxy=in  src=10.244.0.18:53070 dst=10.244.0.17:80 tls=no_tls_from_remote duration=25µs response-length=0B
```

and on the outbound side,

```sh
req id=0:0 proxy=out src=10.244.0.18:53064 dst=10.96.16.38:8000 tls=not_provided_by_service_discovery :method=GET :authority=httpbin.httpbin:8000 :path=/status/200
rsp id=0:0 proxy=out src=10.244.0.18:53064 dst=10.96.16.38:8000 tls=not_provided_by_service_discovery :status=200 latency=6996µs
end id=0:0 proxy=out src=10.244.0.18:53064 dst=10.96.16.38:8000 tls=not_provided_by_service_discovery duration=30µs response-length=0B
```

Issue the same `curl` command again:

```sh
kubectl exec curl-85bcfccf97-qjrzk -- curl httpbin.httpbin:8000/status/200
```

Now `tap` reports that `tls=true` on both the inbound and outbound sides.

E.g. on the inbound side,

```sh
req id=0:0 proxy=in  src=10.244.0.18:53070 dst=10.244.0.17:80 tls=no_tls_from_remote :method=GET :authority=httpbin.httpbin:8000 :path=/status/200
rsp id=0:0 proxy=in  src=10.244.0.18:53070 dst=10.244.0.17:80 tls=no_tls_from_remote :status=200 latency=4330µs
end id=0:0 proxy=in  src=10.244.0.18:53070 dst=10.244.0.17:80 tls=no_tls_from_remote duration=25µs response-length=0B
req id=0:2 proxy=in  src=10.244.0.18:40564 dst=10.244.0.17:80 tls=true :method=GET :authority=httpbin.httpbin:8000 :path=/status/200
rsp id=0:2 proxy=in  src=10.244.0.18:40564 dst=10.244.0.17:80 tls=true :status=200 latency=2155µs
end id=0:2 proxy=in  src=10.244.0.18:40564 dst=10.244.0.17:80 tls=true duration=18µs response-length=0B
```

and on the outbound side,

```sh
req id=0:0 proxy=out src=10.244.0.18:53064 dst=10.96.16.38:8000 tls=not_provided_by_service_discovery :method=GET :authority=httpbin.httpbin:8000 :path=/status/200
rsp id=0:0 proxy=out src=10.244.0.18:53064 dst=10.96.16.38:8000 tls=not_provided_by_service_discovery :status=200 latency=6996µs
end id=0:0 proxy=out src=10.244.0.18:53064 dst=10.96.16.38:8000 tls=not_provided_by_service_discovery duration=30µs response-length=0B
req id=0:2 proxy=out src=10.244.0.18:54904 dst=10.244.0.17:80 tls=true :method=GET :authority=httpbin.httpbin:8000 :path=/status/200
rsp id=0:2 proxy=out src=10.244.0.18:54904 dst=10.244.0.17:80 tls=true :status=200 latency=5543µs
end id=0:2 proxy=out src=10.244.0.18:54904 dst=10.244.0.17:80 tls=true duration=35µs response-length=0B
```

`linkerd edges` seems to be working correctly:

```sh
linkerd -n httpbin edges po                                                                      
SRC                                   DST                       SRC_NS    DST_NS    SECURED
curl-85bcfccf97-qjrzk                 httpbin-d86f58cf6-chnbk   default   httpbin   √
linkerd-prometheus-6ffbd6b86c-q7sn4   httpbin-d86f58cf6-chnbk   linkerd   httpbin   √
```

### Environment

- Kubernetes Version: k8s 1.18
- Cluster Environment: Kind
- Linkerd version: edge-20.9.3
