### ISSUE TITLE
EWMA loadbalancing not working as expected 

### ISSUE THREAD

**Issue by yeshwanth1312** [linkerd/linkerd2#5017]
## Bug Report
EWMA loadbalancing not working as expected 

### What is the issue?
linkerd is not sending more requests to least latency pod , Instead its sending equal rps to high latency pod vs low latency pod 

### How can it be reproduced?
Deploy two apps and talk them via Kube service and send more rps

### Logs, error output, etc

![image](https://user-images.githubusercontent.com/34922578/94460484-cd819880-0186-11eb-865d-5add232facb4.png)
![image](https://user-images.githubusercontent.com/34922578/94460537-dffbd200-0186-11eb-9cec-7f974c163f8d.png)

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: v1.17.6 
- Cluster Environment: (GKE, AKS, kops, ...) Running on Bare metal , Built using kubespray
- Host OS: Centos7
- Linkerd version: 
  Client version: stable-2.8.1
  Server version: stable-2.8.1

### Additional context

Slack discussion in Linkerd workspace about the issue : https://linkerd.slack.com/archives/C89RTCWJF/p1601061489075100

**Comment by grampelberg** [comment]
@kleimkuhler can you take a look and verify that we can replicate this? BB or slowcooker should be able to show it off pretty easily.

**Comment by kleimkuhler** [comment]
@grampelberg Yep I'll take a look

**Comment by kleimkuhler** [comment]
I am reproducing this on `stable-2.8.1` right now, but not the most recent edge `edge-20.9.4`.

With the YAML file below that creates a load of 500 rps, I have the following happening:

### stable-2.8.1

```
❯ linkerd stat deploy/fast deploy/slow
NAME   MESHED   SUCCESS       RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
fast      1/1   100.00%   17.7rps           1ms           1ms           1ms          2
slow      1/1   100.00%   17.7rps          45ms          67ms          93ms          2
```

Note the fact that the RPS of both pods is not close to the expected 500 RPS from the `slow-cooker` job.

### edge-20.9.4

```
❯ linkerd stat deploy/fast deploy/slow
NAME   MESHED   SUCCESS        RPS   LATENCY_P50   LATENCY_P95   LATENCY_P99   TCP_CONN
fast      1/1   100.00%   489.7rps           1ms           1ms           1ms          2
slow      1/1   100.00%     0.1rps          45ms          50ms          50ms          2
```

Here, RPS is closer to what we'd expect.

### Reproducing

This YAML file creates a `fast` and `slow` deployment. `slow` waits `50ms` before responding.

After installing linkerd, inject the resources below:

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminus
  template:
    metadata:
      labels:
        app: terminus
    spec:
      containers:
      - name: fast
        image: buoyantio/bb:v0.0.6
        args:
        - terminus
        - "--h1-server-port=8080"
        - "--response-text=fast"
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terminus
  template:
    metadata:
      labels:
        app: terminus
    spec:
      containers:
      - name: slow
        image: buoyantio/bb:v0.0.6
        args:
        - terminus
        - "--h1-server-port=8080"
        - "--sleep-in-millis=50"
        - "--response-text=slow"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: terminus-svc
  labels:
    app: terminus-svc
spec:
  selector:
    app: terminus
  ports:
  - name: http
    port: 8080
    targetPort: 8080
---
apiVersion: batch/v1
kind: Job
metadata:
  name: slow-cooker
spec:
  template:
    metadata:
      labels:
        app: slow-cooker
    spec:
      containers:
      - name: slow-cooker
        image: buoyantio/slow_cooker:1.3.0
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          sleep 15 # wait for pods to start
          /slow_cooker/slow_cooker -qps 500 -metric-addr 0.0.0.0:9999 http://terminus-svc:8080
        ports:
        - containerPort: 9999
      restartPolicy: OnFailure
```
