### ISSUE TITLE
multicluster: single network with private endpoints for gateways

### ISSUE THREAD

**Issue by Dariusch** [linkerd/linkerd2#5024]
### What problem are you trying to solve?

Two clusters running on the same network do not need to communicate via the public internet with each other.
Having large payloads can be costly for in and egress traffic.

As I am running mostly in GKE there is a concept of an internal load balancer.
You generate a static private IP and assign it to the Service of type LoadBalancer.

### How should the problem be solved?

One solution might be to extend the helm chart for the gateway to accept service annotations like:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: some-service-name
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
...
```

As I am still evaluating linkerd I cannot predict any side effects which might occur either with mTLS or service mirroring.

### Any alternatives you've considered?

Not yet.

### How would users interact with this feature?

As there is only a change in routing there shouldn't be an interaction change.

Best regards,
Dariusch
