### ISSUE TITLE
Mirrored Service connectivity with Multicluster scenario

### ISSUE THREAD

**Issue by leon-andria** [linkerd/linkerd2#5096]
## Bug Report
Doing requests to the mirrored service require 3-4 times before to get 200 status code until you have a constant activities on the service; otherwise you got 503 status code.
When you don't do any activities after ~60s, you got back 503 status code and so on...
I notice this behavior is edge-20.9.4 (8-9 requests) and edge-20.9.1 (4-6 requests) and edge-20.9.2 (2-4 requests).

### What is the issue?
I believe that a connectivity issue when we open a session from the gateway, there is some kind of latency ?

### How can it be reproduced?
1. Create 2 clusters
2. Create a namespace with whoami and exported service
3. from the mirrored service cluster, use nginx with curl

```yaml
---
kind: Namespace
apiVersion: v1
metadata:
  name: net-pol
  annotations:
    linkerd.io/inject: enabled
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: net-pol
  name: whoami
  labels: 
    app: whoami      
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami     
    spec:
      containers:
      - name: whoami-container
        image: containous/whoami
        imagePullPolicy: Always
        ports: 
          - name: web
            containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
---
kind: Service
apiVersion: v1
metadata:
  name: whoami
  namespace: net-pol  
  labels:
    mirror.linkerd.io/exported: "true"  
spec:
  ports:
  - protocol: TCP
    port: 80
    name: web
  selector:
    app: whoami
```

install this nginx into the namespace where the mirrored service was created
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        linkerd.io/inject: enabled        
        config.linkerd.io/proxy-log-level: debug
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
````

### Environment

- Kubernetes Version: 1.17.9
- Cluster Environment: AKS
- Host OS: Linux
- Linkerd version: edge-20.10.3

### Possible solution
Ensure to have a retry policy to call the service.
