### ISSUE TITLE
2.9 - ServiceTopology and EndpointSlices testing

### ISSUE THREAD

**Issue by cpretzer** [linkerd/linkerd2#5115]
This ticket keeps track of the testing performed to validate that the ServiceTopology and EndpointSlices features are fully functional for the 2.9 release.

To test these features, I used k3d to create clusters with the feature gates enabled and disabled. Some of the values in the feature-gates flag below are redundant based on the default values. They are set here in order to be explicit about whether the features are enabled or disabled.

enabled:
`k3d cluster create linkerd-st --k3s-server-arg  '--kube-apiserver-arg=feature-gates=EndpointSlice=true,EndpointSliceProxying=true,ServiceTopology=true' --servers 3 --image docker.io/rancher/k3s:v1.19.3-k3s2
`

disabled:
`k3d cluster create linkerd-st --k3s-server-arg  '--kube-apiserver-arg=feature-gates=EndpointSlice=false,EndpointSliceProxying=false,ServiceTopology=false' --servers 3 --image docker.io/rancher/k3s:v1.19.3-k3s2
`

Each of the three nodes has the following taints and labels:
- k3d-linkerd-st-server-0
    - ```yaml
       taints:
       - effect: NoSchedule
         key: emojivoto
         value: zone
      ```
    - ```yaml
        labels:
            ...
            kubernetes.io/hostname: k3d-linkerd-st-server-0
            ...
            topology.kubernetes.io/region: east
            topology.kubernetes.io/zone: us
      ```
- k3d-linkerd-st-server-1
    - ```yaml
       taints:
       - effect: NoSchedule
         key: emojivoto
         value: region
      ```
    - ```yaml
        labels:
            ...
            kubernetes.io/hostname: k3d-linkerd-st-server-1
            ...
            topology.kubernetes.io/region: west
            topology.kubernetes.io/zone: us
      ```
- k3d-linkerd-st-server-2
    - ```yaml
       taints:
       - effect: NoSchedule
         key: emojivoto
         value: hostname
      ```
    - ```yaml
        labels:
            ...
            kubernetes.io/hostname: k3d-linkerd-st-server-2
            ...
            topology.kubernetes.io/region: east
            topology.kubernetes.io/zone: asia
      ```
To test these values, I [created a few versions](https://gist.github.com/cpretzer/1e04b1601ee21729686e25bf1feb1eb0) of emojivoto with various entries for `topologyKeys`:
- emojivoto-all-topologies.yml: `topologyKeys` set to `"*"`
- emojivoto-hostname.yml: `topologyKeys` set to `kubernetes.io/hostname`
- emojivoto-mixed-topologies.yml:
  - emoji-svc `topologyKeys` set to `kubernetes.io/hostname` and `topology.kubernetes.io/region`
  - voting-svc `topologyKeys` set to `kubernetes.io/hostname` and `topology.kubernetes.io/zone`
  - web-svc `topologyKeys` set to `topology.kubernetes.io/zone`, `topology.kubernetes.io/region`, and `"*"`
- emojivoto-no-topologies.yml: no `topologyKeys` defined
- emojivoto-region.yml: `topologyKeys` set to `topology.kubernetes.io/region`
- emojivoto-st.yml:
  - emoji-svc `topologyKeys` set to `kubernetes.io/hostname` and `"*"`
  - voting-svc `topologyKeys` set to `kubernetes.io/hostname`
  - web-svc `topologyKeys` set to `topology.kubernetes.io/zone`
- emojivoto-zone.yml: `topologyKeys` set to `topology.kubernetes.io/zone`

### ServiceTopologies Feature Flag Enabled
🎉 | emojivoto-all-topologies.yml | emojivoto-hostname.yml | emojivoto-mixed-topologies.yml | emojivoto-no-topologies.yml | emojivoto-region.yml | emojivoto-st.yml | emojivoto-zone.yml
------ | ------- | ------ | ------ | ------ | ------ | ------ | ------
Service Topology Enabled Enabled | All Pods should be able to communicate with each other | Pods on the same hostname should be able to communicate with each other | web -> voting <br> web -> emoji <br> emoji -> voting| All pods should be able to communicate with each other | web -> emoji <br> web -x-> voting <br> voting -x-> emoji | web -> emoji <br> web -x-> voting <br> voting -> emoji | web -x-> emoji <br> web -> voting <br> voting -x-> emoji

### ServiceTopologies Feature Flag Disabled
- All pods can always communicate with each other, even when `topololgyKeys` are included in the Service definitions
 
### EndpointSlices Feature Flag Enabled
- `linkerd install --enable-endpoint-slices`
   - All services have both Endpoint and EndpointSlice resources and pods can communicate with each other
- `linkerd install`
   - All services have Endpoint resources and pods can communicate with each other

### EndpointSlices Feature Flag Disabled
- `linkerd install --enable-endpoint-slices`
   - Install fails with the error message `Error: no EndpointSlice resources exist in the cluster` __Is this behavior sufficient? Should we add an option to `linkerd check --pre`?__
- `linkerd install`
   - All services have Endpoint resources and pods can communicate with each other
