### ISSUE TITLE
Kong ingress not passing TLS 

### ISSUE THREAD

**Issue by fritzstauff** [linkerd/linkerd2#5160]
### What is the issue?
Ingress example in the [DOCS](https://linkerd.io/2/tasks/using-ingress/#kong) between Kong and Linkerd2 do not produce TLS communication between app and kong 
### How can it be reproduced?
Install emoji app:
```
curl -sL https://run.linkerd.io/emojivoto.yml \
  | kubectl apply -f -
```

Install kong:
```
kubectl apply -f https://bit.ly/k4k8s
```

Inject service mesh:
```
kubectl get -n kong deploy -o yaml \
  | linkerd inject - \
  | kubectl apply -f -

kubectl get -n emojivoto deploy -o yaml \
  | linkerd inject - \
  | kubectl apply -f -
```
Apply Kong config: 

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: emojivoto-linkerd-header
  namespace: emojivoto
plugin: request-transformer
config:
  add:
    headers:
    - l5-dst-override:web-svc.emojivoto.svc.cluster.local
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emojivoto-web
  namespace: emojivoto
  annotations:

    kubernetes.io/ingress.class: "kong"
    konghq.com/strip-path: "false"
    konghq.com/plugins: emojivoto-linkerd-header  # This annotation will link the plugin to the Ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: web-svc
              servicePort: http
```
Access kong proxy and tap emojivoto app
```
linkerd -n emojivoto tap -o json deploy/web > log
```

### Logs, error output, etc

https://gist.github.com/fritzstauff/954cfa123e671d4651e65db8896918b7

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: GitVersion:"v1.18.8"
- Cluster Environment: Docker Desktop Kuberenetes for mac. Same result with minikube.
- Host OS: Catalina 10.15.7
- Linkerd version: stable-2.8.1

### Possible solution
Not sure

### Additional context
TLS works fine with Nginx ingress. For some reason, the Kong ingress does not.

**Comment by kleimkuhler** [comment]
Thanks for the report @fritzstauff! I am seeing TLS connections between Emojivoto and Kong on `edge-20.11.`.

I've set this up with Linkerd `edge-20.11.1` which was just released today as the `stable-2.9.0` release candidate and I'm seeing it work correctly. Because the new stable should be released so soon (possibly by end of week), I'm inclined to say this is fixed now and that you should consider upgrading if you can!

I'm not sure why this does not work on `stable-2.8.1`; I reproduced it myself and I do see the same issue as you.

My setup was a little different than what you posted above. I'll list it below so that you can confirm for yourself if you'd like. This is on a k3d cluster so it should be reproducible on whatever you use.

I created a new `emojivoto-web` image that when voting will send it's request to the ingress service `kong-proxy.kong:80`. It overrides the request `Host` header and sets it to `web-svc`. This way we are generating requests from inside the cluster, but still going through the ingress for voting.

I also adjusted the `kong-config.yaml` in two ways. The path it matches on is `/api/vote` now. I'm not sure why it was `/web` before. I also removed the `konghq.com/strip-path: "true"` annotation. This is probably worth a documentation update!

My steps:

```
kubectl apply -f https://bit.ly/kong-ingress-dbless
```

```
linkerd install |kubectl apply -f -
```

Inject kong with the new `--ingress` annotation:


```
kubectl get -n kong deploy -o yaml |linkerd inject --ingress - |kubectl apply -f -
```

Apply `emojivoto-inject.yaml`. This is emojivoto already injected and `deploy/vote-bot` removed.

Apply `kong-config.yaml`. This is different from yours as explained above.

Apply `vote-bot.yaml`. This uses the `buoyantio/emojivoto-web:vote-bot-header` image I created and overrides the URL that voting uses. Note that this `deploy/vote-bot` is not injected. You'll see calls to `/api/list` not TLS'd, but you will see calls to `/api/vote` that go through the Ingress TLS'd.

Then when I tap `deploy/web` I see the following:

```
  "source": {
    "ip": "10.42.0.18",
    "port": 35660,
    "metadata": {
      "client_id": "kong-serviceaccount.kong.serviceaccount.identity.linkerd.cluster.local",
      "control_plane_ns": "linkerd",
      "deployment": "ingress-kong",
      "namespace": "kong",
      "pod": "ingress-kong-57f49c8c7-mv48l",
      "pod_template_hash": "57f49c8c7",
      "serviceaccount": "kong-serviceaccount",
      "tls": "true"
    }
 ```

## YAMLs

`emojivoto-inject.yaml`:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: emojivoto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emoji
  namespace: emojivoto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voting
  namespace: emojivoto
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web
  namespace: emojivoto
---
apiVersion: v1
kind: Service
metadata:
  name: emoji-svc
  namespace: emojivoto
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: emoji-svc
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: emojivoto
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
  selector:
    app: voting-svc
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: web-svc
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: emoji
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v10
  name: emoji
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emoji-svc
      version: v10
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: emoji-svc
        version: v10
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: buoyantio/emojivoto-emoji-svc:v10
        name: emoji-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: emoji
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v10
  name: voting
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      version: v10
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: voting-svc
        version: v10
    spec:
      containers:
      - env:
        - name: GRPC_PORT
          value: "8080"
        - name: PROM_PORT
          value: "8801"
        image: buoyantio/emojivoto-voting-svc:v10
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          requests:
            cpu: 100m
      serviceAccountName: voting
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v10
  name: web
  namespace: emojivoto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-svc
      version: v10
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: web-svc
        version: v10
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: buoyantio/emojivoto-web:v10
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: web
---
```

`kong-config.yaml`:

```
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: emojivoto-linkerd-header
  namespace: emojivoto
plugin: request-transformer
config:
  add:
    headers:
    - l5-dst-override:web-svc.emojivoto.svc.cluster.local
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: emojivoto-web
  namespace: emojivoto
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/plugins: emojivoto-linkerd-header  # This annotation will link the plugin to the Ingress
spec:
  rules:
    - http:
        paths:
          - path: /api/vote
            backend:
              serviceName: web-svc
              servicePort: http
```

`vote-bot.yaml`:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: vote-bot
  name: vote-bot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-bot
  template:
    metadata:
      labels:
        app: vote-bot
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: web-svc.emojivoto:80
        - name: VOTE_OVERRIDE
          value: kong-proxy.kong:80
        image: buoyantio/emojivoto-web:vote-bot-header
        name: vote-bot
        resources:
          requests:
            cpu: 10m
```
