### ISSUE TITLE
Intermittent [RST, ACK] received by sidecar resulting in 502 errors

### ISSUE THREAD

**Issue by ael-g** [linkerd/linkerd2#5211]
## Bug Report
Intermittent 502 errors on pod with linkerd side-car.

### What is the issue?
I have Kubernetes liveness/readiness HTTP probe getting 502 errors to a NodeJS v12 container proxified by linkerd.
The 502 errors are quite irregular in time but happens to any http node listening service, every 10-30 minutes.

### How can it be reproduced?
Deploy a Kubernetes deployment like this:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-errors
  name: test-errors
spec:
  replicas: 10
  selector:
    matchLabels:
      app: test-errors
  template:
    metadata:
      annotations:
        config.linkerd.io/enable-debug-sidecar: "true"
    spec:
      containers:
      - args:
        - --trace_gc
        - index
        command:
        - node
        image: duluca/minimal-node-web-server
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: node
``` 

### Logs, error output, etc
When starting the debug container with `config.linkerd.io/enable-debug-sidecar: "true"`, I observed that 502 errors happened when the connection looks closed on NodeJS side, but linkerd-proxy thinks it's still open:
```
# Connection open at the start of the container
6 0.000934966    127.0.0.1 → 127.0.0.1    TCP 76 48066 → 3000 [SYN] Seq=0 Win=43690 Len=0 MSS=65495 SACK_PERM=1 TSval=1980822319 TSecr=0 WS=128
....
28 5.000358282 127.0.0.1 → 127.0.0.1 HTTP 162 GET / HTTP/1.1
29 5.002003529 127.0.0.1 → 127.0.0.1 HTTP 1044 HTTP/1.1 200 OK (text/html)
30 5.002024416    127.0.0.1 → 127.0.0.1    TCP 68 48066 → 3000 [ACK] Seq=189 Ack=1953 Win=42880 Len=0 TSval=1980827320 TSecr=1980827320
....
# this probe is OK, lots of following probes are OK too, then:
2637 495.008389651 127.0.0.1 → 127.0.0.1 HTTP 162 GET / HTTP/1.1
2638 495.008881120    127.0.0.1 → 127.0.0.1    TCP 68 3000 → 48066 [RST, ACK] Seq=96625 Ack=9401 Win=43776 Len=0 TSval=1981317283 TSecr=198131728

-> makes the 502 error and then linkerd-proxy connects again
2659 500.001281043    127.0.0.1 → 127.0.0.1    TCP 76 52230 → 3000 [SYN] Seq=0 Win=43690 Len=0 MSS=65495 SACK_PERM=1 TSval=1981322275 TSecr=0 WS=128
2660 500.001292384    127.0.0.1 → 127.0.0.1    TCP 76 3000 → 52230 [SYN, ACK] Seq=0 Ack=1 Win=43690 Len=0 MSS=65495 SACK_PERM=1 TSval=1981322275 TSecr=1981322275 WS=128
```
I cannot see any RST packet before warning linkerd-proxy that node is closing the connection.
But it seems to have something to do with nodejs because I cannot reproduce if I switch my node container for a nginx container.

#### `linkerd check` output

```
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
‼ cli is up-to-date
    is running version 2.8.1 but the latest stable version is 2.9.0
    see https://linkerd.io/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.8.1 but the latest stable version is 2.9.0
    see https://linkerd.io/checks/#l5d-version-control for hints
√ control plane and cli versions match

linkerd-addons
--------------
√ 'linkerd-config-addons' config map exists

Status check results are √
```

### Environment

- Kubernetes Version: v1.16.13-gke.401
- Cluster Environment: GKE
- Linkerd version: stable-2.8.1
