### ISSUE TITLE
Bring-your-own-tracing with the jaeger extension

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd2#5234]
By deafult, the linkerd-jaeger extension installs an OpenCensus collector and a Jaeger backend.

However, for users who have an existing Jaeger backend, it should be possible to configure the linkerd-jaeger extension to have the oc-collector send traces to that existing Jaeger backend.

Similarly, for users who have an existing OpenCensus collector, it should be possible to configure the jaeger-injector to point injected proxies at that existing collector.

**Comment by adleong** [comment]
Fixed by https://github.com/linkerd/linkerd2/pull/5499

**Comment by ericjee** [comment]
Hi @adleong ,Thx for the great work:)  
Quick question, How to handle the second scenario as you described since I have my own Opentelemetry collector.

**Comment by arunmat** [comment]
Looks like the second scenario as described by @adleong is not covered today.

**Comment by adleong** [comment]
@ericjee @arunmat good catch that the second scenario isn't covered by the docs.  are either of you interested in submitting a PR to fix this omission?  it should be as simple as setting the `webhook.collectorSvcAddr` and `webhook.collectorSvcAccount` chart values (similarly to how we set the `collector.jaegerAddr` values in the bring-your-own-jaeger example).  For reference, the full list of configurable values can be found in the [chart readme](https://github.com/linkerd/linkerd2/tree/main/jaeger/charts/linkerd-jaeger)

**Comment by arunmat** [comment]
@adleong I think its more than just the doc. I think the helm chart should be modified NOT to deploy the bundled collector and jaeger when custom values are set for `webhook.collectorSvcAddr`, `webhook.collectorSvcAccount` and `collector.jaegerAddr`.

**Comment by whiskeysierra** [comment]
@arunmat If you're willing to run a kustomize postrender step, you can apply a `$patch: delete` to the resources you don't want to deploy. See also https://tech.aabouzaid.com/2021/05/delete-a-manifest-from-kustomize-base.html.

**Comment by rucciva** [comment]
Hi @adleong , is it also possible to use existing  otel collector in another namespace? Currently, i have installed jaeger injector inside linkerd namespace and the otel collector is in another namespace, but i don't see any traffic reaching the otel collector port from linkerd proxy

**Comment by whiskeysierra** [comment]
Definitely works, we're running that setup. Make sure your collector is
part of the mesh, that threw us off at the beginning. The proxies only
support TLS when talking to the collector.

**Comment by rucciva** [comment]
hi @whiskeysierra , thanks for replying.

my collector is already part of the mesh, in fact i can confirm that it can receive otlp traffic from [ingress-nginx](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#otlp-collector-host)
<img width="1249" alt="Screen Shot 2023-05-07 at 17 21 54" src="https://user-images.githubusercontent.com/4647473/236671847-138bf5a8-8cbe-4980-be2c-fe587b9f4187.png">

i use the [otel helm chart](https://github.com/open-telemetry/opentelemetry-helm-charts) to install the collector with this values.yaml
```yaml
mode: "deployment"

config:
  receivers:
    opencensus:
    jaeger: null
    prometheus: null
    zipkin: null
  exporters:
    otlp:
      endpoint: datadog.datadog.svc.cluster.local:4317
      tls:
        insecure: true
    logging: null
  service:
    extensions:
      - health_check
      - memory_ballast
    pipelines:
      logs: null
      metrics: null
      traces:
        receivers:
          - opencensus
          - otlp
        processors:
          - memory_limiter
          - batch
        exporters:
          - otlp

ports:
  opencensus:
    enabled: true
    containerPort: 55678
    servicePort: 55678
    protocol: TCP
    appProtocol: grpc
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
```
