### ISSUE TITLE
Updated TLS secrets not being picked up by tap or proxy-injector

### ISSUE THREAD

**Issue by r8474** [linkerd/linkerd2#5272]
### What is the issue?

We recently upgraded from `edge 20.2.2` to `stable 2.9.0` using the official Helm chart. We followed the setup documented [here](https://linkerd.io/2/tasks/automatically-rotating-webhook-tls-credentials/) in order to automatically rotate our webhook TLS credentials with cert manager. These certificates are being rotated correctly and the associated TLS secrets updated.

The issue is that after the TLS secrets are rotated by cert-manager, the `tap` and `proxy-injector` pods start producing the following error:
```
http: TLS handshake error from 127.0.0.1:52008: remote error: tls: bad certificate
```
These pods have to be manually restarted at which point they pick up the secrets correctly and are fine until the next certificate refresh.

We are using ArgoCD to manage deployments and Cert manager is version `0.15.1`.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2020-11-23T20:07:30Z
    see https://linkerd.io/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2020-11-24T02:25:03Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints
√ proxy-injector webhook has valid cert
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2020-11-24T02:25:03Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints
√ sp-validator webhook has valid cert
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2020-11-24T02:25:03Z
    see https://linkerd.io/checks/#l5d-webhook-cert-not-expiring-soon for hints

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √
```

### Environment

- Kubernetes Version: 1.16
- Cluster Environment: EKS
- Host OS: Amazon Linux
- Linkerd version: 2.9.0

**Comment by alpeb** [comment]
Thanks for the report @r8474 . You're right, those components aren't detecting when the secrets get updated with the new cert.
I'd like to confirm something though, before looking into this: In the case of the proxy-injector for example, you have to set `proxyInjector.caBundle`, which is a cert root that won't change during cert rotation, thus you should have cert-manager configured to generate certs that can be verified with that bundle. Does that match your setup?

**Comment by r8474** [comment]
Thanks for taking a look @alpeb ! I can confirm that we do have the external secrets for the three webhook related components configured:
```
        proxyInjector:
          externalSecret: true
          caBundle: |-
            -----BEGIN CERTIFICATE-----
            <CERTIFICATE>
            -----END CERTIFICATE-----

        profileValidator:
          externalSecret: true
          caBundle: |-
            -----BEGIN CERTIFICATE-----
            <CERTIFICATE>
            -----END CERTIFICATE-----

        tap:
          externalSecret: true
          caBundle: |-
            -----BEGIN CERTIFICATE-----
            <CERTIFICATE>
            -----END CERTIFICATE-----
```
Obviously, <CERTIFICATE> above contains the actual certificate data for the CA. As stated in the OP, the CA data was generated by following [the guide](https://linkerd.io/2/tasks/automatically-rotating-webhook-tls-credentials/). We have an issuer set up:
```
apiVersion: cert-manager.io/v1alpha3
kind: Issuer
metadata:
  name: webhook-issuer
  namespace: linkerd
spec:
  ca:
    secretName: webhook-issuer-tls
```
And certificates:
```
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 24h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  keyAlgorithm: ecdsa
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: linkerd-sp-validator
  namespace: linkerd
spec:
  secretName: linkerd-sp-validator-k8s-tls
  duration: 24h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-sp-validator.linkerd.svc
  keyAlgorithm: ecdsa
  usages:
  - server auth
---
apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: linkerd-tap
  namespace: linkerd
spec:
  secretName: linkerd-tap-k8s-tls
  duration: 24h0m0s
  renewBefore: 1h0m0s
  issuerRef:
    name: webhook-issuer
    kind: Issuer
  commonName: linkerd-tap.linkerd.svc
  keyAlgorithm: ecdsa
  usages:
  - server auth
```
Correct me if I'm wrong but I gathered from your comment that the three webhook components will not retrieve a new certificate when the secret is updated in which case I assume they will need to restart to pick it up. If so, which component is watching that secret and then triggering pod restarts (or are the webhook pods themselves watching it and then terminating if it updates)?
