### ISSUE TITLE
injector: `linkerd.io/proxy-version` is incorrect

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#5338]
When overriding a proxy version via annotation, the injector sets an incorrect `linkerd.io/proxy-version` annotation:

```
metadata:
  annotations:
    config.linkerd.io/proxy-image: ghcr.io/olix0r/l2-proxy
    config.linkerd.io/proxy-version: detect.e7d061ef
    linkerd.io/created-by: linkerd/proxy-injector stable-2.9.0
    linkerd.io/identity-mode: default
    linkerd.io/inject: enabled
    linkerd.io/proxy-version: stable-2.9.0
    ort.olix0r.net/concurrency-limit: "20"
    ort.olix0r.net/request-limit: "5000"
    ort.olix0r.net/threads: "5"
...
    image: ghcr.io/olix0r/l2-proxy:detect.e7d061ef
```

To fix this, we can do one or more of the following:

* Change the annotation to be `linkerd.io/injector-version`, which will make it correct.
* Change the annotation's value to match the override.
* Omit the annotation.
