### ISSUE TITLE
Create prom scrape rule for the extension components

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#5429]
The existing `linkerd-controller` rule fails to generate proper metrics for the viz components, resulting in empty charts in charts like Linkerd Health.

A new rule should be created to capture the metrics for the viz components:
```
- job_name: 'linkerd-extensions'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['linkerd-viz']
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_linkerd_io_extension
        - __meta_kubernetes_pod_label_component
        - __meta_kubernetes_pod_container_port_name
        action: keep
        regex: (.*);(.*);admin-http$
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: component
```

The Linkerd Health chart should be have a section added targetting this new job.
