### ISSUE TITLE
viz: support `--registry` flag

### ISSUE THREAD

**Issue by Pothulapati** [linkerd/linkerd2#5430]
## Feature Request

Support a registry flag to override the registry of all images present in the viz extension. This is useful with private registries.

The core install already has a relevant flag, where that logic is done through the CLI and hence Go, But with Viz, It's important that this logic happens through Helm, so that this field is supported both through Helm and CLI.

**Comment by jimil749** [comment]
Hey @Pothulapati! Can you explain a bit more about how this has to implemented via helm. Because with the `linkerd install` command, we are implementing the `registry` flag in `registryOverride` in `root.go`, so do we also want to do something similar for the `viz install`? I am confused as in how exactly do we want to achieve this via helm?

**Comment by alpeb** [comment]
Hi @jimil749 :wave: 
If you check the output of `linkerd viz install -h` you'll see there are no flags (except for `--skip-checks`) besides the same ones `helm install` exposes to change config (`--set-*` and `--values`). 
I think we should leave the addition of a flag like `--registry` to `linkerd viz install` for later (if at all), and first add support for custom registries in the helm charts. So currently we have this:
https://github.com/linkerd/linkerd2/blob/8d50631727c3c4e4536a2c55f98965007303e023/viz/charts/linkerd-viz/values.yaml#L98-L107
We should split `name` so we end up with something like this:
```yaml
dashboard:
  # -- Number of replicas of dashboard
  replicas: 1
  # -- log level of the dashboard component
  logLevel: *log_level
  image:
    # -- Docker registry for the web instance
    registry: ghcr.io/linkerd
    # -- Docker image name for the web instance
    name: web
    # -- Docker image tag for the web instance
    tag: *linkerd_version
```
And reflecting this in the `tap` template so we end up with:
```yaml
        image: {{.Values.tap. image.registry}}.{{.Values.tap.image.name}}:{{ default (default .Values.linkerdVersion .Values.controllerImageVersion) .Values.tap.image.tag}}
```
And so on with all the `values.yaml` and template files. This would not require go code changes, and would be configurable in the CLI via the `--set-*` flags.
