### ISSUE TITLE
Avoid multi-cluster LoadBalancer Service requirement

### ISSUE THREAD

**Issue by erwbgy** [linkerd/linkerd2#5462]
### What problem are you trying to solve?

LoadBalancer type Services may not be supported or allowed in some Kubernetes clusters - for example due to:
* Being on-prem or in a lab with no "load-balancer as a service" capability
* Security concerns around exposing Services externally
* Policy that requires all incoming traffic to go via ingress proxies

Not all clusters support LoadBalancer Services but all should support ExternalName.  I have clusters where I can't use Linkerd multi-cluster because of the LoadBalancer requirement.

### How should the problem be solved?

Support the use of ExternalName Service objects as suggested in #4590.

Linkerd multicluster already supports LoadBalancer Services where the gateway address is a hostname (#4588):

> When a target cluster gateway is exposed as a hostname rather than with a fixed IP address, the service mirror controller fails to create mirror services and gateway mirrors for that gateway. This is because we only look at the IP field of the gateway service.
> 
> We make two changes to address this problem:
> 
> First, when extracting the gateway spec from a gateway that has a hostname instead of an IP address, we do a DNS lookup to resolve that hostname into an IP address to use in the mirror service endpoints and gateway mirror endpoints.
> 
> Second, we schedule a repair job on a regular (1 minute) to update these endpoint objects. This has the effect of re-resolving the DNS names every minute to pick up any changes in DNS resolution.

Using ExternalName Services can be supported in a similar way: if the Service is of type ExternalName then get the hostname from the spec.externalName field rather than the status.loadBalancer.ingress[0].hostname field.

It looks like this should be a simple change around https://github.com/linkerd/linkerd2/blob/main/multicluster/cmd/link.go#L163 and updating some tests?

### Any alternatives you've considered?

Implementing a cluster controller manager to make LoadBalancer Services work is an option where there is no external load balancer service but is a significant effort to solve this simple use case.  The security and policy issues are not easy to work around so there would likely need to be some other way to set the gateway IP, perhaps by writing a custom controller.

### How would users interact with this feature?

https://github.com/linkerd/linkerd2/issues/4590#issue-637617178

**Comment by adleong** [comment]
Hi @erwbgy, is this problem already addressed by https://github.com/linkerd/linkerd2/pull/5307 ?

**Comment by erwbgy** [comment]
The #5307 change allows the gateway address to be specified manually which will suit some use cases, but it does mean that the information may need to be duplicated from the Service object.  For example if I have an ExternalName Service then I'd need to copy the value from the .Spec.ExternalName field and pass it as a gateway-addresses parameter.  While this is not a big deal I can imagine future issues when the value is only changed in one of the two places.  Treating all types of Services the same will also likely make documentation of setups that don't use LoadBalancer Services easier.

**Comment by adleong** [comment]
Thanks for clarifying @erwbgy.  My concern is that the ExternalIP field is intended for a slightly different purpose: it specifies all the different IP addresses for which this service can receive traffic which is sort of the reverse of what we want.  Just because a service can receive traffic for an ip address doesn't mean that ip address is what this specific client should use to contact that service.  

That's why it's my preference to let the client be explicit and directly specify the gateway address to use.

**Comment by erwbgy** [comment]
@adleong We don't have any specific use-case for ExternalIP. I was trying to address #5460 as well but as you commented there the gateway-addresses parameter will meet that need once it is re-added.  I'll remove ExternalIP and just leave ExternalName.

**Comment by adleong** [comment]
I think `ExternalName` is something else altogether.  I believe that externalName is a DNS name that the service will route TO, not an address by which the service is addressable.  See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#servicespec-v1-core

**Comment by erwbgy** [comment]
That says:

> externalName is the external reference that discovery mechanisms will return as an alias for this service (e.g. a DNS CNAME record)

so it doesn't have to be outbound only.

However with this change I see that `linkerd multicluster` just creates a Link object so it is easier to just create that directly and set the gatewayAddress field:
```
apiVersion: multicluster.linkerd.io/v1alpha1
kind: Link
metadata:
  name: east
  namespace: linkerd-multicluster
spec:
  clusterCredentialsSecret: cluster-credentials-east
  gatewayAddress: linkerd-gateway.east.mydomain.com
  gatewayIdentity: linkerd-gateway.linkerd-multicluster.serviceaccount.identity.linkerd.cluster.local
  gatewayPort: "4143"
  probeSpec:
    path: /health
    period: 3s
    port: "4181"
  selector:
    matchExpressions:
    - key: mirror.linkerd.io/exported
      operator: Exists
  targetClusterDomain: cluster.local
  targetClusterLinkerdNamespace: linkerd
  targetClusterName: east
```
which is presumably what the --gateway-addresses option will do when re-added so closing this in favour of https://github.com/linkerd/linkerd2/issues/5471.
