### ISSUE TITLE
Linkerd-viz Helm Chart Invalid PodAffinity

### ISSUE THREAD

**Issue by tustvold** [linkerd/linkerd2#5511]
### What is the issue?

The linkerd-viz helm chart included in edge-21.1.1 references `.Values.controllerComponentLabel` that is not set by the chart

### How can it be reproduced?

```
helm template linkerd-edge/linkerd-viz --set enablePodAntiAffinity=true
```

Produces an invalid affinity spec

```
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: 
            operator: In
            values:
            - tap
        topologyKey: failure-domain.beta.kubernetes.io/zone
```

### Environment

- Kubernetes Version: N/A
- Cluster Environment: N/A
- Host OS: N/A
- Linkerd version: edge-21.1.1

### Workaround

This can be worked around by setting controllerComponentLabel to "component"

### Possible solution

Change

```
{{- $local := dict "component" "tap" "label" .Values.controllerComponentLabel -}}
{{- include "linkerd.pod-affinity" $local | nindent 6 -}}
{{- end }}
```
to
```
{{- $local := dict "component" "tap" "label" "component" -}}
{{- include "linkerd.pod-affinity" $local | nindent 6 -}}
{{- end }}
```

**Comment by klingerf** [comment]
I've run into this issue too, with edge-21.1.1. Applying the output of `linkerd viz install --ha` to my cluster produces the following error:

```
error: error validating "STDIN": error validating data: [ValidationError(Deployment.spec.template.spec.affinity.podAntiAffinity.preferredDuringSchedulingIgnoredDuringExecution[0].podAffinityTerm.labelSelector.matchExpressions[0]): missing required field "key" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement, ValidationError(Deployment.spec.template.spec.affinity.podAntiAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].labelSelector.matchExpressions[0]): missing required field "key" in io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelectorRequirement]; if you choose to ignore these errors, turn validation off with --validate=false
```

The tap deployment includes a `podAntiAffinity` config, and this `podAffinityTerm` is invalid because it's missing a `key` value:

```yaml
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: 
                  operator: In
                  values:
                  - tap
              topologyKey: failure-domain.beta.kubernetes.io/zone
```
