### ISSUE TITLE
Install with --ha option

### ISSUE THREAD

**Issue by kfirfer** [linkerd/linkerd2#5529]
Hello
When installing with --ha argument, the `prometheus.enabled:false` and the controller log level configuration are ignored

this is the command:
```
linkerd upgrade --ha --controller-log-level=warn --proxy-cpu-request=0.01 --proxy-cpu-limit=2 --proxy-memory-request=10Mi --proxy-memory-limit=2Gi --config=linkerd/config.yaml | kubectl apply -f -

```

This is the config.yaml:

```
global:
  prometheusUrl: http://thanos-query.monitoring.svc.cluster.local:9090
  prometheus:
    enabled: false

prometheus:
  enabled: false
```

Linkerd version: 2.9.1 stable
