### ISSUE TITLE
How to use Linkerd2 with Ingress Nginx as TCP routing in order to externally connect to MongoDB instances

### ISSUE THREAD

**Issue by percenuage** [linkerd/linkerd2#5637]
### What is the issue?
Hello, I would like to externally connect to my MongoDB instance (https://github.com/bitnami/charts/tree/master/bitnami/mongodb) deployed in GKE cluster. It's a standalone architecture with no SSL by now.

Architecture:

```text
[ CLIENT ] --(27017/TCP)--> [ INGRESS ] --(27017/TCP)--> [ SERVICE ] --(27017/TCP)--> [ MONGODB_POD ]
```

I'm using Ingress Nginx to handle domain routing. 

As Ingress do not support TCP/UDP routing, I can't connect to my Mongodb using 2017 port like `mongo "mongodb://mongo.yolo.org:27017/admin"` --> `Socket operation timed out`.

So I read [here](https://linkerd.io/2/features/protocol-detection/) that linkerd could to the job (maybe I'm wrong or do thing in the wrong way), so I installed it following this [doc](https://linkerd.io/2/getting-started/).
After that, I configured Ingress / Linkerd following [Ingress Traffic](https://linkerd.io/2/tasks/using-ingress/) as a **Proxy Ingress Mode** (with `linkerd.io/inject: ingress` annotation in my global `ingress-nginx-controller`).

The result is the same --> `Socket operation timed out`.

However, I found this doc on Ingress (https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/) to expose single TCP port. With this, I can connect to my mongo instance with this configmap:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  27017: "foo/yolo-db:27017"
```

But my final requirement is to deploy many MongoDB instances in replicaset for each client I have with a custom domain like `mongo.<client>.yolo.org`. I don't want to manage different mongo port for each client.

Thanks for your help 😄 (If you have other solutions, I would be happy to read it!).

This issue seems to be related to #4211.

### How can it be reproduced?

1. Install Nginx Ingress (chart version **ingress-nginx-3.13.0** / app version **0.41.2**)
2. Install bitnami/mongodb@10.5.1 chart using these values:

```yaml
fullnameOverride: yolo-db

image:
  tag: 4.2.11-debian-10-r57

architecture: standalone

auth:
  enabled: false

arbiter:
  enabled: false

persistence:
  size: 2Gi

serviceAccount:
  create: false

rbac:
  create: false

metrics:
  enabled: false

pdb:
  create: false

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 512Mi

```

3. Apply this Ingress extension for MongoDB service:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.global-static-ip-name: yolo-dev-ip
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
  name: yolo-db
spec:
  rules:
    - host: mongo.yolo.org
      http:
        paths:
          - path: /
            backend:
              serviceName: yolo-db
              servicePort: 27017
#---
#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    meta.helm.sh/release-name: yolo-db
#    meta.helm.sh/release-namespace: foo
#  labels:
#    app.kubernetes.io/component: mongodb
#    app.kubernetes.io/instance: yolo-db
#    app.kubernetes.io/managed-by: Helm
#    app.kubernetes.io/name: mongodb
#    helm.sh/chart: mongodb-10.5.1
#  name: yolo-db
#  namespace: foo
#spec:
#  clusterIP: 10.19.244.74
#  ports:
#    - name: mongodb
#      port: 27017
#      protocol: TCP
#      targetPort: mongodb
#  selector:
#    app.kubernetes.io/component: mongodb
#    app.kubernetes.io/instance: yolo-db
#    app.kubernetes.io/name: mongodb
#  type: ClusterIP

```

### Logs, error output, etc

```bash
$ mongo "mongodb://root:pass@mongo.yolo.org:27017/admin"
MongoDB shell version v4.2.7
connecting to: mongodb://mongo.yolo.org:27017/admin?compressors=disabled&gssapiServiceName=mongodb
2021-01-30T13:27:01.605+0100 E  QUERY    [js] Error: couldn't connect to server mongo.yolo.org:27017, connection attempt failed: NetworkTimeout: Error connecting to mongo.yolo.org:27017 (35.241.209.96:27017) :: caused by :: Socket operation timed out :
connect@src/mongo/shell/mongo.js:341:17
@(connect):2:6
2021-01-30T13:27:01.612+0100 F  -        [main] exception: connect failed
2021-01-30T13:27:01.612+0100 E  -        [main] exiting with code 1
```

#### `linkerd check` output

```bash
$ linkerd check
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running
√ can initialize the client
√ can query the control plane API

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ control plane self-check
√ [kubernetes] control plane can talk to Kubernetes
√ [prometheus] control plane can talk to Prometheus
√ tap api service is running

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-prometheus
------------------
√ prometheus add-on service account exists
√ prometheus add-on config map exists
√ prometheus pod is running

linkerd-grafana
---------------
√ grafana add-on service account exists
√ grafana add-on config map exists
√ grafana pod is running

Status check results are √

```

### Environment

- Kubernetes Version: v1.17.14-gke.1600
- Cluster Environment: GKE
- Host OS: Container-optimized OS with containerd (cos_containerd)
- Linkerd version: stable-2.9.2

### Additional context

- GKE cluster with private node on production
- Distributed architecture with 1 Mongodb replicaset instance
- 1 namespace by client with same architecture for each (so for 4 clients, I have 4 independents Mongodb instances)
