### ISSUE TITLE
Keycloak container is not getting ready when injecting linkerd proxy

### ISSUE THREAD

**Issue by pachalk** [linkerd/linkerd2#5749]
My issue is quite similar to this https://github.com/linkerd/linkerd2/issues/3936
Tried to skip port of keycloak 7600 still not working when i inject linkerd for keycloak auth container is running and immediately going to terminating status. But linkerd-proxy container is running inside the pod.

We have init containers which checks for postgres db ready or not then we have keycloak container
Linkerd-proxy container logs
```
time="2021-02-15T16:22:17Z" level=info msg="running version stable-2.9.2"
[     0.000951s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.001770s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.001826s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.001833s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.001837s]  INFO ThreadId(01) linkerd2_proxy: Tap interface on 0.0.0.0:4190
[     0.001840s]  INFO ThreadId(01) linkerd2_proxy: Local identity is default.new.serviceaccount.identity.linkerd.cluster.local
[     0.001849s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.001855s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.002162s]  INFO ThreadId(01) outbound: linkerd2_app: listen.addr=127.0.0.1:4140 ingress_mode=false
[     0.002235s]  INFO ThreadId(01) inbound: linkerd2_app: listen.addr=0.0.0.0:4143
[     0.329291s]  WARN ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=ip:40836 target.addr=podip:4191}: rustls::session: Sending fatal alert AccessDenied    
[     0.329481s]  INFO ThreadId(02) daemon:admin{listen.addr=0.0.0.0:4191}:accept{peer.addr=ip:40836 target.addr=podip:4191}: linkerd2_app_core::serve: Connection closed error=unexpected error: no server certificate chain resolved
[     0.543760s]  INFO ThreadId(02) daemon:identity: linkerd2_app: Certified identity: default.new.serviceaccount.identity.linkerd.cluster.local
[   332.166074s]  WARN ThreadId(01) inbound:accept{peer.addr=ip:60710 target.addr=podip:9990}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111)
[   662.166313s]  WARN ThreadId(01) inbound:accept{peer.addr=ip:36420 target.addr=podip:9990}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111)
[   992.166169s]  WARN ThreadId(01) inbound:accept{peer.addr=ip:40328 target.addr=podip:9990}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111)
[  1322.166103s]  WARN ThreadId(01) inbound:accept{peer.addr=ip:44232 target.addr=podip:9990}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111)
[  1652.166186s]  WARN ThreadId(01) inbound:accept{peer.addr=ip:48138 target.addr=podip:9990}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111)
[  1982.166321s]  WARN ThreadId(01) inbound:accept{peer.addr=ip:52064 target.addr=podip:9990}: linkerd2_app_core::errors: Failed to proxy request: error trying to connect: Connection refused (os error 111)
```

Environment - EKS 
Kubernetes version - 1.17 
Linkerd version - 2.9.2 installed using CLI

I tried with this

```
  keycloak:
    podAnnotations:
      config.linkerd.io/skip-inbound-ports: "7600" # skip keycloak cluster discovery
      config.linkerd.io/skip-outbound-ports: "7600"
```

even with my database port postgress too still not working 

Please help me what should i do in this scenario. Thank you in advance

**Comment by pachalk** [comment]
I am getting no_tls_from_remote the src ip is nodeip and dst is podip. I injected linkerd only on application pods not for kube-system is it normal getting this or what we should do if need secure communication from node to pod. Any suggestions would be appreciative..

req id=1:1 proxy=in  src=172.31.26.8:55996 dst=172.31.31.8:3000 tls=no_tls_from_remote :method=GET :authority=172.31.31.8:3000 :path=/
rsp id=1:1 proxy=in  src=172.31.26.8:55996 dst=172.31.31.8:3000 tls=no_tls_from_remote :status=200 latency=298µs
end id=1:1 proxy=in  src=172.31.26.8:55996 dst=172.31.31.8:3000 tls=no_tls_from_remote duration=30µs response-length=1899B

**Comment by samstride** [comment]
@pachalk , I am running:

- keycloak-x-12.0.3 (https://www.keycloak.org/2020/12/first-keycloak-x-release.adoc.html)
- with Postgres 12.6 as DB vendor
- on Rancher v1.18.5

and I have no issues injecting linkerd.

Example deployment yaml with a [modified image](https://hub.docker.com/repository/docker/ownage/keycloak-x-postgres) for purpose of demonstration below:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: ownage/keycloak-x-postgres:12.0.3
          imagePullPolicy: IfNotPresent
          args: [
              --show-config
              --verbose
              --http-enabled=true,
            ]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_DB_URL
              value: "jdbc:postgresql://<DB_HOST>/keycloak"
            - name: KC_DB_USERNAME
              value: "keycloak"
            - name: KC_DB_PASSWORD
              value: "keycloak"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
```
