### ISSUE TITLE
failed to load [extension-apiserver-authentication] config: configmaps \"extension-apiserver-authentication\" is forbidden

### ISSUE THREAD

**Issue by gr8Adakron** [linkerd/linkerd2#5806]
Getting the following error while executing `linkerd install > file.yaml` via kustomize structure.

The cluster created by Kubernetes is through ArgoCD app - which is very small configuration of clusterIP with whitelist/blacklisting kinds.

All the Services/Deployment getting created except `linkerd-tap`. and related, hence getting following error on GCP kubernetes:

**> Fatal msg="failed to load [extension-apiserver-authentication] config: configmaps \"extension-apiserver-authentication\" is forbidden: User \"system:serviceaccount:linkerd:linkerd-tap\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"kube-system\"**

**Comment by gr8Adakron** [comment]
@wmorgan any help will be appreciated.

**Comment by gr8Adakron** [comment]
Anyway got resolve by proving a separate ClusterRoleBinding(RBAC) for **argo-cd** user which is responsible for maintaining the GKE cluster, configuration in below snippet:


```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-manager-tap-admin
  labels:
    linkerd.io/control-plane-component: tap
    linkerd.io/control-plane-ns: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: linkerd-linkerd-tap-admin
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: kube-system

```
