### ISSUE TITLE
Linkerd proxy injector webhook requests fail after the certificate expires and it doesn't pick up new certificates generated by cert manager.

### ISSUE THREAD

**Issue by sagargulabani** [linkerd/linkerd2#5888]
### What is the issue?

I am trying to follow this [article](https://linkerd.io/2/tasks/automatically-rotating-webhook-tls-credentials/) and trying to rotate the webhook TLS credentials for the proxy injector using cert manager.
Cert manager rotates the certificates after a period of 5 hours before the old certificate expires for example's sake, lets say at time (x-5).
The proxy injector is still using the old certificate.
When we reach the time x, what I expect to happen is that linkerd should restart the proxy injector pod so it comes up with the new certificate.
However the linkerd pod keeps on running with the old certificate and all webhook requests to the proxy injector fail becaue of which no new pods can be scheduled on the cluster.
 
We are using Helm chart for linkerd to deploy linkerd on our cluster.

The certificate is generated using this.
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-proxy-injector
  namespace: linkerd
spec:
  secretName: linkerd-proxy-injector-k8s-tls
  duration: 24h
  renewBefore: 5h
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  commonName: linkerd-proxy-injector.linkerd.svc
  dnsNames:
  - linkerd-proxy-injector.linkerd.svc
  isCA: false
  privateKey:
    algorithm: ECDSA
  usages:
  - server auth
  ```

In the helm chart, we set the following to true
```
    proxyInjector:
      externalSecret: true
```
and we set `proxyInjector.caBundle` to the tls.crt from the secret generated because of the above certificate.

### How can it be reproduced?

This issue can be reproduced by waiting for the certificate picked up by the linkerd proxy injector to expire and trying to schedule a pod after that.

### Logs, error output, etc

The logs show something like `remote error: tls: bad certificate `

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

N/A

```text
your output here ...
```

### Environment

- Kubernetes Version:
- Cluster Environment: EKS
- Host OS: 
- Linkerd version: 2.9.2

### Possible solution

Restart the pod after the certificate expires.
