### ISSUE TITLE
Dashboard : Websocket error on a tap

### ISSUE THREAD

**Issue by vikas027** [linkerd/linkerd2#5897]
## Bug Report
Websocket error while doing a _tap_

### What is the issue?
When I start a `tap`, there is an error at the bottom of left
```text
An error has occurred.
Websocket error: undefined
```

### How can it be reproduced?
Ambassador Service Annotations (which creates an ELB with a TCP passthrough)
```yaml
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
```

Ambassador Mappings
```yaml
# Default Mappings
---
apiVersion: getambassador.io/v2
kind: Module
metadata:
  namespace: ambassador
  name: ambassador
spec:
  config:
    add_linkerd_headers: true
    use_proxy_proto: true

# on Linkerd Web Service
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: getambassador.io/v2
      kind: Mapping
      name: linkerd-web-mapping
      host: linkerd.<redacted>
      prefix: /
      host_rewrite: web.linkerd-viz.svc.cluster.local:8084
      service: web.linkerd-viz.svc.cluster.local:8084
      use_websocket: true
      timeout_ms: 60000
```

### Logs, error output, etc
Ambassador Pod Logs has a `403` error code
```bash
ambassador-7dd598fbd8-mz98t ambassador ACCESS [2021-03-14T06:53:36.523Z] "GET /api/tap HTTP/1.1" 403 - 0 83 10 - "X.X.X.X" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0" "63aca025-b56c-4271-ac8c-60af2063f752" "web.linkerd-viz.svc.cluster.local:8084" "X.X.X.X":8084"
```

![2021-03-14_17-11-43](https://user-images.githubusercontent.com/6998650/111059592-ea1e4c80-84ea-11eb-96c2-38e0af897110.png)

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
❯ linkerd check                
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-jaeger
--------------
√ linkerd-jaeger extension Namespace exists
√ collector and jaeger service account exists
√ collector config map exists
√ jaeger extension pods are injected
√ jaeger extension pods are running

Status check results are √

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check

Status check results are √
```

### Environment

- Kubernetes Version: v1.19.8
- Cluster Environment: EKS
- Host OS: Bottlerocket
- Linkerd version: v2.10.0

### Similar Tickets
- https://github.com/linkerd/linkerd2/issues/2899
- https://github.com/pomerium/pomerium/issues/430

**Comment by adleong** [comment]
I spent a little bit of time and wasn't able to reproduce this.  However, I have not yet tried with the dashboard exposed through ambassador.

**Comment by Pothulapati** [comment]
Hey @vikas027, I was not able to replicate this, especially because of the comples setup i.e ambassador and EKS.

Can you provide us more logs i.e web's and tap's. Both the component and proxy logs would be useful. 🤔

**Comment by vikas027** [comment]
Hello @Pothulapati and @adleong,

Thanks for looking into this. I am seeing the same behaviour in a GKE cluster too with Linkerd versions 2.8 and 2.9 too.
It is quite likely something is not configured correctly in my Ambassador configure for Linkerd, rest everything is working fine on Ambassador.

Here are some logs. Please let me know should you need any more logs.

Firefox developers tool (`403` error)
![2021-03-20_13-01-45](https://user-images.githubusercontent.com/6998650/111856849-a6f82980-8981-11eb-86c9-fe1a949d5211.png)
Not sure if this helps but here is a curl representation copied from Firefox.
```
curl 'wss://linkerd.mydomain.net/api/tap' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Sec-WebSocket-Version: 13' -H 'Origin: https://linkerd.mydomain.net' -H 'Sec-WebSocket-Extensions: permessage-deflate' -H 'Sec-WebSocket-Key: 9MsDilbH3prI+Y6BuNEDAA==' -H 'Connection: keep-alive, Upgrade' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade: websocket'
```

This command did not generate any error on tap pod `tap-688b97646d-7zhsk` (which has `tap-688b97646d-7zhsk` and `linkerd-proxy` containers)
```
❯ stern -l component=tap -n linkerd-viz
```

Ambassador pod logs
```
❯ k get po              
NAME                                READY   STATUS    RESTARTS   AGE
ambassador-7dd598fbd8-85kkp         2/2     Running   1          140m
ambassador-7dd598fbd8-nzbnd         2/2     Running   1          123m
ambassador-7dd598fbd8-v5zpx         2/2     Running   1          123m
ambassador-agent-5cfcb96484-w8qbt   2/2     Running   0          140m
ambassador-redis-64b7c668b9-bs2k5   2/2     Running   0          123m

❯ stern -l pod-template-hash=7dd598fbd8 -n ambassador
ambassador-7dd598fbd8-nzbnd ambassador ACCESS [2021-03-20T02:03:47.039Z] "GET /api/tps-reports?skip_stats=true&resource_type=namespace&all_namespaces=true&window=1m HTTP/1.1" 200 - 0 578 6 5 "119.18.0.112" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0" "265145d9-fc6f-438d-bb04-ec2db9a0014c" "web.linkerd-viz.svc.cluster.local:8084" "172.20.229.97:8084"
ambassador-7dd598fbd8-nzbnd ambassador ACCESS [2021-03-20T02:03:47.039Z] "GET /api/tps-reports?skip_stats=true&resource_type=all&all_namespaces=true&window=1m HTTP/1.1" 200 - 0 2666 14 14 "119.18.0.112" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0" "e2538483-e099-47ee-ab07-a6c1802ebed9" "web.linkerd-viz.svc.cluster.local:8084" "172.20.229.97:8084"
ambassador-7dd598fbd8-nzbnd ambassador ACCESS [2021-03-20T02:03:47.039Z] "GET /api/tps-reports?resource_type=authority&all_namespaces=true&window=1m HTTP/1.1" 200 - 0 552 83 83 "119.18.0.112" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0" "0f90ab9c-c69e-48df-a215-8cdab5101ab0" "web.linkerd-viz.svc.cluster.local:8084" "172.20.229.97:8084"
ambassador-7dd598fbd8-v5zpx ambassador ACCESS [2021-03-20T02:03:52.214Z] "GET /api/tap HTTP/1.1" 403 - 0 106 5 - "119.18.0.112" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko/20100101 Firefox/86.0" "3701ecfd-5476-40ad-8dc6-0e2d71a5a2db" "web.linkerd-viz.svc.cluster.local:8084" "172.20.229.97:8084"
```

**Comment by cakuros** [comment]
This is happening because the Web deployment is doing an Origin check on the upgrade request.  When you click the "start" button, you can see in the request headers it sends "Origin: linkerd.mydomain.net".  Because you're doing a `host_rewrite` in the `Mapping` to "web.linkerd-viz.svc.cluster.local", the Web deploy gets mad and says:

```
time="2021-05-04T18:28:45Z" level=error msg="websocket: request origin not allowed by Upgrader.CheckOrigin"
2021/05/04 18:28:45 http: superfluous response.WriteHeader call from go.opencensus.io/plugin/ochttp.(*trackingResponseWriter).WriteHeader (server.go:221)
```

This seems to just be a thing that golang websocket implementations do if the Origin header is present (https://github.com/golang/net/blob/bbd867fde50d/websocket/server.go#L99).  If the header is removed by Ambassador, then it stops complaining.

This is my final `Mapping` and `Deployment` yaml:

```yaml
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: linkerd-viz-dashboard
  namespace: linkerd-viz
spec:
  prefix: /
  host: viz.mydomain.net
  host_rewrite: web.linkerd-viz.svc
  service: web.linkerd-viz:8084
  remove_request_headers:
  - Origin
  allow_upgrade:
  - websocket
  timeout_ms: 60000
```
