### ISSUE TITLE
When rolling pods with multiple named ports, destination sometimes returns port 0

### ISSUE THREAD

**Issue by riccardofreixo** [linkerd/linkerd2#5912]
We have hit this issue in production a few times in recent weeks. The observable symptoms are:

1. The source `linkerd-proxy` resolves the destination port of one or more addresses to port 0.
2. The destination `linkerd-proxy` fails to connect locally to port 0, and receives an OS error 111.
3. If this is a HTTP connection, the destination `linkerd-proxy` handles that failure by responding with a HTTP responde with status code 502.
4. Eventually the problem resolves itself. We haven't investigated why, but we presume it's because the source `linkerd-proxy` eventually does a fresh lookup, at which point ports are stabilised and thus the Kube Endpoints API returns a single subset, avoiding the bug.

# Why it happens

When pods are rolling, if all pods are not ready for exactly the same ports, the Kube Endpoints API will return multiple subnets with the same address repeated across them, each subset covering a different set of ports, which results in the same address being repeated across subsets. Here is an example:

```yaml
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: name1
  name: name1
  namespace: ns
subsets:
- addresses:
  - ip: 172.17.0.1
    nodeName: name1-1
    targetRef:
      kind: Pod
      name: name1-1
      namespace: ns
  - ip: 172.17.0.2
    nodeName: name1-2
    targetRef:
      kind: Pod
      name: name1-2
      namespace: ns
  ports:
  - name: port1
    port: 8989
    protocol: TCP
- addresses:
  - ip: 172.17.0.1
    nodeName: name1-1
    targetRef:
      kind: Pod
      name: name1-1
      namespace: ns
  notReadyAddresses:
  - ip: 172.17.0.2
    nodeName: name1-2
    targetRef:
      kind: Pod
      name: name1-2
      namespace: ns
  ports:
  - name: port2
    port: 9999
    protocol: TCP
```

The existing code for `endpointsToAddresses` loops through all subsets, and the later occurrences of an address overwrites previous ones, with the last one prevailing.

If the last one happened to be for an irrelevant port, and the port is named, `resolveTargetPort` fails to resolve the port and thus resolves it to port 0. This then overwrites the address with port 0, returning port 0 to clients, ultimately leading `linkerd-proxy` to forward connections to port 0.

In the example above, since `172.17.0.1` is ready for both ports `8989` and `9999`, the current code will write the correct address to `addresses` in the first pass of the loop through subsets, but then in the second pass it will overwrite it with port 0.

Since `172.17.0.2` is under `notReadyAddresses` for port `9999`, it doesn't suffer the same fate and doesn't get overwritten.

The result is that in practice you get seemingly random pods receiving traffic to port 0, while other pods receive traffic normally, depending on how the race condition manifested itself.

# Workaround

For the existing code, the best workaround we could come up with is to replace named ports with integer ports, which skirts around the bug altogether.

# PR

Have raised a PR with a potential fix and new test case: https://github.com/linkerd/linkerd2/pull/5911
