### ISSUE TITLE
Service Profile not getting implemented

### ISSUE THREAD

**Issue by gr8Adakron** [linkerd/linkerd2#6065]
### What is the issue?

Applying service profile but not showing on the dashboard

### How can it be reproduced?

Client version: stable-2.10.1
Server version: stable-2.10.1

Install `linkerd` and `linkerd-viz`

Inserted a sample ServiceProfile:

```
### ServiceProfile for a-service ###
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  name: a-service.a-namespace.svc.cluster.local
  namespace: a-namespace
spec:
  # A service profile defines a list of routes.  Linkerd can aggregate metrics
  # like request volume, latency, and success rate by route.
  routes:
  - name: /ambassador/v0/check
    condition:
      method: GET
      pathRegex: /ambassador/v0/check.*
```

### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check`  and `linkerd viz check`output

```text
Status check results are √
```

### Environment

- Kubernetes Version: Server Version: v1.17.17-gke.3000
- Cluster Environment: (GKE)
- Host OS: Linux
- Linkerd version: 2.10.1

### Possible solution
Nothing related to permission as far as I have researched.
