### ISSUE TITLE
Provide trust anchors via secret

### ISSUE THREAD

**Issue by Sadzeih** [linkerd/linkerd2#6108]
### What problem are you trying to solve?
Hello!
I'm trying to automate deployment of Linkerd in multiple clusters linked together.

Right now I deploy linkerd with the cluster with the terraform helm provider and use the google provider to get the trust anchor from the Secret Manager.

This works but is not great since we are starting to use ArgoCD to deploy in Kubernetes, so I want to move the deployment of linkerd from the terraform module entirely. I would love to be able to deploy the helm chart without putting the certificate in the values file (since it is not very secure). I would prefer to use a secret. That would also allow me to rotate the certificate more easily.

### How should the problem be solved?

Right now in the helm chart the trust anchors are given with an environment variable:

```yaml
- name: LINKERD2_IDENTITY_TRUST_ANCHORS
  value: "{{b64enc .Values.identityTrustAnchorsPEM}}"
```

If we used a secret this would be:
```yaml
- name: LINKERD2_IDENTITY_TRUST_ANCHORS
  valueFrom:
    secretKeyRef:
      name: {{ .Values.identityTrustAnchorsSecret }}
      key: ca.crt
```

This could be templated in a way to not break the current way of doing it like this:
```yaml
{{- if .Values.identityTrustAnchorsSecret }}
- name: LINKERD2_IDENTITY_TRUST_ANCHORS
  valueFrom:
    secretKeyRef:
      name: {{ .Values.identityTrustAnchorsSecret }}
      key: ca.crt
{{- else }}
- name: LINKERD2_IDENTITY_TRUST_ANCHORS
  value: "{{b64enc .Values.identityTrustAnchorsPEM}}"
{{- end }}
```

This way, I can use a Sealed Secret or a secret operator (like aws-secret-operator).
