### ISSUE TITLE
Missing PSP in extensions

### ISSUE THREAD

**Issue by alpeb** [linkerd/linkerd2#6122]
### What is the issue?

viz' [psp.yaml](https://github.com/linkerd/linkerd2/blob/main/viz/charts/linkerd-viz/templates/psp.yaml) makes reference to a `psp` Role in the `linkerd-viz` namespace that doesn't exist. Also the `metrics-api` and `tap-injector` ServiceAccounts are not included in that RoleBinding. 

Also the mc and jaeger extensions don't have any Roles+RoleBindings attaching to the `linkerd-linkerd-control-plane` PSP.

As a result these extensions can't start in a PSP-enabled cluster.

### How can it be reproduced?

- Create a PSP-enabled cluster: `k3d cluster create --k3s-server-arg=--kube-apiserver-arg=enable-admission-plugins=PodSecurityPolicy,NodeRestriction`
- Setup the `kube-system` PSP:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  volumes:
  - '*'
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: r-privileged
  namespace: kube-system
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-privileged
  namespace: kube-system
roleRef:
  kind: Role
  name: r-privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
```
- Install `linkerd`. It should work
- Install `linkerd viz`. None of the pods should come up:
```
$ k -n linkerd-viz describe rs metrics-api-859c96f78f
...
Events:
  Type     Reason        Age                From                   Message
  ----     ------        ----               ----                   -------
  Warning  FailedCreate  4s (x12 over 15s)  replicaset-controller  Error creating: pods "metrics-api-859c96f78f-" is forbidden: PodSecurityPolicy: unable to admit pod: []
```
### Environment

- Kubernetes Version: 1.19
- Cluster Environment: (GKE, AKS, kops, ...): k3d
- Host OS: Linux 
- Linkerd version: edge-21.4.5

### Possible solution

Create the missing Role/RoleBindings, add the missing SAs.

### Additional context

PSP will be deprecated on k8s 1.21, but worth fixing for now.
