### ISSUE TITLE
Cannot expose linkerd dashboard via ingress

### ISSUE THREAD

**Issue by BrentFathom5** [linkerd/linkerd2#6162]
I have a 3 node K3s cluster with Linkerd and NGINX Ingress Controller. I installed Linkerd with a default configuration:

```
linkerd install | kubectl apply -f -
```

Then to install the NGINX Ingress Controller I used helm with a default configuration as well:

```
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

helm install ingress-nginx ingress-nginx/ingress-nginx
```

I can access the Linkerd dashboard by calling `linkerd viz dashboard`, but I'd like to expose the dashboard with an Ingress definition. I modified the example yaml file from Linkerd's website located [here][1], so that I could use a prefix path. In the end, my yaml file looked like this:

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: web-ingress-auth
  namespace: linkerd-viz
data:
  auth: YWRtaW46JGFwcjEkbjdDdTZnSGwkRTQ3b2dmN0NPOE5SWWpFakJPa1dNLgoK
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: linkerd-viz
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/upstream-vhost: $service_name.$namespace.svc.cluster.local:8084
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Origin "";
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;      
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: web-ingress-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
spec:
  rules:
  - http:
      paths:
        - path: /linkerd
          pathType: Prefix
          backend:
            serviceName: web
            servicePort: 8084
```

For any of my other custom microservices, I can simply access them via the public IP address of my nginx ingress service. I can get this IP like this:

```
kubectl describe svc ingress-nginx-controller | grep "LoadBalancer Ingress" | awk '{ print $3 }'
```

When I try accessing the dashboard at http://EXPOSED_IP/linkerd, I am prompted to enter my username and password (both **admin** by default), but then I get a 404 not found error. 

Does anybody know what could be the issue? Thank you very much!

  [1]: https://linkerd.io/2.10/tasks/exposing-dashboard/#nginx

### Environment

- Kubernetes Version: 

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0+k3s2", GitCommit:"2ea6b16315c093d739c370f8f035ad3fa5eb5d11", GitTreeState:"clean", BuildDate:"2020-12-22T02:10:12Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- Cluster Environment: (AWS)
- Host OS: 

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Amazon
Description:    Amazon Linux release 2 (Karoo)
Release:        2
Codename:       Karoo

- Linkerd version:

Client version: stable-2.10.2
Server version: stable-2.10.2
