### ISSUE TITLE
Skaffold failed to deploy due to Linkerd & broke CICD pipeline

### ISSUE THREAD

**Issue by saul-gush** [linkerd/linkerd2#6293]
### What is the issue?
Got error message in skaffold deployment when enabling the linkerd annotation. Caused CICD to stop working. 

### How can it be reproduced?

Run a database is ready check in init container before spinning up main container. If I turn off the linkerd annotation, it works. 
```yaml
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: go-app-user-auth-service
    spec:
      initContainers:
        - name: check-db-ready
          image: gushcloud/postgresql-client:latest
          command: ['sh', '-c', 'until pg_isready -h timescaledb-service -p 5432; do echo waiting for database; sleep 2; done;']
```

### Logs, error output, etc
![image](https://user-images.githubusercontent.com/63714857/122414957-6bb8c700-cf7f-11eb-8b5f-88dae9362dc0.png)

### Environment

- Kubernetes Version: 1.20
- Cluster Environment: Digitalocean
- Linkerd version: 2.10
