### ISSUE TITLE
Support custom annotations on Prometheus' service account in the linkerd-viz Helm chart

### ISSUE THREAD

**Issue by panos--** [linkerd/linkerd2#6411]
### What problem are you trying to solve?

Using the linkerd-viz Helm chart I'm trying to implement Prometheus remote write to [Amazon Managed Service for Prometheus](https://aws.amazon.com/prometheus/). The Linkerd is running on [EKS](https://aws.amazon.com/eks/).

For linkerd-viz's Prometheus to be able to write to the remote Prometheus it has to authenticate against it. To authenticate it needs credentials which should be passed to the Prometheus pod using [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

This can be done by specifying an [annotation](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) on the service account associated with the Prometheus pod. 

Currently the Helm chart doesn't support specifying annotations on the prometheus service account, so it is not possible to implement this solution.

### How should the problem be solved?

The linkerd-viz Helm chart should allow specifying custom annotations for the Prometheus service account. For example using Helm values like this:

```yaml
prometheus:
  serviceAccount:
    annotations:
      my-custom-annotation: some-value
```

This could be implemented by adding something like this to `prometheus-rbac.yaml`:

```yaml
# ...
kind: ServiceAccount
metadata:
  name: prometheus
  # ...
  annotations:
{{ toYaml .Values.prometheus.serviceAccount.annotations | indent 4 }}
# ...
```

### Any alternatives you've considered?

Static credentials can be configured on the remote write config to make the remote write work. But this feature request is about enabling the use of IRSA to be able to avoid having to use static credentials.

### How would users interact with this feature?

The linkerd-viz chart's Helm values are the only UI for this.
