### ISSUE TITLE
linkerd-config-overrides secret generated with linkerd-cli and not helm chart

### ISSUE THREAD

**Issue by darkn3rd** [linkerd/linkerd2#6456]
Linkerd CLI generates a secret `linkerd-config-overrides` and the helm chart does not generate.  The other secrets `linkerd-identity-issuer`, `linkerd-proxy-injector-k8s-tls`, `linkerd-sp-validator-k8s-tls` are the same.

Is this something needed to be done in the helm chart?  How would one generate this for the helm chart?

### Steps

```bash
# set date with BSD or GNU date
exp=$(date -v+8760H +"%Y-%m-%dT%H:%M:%SZ" 2> /dev/null) || \
 exp=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ")

# create ca and identity issuer certs
step certificate create root.linkerd.cluster.local ca.crt ca.key
step certificate create identity.linkerd.cluster.local issuer.crt issuer.key

# create manifests w/ helm
# ref. https://linkerd.io/2.10/tasks/install-helm/
helm template linkerd2 \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer.key \
  --set identity.issuer.crtExpiry=$exp \
  linkerd/linkerd2 > helm_output.yaml

# create manifests w/ linkered
# doc. https://linkerd.io/2.10/tasks/generate-certificates/#passing-the-certificates-to-linkerd
linkerd install \
  --identity-trust-anchors-file ca.crt \
  --identity-issuer-certificate-file issuer.crt \
  --identity-issuer-key-file issuer.key > linkerd_cli.yaml
```

### Expected Results

The secrets would be similar.

### Actual Results

The linkerd cli adds this extra secret:

```yaml
apiVersion: v1
data:
  linkerd-config-overrides: aWRlbnRp...0tCg==
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-config-overrides
  namespace: linkerd
```

When this is decoded, the secret contents for `linkerd-config-overrides` is something like this:

```yaml
identity:
  issuer:
    tls:
      crtPEM: |
        -----BEGIN CERTIFICATE-----
        MIIB...MyCR
        -----END CERTIFICATE-----
      keyPEM: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIB...oZgH5w==
        -----END EC PRIVATE KEY-----
identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBjTCCAT...SEC50nluPovZhy5WAgRmufs=
  -----END CERTIFICATE-----
```
