### ISSUE TITLE
Multicluster - 508 loop detected on cross mirroring of service 

### ISSUE THREAD

**Issue by nomis-rzp** [linkerd/linkerd2#6569]
### What is the issue?
Im following the doc https://linkerd.io/2.10/tasks/multicluster/ to setup multicluster. I did an extra step of cross mirroring of services by linking both the cluster and applying Traffic Split on both east and west cluster. After cross mirroring of service, when we make requests to "frontend" i get "508 Loop Detected" randomly . Error from linkerd-gateway pod.
```
linkerd_app_core::errors: Failed to proxy request: gateway loop detected
```

### How can it be reproduced?
Considering you have an west and east cluster and followed the steps till "mulitcluster link"

Apply mulitcluster link of west
```
linkerd --context=east multicluster link --cluster-name east |
  kubectl --context=west apply -f -
```
Apply multicluster link on east
```
linkerd --context=west multicluster link --cluster-name west |
  kubectl --context=east apply -f -
 ```
 Export Services on both the cluster
 ```
 kubectl --context=east label svc -n test podinfo mirror.linkerd.io/exported=true
 kubectl --context=west label svc -n test podinfo mirror.linkerd.io/exported=true
 ```
 Applying Traffic Split on west
 ```
 cat <<EOF | kubectl --context=west apply -f -
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: podinfo
  namespace: test
spec:
  service: podinfo
  backends:
  - service: podinfo
    weight: 50
  - service: podinfo-east
    weight: 50
EOF
```
Applying traffic Split on east
```
cat <<EOF | kubectl --context=east apply -f -
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: podinfo
  namespace: test
spec:
  service: podinfo
  backends:
  - service: podinfo
    weight: 50
  - service: podinfo-west
    weight: 50
EOF
```
Make requests to http://frontend:8080 and we get 508 loop detected randomly

### Logs, error output, etc
Making request to http://frontend:8080 after coss mirroring service.

Success from west
```
curl http://frontend:8080
{
  "hostname": "podinfo-86bb9b8645-mjppr",
  "version": "4.0.2",
  "revision": "b4138fdb4dce7b34b6fc46069f70bb295aa8963c",
  "color": "#6c757d",
  "logo": "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif",
  "message": "greetings from west",
  "goos": "linux",
  "goarch": "amd64",
  "runtime": "go1.14.3",
  "num_goroutine": "9",
  "num_cpu": "4"
}
```
Success from east
```
curl -vvv http://frontend:8080
{
  "hostname": "podinfo-76fbcc46d-6skvk",
  "version": "4.0.2",
  "revision": "b4138fdb4dce7b34b6fc46069f70bb295aa8963c",
  "color": "#007bff",
  "logo": "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif",
  "message": "greetings from east",
  "goos": "linux",
  "goarch": "amd64",
  "runtime": "go1.14.3",
  "num_goroutine": "9",
  "num_cpu": "4"
  }
 ```
Loop Detected
```
curl -vvv http://frontend:8080
* Mark bundle as not supporting multiuse
< HTTP/1.1 508 Loop Detected
< server: nginx/1.21.1
< date: Tue, 27 Jul 2021 07:24:05 GMT
< content-length: 0
```
Error from linkerd-gateway pod
```
linkerd_app_core::errors: Failed to proxy request: gateway loop detected
```
### Environment

- Kubernetes Version: 1.18
- Cluster Environment: EKS (AWS managed kubernetes) 
- Host OS: Amazon Linux
- Linkerd version: Client version: stable-2.10.2 , Server version: stable-2.10.2

**Comment by nomis-rzp** [comment]
Architecture which im trying to implement.
![Blank diagram(1)](https://user-images.githubusercontent.com/49149863/127298089-7f155700-9a09-470e-b961-ed2ba1be095f.jpeg)

**Comment by alpeb** [comment]
Thanks for the detailed description @nomis-rzp. The setup looks sane to me. I'll try to reproduce the problem locally and let you know.

**Comment by alpeb** [comment]
Ok there's indeed an infinite looping issue because the cross-cluster requests are handled by the traffic splits, which could route back the request to the origin cluster.

For example say you request podinfo on west, which the trafficsplit could redirect to the podinfo trafficsplit on east, which itself could redirect back to east's trafficsplit, etc...

**Comment by nomis-rzp** [comment]
>For example say you request podinfo on west, which the trafficsplit could redirect to the podinfo trafficsplit on east, which itself could redirect back to east's trafficsplit, etc...

@alpeb Yes that's right . Even i was also suspecting the same. Traffic going to the other cluster does a traffic split again. Any suggestion to fix it ?

If we do not point frontend to both cluster, it will become a single point of failure.

**Comment by alpeb** [comment]
The issue is that your trafficsplits have the same service in the apex (`spec.service`) and in the first leaf. You could leave the podinfo as the apex, but edit it so it doesn't point to a pod. And then replace the leaf service with a new service "podinfo-leaf" that points to the podinfo pods. And then you would only mirror "podinfo-leaf".

So when you request podinfo on west, the TS could redirect it to "podinfo-leaf" on east, not the TS on east, so no further redirection would occur. I haven't tried this, so let me know how it goes!

**Comment by alpeb** [comment]
Forget about the part where I said to edit the `podinfo` service so it doesn't point to a pod. Instead copy it verbatim to another service named `podinfo-leaf`, in both clusters. Now remove the `mirror.linkerd.io/exported` label from the original `podinfo` service, so now only `podinfo-leaf` is mirrored.

You'll end with services like this in west (and similarly in east):
```console
 k -n test get svc 
NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
frontend              ClusterIP   10.43.226.206   <none>        8080/TCP            23m
podinfo-leaf-east  ClusterIP   10.43.127.95    <none>        9898/TCP,9999/TCP   10m
podinfo-leaf          ClusterIP   10.43.71.68     <none>        9898/TCP,9999/TCP   9m22s
podinfo               ClusterIP   10.43.235.202   <none>        9898/TCP,9999/TCP   23m
```

Now replace your TrafficSplits so they look like this:

In west:
```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
 name: podinfo
 namespace: test
spec:
 service: podinfo
 backends:
 - service: podinfo-leaf
   weight: 50
 - service: podinfo-leaf-east
   weight: 50
```

In east:
```yaml
apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
 name: podinfo
 namespace: test
spec:
 service: podinfo
 backends:
 - service: podinfo-leaf
   weight: 50
 - service: podinfo-leaf-west
   weight: 50
```

And you should no longer observe loops because when the TS in west makes a cross-cluster request to `podinfo-leaf-east` it's gonna be routed to the `podinfo-leaf` in east and that's it. Whereas in your original example the cross-cluster request to `podinfo-east` would be routed to the `podinfo` service in east, which is behind a TS in east which in the 50% of the cases it's gonna route it back into the west cluster. Makes sense?
