### ISSUE TITLE
Prometheus-Operator PodMonitor Support

### ISSUE THREAD

**Issue by kehao95** [linkerd/linkerd2#6596]
### What problem are you trying to solve?

I have powerful Prometheus setup deployed with prometheus-operator, extended with Thanos.
I want to bring my own Prometheus without changing prometheus config. But do it in prometheus-operator way.

### How should the problem be solved?

The Prometheus-Operator provided [PodMonitor](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#podmonitor) resource.  It help prometheus to discover targets (pods) by LabelSelector. 
(Under the hood, it translate and append the monitor CRD into prometheus config. Then reload Prometheus config.)

Since linkerd will label the injected pods. A single PodMonitor will be enough for all sidecars to be discovered & scrape by Prometheus.

### Any alternatives you've considered?
If we don't want this built in at least added the tutorial to the doc.

### How would users interact with this feature?
Some command that generate a `PodMonitor` for user to install.

**Comment by kehao95** [comment]
I figured out a working example for my prometheus deployment:
```yaml
# linkerd-sidecar-podmonitor.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: linkerd-sidecar-podmonitor
  namespace: linkerd-viz
spec:
  podTargetLabels:
  - "linkerd.io/proxy-deployment"  # pass proxy-deployment label for additional info (optional)
  podMetricsEndpoints:               # tell prometheus which port/path to scrape
  - interval: 30s
    path: /metrics
    port: linkerd-admin
  jobLabel: linkerd-sidecar
  selector: 
    matchExpressions:       # label selector match all injected pods
    - key: linkerd.io/control-plane-ns
      operator: Exists
  namespaceSelector:
    any: true  # search pods in all namespaces
```
