### ISSUE TITLE
filter default list of `opaque-ports` during proxy injection

### ISSUE THREAD

**Issue by kleimkuhler** [linkerd/linkerd2#6729]
#6719 changed the proxy injector so that it adds the default list of opaque ports to pods and services. While this covers most cases, there is an edge case that it would currently miss.

If the service's spec exposes ports with a `targetPort`, then blindly copying the default list of opaque ports would not cover this case. For example, if the service maps `80` -> `3306`, then it's opaque ports should account for this; `3306` should be substituted with `80` since that is the port that is opaque.

While fixing this, it would also be worth making sure the default list for pods _and_ services only takes into account ports that are exposed by the workloads spec. If a workload does not expose any ports in the default list, then the `opaque-ports` list should not be added.

After this change, the proxy injector should properly annotate the following manifest:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: kube-public
spec:
  selector:
    app: test
  ports:
  - name: foo
    port: 9090
    targetPort: 3306
  - name: bar
    port: 5432
    targetPort: 9091
  - name: baz
    port: 9092
    targetPort: not-an-int
---
apiVersion: v1
kind: Pod
metadata:
  name: foo
  labels:
    app: test
spec:
  containers:
  - name: foo
    image: mysql
    ports:
    - containerPort: 3306
```

`service/svc` annotation: `9090,5432`
`pod/foo` annotation: `3306`
