### ISSUE TITLE
linkerd viz dashboard fails when proxied through traefik ingressroutes

### ISSUE THREAD

**Issue by ieaves** [linkerd/linkerd2#6832]
## Bug Report

This may be a configuration issue on my part so I'd like to apologize in advance if that's the case. However, I can't get the recommended traefik ingress object to successfully proxy the linkerd viz dashboard.

### What is the issue?

Proxy ingress to the linkerd viz web service nominally works but loads empty results like below:
![Screenshot from 2021-09-07 14-08-37](https://user-images.githubusercontent.com/7785207/132398070-73ff9c01-a100-41dc-a000-f902da0c99ba.png)

The dashboard loads correctly using both `linkerd viz dashboard` and directly port-forwarding to the web service.

### How can it be reproduced?

The recommended traefik ingress [definition](https://linkerd.io/2.10/tasks/exposing-dashboard/#traefik) fails to load cluster data. In this case I'm using a traefik ingressroute rather than a kubernetes ingress.

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers
  namespace: linkerd-viz
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: web.linkerd-viz.svc.cluster.local:8084
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name:  web-ingress
  namespace: linkerd-viz
spec:
  entryPoints:
  - web
  routes:
  - match: Host(`dashboard.example.com`)
    kind: Rule
    priority: 0
    middlewares:
    - name: headers
    services:
    - name: web
      kind: Service
      port: 8084
```

### Logs, error output, etc

There appears to be a GET to `https://linkerd.tinglacier.com/api/tps-reports?resource_type=namespace&namespace=all&tcp_stats=true&window=1m` which returns 401 Unauthorized `CORS Missing Allow Origin`.

#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
W0907 14:32:33.779467  152336 warnings.go:67] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ control plane is up-to-date
√ control plane and cli versions match

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ prometheus is installed and configured correctly
√ can initialize the client
√ viz extension self-check
```

### Environment

- Kubernetes Version: v1.21.2
- Cluster Environment: k0s
- Host OS: ubuntu 20.04
- Linkerd version: 2.10.2

### Additional context

I've been at this for awhile now with various combinations of CORS based header permissions as well though none have changed the result. It doesn't obviously appear to be an issue with the ingress itself since I'm successfully hitting the web service (it returns html and enforces it's deployment `enforced-host` rules). At the same time everything works beautifully using `linkerd viz dashboard` which paints the opposite picture.
