### ISSUE TITLE
linkerd-proxy not gracefully stopping

### ISSUE THREAD

**Issue by magec** [linkerd/linkerd2#6993]
### What is the issue?

Linkerd-proxy sidecar is left out running even though a *SIGTERM* is sent to it and no other containers are running in the pod.
This is related to this issue (https://github.com/linkerd/linkerd2/issues/3751).

Our set up uses `linkerd-await` with `--shutdown` to signal `linkerd-proxy` upon termination of the main container. Even though, the main container finishes, and it correctly sends the signal to linkerd-proxy (which correctly receives it and starts the shutdown process), it fails to gracefully finish (and stays in an infinite loop).

 This is revealed because we have set a very large `terminationGracePeriodSeconds` in the pod, so in the end, `linkerd2-proxy` only finishes when a SIGKILL is sent.

### How can it be reproduced?
It only happens on some pods of the same deployment, but I do not know the reason yet.

### Logs, error output, etc
We have set `linkerd2-proxy` into debug mode and, after receiving the shutdown it says:
```
[   252.250155s]  INFO ThreadId(01) linkerd2_proxy: Received shutdown via admin interface
```

Then it starts the shutdown process, and in the end, it keeps saying:
```
[   427.758651s] DEBUG ThreadId(01) identity:identity_daemon{peer.addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [59, 124, 219, 122, 11, 135, 22, 180] }
[   427.758675s] DEBUG ThreadId(01) identity:identity_daemon{peer.addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135, 22, 180] }
[   428.861901s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.29.109:48970 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [59, 124, 219, 122, 11, 135, 22, 180] }
[   428.861930s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.29.109:48970 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135, 22, 180] }
[   428.894642s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.29.109:48970 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [59, 124, 219, 122, 11, 135, 22, 180] }
[   428.894671s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.29.109:48970 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135, 22, 180] }
[   429.130782s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.29.109:48970 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [59, 124, 219, 122, 11, 135, 22, 180] }
[   429.130810s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.29.109:48970 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135, 22, 180] }

```
in a loop.

strace of this moment:
```
[pid 3029021] write(1, "[  2824.198359s] DEBUG ThreadId(01) identity:identity_daemon{peer.addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135,
22, 180] }\n", 260) = 260
[pid 3029021] writev(17, [{iov_base="\27\3\3\0\"K\311%\243~\347\334@eCs\267_L\336\243Zn2\377\363\315\37<3+\243{\276P\21\264\206g", iov_len=39}], 1) = 39
[pid 3029021] epoll_wait(3,
[{EPOLLIN|EPOLLOUT, {u32=16777225, u64=16777225}}, {EPOLLIN|EPOLLOUT, {u32=10, u64=10}}], 1024, -1) = 2
[pid 3029021] recvfrom(21, "\27\3\3\0\"\2162\24\3748|\276\377r\35\3104\357/\f8\371\6/\242mB\242\33\223\331N5A>\264\r\275&", 18437, 0, NULL, NULL) = 39
[pid 3029021] recvfrom(21, 0x563d33d59cd0, 18437, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 3029021] write(1, "[  2824.592490s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.151.144:49956 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [59, 124, 219, 122, 11, 135
, 22, 180] }\n", 262) = 262
[pid 3029021] write(1, "[  2824.592583s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.151.144:49956 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135, 22
, 180] }\n", 258) = 258
[pid 3029021] writev(21, [{iov_base="\27\3\3\0\"l\371\270\364\343\223\32$\r<N?\317\254\214kW\37\326U\255\327eQ_\17\205\230p\256q2\24\251", iov_len=39}], 1) = 39
[pid 3029021] recvfrom(22, "\27\3\3\0\"@G\332(\340\354k\22\241\223\256\26@\341\321\210E\275[\244\0235\270\346\257\275>$+\27\204\322m{", 18437, 0, NULL, NULL) = 39
[pid 3029021] recvfrom(22, 0x563d33d5f850, 18437, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 3029021] write(1, "[  2824.592848s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.151.144:49956 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [59, 124, 219, 122, 11, 135
, 22, 180] }\n", 262) = 262
[pid 3029021] write(1, "[  2824.592919s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.151.144:49956 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135, 22
, 180] }\n", 258) = 258
[pid 3029021] writev(22, [{iov_base="\27\3\3\0\"!\344\355\345?\26\225\251\264U\360\"pC\224\341\321\270\36/A\301\266\341\212\254\0\316*\324\332\304\220\337", iov_len=39}], 1) = 39
[pid 3029021] epoll_wait(3,
[{EPOLLIN|EPOLLOUT, {u32=11, u64=11}}], 1024, -1) = 1
[pid 3029021] recvfrom(23, "\27\3\3\0\"\327\3516\\`\221\237\270\2\306\210\326\270\0240:X\243\320*g5\211\364\6\226,\207L\365\3Y\215\232", 18437, 0, NULL, NULL) = 39
[pid 3029021] recvfrom(23, 0x563d33d65730, 18437, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 3029021] write(1, "[  2824.891329s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.151.144:49956 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_read: received frame=Ping { ack: false, payload: [59, 124, 219, 122, 11, 135
, 22, 180] }\n", 262) = 262
[pid 3029021] write(1, "[  2824.891418s] DEBUG ThreadId(01) outbound:accept{client.addr=10.2.151.144:49956 target.addr=10.3.254.114:6432}:poll_profile:h2:Connection{peer=Client}: h2::codec::framed_write: send frame=Ping { ack: true, payload: [59, 124, 219, 122, 11, 135, 22
, 180] }\n", 258) = 258
[pid 3029021] writev(23, [{iov_base="\27\3\3\0\"\361\205\35\227p\2724S\216D\n>\217\300\273\307\5 \374\310\277:\363\350x\225]\326\n?Y\370w\235", iov_len=39}], 1) = 39

```
#### `linkerd check` output

```text
kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ controller pod is running

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist
√ control plane PodSecurityPolicies exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-api
-----------
√ control plane pods are ready
√ can initialize the client
√ can query the control plane API

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.10.0 but the latest stable version is 2.10.2
    see https://linkerd.io/2.10/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.10.0 but cli running stable-2.10.2
    see https://linkerd.io/2.10/checks/#l5d-version-control for hints

Status check results are √

Linkerd extensions checks
=========================

linkerd-viz
-----------
√ linkerd-viz Namespace exists
√ linkerd-viz ClusterRoles exist
√ linkerd-viz ClusterRoleBindings exist
√ tap API server has valid cert
√ tap API server cert is valid for at least 60 days
√ tap API service is running
√ linkerd-viz pods are injected
√ viz extension pods are running
√ can initialize the client
√ viz extension self-check

Status check results are √

```

### Environment

- Kubernetes Version: Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- Cluster Environment: None
- Host OS: Flatcar Container Linux by Kinvolk stable (2605.9.0)
- Linkerd version: stable-2.10.0

### Possible solution
I think it would be nice having a grace period configurable using an annotation inside linkerd-proxy, if after receiving the TERM signal (or the /shutdown) it does not shutdown for that time, it will 'self desctruct'.

**Comment by olix0r** [comment]
@magec Thanks for the detailed report! First, we should probably look into the shutdown behavior to see why the profile task keeps the proxy alive -- have all application containers terminated at this point? And I agree that we should probably provide some default termination grace period (1m?)

**Comment by magec** [comment]
A default termination grace period of 1 minute will be awesome.

> have all application containers terminated at this point?

This is a good question, because I see inconsistencies here, and maybe is related to the issue. Kubernetes says:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-09-29T23:27:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-09-30T08:34:45Z"
    message: 'containers with unready status: [linkerd-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-09-30T08:34:45Z"
    message: 'containers with unready status: [linkerd-proxy]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-09-29T23:27:42Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://4131fe93526f92fb65ee5b2b151099744dc01c5606d3e8446fa423dd925d24df
    image: cr.l5d.io/linkerd/proxy:stable-2.10.0
    imageID: docker-pullable://cr.l5d.io/linkerd/proxy@sha256:37ca8bd6131ac014bbd0b464c467eb0cadd651361e58b8dea6becfc9679c5a14
    lastState: {}
    name: linkerd-proxy
    ready: false
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-09-29T23:27:45Z"
  - containerID: docker://7b02cd482b17fcec3f4a2f0b73568c2089f4cf43e572c4217b79e0b6c917ef42
    image: [FILTERED]
    imageID: docker-pullable://[FILTERED]
    lastState: {}
    name: onesignal
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-09-29T23:27:44Z"
  - containerID: docker://582a64c40716537fd905447ff3c9afacec930bdd706e1c039ad844d5e25ff027
    image: prom/statsd-exporter:v0.22.1
    imageID: docker-pullable://prom/statsd-exporter@sha256:222e90967ed167c7a2458b1c35a3ddab0fb869b5b74a6aa86eeb6bc57b0de719
    lastState: {}
    name: statsd-exporter
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-09-29T23:27:45Z"
  hostIP: 10.99.3.11
  initContainerStatuses:
  - containerID: docker://91acbd6c2afbdaaa875ef238fd7bb1a116ada1f5088457997d12a7fb17713753
    image: cr.l5d.io/linkerd/proxy-init:v1.3.9
    imageID: docker-pullable://cr.l5d.io/linkerd/proxy-init@sha256:c217b1b9355605bf5efb3bfe1ffa28cdabd1ad66ac34d909d1f5c5a58d56150e
    lastState: {}
    name: linkerd-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://91acbd6c2afbdaaa875ef238fd7bb1a116ada1f5088457997d12a7fb17713753
        exitCode: 0
        finishedAt: "2021-09-29T23:27:43Z"
        reason: Completed
        startedAt: "2021-09-29T23:27:43Z"
  phase: Running
  podIP: 10.2.29.133
  podIPs:
  - ip: 10.2.29.133
  qosClass: Burstable
  startTime: "2021-09-29T23:27:42Z"
```
There are 3 containers in the pod, the main one, one sidecar (an exporter) and `linkerd-proxy`. Kubernetes says that they are all running, and that `linkerd-proxy` is in `NotReady` (`linkerd-proxy` is not ready because it stopped its admin ports and its readiness test is falsy), but the funny part is that the rest of the containers are not being run at all and kubernetes says they are still running.

If I get into the node and I can see that for this pod, only `linkerd-proxy` and the `pause` one (injected by k8s for maintaning the network ns) are running.

```
$ docker ps |grep rxv7f
4131fe93526f        c26c9a2f5781                               "/usr/bin/linkerd2-p…"    10 hours ago        Up 10 hours                             k8s_linkerd-proxy_rails-sidekiq-default-c599b8f89-rxv7f_rails-production_fb237204-665c-495a-8925-9eb47f5a86c7_0
6ca54cacdca8        k8s.gcr.io/pause:3.2                       "/pause"                  10 hours ago        Up 10 hours                             k8s_POD_rails-sidekiq-default-c599b8f89-rxv7f_rails-production_fb237204-665c-495a-8925-9eb47f5a86c7_0
```

Which is weird. If I kill `linkerd` with a `docker kill` the pod is terminated.
