### ISSUE TITLE
Healthchecks are not passed when `all-authenticated` policy mode is on

### ISSUE THREAD

**Issue by aatarasoff** [linkerd/linkerd2#7050]
### What is the issue?
After turning on the `all-authenticated` policy mode, affected pods cannot start because of 403 error.

### How can it be reproduced?
Just add `config.linkerd.io/default-inbound-policy: all-authenticated` annotation on a namespace.

### Logs, error output, etc
```
{"timestamp":"[    48.376757s]","level":"INFO","fields":{"message":"Request failed","error":"unauthorized connection on server default:all-authenticated"},"target":"linkerd_app_core::errors::respond","spans":[{"name":"inbound"},{"client.addr":"<kubelet_ip>","name":"accept"},{"port":80,"name":"server"},{"v":"1.x","name":"http"},{"client.addr":"<kubelet_ip>","name":"rescue"}],"threadId":"ThreadId(1)"}


{"timestamp":"[    48.376773s]","level":"DEBUG","fields":{"message":"Handling error on HTTP connection","status":"403 Forbidden","version":"HTTP/1.1","close":"false"},"target":"linkerd_app_core::errors::respond","spans":[{"name":"inbound"},{"client.addr":"<kubelet_ip>","name":"accept"},{"port":80,"name":"server"},{"v":"1.x","name":"http"}],"threadId":"ThreadId(1)"}
```

#### `linkerd check` output

```Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days
√ policy-validator webhook has valid cert
√ policy-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
√ control plane is up-to-date
√ control plane and cli versions match

linkerd-control-plane-proxy
---------------------------
√ control plane proxies are healthy
√ control plane proxies are up-to-date
√ control plane proxies and cli versions match

linkerd-ha-checks
-----------------
√ pod injection disabled on kube-system

Status check results are √
```

### Environment

- Kubernetes Version: 1.20.9-gke.1001
- Cluster Environment: GKE
- Host OS: Container-Optimized OS with Docker (cos)
- Linkerd version: 2.11.0

### Possible solution
Something like this (https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/) would be nice.

Workaround:
```
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: coolns
  name: serving-port
  labels:
    anna.money/server-type: common
spec:
  podSelector:
    matchLabels:
      linkerd.io/control-plane-ns: linkerd
  port: serving-port
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: coolns
  name: linkerd-admin-port
  labels:
    anna.money/server-type: common
spec:
  podSelector:
    matchLabels:
      linkerd.io/control-plane-ns: linkerd
  port: linkerd-admin
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: coolns
  name: allow-healthchecks
spec:
  server:
    selector:
      matchLabels:
        anna.money/server-type: common
  client:
    unauthenticated: true
    networks:
# kubelet CIDRs here, for example with templating
{% for n in range(x, y) %}
{% for m in range(0, 256) %}
      - cidr: 10.{{ n }}.{{ m }}.1/32
{% endfor %}
{% endfor %}
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: coolns
  name: allow-authenticated
spec:
  server:
    selector:
      matchLabels:
        anna.money/server-type: common
  client:
    meshTLS:
      identities:
        - "*"
```

### Additional context
Original thread from official slack: https://linkerd.slack.com/archives/C89RTCWJF/p1633592434126000

**Comment by aatarasoff** [comment]
@olix0r it was the first that I did.

I've added this `ServerAuthorization` to allow kubelet request pods:
```
---
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: coolns
  name: allow-healthchecks
spec:
  server:
    selector:
      matchLabels:
        anna.money/server-type: common
  client:
    unauthenticated: true
    networks:
# kubelet CIDRs here, for example with templating
{% for n in range(x, y) %}
{% for m in range(0, 256) %}
      - cidr: 10.{{ n }}.{{ m }}.1/32
{% endfor %}
{% endfor %}
```

It solved the problem with healthchecks but add the new one. Pods started to reject any request from other pods:
```
{"timestamp":"[   378.100787s]","level":"INFO","fields":{"message":"Request denied","server":"serving-port","tls":"Some(Established { client_id: Some(ClientId(\"nginx-ingress.serviceaccount.identity.linkerd.cluster.local\")), negotiated_protocol: None })","client":"<other_pod_address>"},"target":"linkerd_app_inbound::policy::authorize::http","spans":[{"name":"inbound"},{"port":80,"name":"server"}],"threadId":"ThreadId(1)"}


{"timestamp":"[   378.100852s]","level":"INFO","fields":{"message":"Request failed","error":"unauthorized connection on server serving-port"},"target":"linkerd_app_core::errors::respond","spans":[{"name":"inbound"},{"port":80,"name":"server"},{"client.addr":"<other_pod_address>","name":"rescue"}],"threadId":"ThreadId(1)"}
```

Then I added another one authorization to explicitly allow meshed connections:
```
apiVersion: policy.linkerd.io/v1beta1
kind: ServerAuthorization
metadata:
  namespace: coolns
  name: allow-authenticated
spec:
  server:
    selector:
      matchLabels:
        anna.money/server-type: common
  client:
    meshTLS:
      identities:
        - "*"
```

But it means that (at least in my case) `all-authenticated` mode is useless because it is clearer to use `deny` mode and setup policies manually. 

Moreover, this workaround relies on internal implementation of GKE and some magic knowledge. It leads to potential risks in case of changes in GKE that we cannot control.

I see that Istio try to fix the healthchecks problem another way: https://istio.io/latest/docs/ops/configuration/mesh/app-health-check/. What do you think about this approach? For me it is more transparent for an end user.
