### ISSUE TITLE
Possible CNI Plugin High Availability Issue

### ISSUE THREAD

**Issue by milsman2** [linkerd/linkerd2#7066]
### What is the issue?
My issue is that I cannot seem to get Linkerd2 to have all pods up and running with the CNI plugin and Linkerd2 in high availability. I always have the same issue which seems to be centered around TLS.
### How can it be reproduced?
I am running my clusters with K3s and deploying all apps as subcharts through ArgoCD. My deployment is as such:

Chart.yaml:
```
apiVersion: v2
name: linkerd2
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: linkerd2
  version: 2.10.2
  repository: https://helm.linkerd.io/stable
```

```
Values.yaml:

linkerd2:
  identityTrustAnchorsPEM: |
  **omitted**
  identity:
    externalCA: false
    issuer:
      scheme: linkerd.io/tls
      clockSkewAllowance: 20s
      issuanceLifetime: 24h0m0s
      crtExpiry: 2022-10-09T08:39:18Z
      tls:
        crtPEM: |
        **omitted**
        keyPEM: |
       **omitted**
  enablePodAntiAffinity: true
  proxy:
    resources:
      cpu:
        request: 100m
      memory:
        limit: 250Mi
        request: 20Mi   
  controllerReplicas: 3
  controllerResources: &controller_resources
    cpu: &controller_resources_cpu
      limit: ""
      request: 100m
    memory:
      limit: 250Mi
      request: 50Mi
  destinationResources: *controller_resources
  identityResources:
    cpu: *controller_resources_cpu
    memory:
      limit: 250Mi
      request: 10Mi
  heartbeatResources: *controller_resources
  proxyInjectorResources: *controller_resources
  webhookFailurePolicy: Fail
  spValidatorResources: *controller_resources
  cniEnabled:
    true
```

Chart.yaml:
```
apiVersion: v2
name: linkerd2-cni
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: linkerd2-cni
  version: 2.10.2
  repository: https://helm.linkerd.io/stable
```
values.yaml:
```
linkerd2-cni:
  namespace: linkerd-cni
  installNamespace: true
  inboundProxyPort: 4143
  outboundProxyPort: 4140
  ignoreInboundPorts: ""
  ignoreOutboundPorts: ""
  proxyAdminPort: 4191
  proxyControlPort: 4190
  cniPluginImage:   "cr.l5d.io/linkerd/cni-plugin"
  cniPluginVersion: stable-2.10.2
  logLevel:         info
  portsToRedirect:  ""
  proxyUID:         2102
  destCNINetDir:    "/etc/cni/net.d"
  destCNIBinDir:    "/opt/cni/bin"
  useWaitFlag:      false
  priorityClassName: ""
  enablePSP: false
  imagePullSecrets:
  extraInitContainers: []
```
### Logs, error output, etc

(If the output is long, please create a [gist](https://gist.github.com/) and
paste the link here.)

#### `linkerd check` output

```text
Linkerd core checks
===================

kubernetes-api
--------------
√ can initialize the client
√ can query the Kubernetes API

kubernetes-version
------------------
√ is running the minimum Kubernetes API version
√ is running the minimum kubectl version

linkerd-existence
-----------------
√ 'linkerd-config' config map exists
√ heartbeat ServiceAccount exist
√ control plane replica sets are ready
√ no unschedulable pods
√ control plane pods are ready
√ cluster networks contains all node podCIDRs

linkerd-config
--------------
√ control plane Namespace exists
√ control plane ClusterRoles exist
√ control plane ClusterRoleBindings exist
√ control plane ServiceAccounts exist
√ control plane CustomResourceDefinitions exist
√ control plane MutatingWebhookConfigurations exist
√ control plane ValidatingWebhookConfigurations exist

linkerd-cni-plugin
------------------
√ cni plugin ConfigMap exists
√ cni plugin ClusterRole exists
√ cni plugin ClusterRoleBinding exists
√ cni plugin ServiceAccount exists
√ cni plugin DaemonSet exists
√ cni plugin pod is running on all nodes

linkerd-identity
----------------
√ certificate config is valid
√ trust anchors are using supported crypto algorithm
√ trust anchors are within their validity period
√ trust anchors are valid for at least 60 days
√ issuer cert is using supported crypto algorithm
√ issuer cert is within its validity period
√ issuer cert is valid for at least 60 days
√ issuer cert is issued by the trust anchor

linkerd-webhooks-and-apisvc-tls
-------------------------------
√ proxy-injector webhook has valid cert
√ proxy-injector cert is valid for at least 60 days
√ sp-validator webhook has valid cert
√ sp-validator cert is valid for at least 60 days

linkerd-version
---------------
√ can determine the latest version
√ cli is up-to-date

control-plane-version
---------------------
√ can retrieve the control plane version
‼ control plane is up-to-date
    is running version 2.10.2 but the latest stable version is 2.11.0
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints
‼ control plane and cli versions match
    control plane running stable-2.10.2 but cli running stable-2.11.0
    see https://linkerd.io/2.11/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
| The "linkerd-controller-864dd8dc78-xwj55" pod is not running 

time="2021-10-09T20:20:05Z" level=info msg="running version stable-2.10.2"
[     0.002144s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.002830s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.002846s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.002849s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.002851s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
[     0.002853s]  INFO ThreadId(01) linkerd2_proxy: Local identity is linkerd-proxy-injector.linkerd.serviceaccount.identity.linkerd.cluster.local
[     0.002856s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.002859s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via linkerd-dst-headless.linkerd.svc.cluster.local:8086 (linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     2.807144s]  INFO ThreadId(02) linkerd_app_core::serve: Connection closed error=TLS detection timed out
[    69.617802s]  INFO ThreadId(02) linkerd_app_core::serve: Connection closed error=TLS detection timed out
[   129.674359s]  INFO ThreadId(02) linkerd_app_core::serve: Connection closed error=TLS detection timed out
[   132.678800s]  INFO ThreadId(02) linkerd_app_core::serve: Connection closed error=TLS detection timed out
```

### Environment

- Kubernetes Version: v1.21
- Cluster Environment: K3s on bare metal
- Host OS: Ubuntu 20.04 LTS
- Linkerd version: stable-2.10.2

### Possible solution
No Idea.
### Additional context
This definitely does not work for me right off the bat. However, when cniEnabled is set to false, the app installs just fine. After trying to deploy again with cniEnabled set to true and the app still running I always get one set of pods not functioning. 

Screencap attached
![Linkerd2 with CNI](https://user-images.githubusercontent.com/72627575/136672568-5588f13e-08ce-4ff1-aa1b-8d5edfab6d82.PNG)
![Linkerd2 No CNI](https://user-images.githubusercontent.com/72627575/136672569-67bfb87c-f293-4035-8434-8d2e8bd95d93.PNG)
.
