### ISSUE TITLE
Traffic reaching cluster via k3s traefik ingress ignores custom l5d-dst-override header

### ISSUE THREAD

**Issue by tobiasmuehl** [linkerd/linkerd2#7234]
### What is the issue?

Route metrics aren't generated

### How can it be reproduced?

On a fresh VPS, run:

```
mkdir -p /var/lib/rancher/k3s/server/manifests/
vi /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
```

paste: 

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    dashboard:
      enabled: true
```

Install single node k3s cluster

```
curl -sfL https://get.k3s.io | sh -
```

Install linkerd CLI

```
curl -fsL https://run.linkerd.io/install | sh
```

Install Linkerd and dashboard

```
linkerd install | kubectl apply -f -
linkerd viz install | kubectl apply -f -
```

Install booksapp and routes as outlined in [the docs](https://linkerd.io/2.11/tasks/books/#service-profiles).

Everything seems to work ok, per-route metrics show up fine in viz dashboard. Let's enable ingress for this app:

```yml
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: booksapp-ingressroute
  namespace: booksapp
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: webapp
          port: 7000
      middlewares:
        - name: books-l5d-header-middleware
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: books-l5d-header-middleware
  namespace: booksapp
spec:
  headers:
    customRequestHeaders:
      l5d-dst-override: 'webapp.booksapp.svc.cluster.local:7000'
```

Afterwards, delete the traffic generator/bot

```
kubectl -n booksapp delete deploy/traffic
```

Now, the app is exposed on the IP of the VPS on port 80. App itself works fine. However, no per-route metrics show up.

### Logs, error output, etc

We can verify that traefik middleware is installed by looking at the dashboard ([screenshot](https://i.imgur.com/hM2W1U5.png))

```
kubectl get pod -n kube-system

# find traefik pod
kubectl port-forward traefik-57788b689c-8tgbq -n kube-system 9000:9000
# then, open browser on http://localhost:9000/dashboard/
```

We can check with tap to see that the `:authority` isn't set properly, the `l5d-dst-override` header is not configured properly.

```
linkerd viz tap -n booksapp deploy/webapp -o wide | grep req

req id=12:0 proxy=in  src=10.42.0.1:49834 dst=10.42.0.37:7000 tls=no_tls_from_remote :method=GET :authority=10.42.0.37:7000 :path=/ping dst_res=deploy/webapp dst_ns=booksapp
req id=19:0 proxy=in  src=10.42.0.1:60634 dst=10.42.0.38:7000 tls=no_tls_from_remote :method=GET :authority=10.42.0.38:7000 :path=/ping dst_res=deploy/webapp dst_ns=booksapp
req id=17:0 proxy=in  src=10.42.0.26:42484 dst=10.42.0.33:7000 tls=true :method=GET :authority=162.55.167.52 :path=/images/favicon.ico src_res=deploy/traefik src_ns=kube-system dst_res=deploy/webapp dst_ns=booksapp
```

#### `linkerd check` output

[linkerd check looks good](https://gist.github.com/tobiasmuehl/eaa8b457c49b17ffd121abc804fb939f)

### Environment

- Kubernetes Version: v1.21.5+k3s2
- Cluster Environment: k3s v1.21.5+k3s2
- Host OS: Ubuntu 20
- Linkerd version: stable-2.11.1

### Possible solution

Using Chrome browser extension [ModHeader](https://modheader.com/), we can manually override the `Host` header of the request and set it to `webapp.booksapp.svc.cluster.local`. This fixes per-route metrics (but breaks the dashboard, so look at the dashboard from another browser or add a URL filter to ModHeader rule)
