### ISSUE TITLE
multicluster in GKE

### ISSUE THREAD

**Issue by ezemegwara** [linkerd/linkerd2#7273]
### What is the issue?
I can't access services in the east cluster.

### How can it be reproduced?
so I installed Linkerd and the Multi-cluster Components on two GKE clusters following the official documentation.
I linked both clusters, deployed the apps. I am using Nginx ngress 
all deployment and ingress pods was injected with Linkerd-proxy on both clusters

on the west cluster: I have frontend and cart deployment. so I exported both Services to the east
on the east cluster: I have currency and email deployment.  I exported both Services to the west

I am not confident on my ingress resources. when I deployed the same things with Istio, it worked fine probably because istio came with its ingress

#### ingress on west cluster

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-shop-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
```
#### ingress on east cluster

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: online-shop-ingress
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-west
            port:
              number: 80
```

### Logs, error output, etc

when I access the west public IP, the fronend loads but show errors about the currencyservice
```
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp: lookup currencyservice on 10.3.240.10:53: no such host"
could not retrieve currencies
```
the interesting thing is, when I access the east public IP, the fronend loads with the same error as above
so I am confused, if the link, gateway, ingress or controller are badly configured. how is the east cluster accessing the frontend (though with error) of the west cluster

#### `linkerd check` output for both clusters

```
Status check results are √
```

#### Endpoint check for currencyservice-east

```
kubectl --context=$west get endpoints currencyservice-east \ 
  -o 'custom-columns=ENDPOINT_IP:.subsets[*].addresses[*].ip'
kubectl --context=$east -n linkerd-multicluster get svc linkerd-gateway \
  -o "custom-columns=GATEWAY_IP:.status.loadBalancer.ingress[*].ip"
ENDPOINT_IP
34.141.58.61
GATEWAY_IP
34.141.58.61
```
### Environment

- Kubernetes Version: 1.20
- Cluster Environment: (GKE)
- Host OS:
- Linkerd version: Client version: stable-2.11.0
