### ISSUE TITLE
Disable Privilege Escalation linkerd containers installed through Helm

### ISSUE THREAD

**Issue by shafanaS** [linkerd/linkerd2#7282]
### What is the issue?
When linkerd installed through helm charts in a kuberenetes cluster, in linkerd containers privilege escalation should be disabled. 
In the below deployments of linkerd, for container configurations `allowPrivilegeEscalation: false` flag should be set.

- linkerd-controller       
- linkerd-destination   
- linkerd-identity     
- linkerd-proxy-injector   
- linkerd-sp-validator

 There should be a way to disable privilege escalation when deploying through helm chart. 

### How can it be reproduced?
Install linkerd using below commands. 
```
helm repo add linkerd https://helm.linkerd.io/stable
helm repo update
helm upgrade --install linkerd2 --wait \
  --set-file identityTrustAnchorsPEM=/tmp/ca.crt \
  linkerd/linkerd2 \
  -f linkerd2/values.yaml -f linkerd2/ha-values.yaml \
  --set identity.issuer.scheme=kubernetes.io/tls \
  --set installNamespace=false --set linkerdVersion=stable-2.10.0 \
  -n linkerd --version 2.10.0
```

### Logs, error output, etc
After deployment yaml file snippet.

```
      containers:
      - args:
        - sp-validator
        - -log-level=info
        - -log-format=plain
        image: choreocontrolplane.azurecr.io/linkerd/controller:stable-2.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 9997
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: sp-validator
        ports:
        - containerPort: 8443
          name: sp-validator
          protocol: TCP
        - containerPort: 9997
          name: admin-http
          protocol: TCP
        readinessProbe:
          failureThreshold: 7
          httpGet:
            path: /ready
            port: 9997
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          runAsUser: 2103
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/linkerd/tls
          name: tls
          readOnly: true
```

#### `linkerd check` output

```text
your output here ...
```

### Environment

- Kubernetes Version:  1.19.11
- Cluster Environment: (GKE, AKS, kops, ...)
- Host OS: Linux
- Linkerd version: 2.10.0

### Possible solution
Helm chart should support disable of privilege escalation containers.
