### ISSUE TITLE
Disabling mTLS via annotation does not work

### ISSUE THREAD

**Issue by rdavyd** [linkerd/linkerd2#7479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the issue?

I want to disable using mTLS between all workloads. I found in documentation that it can be done via `config.linkerd.io/disable-identity` annotation.
Created separate POD and Deployment both with linkerd sidecars and tcpdumped traffic from separate POD to POD of deployment and it was still encrypted.

### How can it be reproduced?

1. Create resources:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: test-linkerd
  annotations:
    linkerd.io/inject: enabled
    config.linkerd.io/disable-identity: ""
spec:
  containers:
  - image: amouat/network-utils:latest
    imagePullPolicy: IfNotPresent
    command:
    - tail
    - -f
    - /dev/null
    name: test
  securityContext:
    fsGroup: 64001
    runAsUser: 64001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-linkerd
spec:
  selector:
    matchLabels:
      app: nginx-linkerd
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-linkerd
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/disable-identity: ""
    spec:
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.20
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: cache
          mountPath: /var/cache/nginx
      securityContext:
        fsGroup: 64001
        runAsUser: 64001
        runAsGroup: 64001
      volumes:
      - name: cache
        emptyDir:
          sizeLimit: 40Mi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-linkerd
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nginx-linkerd
```
2. kubectl exec into `test-linkerd` POD and `curl http://nginx-linkerd:8080`

### Logs, error output, etc

Traffic is encrypted in dump:
![image](https://user-images.githubusercontent.com/57534322/146344305-b2dbe8c6-07b7-430e-8a67-45aa9733d30e.png)

### output of `linkerd check -o short`

```text
Linkerd core checks
===================


Status check results are √
```

### Environment

- k8s version: 1.21.6
- env: On premise
- OS: Ubuntu 20.04
- CNI: kube-router
- linkerd version: 2.11.1 (non-HA) + linkerd-cni 2.11.1 (both installed via helm)
