### ISSUE TITLE
Issue with ExternalName services

### ISSUE THREAD

**Issue by jondlm** [linkerd/linkerd2#748]
I recently tried running conduit against our kubernetes cluster running locally on minikube and ran into an issue where the conduit proxy is returning a 500 for requests that succeed without the proxy in place. I've spent some time coming up with a minimal repro case and I believe I've determined that the conduit proxy doesn't correctly handle services that use an `externalName` to point to a service in a different namespace.

To start, this is the error I'm seeing in the logs for the `conduit-proxy` container that sits alongside my app:
```
INFO conduit_proxy using controller at HostAndPort { host: DnsName("proxy-api.conduit.svc.cluster.local"), port: 8086 }
INFO conduit_proxy routing on V4(127.0.0.1:4140)
INFO conduit_proxy proxying on V4(0.0.0.0:4143) to None
INFO conduit_proxy::transport::connect "controller-client", DNS resolved DnsName("proxy-api.conduit.svc.cluster.local") to 10.109.40.159
ERR! conduit_proxy turning operation timed out after Duration { secs: 10, nanos: 0 } into 500
```

## Versions
| thing | version |
| -- | -- |
| conduit client | v0.3.1 |
| conduit server | v0.3.1 |
| kubernetes | v1.9.0 |
| minikube | v0.25.0 |

## Minimal repro

I start by applying the following resources to my cluster. Basically, I've got `app1`, which lives in `namespace`, that will read the `APP2_HOST` environment variable to determine where to make calls under the hood to `app2` which lives in `namespace2`.
```
# ------------------------------------------------------------------------------
# Namespaces
# ------------------------------------------------------------------------------
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace1

---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace2

# ------------------------------------------------------------------------------
# Services
# ------------------------------------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: app1
  namespace: namespace1
spec:
  selector:
    app: app1
  ports:
  - name: http
    port: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: namespace1
spec:
  type: ExternalName
  externalName: app2.namespace2.svc.cluster.local

---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: namespace2
spec:
  ports:
  - port: 8000
  selector:
    app: app2

# ------------------------------------------------------------------------------
# Deployments
# ------------------------------------------------------------------------------
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: namespace1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      namespace: namespace1
      labels:
        app: app1
    spec:
      containers:
      - name: name
        image: jondlm/app1:latest
        env:
        - name: APP2_HOST
          value: app2:8000
        ports:
        - containerPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: namespace2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      namespace: namespace2
      labels:
        app: app2
    spec:
      containers:
      - name: name
        image: citizenstig/httpbin
        ports:
        - containerPort: 8000
```

Below is the source code for `app1`. It basically just calls `app2` and returns that response.
```
package main

import (
	"fmt"
	"io/ioutil"
	"net/http"
	"os"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, req *http.Request) {
		r, err := http.Get(fmt.Sprintf("http://%s%s", os.Getenv("APP2_HOST"), req.URL.Path))
		if err != nil {
			return
		}
		defer r.Body.Close()

		body, _ := ioutil.ReadAll(r.Body)
		w.WriteHeader(r.StatusCode)
		w.Write(body)
	})
	fmt.Println("listening on port 8000")
	http.ListenAndServe("0.0.0.0:8000", nil)
}
```

`app2` is the same thing that runs http://httpbin.org. It just returns some JSON.

So, after all that stuff is running in my cluster, I run the following to see the request succeeds:
```
$ kubectl -n namespace1 port-forward $(kubectl -n namespace1 get pod -l app=app1 -o jsonpath='{.items[0].metadata.name}') 8000:8000
Forwarding from 127.0.0.1:8000 -> 8000
```

```
$ time curl -v localhost:8000/get
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /get HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Wed, 11 Apr 2018 23:19:22 GMT
< Content-Length: 197
< Content-Type: text/plain; charset=utf-8
<
{
  "args": {},
  "headers": {
    "Accept-Encoding": "gzip",
    "Host": "app2:8000",
    "User-Agent": "Go-http-client/1.1"
  },
  "origin": "172.17.0.25",
  "url": "http://app2:8000/get"
}
* Connection #0 to host localhost left intact
curl -v localhost:8000/get  0.00s user 0.00s system 29% cpu 0.026 total
```

As you can see, that call works. Next I inject the conduit proxy (lines 57-81 is the `app1` deployment):
```
$ cat kubernetes.yaml | sed -n 57,81p | conduit inject - | kubectl apply -f -
deployment "app1" configured
```

After that proxy has joined the mesh successfully, I again forward the same port and attempt the call again:
```
$ time curl -v localhost:8000/get
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /get HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Date: Wed, 11 Apr 2018 23:13:23 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
curl -v localhost:8000/get  0.00s user 0.01s system 0% cpu 10.038 total
```

This time you can see the call fails after about 10 seconds. If I make the following change to the `app1` deployment to go directly to `app2.namespace2` the call will again succeed.
```
diff --git a/kubernetes.yaml b/kubernetes.yaml
index c1592ca..e595d0a 100644
--- a/kubernetes.yaml
+++ b/kubernetes.yaml
@@ -76,7 +76,7 @@ spec:
         image: jondlm/app1:latest
         env:
         - name: APP2_HOST
-          value: app2:8000
+          value: app2.namespace2:8000
         ports:
```

So, this leads me to the conclusion that conduit is choking on the `app2` service that lives in `namespace1` that is an `externalName` to `app2.namespace2.svc.cluster.local`.

Thank you for you time! Looking forward to being able to really kick the tires on conduit.

**Comment by olix0r** [comment]
@jondlm thank you for this outstanding report!

To confirm that I understand the issue: your application, in _namespace1_, is sending a request with `Host: app2`; and `app2.namespace1` is an `ExternalName` refering `app2.namespace2.svc.cluster.local`. And, when the proxy tries to route such a request, it fails with a 500 after 10 seconds.

This sounds like a problem with our service discovery service. There are a number of fixes on master (such as for #155) that improve service discovery behavior.  If you're feeling especially adventurous, you can try to run master off of, for instance, a docker tag like `git-259fdcd1`.

For example:
```
conduit install --conduit-version=git-259fdcd1 | ...
conduit inject --conduit-version=git-259fdcd1 k8s.yml | ...
```

In the meantime, we can try to reproduce this behavior ourselves to debug further.

Thanks again for trying Conduit and especially for taking the time to write a detailed issue!

**Comment by olix0r** [comment]
It does appear that this issue is resolved on master.  Let me describe how I tested this:

1. start docker-for-mac with kubernetes enabled
2. Install conduit: `conduit install -v git-259fdcd1`
3. Install the emojivoto app in a test namespace, with conduit: `curl https://raw.githubusercontent.com/runconduit/conduit-examples/master/emojivoto/emojivoto.yml | conduit inject - | kubectl apply -f -`. 
4. Once that starts, disable the traffic generator so we know what we're looking at: `kubectl delete deploy/vote-bot -n emojivoto`

At this point, the `emojivoto` namespace is populated with several services:
```
NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/emoji    1         1         1            1           5d
deploy/voting   1         1         1            1           5d
deploy/web      1         1         1            1           5d

NAME                   DESIRED   CURRENT   READY     AGE
rs/emoji-6676787fcd    0         0         0         5d
rs/emoji-6c694694bb    0         0         0         5d
rs/emoji-cb55477c4     1         1         1         13m
rs/voting-56c55b5c7b   0         0         0         5d
rs/voting-7c4948f5cb   1         1         1         13m
rs/voting-7f6d846b56   0         0         0         5d
rs/web-59956dc84d      0         0         0         5d
rs/web-5fcbcd8dd       1         1         1         13m
rs/web-794d7676d4      0         0         0         5d

NAME            AGE
deploy/emoji    5d
deploy/voting   5d
deploy/web      5d

NAME                   AGE
rs/emoji-6676787fcd    5d
rs/emoji-6c694694bb    5d
rs/emoji-cb55477c4     13m
rs/voting-56c55b5c7b   5d
rs/voting-7c4948f5cb   13m
rs/voting-7f6d846b56   5d
rs/web-59956dc84d      5d
rs/web-5fcbcd8dd       13m
rs/web-794d7676d4      5d

NAME                         READY     STATUS    RESTARTS   AGE
po/emoji-cb55477c4-8gfgb     2/2       Running   0          13m
po/voting-7c4948f5cb-x4rqr   2/2       Running   1          13m
po/web-5fcbcd8dd-626fn       2/2       Running   0          13m

NAME             TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
svc/emoji-svc    ClusterIP      None            <none>        8080/TCP       5d
svc/voting-svc   ClusterIP      None            <none>        8080/TCP       5d
svc/web-svc      LoadBalancer   10.99.131.238   localhost     80:30994/TCP   5d
```

4. Then, I created an application instance in the `bot` namespace.  This namespace includes the `emojivoto` ExternName Service.
```
NAME           DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/voter   1         1         1            1           9m

NAME                  DESIRED   CURRENT   READY     AGE
rs/voter-694667bb85   0         0         0         9m
rs/voter-cfdfc8859    1         1         1         5m

NAME           AGE
deploy/voter   9m

NAME                  AGE
rs/voter-694667bb85   9m
rs/voter-cfdfc8859    5m

NAME                       READY     STATUS    RESTARTS   AGE
po/voter-cfdfc8859-qj59s   2/2       Running   0          5m

NAME            TYPE           CLUSTER-IP   EXTERNAL-IP                           PORT(S)   AGE
svc/emojivoto   ExternalName   <none>       web-svc.emojivoto.svc.cluster.local   <none>    9m
```

I see stats on the dashboard at this point, but to confirm it manually, I logged into the pod:

```
:; kubectl -n bot exec -c vote-bot $(kubectl get pods --no-headers -n bot |awk '{print $1}') -i -t bash
root@voter-cfdfc8859-qj59s:/# curl -sv http://emojivoto/ -o /dev/null
* Hostname was NOT found in DNS cache
*   Trying 10.99.131.238...
* Connected to emojivoto (10.99.131.238) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: emojivoto
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: text/html
< date: Thu, 12 Apr 2018 00:31:12 GMT
< content-length: 560
< 
{ [data not shown]
* Connection #0 to host emojivoto left intact
```

🎉 🎉 🎉 

So, it seems to me that we've fixed this on master.  It would be helpful, though, to get confirmation that my reproduction is accurate.

We're just wrapping up the 0.4 release, so I'd expect a fix out in the coming days.

---

Appendix:

bot.yml:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: bot

---
apiVersion: v1
kind: Service
metadata:
  name: emojivoto
  namespace: bot
spec:
  type: ExternalName
  externalName: web-svc.emojivoto.svc.cluster.local

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: voter
  namespace: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: voter
    spec:
      containers:
      - command:
        - emojivoto-vote-bot
        env:
        - name: WEB_HOST
          value: emojivoto
        image: buoyantio/emojivoto-web:v3
        name: vote-bot
```
