### ISSUE TITLE
`linkerd multicluster link` command includes non-unique rolebinding

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#7496]
### What is the issue?

When running `linkerd multicluster link` for the `foo` cluster, it creates the following resources:

```
secret/cluster-credentials-foo
clusterrole.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-foo
clusterrolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-foo
role.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-foo
rolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-foo
serviceaccount/linkerd-service-mirror-foo
deployment.apps/linkerd-service-mirror-foo
rolebinding.rbac.authorization.k8s.io/multicluster-link-psp
service/probe-gateway-foo
```

Note that all of the resources except `multicluster-link-psp` include the `-foo` suffix. This means that if I run `linkerd multicluster link` a second time to link a different cluster, the second invocation is going to produce an identical `multicluster-link-psp` rolebinding, which clobbers the first rolebinding.

### How can it be reproduced?

First install one multicluster link:

```
$ linkerd --context aks-viz multicluster link --cluster-name foo | kubectl apply -f -
secret/cluster-credentials-foo created
clusterrole.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-foo created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-foo created
role.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-foo created
rolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-foo created
serviceaccount/linkerd-service-mirror-foo created
deployment.apps/linkerd-service-mirror-foo created
rolebinding.rbac.authorization.k8s.io/multicluster-link-psp created
service/probe-gateway-foo created
```

Then install a second one with a different cluster name:

```
$ linkerd --context aks-viz multicluster link --cluster-name bar | kubectl apply -f -
secret/cluster-credentials-bar created
link.multicluster.linkerd.io/bar created
clusterrole.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-bar created
clusterrolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-access-local-resources-bar created
role.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-bar created
rolebinding.rbac.authorization.k8s.io/linkerd-service-mirror-read-remote-creds-bar created
serviceaccount/linkerd-service-mirror-bar created
deployment.apps/linkerd-service-mirror-bar created
rolebinding.rbac.authorization.k8s.io/multicluster-link-psp configured
service/probe-gateway-bar created
```

Note this line:

```
rolebinding.rbac.authorization.k8s.io/multicluster-link-psp configured
```

### Logs, error output, etc

@alpeb also points out the the rolebinding itself has an issue. Here's the rolebinding:

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multicluster-link-psp
  namespace: linkerd-multicluster
  labels:
    linkerd.io/extension: multicluster
    namespace: linkerd-multicluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp
subjects:
- kind: ServiceAccount
  name: linkerd-service-mirror-dive-viz
  namespace: linkerd-multicluster
```

> Also, `roleRef.name` is pointing to `psp` but that's not defined. Should be `linkerd-psp` which is the name of the `PodSecurityPolicy` resource declared in the `linkerd-control-plane` chart.

### output of `linkerd check -o short`

```text
Status check results are √
```

### Environment

- Kubernetes version: v1.21.1
- Cluster Environment: AKS
- Linkerd version: edge-21.12.3

### Possible solution

Add a `-{clusterName}` suffix to the role binding, fix the role name in the rolebinding itself.
