### ISSUE TITLE
Server CRD definition causes empty label selector to be rejected on apply

### ISSUE THREAD

**Issue by aw185176** [linkerd/linkerd2#7904]
### What is the issue?

I need to apply the configuration described by https://linkerd.io/2.11/tasks/restricting-access/#setting-a-default-policy from Go code, specifically the Server object which matches all pods so that I can grant access to the admin port, per #7050:

```
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: emojivoto
  name: admin
spec:
  port: linkerd-admin
  podSelector:
    matchLabels: {} # every pod
  proxyProtocol: HTTP/1
```

The typical way to provide an empty label selector would be `&metav1.LabelSelector{}`, but the CRD schema for Server objects enforces that one of either `matchLabels` or `matchExpressions` _must_ exist.  However, because metav1.LabelSelector uses `omitempty` on MatchLabels/MatchExpressions providing an empty map to emulate the above YAML configuration results in the field being dropped entirely, which causes the Linkerd webhook to reject the object.

I believe this makes it impossible to actually implement the above object definition in Go today.  Note that the definition used for LabelSelectors in resources like `NetworkPolicy` does not look the same, if you check the OpenAPI schema in kubernetes/kubernetes 

### How can it be reproduced?

Try to write Go code which creates the example object described above, pulled from official L5d docs.

### Logs, error output, etc

```
"error":"failed to apply probe policy resources: Server/testing/admin dry-run failed, reason: Invalid, error: Server.policy.linkerd.io \"admin\" is invalid: [<nil>: Invalid value: \"\": \"spec.podSelector\" must validate one and only one schema (oneOf). Found none valid, spec.podSelector.matchExpressions: Required value]",
```

### output of `linkerd check -o short`

N/A

### Environment

Kind 1.2x

### Would you like to work on fixing this bug?

no

**Comment by alpeb** [comment]
Thanks @aw185176 for the report :+1: 

@olix0r This would mean creating a new `Server` CRD version with this removed from the `podSelector` spec:
```yaml
oneOf:
 - required: [matchExpressions]
 - required: [matchLabels]
```
In `NetworkPolicy`, `matchExpressions` and `matchLabels` are ANDed, matching all objects if none is provided. Should we follow suit?
