### ISSUE TITLE
Nginx ingress controller daemonSet not injecting pods

### ISSUE THREAD

**Issue by haim-ari** [linkerd/linkerd2#7949]
### What is the issue?

Nginx ingress controller daemonSet not injecting pods

The nginx-ingress-controller is injected with:

`linkerd.io/inject:enabled`

In the linkerd proxy injector I see:

```
time="2022-02-23T14:17:26Z" level=info msg="skipped pod/file-exporter-onemata-dl8tb-1666065251: neither the namespace nor the pod have the annotation \"linkerd.io/inject:enabled\""
```

Pods are missing linkerd proxy 

### How can it be reproduced?

* Install Ingress as daemonSet with hostNetwork: "true"
* Set up linkerd

### Logs, error output, etc

```
time="2022-02-23T14:17:26Z" level=info msg="skipped pod/file-exporter-onemata-dl8tb-1666065251: neither the namespace nor the pod have the annotation \"linkerd.io/inject:enabled\""
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================


Status check results are √

Linkerd extensions checks
=========================


Status check results are √


Status check results are √


Status check results are √
```

### Environment

RKE (Rancher 2.5.9)
k8s `v1.20.8`
Ingress Helm Chart version: `3.12.0`
Linkerd `2.11`

Ingress pod annotation in Flux Helm release (Helm values)
```yaml
      podAnnotations:
        linkerd.io/inject: enabled
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
```

```yaml
      hostNetwork: "true"
      kind: DaemonSet
```

**Comment by olix0r** [comment]
> Install Ingress as daemonSet with hostNetwork: "true"

Unfortunately, the Linkerd sidecar cannot currently be added to pods that use `hostNetwork: "true"` because the iptables/cni initialization cannot be isolated to the pod's network.

**Comment by haim-ari** [comment]
Ingresses are behind NLB(L4) in our network.
Configured the following and Linkerd Proxies Injected OK now:

```yaml

      hostNetwork: "false"
      kind: DaemonSet
      service:
        external:
          enabled: true
        type: "NodePort"
        nodePorts:
          http: 32080
          https: 32443
```

```
 initContainerStatuses:
  - containerID: docker://5e57bfda104d879a6a12c9683c581293481309fb8de5ed6ed004044a4083b88c
    image: cr.l5d.io/linkerd/proxy-init:v1.4.0
    imageID: docker-pullable://cr.l5d.io/linkerd/proxy-init@sha256:60d12fbb0b4a53962a5c2a59b496b3ee20052d26c0c56fd2ee38fd7fae62146e
    lastState: {}
    name: linkerd-init
    ready: true
    restartCount: 0
```
