### ISSUE TITLE
Outbound proxy for multicluster requests stuck in fail-fast

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#8143]
### What is the issue?

I'm running linkerd edge-22.3.3 with the multicluster extension in two clusters on AKS. I'm using [slow-cooker](https://github.com/BuoyantIO/slow_cooker) to target a local deployment in one cluster, and that deployment then makes a cross-cluster request to a deployment in the second cluster. Without making any changes in the source or destination cluster, I'm seeing all requests start to fail after the workloads have been running for 2-60 minutes.

From the slow-cooker logs, it seems like we're hitting some sort of 3-second timeout, after which all requests fail:

```
2022-03-18T01:37:11Z   78    530/70/0 600 100% 30s   4 [  5   8  10   16 ]   16      0 
2022-03-18T01:37:41Z   79    542/58/0 600 100% 30s   4 [  5   8  11   16 ]   16      0 
2022-03-18T01:38:11Z   80    166/378/0 600  90% 30s   3 [  5   9  11 3003 ] 3003      0 
2022-03-18T01:38:41Z   81      0/600/0 600 100% 30s   3 [  4   8  11   16 ]   16      0 
2022-03-18T01:39:11Z   82      0/600/0 600 100% 30s   3 [  5   9  13   15 ]   15      0 
```

In the proxy logs of the pod that's making the cross-cluster request, I see thousands of log lines related to fail-fast:

```
[ 63716.245198s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:51894}: linkerd_app_core::errors::respond: Request failed error=HTTP Balancer service in fail-fast
```

Once it gets into this state, it never recovers without intervention. If I stop traffic for a few minutes and then restart it, requests succeed again but it eventually ends up back in fail fast.

### How can it be reproduced?

I've only been able to repro the issue in AKS with the latest linkerd edge. I have another source cluster running linkerd stable that's not showing the issue. And I have a k3d cluster with the latest linkerd edge that's also not showing the issue.

To repro:

Setup two clusters with the same trust root on AKS. Install the latest linkerd edge, linkerd multicluster extension, and link the clusters together. Then inject and start the traffic and hello deployments in the first cluster:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: service
        image: buoyantio/helloworld:0.1.6
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "-addr=:7777"
        - "-text=Hello"
        - "-target=world-west:7778"
        ports:
        - name: http
          containerPort: 7777
        securityContext:
          runAsNonRoot: true
          runAsUser: 007
        readinessProbe:
          tcpSocket:
            port: 7777
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
              - cat
---
apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  selector:
    app: hello
  clusterIP: None
  ports:
  - name: http
    port: 7777
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic
  template:
    metadata:
      labels:
        app: traffic
    spec:
      containers:
      - name: slow-cooker
        image: buoyantio/slow_cooker:1.3.0
        args:
        - "-concurrency=4"
        - "-interval=30s"
        - "-noLatencySummary"
        - "-qps=5"
        - "http://hello:7777"
```

And inject and start the world deployment in the other cluster:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
      - name: service
        image: buoyantio/helloworld:0.1.6
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "-addr=:7778"
        - "-text=World"
        - "-failure-rate=0.1"
        ports:
        - name: http
          containerPort: 7778
        securityContext:
          runAsNonRoot: true
          runAsUser: 007
---
apiVersion: v1
kind: Service
metadata:
  name: world
  labels:
    mirror.linkerd.io/exported: "true"
spec:
  selector:
    app: world
  clusterIP: None
  ports:
  - name: http
    port: 7778
```

Make sure you change the `world-west` target service name to match the mirrored world service name in your cluster.

### Logs, error output, etc

Here are the info logs from a proxy that has entered fail fast:

```
[ 66188.822754s]  WARN ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}: linkerd_stack::failfast: HTTP Logical entering failfast after 3s
[ 66188.822800s]  WARN ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}: linkerd_stack::failfast: HTTP Balancer entering failfast after 3s
[ 66188.822857s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:44690}: linkerd_app_core::errors::respond: Request failed error=HTTP Logical service in fail-fast
[ 66188.823011s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:44670}: linkerd_app_core::errors::respond: Request failed error=HTTP Logical service in fail-fast
[ 66188.823070s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:44700}: linkerd_app_core::errors::respond: Request failed error=HTTP Logical service in fail-fast
[ 66188.823170s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:44702}: linkerd_app_core::errors::respond: Request failed error=HTTP Logical service in fail-fast
[ 66188.827866s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}: linkerd_stack::failfast: HTTP Logical service has recovered
[ 66188.827905s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:44902}: linkerd_app_core::errors::respond: Request failed error=HTTP Balancer service in fail-fast
[ 66188.827978s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:44904}: linkerd_app_core::errors::respond: Request failed error=HTTP Balancer service in fail-fast
[ 66188.828024s]  INFO ThreadId(01) outbound:server{orig_dst=10.0.159.173:7778}:rescue{client.addr=10.244.1.8:44906}: linkerd_app_core::errors::respond: Request failed error=HTTP Balancer service in fail-fast
```

And here's a full minute's worth of linkerd debug logs from the minute where all traffic stops:

[linkerd.txt](https://github.com/linkerd/linkerd2/files/8346336/linkerd.txt)

### output of `linkerd check -o short`

```
$ linkerd check -o short --context aks-dive-staging
Status check results are √
```

### Environment

```
$ kubectl version --short
Client Version: v1.22.5
Server Version: v1.21.2
```

```
$ linkerd version --short --context aks-dive-staging
edge-22.3.3
edge-22.3.3
```

```
$ kubectl get nodes -owide
VERSION    OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
v1.21.2    Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.8+azure
v1.21.2    Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.8+azure
v1.21.2    Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.8+azure
v1.21.2    Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.8+azure
v1.21.2    Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.8+azure
v1.21.2    Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.8+azure
v1.21.2    Ubuntu 18.04.5 LTS   5.4.0-1056-azure   containerd://1.4.8+azure
```
