### ISSUE TITLE
AKS v1.22 linkerd-cni fails to start without `privileged: true` due to permission denied error reading /host/etc/cni/net.d/10-azure.conflist

### ISSUE THREAD

**Issue by tspearconquest** [linkerd/linkerd2#8209]
### What is the issue?

We upgraded our cluster in Azure to v1.22.6 yesterday and another today, both displayed the same issue.

When linkerd-cni attempts to start up, it receives a permission denied error:

### How can it be reproduced?

Install linkerd-cni and linkerd to a cluster running Kubernetes v1.19. Then upgrade the cluster to v1.20, followed by v1.21, followed by v1.22. Wait for the pods to start coming up on v1.22 and look at the linkerd-cni namespace.

### Logs, error output, etc

```
$ kubectl logs po/linkerd-cni-6fbs9 -n linkerd-cni -p
Wrote linkerd CNI binaries to /host/opt/cni/bin
Using CNI config template from CNI_NETWORK_CONFIG environment variable.
      "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
      "k8s_api_root": "https://<redacted>:__KUBERNETES_SERVICE_PORT__",
CNI config: {
  "name": "linkerd-cni",
  "type": "linkerd-cni",
  "log_level": "info",
  "policy": {
      "type": "k8s",
      "k8s_api_root": "https://<redacted>:443",
      "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
  },
  "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/ZZZ-linkerd-cni-kubeconfig"
  },
  "linkerd": {
    "incoming-proxy-port": 4143,
    "outgoing-proxy-port": 4140,
    "proxy-uid": 2102,
    "ports-to-redirect": [],
    "inbound-ports-to-ignore": ["4191","4190"],
    "simulate": false,
    "use-wait-flag": false
  }
}
jq: error: Could not open file /host/etc/cni/net.d/10-azure.conflist: Permission denied
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-existence
-----------------
× control plane pods are ready
    No running pods for "linkerd-destination"
    see https://linkerd.io/2.11/checks/#l5d-api-control-ready for hints

Status check results are ×

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-f9ddcc77d-rpb95 pod
    see https://linkerd.io/2.11/checks/#l5d-viz-pods-injection for hints
× viz extension proxies are healthy
    No "linkerd-proxy" containers found in the "linkerd" namespace
    see https://linkerd.io/2.11/checks/#l5d-viz-proxy-healthy for hints
```

### Environment

- Kubernetes Version: 1.22.6
- Cluster environment: AKS
- Host OS: Ubuntu 18.04
- Linkerd Version: stable-2.11.2

### Additional context

We obtained a shell on one of the pods and found that the ownership of the file in question is UID and GID 1001, and the permissions are 0600. The CNI seems to be able to create its own file but unable to read or write to the 10-azure.conflist file.

```
$ kubectl exec -it po/linkerd-cni-cv5zv -n linkerd-cni -- /bin/sh
# ls -ld /host
drwxr-xr-x 4 root root 4096 Apr  5 17:47 /host
# ls -ld /host/etc
drwxr-xr-x 3 root root 4096 Apr  5 17:47 /host/etc
# ls -ld /host/etc/cni
drwxr-xr-x 3 root root 4096 Apr  5 17:47 /host/etc/cni
# ls -ld /host/etc/cni/net.d
drwxr-xr-x 2 root root 4096 Apr  5 16:25 /host/etc/cni/net.d
# ls -l /host/etc/cni/net.d/
total 12
-rw------- 1 1001  1001  375 Apr  5 17:59 10-azure.conflist
-rw------- 1 root 65532 4138 Apr  5 17:45 ZZZ-linkerd-cni-kubeconfig
```

We have customized the linkerd installation using kustomize, so below is the partial deployment.yaml with the changes that get incorporated by kustomize. In the below, if we change `allowPrivilegeEscalation` and `privileged` to `true` then linkerd-cni starts up, but otherwise it gets the error above.

```
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: linkerd-cni
  namespace: linkerd-cni
  annotations:
    ignore-check.kube-linter.io/host-network: Linkerd CNI requires access to the host network
    ignore-check.kube-linter.io/run-as-non-root: Linkerd CNI requires root access
spec:
  template:
    metadata:
      labels:
        app: linkerd-cni
    spec:
      imagePullSecrets:
      - name: gitlab-registry
      containers:
      - name: install-cni
        imagePullPolicy: Always
        image: <privately hosted image>
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 65532
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: "10m"
            memory: "20Mi"
          requests:
            cpu: "10m"
            memory: "20Mi"
```
