### ISSUE TITLE
NGINX ingress controller shortly returns 502 on graceful shutdown, only when meshed

### ISSUE THREAD

**Issue by SansDK** [linkerd/linkerd2#8214]
### What is the issue?

We are running into an issue when meshing our NGINX ingress controller. We experience a fraction of downtime when we restart our ingress controller pods (one by one, we currently have 2 replicas). We put constant load on a service that we deployed with a linkerd proxy during the restarts to verify if there is any downtime. What is interesting is that this downtime did not happen when we tested this same scenario without meshing the NGINX ingress controller pods.

There are some more details in [this](https://linkerd.slack.com/archives/C89RTCWJF/p1648461869338559) Linkerd Slack thread.

### How can it be reproduced?

Repro steps:

1. Launch Docker Desktop for Windows and enable the Kubernetes feature.
2. Follow Linkerd quick start guide to install Linkerd locally. (https://linkerd.io/2.11/getting-started/)
3. Copy the content of the nginx ingress controller yaml from: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml and paste in a local file.
4. Modify the file. Add the `linkerd.io/inject: enabled` annotation to the `ingress-nginx-controller` Deployment under `spec.template.metadata.annotations`
5. Modify the file. Add `spec.replicas: 2` to the `ingress-nginx-controller` Deployment
6. Deploy the nginx ingress controller with `kubectl apply -f {filename}.yaml`
7. Deploy a test app, for example:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: frontend
          image: httpd
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
  selector:
    app: webserver
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    linkerd.io/inject: enabled
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  name: http
```
8. Check if the app and ingress controller work on `http://localhost/`
9. Execute: `while sleep 0.2; do curl http://localhost/; done`. This should constantly return `<html><body><h1>It works!</h1></body></html>`
10. Kill one nginx pod with `kubectl delete pod {pod} -n ingress-nginx --grace-period=60`
11. You should see `curl: (52) Empty reply from server` in the curl output once.
	_If you don't: wait untill both nginx pods are ready again, and try again. You should see this error within a few tries (2-3x) because traffic is balanced across replicas and you might get lucky :)._
12. Stop the curl while loop

**To verify that this has _something_ to do with the Linkerd proxy on the nginx ingress controller:**
13. Remove the Linkerd inject annotation added in step 4, and redeploy the nginx ingress controller
14. Wait for all nginx pods to be ready again, and then follow steps 9 and 10 again.
	Try this as many times as you like, you will never see the error `curl: (52) Empty reply from server`.

### Logs, error output, etc

[Linkerd proxy logs when shutting down together with a terminating ingress controller pod](https://gist.github.com/SansDK/3e9a51cb6ecdbde5a6e426e2b4db0cab)

[Linkerd proxy logs when starting up together with a new ingress controller pod](https://gist.github.com/SansDK/ed6f32bc471bbd36a4b0f550e0f96cdc)

### output of `linkerd check -o short`

**_control-plane-version_**

can retrieve the control plane version
control plane is up-to-date

**_kubernetes-api_**

can query the Kubernetes API

**_kubernetes-version_**

is running the minimum Kubernetes API version

**_linkerd-config_**

control plane Namespace exists
control plane ClusterRoles exist
control plane ClusterRoleBindings exist
control plane ServiceAccounts exist
control plane CustomResourceDefinitions exist
control plane MutatingWebhookConfigurations exist
control plane ValidatingWebhookConfigurations exist

**_linkerd-existence_**

'linkerd-config' config map exists
heartbeat ServiceAccount exist
control plane replica sets are ready
no unschedulable pods
control plane pods are ready

**_linkerd-version_**

can determine the latest version

### Environment

Kubernetes version: 1.22
Cluster environment: AKS
Linkerd version: 2.11.1
