### ISSUE TITLE
Cannot install into existing namespace (helm chart 2.11.1) via Flux

### ISSUE THREAD

**Issue by petrmac** [linkerd/linkerd2#8247]
### What is the issue?

The helm chart cannot install into existing namespace. It complains with:
`Helm install failed: rendered manifests contain a resource that already exists. Unable to continue with install: Namespace "linkerd" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "linkerd"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "linkerd"`

This occurs despite I have all required annotations in place
e.g.:
```
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
  labels:
    app.kubernetes.io/managed-by: "Helm"
    config.linkerd.io/admission-webhooks: "disabled"
    kubernetes.io/metadata.name: "linkerd"
    kustomize.toolkit.fluxcd.io/name: "infrastructure"
    kustomize.toolkit.fluxcd.io/namespace: "flux-system"
    linkerd.io/control-plane-ns: "linkerd"
    linkerd.io/is-control-plane: "true"
    meta.helm.sh/release-namespace: "linkerd"
    meta.helm.sh/release-name: "linkerd"
```

Any suggestion is much appreciated!

### How can it be reproduced?

Deployed helm chart into existing namespace `linkerd`

### Logs, error output, etc

error above

### output of `linkerd check -o short`

N/A

### Environment

- Kubernetes: v1.22.6
- aks
