### ISSUE TITLE
Viz extension trying to get a "viz" namespace

### ISSUE THREAD

**Issue by pbrissaud** [linkerd/linkerd2#8460]
### What is the issue?

I installed linkerd and linkerd-viz with Helm through ArgoCD, everything works fine. But when I check the viz extension install, I get the error `namespace "viz" not found`. 

And when I use the option `-n linkerd-viz`, I get the same result. Even the `linkerd check` don't run the command anymore. 

I'm really confused right-now.

### How can it be reproduced?

Installing linkerd and linkerd-viz following the doc :  https://linkerd.io/2.11/overview/

I just added the automation of the rotation of the Webhook's TLS certificates : https://linkerd.io/2.11/tasks/automatically-rotating-webhook-tls-credentials/

### Logs, error output, etc

```text
❯ linkerd viz check
linkerd-viz
-----------
× linkerd-viz Namespace exists
    namespace "viz" not found
    see https://linkerd.io/2.11/checks/#l5d-viz-ns-exists for hints

Status check results are ×

❯ kubectl get deployments.apps -n linkerd-viz
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
metrics-api    1/1     1            1           65m
prometheus     1/1     1            1           65m
tap            1/1     1            1           65m
tap-injector   1/1     1            1           65m
web            1/1     1            1           65m
```

### output of `linkerd check -o short`

```text
❯ linkerd  check -o short
Linkerd core checks
===================

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2022-05-10T15:16:45Z
    see https://linkerd.io/2.11/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2022-05-10T15:16:45Z
    see https://linkerd.io/2.11/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints
‼ policy-validator cert is valid for at least 60 days
    certificate will expire on 2022-05-10T15:30:38Z
    see https://linkerd.io/2.11/checks/#l5d-policy-validator-webhook-cert-not-expiring-soon for hints

Status check results are √
```

### Environment

- Kubernetes version : 1.21
- Kubernetes distro : RKE
- Host: Ubuntu 18.04 LTS
- Linkerd Version : 2.11.2

**Comment by mateiidavid** [comment]
Hey @pbrissaud, just to confirm, you've installed viz through the default values. Doing `kubectl get namespaces` lists it there, as in my example?

```sh
:; kubectl get namespaces
NAME              STATUS   AGE
kube-system       Active   3d7h
default           Active   3d7h
kube-public       Active   3d7h
kube-node-lease   Active   3d7h
linkerd-cni       Active   3d7h
linkerd           Active   3d7h
linkerd-viz       Active   7h48m
```

It might be that Argo stripped some labels off the namespace object and that's why the CLI tool is confused. The most important label in this case is `linkerd.io/extension: viz`.

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    config.linkerd.io/proxy-await: enabled
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"config.linkerd.io/proxy-await":"enabled","linkerd.io/inject":"enabled"},"labels":{"linkerd.io/extension":"viz"},"name":"linkerd-viz"}}
    linkerd.io/inject: enabled
  creationTimestamp: "2022-05-09T09:44:59Z"
  labels:
    kubernetes.io/metadata.name: linkerd-viz
    linkerd.io/extension: viz
```

Would you kindly check your namespace object has the label on it? If it doesn't, try adding it, and then re-run through the checks :)
