### ISSUE TITLE
Multicluster automatic failover Active-Active service. 

### ISSUE THREAD

**Issue by nomis4u** [linkerd/linkerd2#8464]
### What problem are you trying to solve?

Assuming we have two k8s cluster running in active active mode which has same applications. 
As of now Linkerd multicluster automatic failover supports k8s service in active-passive mode. 
```
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
name: sample-svc
annotations:
  failover.linkerd.io/primary-service: sample-svc
labels:
  failover.linkerd.io/controlled-by: linkerd-failover
spec:
service: sample-svc
backends:
  - service: sample-svc
    weight: 1
  - service: sample-svc-remote
    weight: 0
```

In above yaml, we cannot keep weight of both the service to 1 because linkerd will automatically change the weights of "primary-service" to 1 and other service to 0. If we cannot have active-active service, during an automatic service failover all the other microservices which "sample-svc" contacts will also failover to one cluster which might not be ideal. 

Proposal is to have multicluster automatic failover to support active-active service so during a failover only that particular service will be moved to the other cluster. 

### How should the problem be solved?

Have a way in TrafficSpit to support active-active service so during any failover event only that particular service will get moved to other cluster and once the service recovers, come back to original state.

### Any alternatives you've considered?

No alternative considered.
