### ISSUE TITLE
Unable to expose a mirrored service using an Ingress

### ISSUE THREAD

**Issue by jeunii** [linkerd/linkerd2#8473]
### What is the issue?

I am trying to expose a mirrored service using an Ingress. My network flow looks like

<img width="421" alt="Screen Shot 2022-05-05 at 2 29 51 PM" src="https://user-images.githubusercontent.com/46089687/167862377-1d93b46f-4e62-4b63-b8f0-23c1f9a57e46.png">

I have a service running in cluster A `nexus`. 

```
kgs --context cluster-a -n cache
NAME    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                     AGE
nexus   ClusterIP   100.108.24.159   <none>        8484/TCP,443/TCP,8080/TCP   27d
```

I have mirrored it into Cluster B

```
kgs --context cluster-b -n cache
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                     AGE
nexus-shoot   ClusterIP   172.19.108.49   <none>        8484/TCP,443/TCP,8080/TCP   17h
```

Its endpoint is

```
k get ep --context gke-build-test -n cache
NAME          ENDPOINTS                                                           AGE
nexus-shoot   10.237.116.42:4143,10.237.116.42:4143,10.237.116.42:4143            17h
```

`10.237.116.42:4143` is the LinkerD Gateway IP:Port of cluster A !

I can communicate with this mirrored service from within cluster-b correctly

```
k exec -n default -it curl-injected-77b698f688-q6g8n -c curl -- curl -v http://nexus-shoot.cache:8080
*   Trying 172.19.108.49:8080...
* Connected to nexus-shoot.cache (172.19.108.49) port 8080 (#0)
> GET / HTTP/1.1
> Host: nexus-shoot.cache:8080
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< server: nginx/1.21.1
...
<

<!DOCTYPE html>
<html lang="en">
<head>
  <title>Nexus Repository Manager</title>
```

Now I want to access this mirrored service using an Ingress. My Ingress Controller is HA Proxy. My ingress object is

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: nexus-shoot.cxpt.only.sap
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nexus-shoot
            port:
              number: 8080
```

Once deployed, when I access `nexus-shoot.cxpt.only.sap`, I get

<img width="943" alt="Screen Shot 2022-05-11 at 9 38 38 AM" src="https://user-images.githubusercontent.com/46089687/167863311-a84524e2-9260-4a21-adfa-d7acc8c232e0.png">

Having a look at the GW logs of cluster A, I see

```
[165535.240649s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated client.addr=10.250.3.114:34012

[165537.332173s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated client.addr=100.104.11.37:33054
[165539.131723s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=direct connections must be mutually authenticated client.addr=100.104.6.158:36006
```

I noticed that traffic flows through the HA Proxy Ingress pods and they werent meshed, so I meshed the Ingress controller deployment

```
k get deployments.apps ingress-ctrl-kubernetes-ingress -o yaml | linkerd inject - | kubectl apply -f -
```

Looking at the logs of the linkerd-proxy of the ingress-ctrl pod, I noticed

```
[ 73131.189849s]  INFO ThreadId(01) outbound:server{orig_dst=10.237.116.42:4143}:rescue{client.addr=172.20.18.199:50872}: linkerd_app_core::errors::respond: Request failed error=connection error: client: Connection reset by peer (os error 104)
[ 73131.189891s]  INFO ThreadId(01) outbound:server{orig_dst=10.237.116.42:4143}: linkerd_app_outbound::http::proxy_connection_close: Received unmeshed response with l5d-proxy-connection set
```

I went ahead and did the following change in the pod template 

from

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-ctrl-kubernetes-ingress
  namespace: ingress-ctrl
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
```

to

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-ctrl-kubernetes-ingress
  namespace: ingress-ctrl
spec:
  template:
    metadata:
      annotations:
        linkerd.io/inject: ingress # <--- change
```

The above config does not allow the pod to come up and gives an error on the linkerd-proxy container

```
[    38.248563s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=ingress-mode routing is HTTP-only client.addr=172.20.4.111:44244
[    39.249449s]  INFO ThreadId(01) outbound: linkerd_app_core::serve: Connection closed error=ingress-mode routing is HTTP-only client.addr=172.20.4.111:44250
```

I went ahead and added the config

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-ctrl-kubernetes-ingress
  namespace: ingress-ctrl
spec:
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: "443" # <--- Added
```

The pod comes up but the issue is still the same. I still get a 502 Error.

Is this a bug or is this a config issue ? 

### How can it be reproduced?

Expose a mirrored service using an Ingress

### Logs, error output, etc

See above

### output of `linkerd check -o short`

```
linkerd check -o short
Status check results are √
```

### Environment

Kubernets version --> v1.20.15
Linkerd version --> 

```
linkerd version
Client version: stable-2.11.2
Server version: stable-2.11.2
```

**Comment by adleong** [comment]
Hi @jeunii 
As per https://linkerd.io/2.11/tasks/using-ingress/#haproxy, have you set the `haproxy.org/request-set-header` annotation on the Ingress resource?  Following those instructions, are you able to use HAProxy as a meshed ingress for local services, or do the problems only occur when routing to mirror services?

**Comment by jeunii** [comment]
Hello @adleong 

The issue occurs only when trying to route to a mirrored service. I am trying to access a mirrored service using an ingress.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: nexus-shoot.cxpt.only.sap
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nexus-shoot # <--- nexus service has been mirrored from shoot cluster
            port:
              number: 8080
```
