### ISSUE TITLE
injectCaFromSecret option no longer works

### ISSUE THREAD

**Issue by tchellomello** [linkerd/linkerd2#8488]
### What is the issue?

Whenever using the `injectCaFromSecret` deploying via `Helm` chart, the Chart does not work.
```bash
helm install linkerd2 --dry-run -f values.yaml linkerd/linkerd2                                                                                                                                                                                                 
Error: INSTALLATION FAILED: execution error at (linkerd2/templates/proxy-injector.yaml:36:28): If proxyInjector.externalSecret is true then you need to provide proxyInjector.caBundle
```

### How can it be reproduced?

1. Create a `values.yaml`
```yaml
# TOCA Linkerd Root CA
identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  [....SNIP....]
  -----END CERTIFICATE-----

cniEnabled: true

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
    issuanceLifetime: 24h0m0s

installNamespace: false

policyValidator:
  externalSecret: true
  injectCaFromSecret: linkerd/linkerd-policy-validator-k8s-tls

proxyInjector:
  externalSecret: true
  injectCaFromSecret: linkerd/linkerd-proxy-injector-k8s-tls
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - cert-manager
      - linkerd-cni

profileValidator:
  externalSecret: true
  injectCaFromSecret: linkerd/linkerd-sp-validator-k8s-tls
  namespaceSelector:
    matchExpressions:
    - key: config.linkerd.io/admission-webhooks
      operator: NotIn
      values:
      - disabled
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - kube-system
      - cert-manager
      - linkerd-cni
```
2. Run the helm chart command to install it
```bash
helm install linkerd2 --dry-run -f values.yaml linkerd/linkerd2                                                                                                                                                                                                 
Error: INSTALLATION FAILED: execution error at (linkerd2/templates/proxy-injector.yaml:36:28): If proxyInjector.externalSecret is true then you need to provide proxyInjector.caBundle
```

### Logs, error output, etc

```
Error: INSTALLATION FAILED: execution error at (linkerd2/templates/proxy-injector.yaml:36:28): If proxyInjector.externalSecret is true then you need to provide proxyInjector.caBundle
```

### output of `linkerd check -o short`

```
Error: INSTALLATION FAILED: execution error at (linkerd2/templates/proxy-injector.yaml:36:28): If proxyInjector.externalSecret is true then you need to provide proxyInjector.caBundle
```

### Environment

- Kubernetes Version: `v.1.23.5`
- Helm version `version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.18.1"}`
- Chart version `linkerd/linkerd2                  	2.11.2       	stable-2.11.2``
- 

### Possible solution

It only works if `caBundle` is specified in the `values.yaml`

### Would you like to work on fixing this bug?

yes
