### ISSUE TITLE
rfc: Allow `AuthorizationPolicy` to target `ServiceAccount` directly?

### ISSUE THREAD

**Issue by olix0r** [linkerd/linkerd2#8565]
Currently, we require that `AuthorizationPolicy` resources reference a `MeshTLSAuthentication` resource to authorize a pod by its service account. Like so:

```yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: linkerd-admin-metrics-viz
  namespace: emojivoto
spec:
    targetRef:
      ...
    requiredAuthenticationRefs:
      - kind: MeshTLSAuthentication
        name: linkerd-viz
---
apiVersion: policy.linkerd.io/v1alpha1
kind: MeshTLSAuthentication
metadata:
  name: linkerd-viz
  namespace: emojivoto
spec:
    identityRefs:
      - kind: ServiceAccount
        name: prometheus
        namespace: linkerd-viz
```

I think we can simplify this in many cases if we support referencing the `ServiceAccount` directly:

```yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: linkerd-admin-metrics-viz
  namespace: emojivoto
spec:
    targetRef:
      ...
    requiredAuthenticationRefs:
      - kind: ServiceAccount
        name: prometheus
        namespace: linkerd-viz
```

This is a more general assertion--we're requiring that the client _somehow_ used a service account to authenticate to the server. Whether that was using mesh TLS or not is an implementation detail (that could be changed in the future).

This feels like a nice quality-of-life improvement.

Thoughts?
