### ISSUE TITLE
Add admin endpoint that returns proxy environment variables and their values

### ISSUE THREAD

**Issue by jeremychase** [linkerd/linkerd2#9067]
### What problem are you trying to solve?

We have a need to see the current environment variables for running Linkerd proxies: while a pod spec includes most of the proxy's environment variables, this environment may include references that are not rendered until the container actually starts.

For example:
```yaml
      - name: _pod_sa
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: spec.serviceAccountName
      - name: LINKERD2_PROXY_IDENTITY_DIR
        value: /var/run/linkerd/identity/end-entity
      - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
        valueFrom:
          configMapKeyRef:
            key: ca-bundle.crt
            name: linkerd-identity-trust-roots
```

There's no reliable, non-racey way to know which value a pod is actually running with except to have the proxy expose its environment values.

### How should the problem be solved?

@zaharidichev Please reply with your thoughts on this.

### Any alternatives you've considered?

No, but we should ensure that the behavior of this proposed endpoint works correctly with #9022
