### ISSUE TITLE
Helm release seems broken at version 2.12

### ISSUE THREAD

**Issue by jancespivo** [linkerd/linkerd2#9320]
### What is the issue?

There is no helm charts with version 2.12.0. IMO it is mismatch of different kind of versions.
See current https://helm.linkerd.io/stable/index.yaml:
```
  linkerd-control-plane:
  - apiVersion: v2
    appVersion: stable-2.12.0
    created: "2022-08-23T20:59:53.601719658Z"
    ...
    urls:
    - https://helm.linkerd.io/stable/linkerd-control-plane-1.9.0.tgz
    version: 1.9.0
```

```
  linkerd2-cni:
  - apiVersion: v1
    appVersion: stable-2.12.0
    created: "2022-08-23T20:59:53.608957714Z"
    ...
    urls:
    - https://helm.linkerd.io/stable/linkerd2-cni-30.3.0.tgz
    version: 30.3.0
```

Thanks for a clarification!

### How can it be reproduced?

helm install linkerd-control-plane  -n linkerd linkerd/linkerd-control-plane --version 2.12.0

### Logs, error output, etc

Error: INSTALLATION FAILED: failed to download "linkerd/linkerd-control-plane" at version "2.12.0"

### output of `linkerd check -o short`

-

### Environment

-

### Would you like to work on fixing this bug?

no
