### ISSUE TITLE
[Helm] CrashLoopBackOff, if identiy issuer is not set (created external before)

### ISSUE THREAD

**Issue by tburschka** [linkerd/linkerd2#9508]
### What is the issue?

During a fresh helm setup the proxy-injector and linkerd-identity pods keep crashing. 

### How can it be reproduced?

Based on this https://github.com/linkerd/linkerd2/issues/7345#issuecomment-979207861  i've created the issuer and trust anchor by my self:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-self-signed-clusterissuer
  namespace: cert-manager
spec:
  selfSigned: {}
```
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "linkerd"
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "linkerd"
  isCA: true
  commonName: root.linkerd.cluster.local
  secretName: linkerd-identity-trust-roots
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: linkerd-self-signed-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
```

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: linkerd-trust-anchor
  namespace: cert-manager
spec:
  ca:
    secretName: linkerd-identity-trust-roots
```

```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
spec:
  secretName: linkerd-identity-issuer
  duration: 48h
  renewBefore: 25h
  issuerRef:
    name: linkerd-trust-anchor
    kind: ClusterIssuer
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
```

```
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
spec:
  sources:
    - secret:
        name: "linkerd-identity-trust-roots"
        key: "ca.crt"
  target:
    configMap:
      key: "ca-bundle.crt"
```

While this is working with linkerd cli:

```
linkerd install \
  --identity-external-issuer  \
  --set "identity.externalCA=true" \
  --set "clusterNetworks=172.16.0.0\/16\,172.16.0.0\/16" \
  | kubectl apply -f
```

it keeps failing with the helm chart:

values.yaml
```
clusterNetworks: "172.16.0.0/16,172.17.0.0/16"

identity:
  externalCA: true
  issuer:
    scheme: ""
```

```
helm upgrade --install linkerd-control-plane linkerd/linkerd-control-plane --namespace linkerd --values values.yaml
```

### Logs, error output, etc

linkerd-itentity identity container
```
time="2022-09-28T06:39:45Z" level=info msg="running version stable-2.12.1"
time="2022-09-28T06:39:45Z" level=info msg="Identity disabled in control plane configuration."
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-existence
-----------------
- pod/linkerd-destination-6b54f89d5-8w6cz container sp-validator is not ready 
```

Hanging there

### Environment

k3d v1.24.4+k3s1

### Would you like to work on fixing this bug?

yes

**Comment by adleong** [comment]
Hi @tburschka

It looks like you want to set the issuer scheme to `kubernetes.io/tls` in your values file.

**Comment by tburschka** [comment]
@adleong 

Since i'm try to avoid this requirement:

https://github.com/linkerd/linkerd2/blob/c8348b3ab4f16e71deaa1135502748d10b93c2dc/charts/linkerd-control-plane/templates/identity.yaml#L18-L20

I needed to unset the ?scheme` variable so that this condition is not met

https://github.com/linkerd/linkerd2/blob/c8348b3ab4f16e71deaa1135502748d10b93c2dc/charts/linkerd-control-plane/templates/identity.yaml#L6

But yesterday i saw, that the `scheme` is used for another thing in this block

https://github.com/linkerd/linkerd2/blob/c8348b3ab4f16e71deaa1135502748d10b93c2dc/charts/linkerd-control-plane/templates/identity.yaml#L145-L155

I assume, that this empty argument leads to my CrashloopBackOff.

In my opinion the identity template, which renders the secret needs another condition for this (like `existingSecret`?) so the secret is not being rendered but scheme is set.

**Comment by iamyogeshg** [comment]
@tburschka scheme does not have to be unset, it can be set to `kubernetes.io/tls` to avoid your requirement. 


@adleong could you please let me know what's the equivalent helm value for this flag -- `identity-external-issuer` ?

**Comment by tburschka** [comment]
@iamyogeshg Thanks, this brings me a step further. but there is still `identityTrustAnchorsPEM` which must be set since it is used here.

https://github.com/linkerd/linkerd2/blob/c8348b3ab4f16e71deaa1135502748d10b93c2dc/charts/partials/templates/_metadata.tpl

@adleong im also interested in the question of @iamyogeshg

**Comment by iamyogeshg** [comment]
@tburschka  For me these values worked, and `linkerd check` is passing, but still unsure whether we need to somehow pass the flag `identity-external-issuer`.

values.yaml

```
identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
proxyInit:
  runAsRoot: true # Required for docker container runtime.
```
