### ISSUE TITLE
failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": context deadline exceeded

### ISSUE THREAD

**Issue by joscabmar** [linkerd/linkerd2#9672]
### What is the issue?

Whenever I try to create a new resource in a namespace that does not have the label `config.linkerd.io/admission-webhooks: disabled` I get the following error:

```
Error from server (InternalError): Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": context deadline exceeded
```

### How can it be reproduced?

The override values:
```
deploymentStrategy:
  rollingUpdate:
    maxUnavailable: 1
enablePodAntiAffinity: true
enablePodDisruptionBudget: true
webhookFailurePolicy: Fail
controllerReplicas: 3
identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
proxyInit:
  iptablesMode: legacy
  runAsRoot: true
enablePSP: true
podMonitor:
  enabled: true
proxyInjector:
  externalSecret: true
  injectCaFrom: linkerd/linkerd-proxy-injector
policyValidator:
  externalSecret: true
  injectCaFrom: linkerd/linkerd-policy-validator
profileValidator:
  externalSecret: true
  injectCaFrom: linkerd/linkerd-sp-validator
```

I omitted `identityTrustAnchorsPEM` but it is also specified.
Installing the chart gives no errors. But just deploying a pod in a namespace where the webhook is active will give you the error:
```
$ kubectl run debugger --rm --tty -i --restart='Never' --namespace linkerd-viz --image tutum/dnsutils --command -- /bin/bash
Error from server (InternalError): Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": context deadline exceeded
```

### Logs, error output, etc

Immediate output from kubectl:
```
Error from server (InternalError): Internal error occurred: failed calling webhook "linkerd-proxy-injector.linkerd.io": failed to call webhook: Post "https://linkerd-proxy-injector.linkerd.svc:443/?timeout=10s": context deadline exceeded
```
When forcing the errors, I see no logs in the linkerd namespace
![Screenshot 2022-10-21 at 13 54 10](https://user-images.githubusercontent.com/6691911/197189936-41848057-4a1a-4159-bcb9-677cebff1d24.png)

### output of `linkerd check -o short`
Linkerd core checks
===================

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2022-10-22T15:26:41Z
    see https://linkerd.io/2.12/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2022-10-21T15:26:41Z
    see https://linkerd.io/2.12/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2022-10-21T15:26:41Z
    see https://linkerd.io/2.12/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints
‼ policy-validator cert is valid for at least 60 days
    certificate will expire on 2022-10-21T15:26:42Z
    see https://linkerd.io/2.12/checks/#l5d-policy-validator-webhook-cert-not-expiring-soon for hints

### Environment

- Kubernetes 1.22
- EKS
- Linkerd stable-2.12.2

### Additional context

The linkerd core checks seem ok. The certificates are renewed on a daily basis via cert-manager.

### Would you like to work on fixing this bug?

yes
