### ISSUE TITLE
linkerd-destination | policy container failed to start

### ISSUE THREAD

**Issue by hungran** [linkerd/linkerd2#9746]
### What is the issue?

We are upgrading linkerd version 2.10.2 to 2.12.2 along with viz, crds by Argocd Application
The linkerd-destination has failed with container `policy`

### How can it be reproduced?

we are using argocd to deploy linker-control-plane, viz, crds
control-plane:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxxx
spec:
  project: xxx
  destination:
    name: xxx
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.9.4
    helm:
      version: v3
      values: |
        controlPlaneTracing: true
        identityTrustAnchorsPEM: &identityTrustAnchorsPEM |
          -----BEGIN CERTIFICATE-----
          redact
          -----END CERTIFICATE-----

        enablePodAntiAffinity: true

        # proxy configuration
        proxy:
          waitBeforeExitSeconds: 30
          cores: 1
          resources:
            cpu:
              limit: 250m
              request: 10m
            memory:
              limit: 50Mi
              request: 50Mi

        controllerResources: &controller_resources
          cpu: &controller_resources_cpu
            limit: 100m
            request: 100m
          memory:
            limit: 250Mi
            request: 250Mi

        # policy controller configuration
        policyController:
          resources: *controller_resources

        # identity configuration
        identity:
          issuer:
            scheme: kubernetes.io/tls
        identityResources: *controller_resources

        # heartbeat configuration
        disableHeartBeat: true

        # proxy injector configuration
        proxyInjector:
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
        proxyInjectorResources: *controller_resources
        webhookFailurePolicy: Fail

        # service profile validator configuration
        profileValidator:
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
        spValidatorResources: *controller_resources

        # policy validator configuration
        policyValidator:
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
```

linkerd-viz
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxx-linkerd-viz
spec:
  project:xxx
  destination:
    name: xxx
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-viz
    targetRevision: 30.3.4
    helm:
      version: v3
      values: |
        identityTrustAnchorsPEM: &identityTrustAnchorsPEM |
          -----BEGIN CERTIFICATE-----
xxxxxx
          -----END CERTIFICATE-----

        linkerdNamespace: linkerd
        enablePodAntiAffinity: true

        resources: &ha_resources
          cpu: &ha_resources_cpu
            limit: 50m
            request: 50m
          memory:
            limit: 250Mi
            request: 50Mi

        # tap configuration
        tap:
          replicas: 2
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
          resources: *ha_resources

        # tap injector configuration
        tapInjector:
          replicas: 2
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
          resources: *ha_resources

        # metrics-api configuration
        metricsAPI:
          replicas: 2
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
          resources: *ha_resources

        # web configuration
        dashboard:
          replicas: 2
          resources: *ha_resources

        grafana:
          externalUrl: https://xxxx

        prometheusUrl: http://xxxx-p-prometheus.prometheus.svc.cluster.local:9090
```

linkerd-crds

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxxxlinkerd-crds
spec:
  project: xxxx
  destination:
    name: xxxx
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: 1.4.0
    helm:
      version: v3
      values: |
```

### Logs, error output, etc

container `policy`, pod `linkerd-destination-xxx`
```
Error: failed to read TLS key: could not load private key

Caused by:
    could not load private key

```
checking certificate from endpoint service
```
openssl s_client -showcerts --servername linkerd-policy-validator.linkerd -connect 172.16.0.249:443
139708049995072:error:0200206F:system library:connect:Connection refused:../crypto/bio/b_sock2.c:110:
139708049995072:error:2008A067:BIO routines:BIO_connect:connect error:../crypto/bio/b_sock2.c:111:
connect:errno=111
```

### output of `linkerd check -o short`

```
 linkerd check -o short                                                                                                                                      in pwsh at 15:37:08
Linkerd core checks
===================

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-01-01T06:22:25Z
    see https://linkerd.io/2.12/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2023-01-01T06:22:24Z
    see https://linkerd.io/2.12/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2023-01-01T06:22:20Z
    see https://linkerd.io/2.12/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.0 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane and cli versions match
    control plane running stable-2.12.2 but cli running stable-2.12.0
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
| pod "linkerd-destination-xxx-vg5vv" status is Running
```

### Environment

Azure Cloud
Linkerd2 version 2.12.2
chart: linkerd-control-plane
chartversion:  1.9.4
hostOS: Ubuntu 18.04.6 LTS
linux (amd64)
Container runtime
containerd://1.4.9+azure
Kubelet version
v1.21.2

### Additional context

we generated Certificate by `cert-manager`

```
apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
  labels:
    config.linkerd.io/admission-webhooks: disabled
    linkerd.io/is-control-plane: "true"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  privateKey:
    algorithm: ECDSA
  usages:
    - server auth
    - client auth
  commonName: linkerd-policy-validator.linkerd.svc
  dnsNames:
    - linkerd-policy-validator.linkerd.svc
 ```

### Would you like to work on fixing this bug?

yes

**Comment by hungran** [comment]
@olix0r hey, do you have any update on this?

**Comment by olix0r** [comment]
@hungran I don't. At a glance, it looks like a misconfiguration. But someone will have to spend time reproducing your config to diagnose the issue.

**Comment by ericsuhong** [comment]
I am not sure whether this is the exact same issue, but we encountered the same issue when we passed "root-ca" profile certificates as crtPem and keyPem fields for components. The issue went away when we passed in "intermediate-ca" profile certificates.

**Comment by hungran** [comment]
@ericsuhong  do you mean `intermediate-ca` for `identity` or  `policy-validator` ?

**Comment by hungran** [comment]
@ericsuhong  thanks, I believed we are using `intermediate-ca` for those components, which we generated by self-signed `CI`

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
spec:
  selfSigned: {}

```
then root CA:
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  secretName: linkerd-trust-anchor
  duration: 87600h0m0s # 10y
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
---
```
then Issuer:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
```
intermediate CA (I believed):
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  privateKey:
    algorithm: ECDSA
  usages:
    - server auth
    - client auth
  commonName: linkerd-policy-validator.linkerd.svc
  dnsNames:
    - linkerd-policy-validator.linkerd.svc
```
