### ISSUE TITLE
Custom annotations in linkerd-viz web service

### ISSUE THREAD

**Issue by jault3** [linkerd/linkerd2#9754]
### What problem are you trying to solve?

I am trying to expose the dashboard that comes with linkerd-viz on a specific domain. I created a custom `Ingress` resource, which works great, but when I try to visit the URL I get this error:

```
It appears that you are trying to reach this service with a host of 'a.b.c.d:8084'.
This does not match /^(localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|\[::1\])(:\d+)?$/ and has been denied for security reasons.
Please see https://linkerd.io/dns-rebinding for an explanation of what is happening and how to fix it.
```

I am using Kong as my ingress controller, and Kong [requires an annotation be added to the `Service`](https://docs.konghq.com/kubernetes-ingress-controller/latest/references/annotations/#konghqcomhost-header) resource to set the Host header on upstream requests. For example, I would add this to the web service to get things working:

```
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: linkerd-viz
  annotations:
    konghq.com/host-header: web.linkerd-viz.svc
```

I took a look at the linkerd-viz helm chart (my deployment method) and didn't see a way to add custom annotations to the service.

### How should the problem be solved?

Somewhat similar to how the `commonLabels` field works for the linkerd-viz helm chart, I would like to be able to specify custom annotations (that are specific to the web service). Perhaps under the `dashboard` section of the values file? (Looking for guidance on the best approach)

```
dashboard:
  service:
    annotations:
      key: value
      other-key: value
```

### Any alternatives you've considered?

The only alternative I've found (if deploying with helm) is to manually modify the service after it gets created in the cluster. It appears to be left intact by helm and the git ops tool (I believe this is due to ArgoCD using server-side applies and it is not the "manager" of that specific annotation, so kubernetes lets it slide).

### How would users interact with this feature?

Modifications to the `values.yaml` file would be optional, but available to add custom annotations

### Would you like to work on this feature?

yes
