### ISSUE TITLE
Linkerd stable CLI does not set default proxy resource requests

### ISSUE THREAD

**Issue by to266** [linkerd/linkerd2#9796]
### What is the issue?

`linkerd install` and `linkerd upgrade` create default proxy injection configs with no default resources set up.

This is all sorts of inconvenient and unwanted. From simple "suddenly none of your HPAs work", to actually draining the cluster of resources

### How can it be reproduced?

`linkerd install` (or `linkerd upgrade`) and inspect the `linkerd-config` ConfigMap in the `linkerd` namespace.

### Logs, error output, etc

The particular default config segment:
```yaml
 proxy:
   accessLog: ""
   await: true
   capabilities: null
   defaultInboundPolicy: all-unauthenticated
   enableExternalProfiles: false
   image:
     name: cr.l5d.io/linkerd/proxy
     pullPolicy: ""
     version: stable-2.12.0
   inboundConnectTimeout: 100ms
   isGateway: false
   isIngress: false
   logFormat: plain
   logLevel: warn,linkerd=info
   opaquePorts: 25,587,3306,4444,5432,6379,9300,11211
   outboundConnectTimeout: 1000ms
   podInboundPorts: ""
   ports:
     admin: 4191
     control: 4190
     inbound: 4143
     outbound: 4140
   requireIdentityOnInboundPorts: ""
   resources:
     cpu:
       limit: ""
       request: ""
     ephemeral-storage:
       limit: ""
       request: ""
     memory:
       limit: ""
       request: ""
   saMountPath: null
   shutdownGracePeriod: ""
   uid: 2102
   waitBeforeExitSeconds: 0

```

### output of `linkerd check -o short`

```text
❯ linkerd check -o short
Linkerd core checks
===================

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.0 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.12.0 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-7f4c9db7bd-mvf6n (stable-2.12.0)
        * linkerd-identity-b455d9dc6-ndtmx (stable-2.12.0)
        * linkerd-proxy-injector-7cb9cb479-g2qhq (stable-2.12.0)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints

Status check results are √

```

### Environment

 - k8s: 1.24.6
 - AKS
 - stable-2.12.0

### Possible solution

Set the resource requests

### Additional context

Seems that the init container (that's also auto-injected) actually has things correctly set. Maybe it was simply accidentally removed / added to the wrong config?

### Would you like to work on fixing this bug?

maybe
