### ISSUE TITLE
Readiness/Liveness Probe Failures in linkerd-destination Pods

### ISSUE THREAD

**Issue by rsajjan3** [linkerd/linkerd2#9798]
### What is the issue?

Since upgrading Linkerd to v2.12.1 we have been noticing readiness/liveness probe errors occurring on the `linkerd-destination` pod, this is happening on all containers within the pod(destination, sp-validator, policy). The probe failures appear to be happening randomly multiple times a day. We have not observed any impact on services using Linkerd, but I would like to understand why this is occurring. 

### How can it be reproduced?

I have not been able to reproduce this on-demand. The probe failures will usually start occurring within a few minutes of the `linkerd-desintation` pod coming up. The interval between failures appears to be random.

### Logs, error output, etc

Probe failure messages:
```
Liveness probe failed: Get "http://10.7.3.34:9997/ping": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Liveness probe failed: Get "http://10.7.3.34:9997/ping": read tcp 10.140.9.6:35002->10.7.3.34:9997: read: connection reset by peer
Readiness probe failed: Get "http://10.7.3.34:9996/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Readiness probe failed: Get "http://10.7.3.34:9990/ready": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Readiness probe failed: Get "http://10.7.3.34:9990/ready": dial tcp 10.7.3.34:9990: connect: connection reset by peer
Liveness probe failed: Get "http://10.7.3.34:9996/ping": dial tcp 10.7.3.34:9996: connect: connection reset by peer
````

### output of `linkerd check -o short`

```
➜  ~ linkerd check -o short                
Linkerd core checks
===================

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2022-12-30T15:03:02Z
    see https://linkerd.io/2.12/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2022-12-30T15:03:04Z
    see https://linkerd.io/2.12/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.12.1 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
	* linkerd-destination-67c856f5d8-6955r (stable-2.12.1)
	* linkerd-destination-67c856f5d8-7z8xz (stable-2.12.1)
	* linkerd-destination-67c856f5d8-l2wnx (stable-2.12.1)
	* linkerd-identity-7b876cdf99-h28v9 (stable-2.12.1)
	* linkerd-identity-7b876cdf99-jxsbc (stable-2.12.1)
	* linkerd-identity-7b876cdf99-xss8r (stable-2.12.1)
	* linkerd-proxy-injector-869cbc9f48-ltg72 (stable-2.12.1)
	* linkerd-proxy-injector-869cbc9f48-rfzjc (stable-2.12.1)
	* linkerd-proxy-injector-869cbc9f48-xx7lb (stable-2.12.1)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints

Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2022-12-16T20:52:42Z
    see https://linkerd.io/2.12/checks/#l5d-tap-cert-not-expiring-soon for hints
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
	* metrics-api-6968db9c5c-bkgkh (stable-2.12.1)
	* tap-66cf5c7bdd-nwsnw (stable-2.12.1)
	* tap-injector-f8646759b-w5g95 (stable-2.12.1)
	* web-7666f68d74-rq8tq (stable-2.12.1)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

- Kubernetes Version: v1.22.13
   - `Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.13", GitCommit:"a43c0904d0de10f92aa3956c74489c45e6453d6e", GitTreeState:"clean", BuildDate:"2022-08-17T18:23:45Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}` 
- Cluster Environment: self-managed on AWS
- Host OS: Ubuntu 18.04.6 LTS
- Linkerd version: 2.12.1

### Additional context

`linkerd-destination` Deployment manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/created-by: linkerd/helm stable-2.12.1
  labels:
    app.kubernetes.io/name: destination
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: stable-2.12.1
    argocd.argoproj.io/instance: linkerd.k8s-test.us-west-2c
    linkerd.io/control-plane-component: destination
    linkerd.io/control-plane-ns: linkerd
  name: linkerd-destination
  namespace: linkerd
spec:
  replicas: 3
  selector:
    matchLabels:
      linkerd.io/control-plane-component: destination
      linkerd.io/control-plane-ns: linkerd
      linkerd.io/proxy-deployment: linkerd-destination
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
        config.linkerd.io/default-inbound-policy: all-unauthenticated
        linkerd.io/created-by: linkerd/helm stable-2.12.1
        linkerd.io/helm-release-version: '1'
        linkerd.io/proxy-version: stable-2.12.1
        linkerd.io/trust-root-sha256: Removed
        logging_service: linkerd
      labels:
        linkerd.io/control-plane-component: destination
        linkerd.io/control-plane-ns: linkerd
        linkerd.io/proxy-deployment: linkerd-destination
        linkerd.io/workload-ns: linkerd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: linkerd.io/control-plane-component
                      operator: In
                      values:
                        - destination
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: linkerd.io/control-plane-component
                    operator: In
                    values:
                      - destination
              topologyKey: kubernetes.io/hostname
      containers:
        - env:
            - name: _pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: _pod_ns
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: _pod_nodeName
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: LINKERD2_PROXY_LOG
              value: 'warn,linkerd=info'
            - name: LINKERD2_PROXY_LOG_FORMAT
              value: plain
            - name: LINKERD2_PROXY_DESTINATION_SVC_ADDR
              value: 'localhost.:8086'
            - name: LINKERD2_PROXY_DESTINATION_PROFILE_NETWORKS
              value: '10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16'
            - name: LINKERD2_PROXY_POLICY_SVC_ADDR
              value: 'localhost.:8090'
            - name: LINKERD2_PROXY_POLICY_WORKLOAD
              value: '$(_pod_ns):$(_pod_name)'
            - name: LINKERD2_PROXY_INBOUND_DEFAULT_POLICY
              value: all-unauthenticated
            - name: LINKERD2_PROXY_POLICY_CLUSTER_NETWORKS
              value: '10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16'
            - name: LINKERD2_PROXY_INBOUND_CONNECT_TIMEOUT
              value: 100ms
            - name: LINKERD2_PROXY_OUTBOUND_CONNECT_TIMEOUT
              value: 1000ms
            - name: LINKERD2_PROXY_CONTROL_LISTEN_ADDR
              value: '0.0.0.0:4190'
            - name: LINKERD2_PROXY_ADMIN_LISTEN_ADDR
              value: '0.0.0.0:4191'
            - name: LINKERD2_PROXY_OUTBOUND_LISTEN_ADDR
              value: '127.0.0.1:4140'
            - name: LINKERD2_PROXY_INBOUND_LISTEN_ADDR
              value: '0.0.0.0:4143'
            - name: LINKERD2_PROXY_INBOUND_IPS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIPs
            - name: LINKERD2_PROXY_INBOUND_PORTS
              value: '8086,8090,8443,9443,9990,9996,9997'
            - name: LINKERD2_PROXY_DESTINATION_PROFILE_SUFFIXES
              value: svc.cluster.local.
            - name: LINKERD2_PROXY_INBOUND_ACCEPT_KEEPALIVE
              value: 10000ms
            - name: LINKERD2_PROXY_OUTBOUND_CONNECT_KEEPALIVE
              value: 10000ms
            - name: LINKERD2_PROXY_INBOUND_PORTS_DISABLE_PROTOCOL_DETECTION
              value: '25,587,3306,4444,5432,6379,9300,11211'
            - name: LINKERD2_PROXY_DESTINATION_CONTEXT
              value: |
                {"ns":"$(_pod_ns)", "nodeName":"$(_pod_nodeName)"}
            - name: _pod_sa
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: _l5d_ns
              value: linkerd
            - name: _l5d_trustdomain
              value: cluster.local
            - name: LINKERD2_PROXY_IDENTITY_DIR
              value: /var/run/linkerd/identity/end-entity
            - name: LINKERD2_PROXY_IDENTITY_TRUST_ANCHORS
              valueFrom:
                configMapKeyRef:
                  key: ca-bundle.crt
                  name: linkerd-identity-trust-roots
            - name: LINKERD2_PROXY_IDENTITY_TOKEN_FILE
              value: /var/run/secrets/tokens/linkerd-identity-token
            - name: LINKERD2_PROXY_IDENTITY_SVC_ADDR
              value: 'linkerd-identity-headless.linkerd.svc.cluster.local.:8080'
            - name: LINKERD2_PROXY_IDENTITY_LOCAL_NAME
              value: >-
                $(_pod_sa).$(_pod_ns).serviceaccount.identity.linkerd.cluster.local
            - name: LINKERD2_PROXY_IDENTITY_SVC_NAME
              value: >-
                linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local
            - name: LINKERD2_PROXY_DESTINATION_SVC_NAME
              value: >-
                linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
            - name: LINKERD2_PROXY_POLICY_SVC_NAME
              value: >-
                linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
          image: 'cr.l5d.io/linkerd/proxy:stable-2.12.1'
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - /usr/lib/linkerd/linkerd-await
                  - '--timeout=2m'
          livenessProbe:
            httpGet:
              path: /live
              port: 4191
            initialDelaySeconds: 10
          name: linkerd-proxy
          ports:
            - containerPort: 4143
              name: linkerd-proxy
            - containerPort: 4191
              name: linkerd-admin
          readinessProbe:
            httpGet:
              path: /ready
              port: 4191
            initialDelaySeconds: 2
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 2102
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /var/run/linkerd/identity/end-entity
              name: linkerd-identity-end-entity
            - mountPath: /var/run/secrets/tokens
              name: linkerd-identity-token
        - args:
            - destination
            - '-addr=:8086'
            - '-controller-namespace=linkerd'
            - '-enable-h2-upgrade=true'
            - '-log-level=info'
            - '-log-format=plain'
            - '-enable-endpoint-slices=true'
            - '-cluster-domain=cluster.local'
            - '-identity-trust-domain=cluster.local'
            - '-default-opaque-ports=25,587,3306,4444,5432,6379,9300,11211'
            - '-enable-pprof=false'
          image: 'cr.l5d.io/linkerd/controller:stable-2.12.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 9996
            initialDelaySeconds: 10
          name: destination
          ports:
            - containerPort: 8086
              name: grpc
            - containerPort: 9996
              name: admin-http
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /ready
              port: 9996
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 2103
        - args:
            - sp-validator
            - '-log-level=info'
            - '-log-format=plain'
            - '-enable-pprof=false'
          image: 'cr.l5d.io/linkerd/controller:stable-2.12.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /ping
              port: 9997
            initialDelaySeconds: 10
          name: sp-validator
          ports:
            - containerPort: 8443
              name: sp-validator
            - containerPort: 9997
              name: admin-http
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /ready
              port: 9997
          resources:
            limits:
              memory: 250Mi
            requests:
              cpu: 100m
              memory: 50Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 2103
          volumeMounts:
            - mountPath: /var/run/linkerd/tls
              name: sp-tls
              readOnly: true
        - args:
            - '--admin-addr=0.0.0.0:9990'
            - '--control-plane-namespace=linkerd'
            - '--grpc-addr=0.0.0.0:8090'
            - '--server-addr=0.0.0.0:9443'
            - '--server-tls-key=/var/run/linkerd/tls/tls.key'
            - '--server-tls-certs=/var/run/linkerd/tls/tls.crt'
            - >-
              --cluster-networks=10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16
            - '--identity-domain=cluster.local'
            - '--default-policy=all-unauthenticated'
            - '--log-level=info'
            - '--log-format=plain'
            - '--probe-networks=0.0.0.0/0'
          image: 'cr.l5d.io/linkerd/policy-controller:stable-2.12.1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /live
              port: admin
          name: policy
          ports:
            - containerPort: 8090
              name: grpc
            - containerPort: 9990
              name: admin
            - containerPort: 9443
              name: policy-https
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /ready
              port: admin
            initialDelaySeconds: 10
          resources: null
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 2103
          volumeMounts:
            - mountPath: /var/run/linkerd/tls
              name: policy-tls
              readOnly: true
      initContainers:
        - args:
            - '--incoming-proxy-port'
            - '4143'
            - '--outgoing-proxy-port'
            - '4140'
            - '--proxy-uid'
            - '2102'
            - '--inbound-ports-to-ignore'
            - '4190,4191,4567,4568'
            - '--outbound-ports-to-ignore'
            - '443'
          image: 'cr.l5d.io/linkerd/proxy-init:v2.0.0'
          imagePullPolicy: IfNotPresent
          name: linkerd-init
          resources:
            limits:
              cpu: 100m
              memory: 20Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          terminationMessagePolicy: FallbackToLogsOnError
          volumeMounts:
            - mountPath: /run
              name: linkerd-proxy-init-xtables-lock
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: linkerd-destination
      volumes:
        - name: sp-tls
          secret:
            secretName: linkerd-sp-validator-k8s-tls
        - name: policy-tls
          secret:
            secretName: linkerd-policy-validator-k8s-tls
        - emptyDir: {}
          name: linkerd-proxy-init-xtables-lock
        - name: linkerd-identity-token
          projected:
            sources:
              - serviceAccountToken:
                  audience: identity.l5d.io
                  expirationSeconds: 86400
                  path: linkerd-identity-token
        - emptyDir:
            medium: Memory
          name: linkerd-identity-end-entity
```
This issue seems related to what we are experiencing: https://github.com/linkerd/linkerd2/issues/9602
