### ISSUE TITLE
Linkerd destination seem not received request because linkerd-proxy has problem with TLS cert

### ISSUE THREAD

**Issue by hungran** [linkerd/linkerd2#9800]
### What is the issue?

We are upgrading linkerd version 2.10.2 to 2.12.2 along with viz, crds by Argocd Application
seem that the connection from proxy side care along with an app throw linkerd-controller has problem

### How can it be reproduced?

we are using argocd to deploy linker-control-plane, viz, crds
control-plane:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxxx
spec:
  project: xxx
  destination:
    name: xxx
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-control-plane
    targetRevision: 1.9.4
    helm:
      version: v3
      values: |
        controlPlaneTracing: true
        identityTrustAnchorsPEM: &identityTrustAnchorsPEM |
          -----BEGIN CERTIFICATE-----
          redact
          -----END CERTIFICATE-----

        enablePodAntiAffinity: true

        # proxy configuration
        proxy:
          waitBeforeExitSeconds: 30
          cores: 1
          resources:
            cpu:
              limit: 250m
              request: 10m
            memory:
              limit: 50Mi
              request: 50Mi

        controllerResources: &controller_resources
          cpu: &controller_resources_cpu
            limit: 100m
            request: 100m
          memory:
            limit: 250Mi
            request: 250Mi

        # policy controller configuration
        policyController:
          resources: *controller_resources

        # identity configuration
        identity:
          issuer:
            scheme: kubernetes.io/tls
        identityResources: *controller_resources

        # heartbeat configuration
        disableHeartBeat: true

        # proxy injector configuration
        proxyInjector:
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
        proxyInjectorResources: *controller_resources
        webhookFailurePolicy: Fail

        # service profile validator configuration
        profileValidator:
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
        spValidatorResources: *controller_resources

        # policy validator configuration
        policyValidator:
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
```

linkerd-viz
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxx-linkerd-viz
spec:
  project:xxx
  destination:
    name: xxx
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-viz
    targetRevision: 30.3.4
    helm:
      version: v3
      values: |
        identityTrustAnchorsPEM: &identityTrustAnchorsPEM |
          -----BEGIN CERTIFICATE-----
xxxxxx
          -----END CERTIFICATE-----

        linkerdNamespace: linkerd
        enablePodAntiAffinity: true

        resources: &ha_resources
          cpu: &ha_resources_cpu
            limit: 50m
            request: 50m
          memory:
            limit: 250Mi
            request: 50Mi

        # tap configuration
        tap:
          replicas: 2
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
          resources: *ha_resources

        # tap injector configuration
        tapInjector:
          replicas: 2
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
          resources: *ha_resources

        # metrics-api configuration
        metricsAPI:
          replicas: 2
          externalSecret: true
          caBundle: *identityTrustAnchorsPEM
          resources: *ha_resources

        # web configuration
        dashboard:
          replicas: 2
          resources: *ha_resources

        grafana:
          externalUrl: https://xxxx

        prometheusUrl: http://xxxx-p-prometheus.prometheus.svc.cluster.local:9090
```

linkerd-crds

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xxxxlinkerd-crds
spec:
  project: xxxx
  destination:
    name: xxxx
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.linkerd.io/stable
    chart: linkerd-crds
    targetRevision: 1.4.0
    helm:
      version: v3
      values: |
```

### Logs, error output, etc

linkerd-destination -c linkerd-proxy
```
[   318.223076s]  INFO ThreadId(01) inbound:server{port=9996}:rescue{client.addr=10.112.65.83:54968}: linkerd_app_core::errors::respond: Request failed error=connection closed before message completed
[   318.223121s]  INFO ThreadId(01) inbound:server{port=9996}:rescue{client.addr=10.112.65.83:54968}: linkerd_app_core::errors::respond: Request failed error=connection closed before message completed
[   318.223127s]  WARN ThreadId(01) inbound:server{port=9996}:rescue{client.addr=10.112.65.83:54968}: linkerd_app_inbound::http::server: Unexpected error error=connection closed before message completed
[   318.223236s]  INFO ThreadId(01) inbound:server{port=9996}:rescue{client.addr=10.112.65.83:54966}: linkerd_app_core::errors::respond: Request failed error=connection closed before message completed
[   318.223259s]  INFO ThreadId(01) inbound:server{port=9996}:rescue{client.addr=10.112.65.83:54966}: linkerd_app_core::errors::respond: Request failed error=connection closed before message completed
[   318.223263s]  WARN ThreadId(01) inbound:server{port=9996}:rescue{client.addr=10.112.65.83:54966}: linkerd_app_inbound::http::server: Unexpected error error=connection closed before message completed
[   321.233644s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=TLS detection timed out client.addr=10.112.66.40:37532
[   324.121021s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=TLS detection timed out client.addr=10.112.64.165:42208
[   329.109294s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=TLS detection timed out client.addr=10.112.66.108:49556
[   336.113401s]  INFO ThreadId(01) inbound: linkerd_app_core::serve: Connection closed error=TLS detection timed out client.addr=10.112.65.157:52686
```

### output of `linkerd check -o short`

```text
Linkerd core checks
===================

linkerd-identity
----------------
‼ issuer cert is valid for at least 60 days
    issuer certificate will expire on 2023-01-01T06:22:25Z
    see https://linkerd.io/2.12/checks/#l5d-identity-issuer-cert-not-expiring-soon for hints

linkerd-webhooks-and-apisvc-tls
-------------------------------
‼ proxy-injector cert is valid for at least 60 days
    certificate will expire on 2023-01-01T06:22:24Z
    see https://linkerd.io/2.12/checks/#l5d-proxy-injector-webhook-cert-not-expiring-soon for hints
‼ sp-validator cert is valid for at least 60 days
    certificate will expire on 2023-01-01T06:22:20Z
    see https://linkerd.io/2.12/checks/#l5d-sp-validator-webhook-cert-not-expiring-soon for hints

linkerd-version
---------------
‼ cli is up-to-date
    is running version 2.12.0 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-cli for hints

control-plane-version
---------------------
‼ control plane is up-to-date
    is running version 2.12.0 but the latest stable version is 2.12.2
    see https://linkerd.io/2.12/checks/#l5d-version-control for hints

linkerd-control-plane-proxy
---------------------------
‼ control plane proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-f677b96f5-ljzxm (stable-2.12.0)
        * linkerd-destination-f677b96f5-wgrvs (stable-2.12.0)
        * linkerd-identity-69645c5cf8-4hvp4 (stable-2.12.0)
        * linkerd-identity-69645c5cf8-l7q69 (stable-2.12.0)
        * linkerd-proxy-injector-7f596bbffb-67rv9 (stable-2.12.0)
        * linkerd-proxy-injector-7f596bbffb-njw8j (stable-2.12.0)
    see https://linkerd.io/2.12/checks/#l5d-cp-proxy-version for hints

linkerd-ha-checks
-----------------
‼ pod injection disabled on kube-system
    kube-system namespace needs to have the label config.linkerd.io/admission-webhooks: disabled if injector webhook failure policy is Fail
    see https://linkerd.io/2.12/checks/#l5d-injection-disabled for hints

                              Linkerd extensions checks
=========================

linkerd-viz
-----------
‼ tap API server cert is valid for at least 60 days
    certificate will expire on 2022-12-23T06:49:32Z
    see https://linkerd.io/2.12/checks/#l5d-tap-cert-not-expiring-soon for hints
‼ linkerd-viz pods are injected
    could not find proxy container for metrics-api-55b97f79d4-58t2d pod
    see https://linkerd.io/2.12/checks/#l5d-viz-pods-injection for hints
‼ viz extension pods are running
    container "linkerd-proxy" in pod "metrics-api-55b97f79d4-58t2d" is not ready
    see https://linkerd.io/2.12/checks/#l5d-viz-pods-running for hints
‼ viz extension proxies are up-to-date
    some proxies are not running the current version:
        * linkerd-destination-f677b96f5-ljzxm (stable-2.12.0)
        * linkerd-destination-f677b96f5-wgrvs (stable-2.12.0)
        * linkerd-identity-69645c5cf8-4hvp4 (stable-2.12.0)
        * linkerd-identity-69645c5cf8-l7q69 (stable-2.12.0)
        * linkerd-proxy-injector-7f596bbffb-67rv9 (stable-2.12.0)
        * linkerd-proxy-injector-7f596bbffb-njw8j (stable-2.12.0)
    see https://linkerd.io/2.12/checks/#l5d-viz-proxy-cp-version for hints

Status check results are √
```

### Environment

- K8S: 1.21.2
- CE: AKS
- HostOS: 
	OS
	linux (amd64)
	OS Image
	Ubuntu 18.04.6 LTS
	Kernel version
	5.4.0-1062-azure
	Container runtime
	containerd://1.4.9+azure
- Linkerd Version: tried 1.12.0, 1.12.1, 1.12.2

### Additional context

 we are using `intermediate-ca` for those components, which we generated by self-signed `CI`

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: self-signed
spec:
  selfSigned: {}

```
then root CA:
```yaml
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  secretName: linkerd-trust-anchor
  duration: 87600h0m0s # 10y
  issuerRef:
    name: self-signed
    kind: ClusterIssuer
  isCA: true
  privateKey:
    algorithm: ECDSA
  usages:
    - cert sign
    - crl sign
    - server auth
    - client auth
  commonName: identity.linkerd.cluster.local
  dnsNames:
    - identity.linkerd.cluster.local
---
```
then Issuer:
```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linkerd-trust-anchor
  namespace: linkerd
spec:
  ca:
    secretName: linkerd-trust-anchor
```
intermediate CA (I believed):
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkerd-policy-validator
  namespace: linkerd
spec:
  secretName: linkerd-policy-validator-k8s-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  issuerRef:
    name: linkerd-trust-anchor
    kind: Issuer
  privateKey:
    algorithm: ECDSA
  usages:
    - server auth
    - client auth
  commonName: linkerd-policy-validator.linkerd.svc
  dnsNames:
    - linkerd-policy-validator.linkerd.svc
```

### Would you like to work on fixing this bug?

maybe
