### ISSUE TITLE
CrashLoopBackOff on linkerd-destination

### ISSUE THREAD

**Issue by aweeraman** [linkerd/linkerd2#9825]
### What is the issue?

We're seeing CrashLoopBackoff on linkerd-destination pods when installing via Helm:

```
linkerd         linkerd-destination-7c4dd5688d-5fsqw        3/4     CrashLoopBackOff   3          11m
linkerd         linkerd-destination-7c4dd5688d-9spgh        3/4     CrashLoopBackOff   3          11m
linkerd         linkerd-destination-7c4dd5688d-vg4x4        3/4     CrashLoopBackOff   3          11m
```
We've tried 2.12.2 assuming that this issue may be relevant for this: https://github.com/linkerd/linkerd2/commit/5cb6755ebe51b868a6528b68d0614d2112b1f753 

### How can it be reproduced?

The result was the same with and without the `set cniEnabled=true`:

```
        helm install linkerd-control-plane \
                -n linkerd \
                --set-file identityTrustAnchorsPEM=${CERT_ROOT}/ca.crt \
                --set-file identity.issuer.tls.crtPEM=${CERT_ROOT}/issuer.crt \
                --set-file identity.issuer.tls.keyPEM=${CERT_ROOT}/issuer.key \
                --set identity.issuer.crtExpiry=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ") \
                -f values-ha.yaml \
                linkerd/linkerd-control-plane --set cniEnabled=true
```

values-ha.yaml:

```yaml
# Get the latest from: helm fetch --untar linkerd/linkerd-control-plane
# and tweak as required.

# Logging
controllerLogLevel: trace
policyController:
    logLevel: linkerd=trace,warn

# -- Create PodDisruptionBudget resources for each control plane workload
enablePodDisruptionBudget: true

# -- Specify a deployment strategy for each control plane workload
deploymentStrategy:
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 25%

# -- add PodAntiAffinity to each control plane workload
enablePodAntiAffinity: true

# nodeAffinity: 

# proxy configuration
proxy:
  resources:
    cpu:
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi

# controller configuration
controllerReplicas: 3
controllerResources: &controller_resources
  cpu: &controller_resources_cpu
    limit: ""
    request: 100m
  memory:
    limit: 250Mi
    request: 50Mi
destinationResources: *controller_resources

# identity configuration
identityResources:
  cpu: *controller_resources_cpu
  memory:
    limit: 250Mi
    request: 10Mi

# heartbeat configuration
heartbeatResources: *controller_resources

# proxy injector configuration
proxyInjectorResources: *controller_resources
webhookFailurePolicy: Fail

# service profile validator configuration
spValidatorResources: *controller_resources
```

### Logs, error output, etc

```
$ kubectl logs linkerd-destination-7c4dd5688d-5fsqw -n linkerd
Defaulted container "linkerd-proxy" out of: linkerd-proxy, destination, sp-validator, policy, noop (init)
time="2022-11-13T17:05:58Z" level=info msg="Found pre-existing key: /var/run/linkerd/identity/end-entity/key.p8"
time="2022-11-13T17:05:58Z" level=info msg="Found pre-existing CSR: /var/run/linkerd/identity/end-entity/csr.der"
[     0.002865s]  INFO ThreadId(01) linkerd2_proxy::rt: Using single-threaded proxy runtime
[     0.004276s]  INFO ThreadId(01) linkerd2_proxy: Admin interface on 0.0.0.0:4191
[     0.004299s]  INFO ThreadId(01) linkerd2_proxy: Inbound interface on 0.0.0.0:4143
[     0.004302s]  INFO ThreadId(01) linkerd2_proxy: Outbound interface on 127.0.0.1:4140
[     0.004317s]  INFO ThreadId(01) linkerd2_proxy: Tap DISABLED
[     0.004361s]  INFO ThreadId(01) linkerd2_proxy: Local identity is linkerd-destination.linkerd.serviceaccount.identity.linkerd.cluster.local
[     0.004365s]  INFO ThreadId(01) linkerd2_proxy: Identity verified via linkerd-identity-headless.linkerd.svc.cluster.local:8080 (linkerd-identity.linkerd.serviceaccount.identity.linkerd.cluster.local)
[     0.004367s]  INFO ThreadId(01) linkerd2_proxy: Destinations resolved via localhost:8086
[    15.005980s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[    30.006528s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[    45.007395s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[    45.018380s]  WARN ThreadId(02) identity:controller{addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}: linkerd_app_core::control: Failed to resolve control-plane component error=failed SRV and A record lookups: failed to resolve SRV record: request timed out; failed to resolve A record: request timed out error.sources=[failed to resolve A record: request timed out, request timed out]
[    60.008102s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[    75.009395s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[    90.010386s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[    90.139833s]  WARN ThreadId(02) identity:controller{addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}: linkerd_app_core::control: Failed to resolve control-plane component error=failed SRV and A record lookups: failed to resolve SRV record: request timed out; failed to resolve A record: request timed out error.sources=[failed to resolve A record: request timed out, request timed out]
[   105.011549s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[   120.012992s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[   120.058222s]  INFO ThreadId(01) linkerd_proxy::signal: received SIGTERM, starting shutdown
[   120.058233s]  INFO ThreadId(01) linkerd2_proxy: Received shutdown signal
[   135.014414s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
[   135.367132s]  WARN ThreadId(02) identity:controller{addr=linkerd-identity-headless.linkerd.svc.cluster.local:8080}: linkerd_app_core::control: Failed to resolve control-plane component error=failed SRV and A record lookups: failed to resolve SRV record: request timed out; failed to resolve A record: request timed out error.sources=[failed to resolve A record: request timed out, request timed out]
[   150.015753s]  WARN ThreadId(01) linkerd_app: Waiting for identity to be initialized...
```

### output of `linkerd check -o short`

```
Linkerd core checks
===================

linkerd-existence
-----------------
\ pod/linkerd-destination-7c4dd5688d-vg4x4 container linkerd-proxy is not ready
```
Spins on the above.

### Environment

- Kubernetes version: 1.21.8
- Cluster environment: OpenStack
- Host version: Fedora CoreOS 33.20210426.3.0
- Linkerd version: stable-2.12.2
