### ISSUE TITLE
Allow AuthorizationPolicy to target native Service resources?

### ISSUE THREAD

**Issue by philomory** [linkerd/linkerd2#9875]
### What problem are you trying to solve?

One of the touted benefits of Linkerd in comparison to, say, Istio, is the use of familiar, native Kubernetes resources wherever possible, instead of requiring the extensive use of custom resources.

Currently, this somewhat breaks down in the realm of `AuthorizationPolicies`, which require you to use a bevy of custom resources, some of which don't seem to carry much information beyond that already covered by existing native resources. For example, most of the information contained in a `Server` CR is already contained in the native `Service` resource, and the only field that isn't (`proxyProtocol`) is optional. While a `Service` resource may not _always_ be sufficient to express the desired policy (and there may be cases where a `Server` is needed because no `Service` should exist covering the pods in question), in many simple cases it seems like the `Service` alone should be sufficient.

### How should the problem be solved?

In support of the avoiding unnecessary requirements for custom resource usage, I'd like to suggest that `AuthorizationPolicy`'s `targetRef` be able to specify a Service, e.g.

```yaml
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: authors-policy
  namespace: booksapp
spec:
  targetRef:
    group: ""
    kind: Service
    name: authors
  requiredAuthenticationRefs:
    - name: webapp
      kind: ServiceAccount
```

### Any alternatives you've considered?

I'd personally like it if `AuthorizationPolicy` could simply directly specify a selector directly, rather than having to reference a separate resource which defines the selector; however, I understand that compatibility with the nascent Gateway API forbids that option.

I've also considered just using Kubernetes' native `NetworkPolicy` instead of utilizing Linkerd's `AuthorizationPolicy`, on the basis of its relative simplicity (while continuing to use Linkerd for mTLS and observability).

### How would users interact with this feature?

Users could optionally target a `Service`  when defining an `AuthorizationPolicy`; targeting a `Server` instead would, of course, still be allowed.

### Would you like to work on this feature?

maybe

**Comment by mateiidavid** [comment]
Hi @philomory! Thanks for raising this. Will do my best to explain how I understand this problem, and why we've solved it the way we have. I do want to start off by saying that I really understand where you're coming from. I'm not the biggest fan of CRDs and they can be tricky to maintain. I'd be all up for getting rid of them, if we could :).

You're right that we do our best to leverage Kubernetes primitives, they're easier to work with and easier for people to understand. The `Service` object is not the best fit in this case. It serves two main purposes:

1. It acts as a `frontend` to consumers (i.e clients) by exposing an IP address and a DNS record, both of which can be called by the consumer;
2. It acts as a `backend`, the _target_ of a client. In general, `Services` map to one or more pods which are collected in `Endpoints` and `EndpointSlices`. 

You'll notice that in both cases, the main "persona" that benefits from the `Service` object is the consumer; through the object they have a consistent mechanism to call a target. If you think the terminology is a bit confusing, you're not alone. You can check [this GatewayAPI doc](https://docs.google.com/document/d/1IzItdX22fHfXCP6Zch6pC8hEImMNJ6MCPqGNW1aaDr8/edit?usp=sharing) that expands a little bit on the glossary.

Going back to our `Service`. When we want to do authorization, we have to do it on the server-side, i.e the producer sitting behind the `Service`. The problem is, `Service` as an object is very client-centric in nature. Suppose you attach the policy to it -- pods can actually side-step the `Service` and call an endpoint directly, authorization becomes harder to enforce as a result. For pods acting as servers and handling connections the fact that a `Service` has been used to connect to them is unknown. A way to think about it is: clients use a `Service` to connect to a target, servers use a `Server` to expose information about where they can be reached, their "public" sockets.

`Server` objects were introduced largely because we want to have a mechanism whereby a port is made public to the cluster. This allows for fine-grained authorization (e.g you want port 8080 reached by everyone but not port 4000? no problem, create two servers) that cannot be side-stepped by clients, since lookups are done on the server-side. A producer will always check which `Servers` (and thus which policies) apply to it, regardless of where the request comes from. If we were to do that with a `Service`, it wouldn't be as easy to enforce.

Hope that more or less makes sense.

**Comment by philomory** [comment]
I guess I wasn't entirely clear in what I was suggesting; I never meant to suggest that the authentication process intimately involve the actual service-level networking (allowing bypassing authentication by directly using Pod IPs); what I meant was that a `Service` object within the Kubernetes API could be allowed as a valid place from which to retrieve the information needed by an authorization policy, that is to say, a `podSelector` and a `port`; those two pieces of information are the only pieces of information that are required to define a `Server` object, and, they are (in many case) already available in `Service` objects. 

The way that the networking is handled need not be adjusted in any way, shape, or form: this is about providing an additional, more concise API that can be used in situations where it matches the user's needs; in situations where the simpler API does not match the user's needs, they could still use the existing `Server` API.

To be absolutely clear, I'm suggesting an implementation in which the following two sets of API objects are _literally_ identical in their behavior:

```
---
apiVersion: v1
kind: Service
metadata:
  name: emoji
spec:
  selector:
    app: emoji-svc
  ports:
    - protocol: TCP
      port: grpc
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: emoji-policy
spec:
  targetRef:
    group: ""
    kind: Service
    name: emoji
  requiredAuthenticationRefs:
    - name: webapp
      kind: ServiceAccount
```
and
```
---
apiVersion: v1
kind: Service
metadata:
  name: emoji
spec:
  selector:
    app: emoji-svc
  ports:
    - protocol: TCP
      port: grpc
---
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  name: emoji
spec:
  podSelector:
    matchLabels:
      app: emoji-svc
  port: grpc
---
apiVersion: policy.linkerd.io/v1alpha1
kind: AuthorizationPolicy
metadata:
  name: emoji-policy
spec:
  targetRef:
    group: ""
    kind: Server
    name: emoji
  requiredAuthenticationRefs:
    - name: webapp
      kind: ServiceAccount
```

You'll note that in these examples, the `Server` object does not provide any information not already present in the `Service` object. If necessary, the Linkerd components involved in enforcing the authorization policy could simply construct a virtual `Server` object in-memory, since its contents can be entirely derived from the `Service` object present in the Kuberentes API.
