### ISSUE TITLE
Validation error: unknown field "path" in io.linkerd.policy.v1beta1.HTTPRoute.spec.rules.filters.requestRedirect

### ISSUE THREAD

**Issue by klingerf** [linkerd/linkerd2#9965]
### What is the issue?

According to the [HTTPRequestRedirect documentation](https://linkerd.io/2.12/reference/authorization-policy/#httprequestredirectfilter), users should be able to supply a `path` field that's used to modify the request path. When I try to set that field, however, I get a validation error:

```
error: error validating "hr2.yml": error validating data: ValidationError(HTTPRoute.spec.rules[0].filters[0].requestRedirect): unknown field "path" in io.linkerd.policy.v1beta1.HTTPRoute.spec.rules.filters.requestRedirect; if you choose to ignore these errors, turn validation off with --validate=false
```

As far as I can tell, `path` isn't a supported property of `requestRedirect` in the validation schema:

https://github.com/linkerd/linkerd2/blob/51d8b583f6f1ffc71c0825aeaf2dc1c5e5d6dc0a/charts/linkerd-crds/templates/policy/httproute.yaml#L325-L360

### How can it be reproduced?

Apply this config:

```yaml
apiVersion: policy.linkerd.io/v1beta1
kind: Server
metadata:
  namespace: default
  name: test-srv
spec:
  podSelector:
    matchLabels:
      linkerd.io/workload-ns: default
  port: asdf
---
apiVersion: policy.linkerd.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-route
spec:
  parentRefs:
  - group: policy.linkerd.io
    kind: Server
    name: test-srv
  rules:
  - matches:
    - method: GET
    filters:
    - type: RequestRedirect
      requestRedirect:
        statusCode: 302
        path:
          type: ReplaceFullPath
          replaceFullPath: /blah
```

### Logs, error output, etc

```
error: error validating "hr2.yml": error validating data: ValidationError(HTTPRoute.spec.rules[0].filters[0].requestRedirect): unknown field "path" in io.linkerd.policy.v1beta1.HTTPRoute.spec.rules.filters.requestRedirect; if you choose to ignore these errors, turn validation off with --validate=false
```

### output of `linkerd check -o short`

N/A

### Environment

```
$ linkerd version
Client version: edge-22.12.1
Server version: edge-22.12.1
```

```
$ kubectl version --short
Client Version: v1.25.2
Kustomize Version: v4.5.7
Server Version: v1.24.0
```

### Possible solution

Update the validation schema? Or update the documentation?

### Would you like to work on fixing this bug?

no
